def get_travel_banks():
    return {
        "course_id": "travel",
        "title": "Travel English",
        "desc": "Essential English for travelling - airport, hotel, taxi, and tourist situations.",
        "short": "Travel confidently in English",
        "icon": "✈️",
        "color": "accent",
        "difficulty": "Beginner",
        "audience": ["Travelers", "Tourists", "Daily Life Learners"],
        "price": "₹149",
        "lessons": [
            {"title": "Airport", "desc": "At the airport", "topic": "Airport", "sentences": [
                ("Where is the check-in counter?", "चेक-इन काउंटर कहाँ है?"),
                ("I would like to check in for my flight.", "मैं अपनी फ्लाइट के लिए चेक-इन करना चाहता हूँ।"),
                ("Please show me your passport and ticket.", "कृपया मुझे अपना पासपोर्ट और टिकट दिखाइए।"),
                ("How many bags are you checking in?", "आप कितने बैग चेक-इन कर रहे हैं?"),
                ("My luggage is overweight.", "मेरा सामान वजन से ज्यादा है।"),
                ("Which gate does the flight depart from?", "फ्लाइट किस गेट से निकलेगी?"),
                ("The flight is delayed by two hours.", "फ्लाइट दो घंटे देरी से है।"),
                ("I have a connecting flight in Delhi.", "दिल्ली में मेरी कनेक्टिंग फ्लाइट है।"),
                ("Where is the boarding gate?", "बोर्डिंग गेट कहाँ है?"),
                ("Please keep your boarding pass ready.", "कृपया अपना बोर्डिंग पास तैयार रखिए।"),
                ("The flight is now boarding.", "फ्लाइट अब बोर्डिंग कर रही है।"),
                ("I need a window seat.", "मुझे खिड़की वाली सीट चाहिए।"),
                ("Is this the right queue for boarding?", "क्या यह बोर्डिंग के लिए सही कतार है?"),
                ("My flight has been cancelled.", "मेरी फ्लाइट कैंसल हो गई है।"),
                ("Where can I get a trolley for my bags?", "मुझे अपने बैग के लिए ट्रॉली कहाँ मिलेगी?"),
                ("The departure lounge is on the second floor.", "डिपार्चर लाउंज दूसरी मंजिल पर है।"),
                ("Please announce when the flight lands.", "फ्लाइट लैंड होने पर कृपया घोषणा कीजिए।"),
                ("I am travelling for business.", "मैं व्यापार के लिए यात्रा कर रहा हूँ।"),
                ("What is the flight duration?", "फ्लाइट की अवधि क्या है?"),
                ("The in-flight meal is served at noon.", "इन-फ्लाइट भोजन दोपहर में परोसा जाता है।"),
                ("Fasten your seat belts, please.", "कृपया अपनी सीट बेल्ट बाँध लीजिए।"),
                ("The seat reclines for comfort.", "आराम के लिए सीट पीछे झुक सकती है।"),
                ("I hope we have a smooth journey.", "मुझे उम्मीद है हमारी यात्रा सुखद होगी।"),
                ("Welcome aboard our flight!", "हमारी फ्लाइट में आपका स्वागत है!"),
                ("Thank you for flying with us.", "हमारे साथ उड़ान भरने के लिए धन्यवाद।"),
            ]},
            {"title": "Check-in & Security", "desc": "Security and check-in procedures", "topic": "Security", "sentences": [
                ("Please place your bags on the conveyor.", "कृपया अपने बैग कन्वेयर पर रखिए।"),
                ("I have liquids in my carry-on bag.", "मेरे हैंड बैग में तरल पदार्थ हैं।"),
                ("Please remove your shoes and belt.", "कृपया अपने जूते और बेल्ट उतारिए।"),
                ("The security check is quick today.", "आज सुरक्षा जाँच जल्दी हो रही है।"),
                ("Do I need to take out my laptop?", "क्या मुझे अपना लैपटॉप निकालना होगा?"),
                ("My laptop is in the bag.", "मेरा लैपटॉप बैग में है।"),
                ("This is a restricted area.", "यह प्रतिबंधित क्षेत्र है।"),
                ("Please show your ID at the counter.", "कृपया काउंटर पर अपना आईडी दिखाइए।"),
                ("You cannot carry sharp objects.", "आप नुकीली वस्तुएँ नहीं ले जा सकते।"),
                ("The metal detector beeped.", "मेटल डिटेक्टर ने बीप की।"),
                ("Please empty your pockets.", "कृपया अपनी जेबें खाली कर दीजिए।"),
                ("Is this the international terminal?", "क्या यह अंतरराष्ट्रीय टर्मिनल है?"),
                ("My boarding pass got scanned.", "मेरा बोर्डिंग पास स्कैन हो गया।"),
                ("The security personnel are very professional.", "सुरक्षा कर्मी बहुत पेशेवर हैं।"),
                ("I was asked to open my bag.", "मुझे अपना बैग खोलने के लिए कहा गया।"),
                ("Mobile phones must be switched off.", "मोबाइल फोन बंद रखने होंगे।"),
                ("Please follow the instructions.", "कृपया निर्देशों का पालन कीजिए।"),
                ("My handbag went through the scanner.", "मेरा हैंडबैग स्कैनर से गुज़रा।"),
                ("You are clear to proceed.", "आप आगे बढ़ सकते हैं।"),
                ("Where is the customs area?", "कस्टम क्षेत्र कहाँ है?"),
                ("I have nothing to declare.", "मेरे पास घोषित करने के लिए कुछ नहीं है।"),
                ("Please open this suitcase for inspection.", "कृपया निरीक्षण के लिए यह सूटकेस खोलिए।"),
                ("The security check takes about ten minutes.", "सुरक्षा जाँच में लगभग दस मिनट लगते हैं।"),
                ("I arrived early for the security check.", "मैं सुरक्षा जाँच के लिए जल्दी पहुँच गया।"),
                ("Safety is the first priority.", "सुरक्षा सबसे पहली प्राथमिकता है।"),
            ]},
            {"title": "Flight & Immigration", "desc": "On the flight and immigration", "topic": "Flight", "sentences": [
                ("What time do we land?", "हम कितने बजे उतरेंगे?"),
                ("Could I have some water, please?", "क्या मुझे कुछ पानी मिल सकता है, कृपया?"),
                ("The flight is flying at 30,000 feet.", "फ्लाइट 30,000 फीट की ऊँचाई पर उड़ रही है।"),
                ("I feel a little airsick.", "मुझे हवा में थोड़ी तबीयत खराब लग रही है।"),
                ("Please bring me a blanket.", "कृपया मुझे एक कंबल दीजिए।"),
                ("The weather is clear for landing.", "लैंडिंग के लिए मौसम साफ है।"),
                ("Please fill the immigration form.", "कृपया इमिग्रेशन फॉर्म भरिए।"),
                ("What is the purpose of your visit?", "आपकी यात्रा का उद्देश्य क्या है?"),
                ("I am here on a tourist visa.", "मैं यहाँ टूरिस्ट वीज़ा पर हूँ।"),
                ("How long will you stay?", "आप कितने समय तक रहेंगे?"),
                ("I will stay for two weeks.", "मैं दो हफ्ते रहूँगा।"),
                ("Where will you be staying?", "आप कहाँ रहेंगे?"),
                ("I have booked a hotel in the city.", "मैंने शहर में एक होटल बुक किया है।"),
                ("Please show me your return ticket.", "कृपया मुझे अपना रिटर्न टिकट दिखाइए।"),
                ("The officer stamped my passport.", "अधिकारी ने मेरे पासपोर्ट पर मोहर लगाई।"),
                ("Welcome to our country!", "हमारे देश में आपका स्वागत है!"),
                ("Where do I collect my luggage?", "मैं अपना सामान कहाँ से लूँ?"),
                ("My suitcase is on belt number 2.", "मेरा सूटकेस बेल्ट नंबर 2 पर है।"),
                ("One of my bags is missing.", "मेरा एक बैग गायब है।"),
                ("Please help me find my luggage.", "कृपया मेरा सामान खोजने में मेरी मदद कीजिए।"),
                ("I have a transit visa.", "मेरे पास ट्रांज़िट वीज़ा है।"),
                ("The connecting flight leaves in 3 hours.", "कनेक्टिंग फ्लाइट 3 घंटे में निकलती है।"),
                ("Do I need a visa for this country?", "क्या मुझे इस देश के लिए वीज़ा चाहिए?"),
                ("My passport is valid for five more years.", "मेरा पासपोर्ट पाँच और साल के लिए वैध है।"),
                ("Travelling abroad is a great experience.", "विदेश यात्रा एक बहुत अच्छा अनुभव है।"),
            ]},
            {"title": "Hotel", "desc": "Stay at a hotel", "topic": "Hotel", "sentences": [
                ("I have a reservation under the name Sharma.", "मेरी बुकिंग शर्मा नाम से है।"),
                ("I would like to check in, please.", "मैं चेक-इन करना चाहता हूँ, कृपया।"),
                ("Do you have any rooms available?", "क्या आपके पास कोई कमरा उपलब्ध है?"),
                ("What is the room rate per night?", "प्रति रात कमरे की दर क्या है?"),
                ("I booked a double room.", "मैंने एक डबल रूम बुक किया है।"),
                ("Does the room have Wi-Fi?", "क्या कमरे में वाई-फाई है?"),
                ("I would like a room with a view.", "मुझे दृश्य वाला कमरा चाहिए।"),
                ("What time is breakfast served?", "नाश्ता कितने बजे परोसा जाता है?"),
                ("Could you please bring extra towels?", "क्या आप कृपया अतिरिक्त तौलिये ला सकते हैं?"),
                ("The air conditioner is not working.", "एयर कंडीशनर काम नहीं कर रहा है।"),
                ("I would like to check out tomorrow.", "मैं कल चेक-आउट करना चाहता हूँ।"),
                ("Can I leave my luggage here?", "क्या मैं अपना सामान यहाँ छोड़ सकता हूँ?"),
                ("The room service is available 24 hours.", "रूम सर्विस 24 घंटे उपलब्ध है।"),
                ("Please wake me up at 6 AM.", "कृपया मुझे सुबह 6 बजे जगा दीजिए।"),
                ("Is breakfast included in the price?", "क्या नाश्ता कीमत में शामिल है?"),
                ("The hotel has a swimming pool.", "होटल में एक स्विमिंग पूल है।"),
                ("I need a taxi to the airport.", "मुझे हवाई अड्डे के लिए टैक्सी चाहिए।"),
                ("The room is very clean and comfortable.", "कमरा बहुत साफ और आरामदायक है।"),
                ("Please give me the Wi-Fi password.", "कृपया मुझे वाई-फाई का पासवर्ड दीजिए।"),
                ("I would like to extend my stay.", "मैं अपना ठहराव बढ़ाना चाहता हूँ।"),
                ("The hotel is near the city centre.", "होटल शहर के केंद्र के पास है।"),
                ("There is a gym on the third floor.", "तीसरी मंजिल पर एक जिम है।"),
                ("Please charge it to my room.", "कृपया इसे मेरे कमरे में लगाइए।"),
                ("The check-out time is 11 AM.", "चेक-आउट का समय सुबह 11 बजे है।"),
                ("Thank you for a pleasant stay.", "सुखद प्रवास के लिए धन्यवाद।"),
            ]},
            {"title": "Tourist Help", "desc": "Get help as a tourist", "topic": "Tourist", "sentences": [
                ("I need a tourist guide.", "मुझे एक टूरिस्ट गाइड चाहिए।"),
                ("Where can I buy tickets for the museum?", "मैं संग्रहालय के टिकट कहाँ से खरीदूँ?"),
                ("Is photography allowed inside?", "क्या अंदर फोटोग्राफी की अनुमति है?"),
                ("What are the visiting hours?", "देखने का समय क्या है?"),
                ("Can you recommend a good sightseeing tour?", "क्या आप एक अच्छा घूमने का टूर सुझा सकते हैं?"),
                ("I would like to visit the historical monument.", "मैं ऐतिहासिक स्मारक देखना चाहता हूँ।"),
                ("Where is the tourist information centre?", "टूरिस्ट सूचना केंद्र कहाँ है?"),
                ("Is this place safe for tourists?", "क्या यह जगह पर्यटकों के लिए सुरक्षित है?"),
                ("Please take our photograph.", "कृपया हमारी फोटो खींच दीजिए।"),
                ("What is the entry fee?", "प्रवेश शुल्क क्या है?"),
                ("I want to buy some souvenirs.", "मैं कुछ स्मृति चिन्ह खरीदना चाहता हूँ।"),
                ("Where can I exchange foreign currency?", "मैं विदेशी मुद्रा कहाँ बदल सकता हूँ?"),
                ("The guide explained the history very well.", "गाइड ने इतिहास बहुत अच्छे से समझाया।"),
                ("Is there a map of the city?", "क्या शहर का नक्शा है?"),
                ("I am interested in local culture.", "मुझे स्थानीय संस्कृति में रुचि है।"),
                ("The local food is delicious.", "स्थानीय खाना बहुत स्वादिष्ट है।"),
                ("Can I take a boat ride on the lake?", "क्या मैं झील पर नाव की सवारी कर सकता हूँ?"),
                ("The sunset point is very beautiful.", "सूर्यास्त देखने की जगह बहुत सुंदर है।"),
                ("How do I reach the old fort?", "मैं पुराने किले तक कैसे पहुँचूँ?"),
                ("I got lost. Can you help me?", "मैं खो गया हूँ। क्या आप मेरी मदद कर सकते हैं?"),
                ("The museum is closed on Mondays.", "संग्रहालय सोमवार को बंद रहता है।"),
                ("I enjoyed the cultural show.", "मुझे सांस्कृतिक कार्यक्रम बहुत पसंद आया।"),
                ("This city has many beautiful places.", "इस शहर में कई सुंदर जगहें हैं।"),
                ("Travelling teaches you many things.", "यात्रा आपको बहुत कुछ सिखाती है।"),
                ("I will definitely come back again.", "मैं निश्चित रूप से फिर आऊँगा।"),
            ]},
            {"title": "Travel Emergencies", "desc": "Handle emergencies while travelling", "topic": "Travel Emergency", "sentences": [
                ("I have lost my passport.", "मेरा पासपोर्ट खो गया है।"),
                ("Where is the nearest embassy?", "सबसे नज़दीकी दूतावास कहाँ है?"),
                ("My luggage has been stolen.", "मेरा सामान चोरी हो गया है।"),
                ("I need to report a theft.", "मुझे चोरी की रिपोर्ट करनी है।"),
                ("My flight ticket is missing.", "मेरा फ्लाइट टिकट गायब है।"),
                ("I missed my connecting flight.", "मैं अपनी कनेक्टिंग फ्लाइट मिस कर गया।"),
                ("Can I rebook my flight?", "क्या मैं अपनी फ्लाइट दोबारा बुक कर सकता हूँ?"),
                ("I have lost my wallet.", "मेरा बटुआ खो गया है।"),
                ("Please help me contact my family.", "कृपया मेरे परिवार से संपर्क करने में मेरी मदद कीजिए।"),
                ("I need medical help.", "मुझे चिकित्सा सहायता चाहिए।"),
                ("Where is the hospital?", "अस्पताल कहाँ है?"),
                ("I have travel insurance.", "मेरे पास यात्रा बीमा है।"),
                ("The airline will provide a hotel.", "एयरलाइन होटल उपलब्ध कराएगी।"),
                ("My reservation was not found.", "मेरी बुकिंग नहीं मिली।"),
                ("The hotel lost my booking.", "होटल ने मेरी बुकिंग खो दी।"),
                ("I need an emergency cash advance.", "मुझे आपातकालीन नकद अग्रिम चाहिए।"),
                ("Please do not panic.", "कृपया घबराइए मत।"),
                ("The consulate will issue a new passport.", "वाणिज्य दूतावास नया पासपोर्ट जारी करेगा।"),
                ("I am stranded at the airport.", "मैं हवाई अड्डे पर फंस गया हूँ।"),
                ("Please book me the next available flight.", "कृपया मुझे अगली उपलब्ध फ्लाइट बुक कर दीजिए।"),
                ("My phone has been stolen.", "मेरा फोन चोरी हो गया है।"),
                ("Can I use your phone to make a call?", "क्या मैं कॉल करने के लिए आपका फोन इस्तेमाल कर सकता हूँ?"),
                ("I need to cancel my hotel booking.", "मुझे अपनी होटल बुकिंग कैंसल करनी है।"),
                ("The travel agent will help me.", "ट्रैवल एजेंट मेरी मदद करेगा।"),
                ("Stay calm, everything will be fine.", "शांत रहिए, सब कुछ ठीक हो जाएगा।"),
                ("Could we have a table for three?", "क्या हमें तीन लोगों के लिए टेबल मिल सकती है?"),
                ("I would like to see the menu, please.", "मैं मेनू देखना चाहूँगा, कृपया।"),
                ("What is the specialty of this place?", "इस जगह की खासियत क्या है?"),
                ("I will have the chef's special.", "मैं शेफ की स्पेशल डिश लूँगा।"),
                ("Is the water safe to drink here?", "क्या यहाँ का पानी पीने के लिए सुरक्षित है?"),
                ("I would like it without onions, please.", "मुझे यह बिना प्याज़ के चाहिए, कृपया।"),
                ("The food looks amazing!", "खाना बहुत शानदार लग रहा है!"),
                ("Could I have the bill, please?", "क्या मुझे बिल मिल सकता है, कृपया?"),
                ("Do you accept credit cards?", "क्या आप क्रेडिट कार्ड स्वीकार करते हैं?"),
                ("I left a tip for the waiter.", "मैंने वेटर के लिए टिप छोड़ी।"),
                ("This dish is too spicy for me.", "यह डिश मेरे लिए बहुत तीखी है।"),
                ("Is there a vegetarian option?", "क्या कोई शाकाहारी विकल्प है?"),
                ("We would like to order dessert.", "हम मिठाई ऑर्डर करना चाहेंगे।"),
                ("The restaurant has outdoor seating.", "रेस्तराँ में बाहर बैठने की व्यवस्था है।"),
                ("Please bring me a fork and knife.", "कृपया मुझे कांटा और चाकू दीजिए।"),
                ("The service was very fast.", "सेवा बहुत तेज़ थी।"),
                ("Can I have this packed to take away?", "क्या मैं इसे पैक करवा सकता हूँ?"),
                ("The local dishes are worth trying.", "स्थानीय व्यंजन आज़माने लायक हैं।"),
                ("The restaurant is fully booked tonight.", "रेस्तराँ आज रात पूरी तरह बुक है।"),
                ("We will come back tomorrow.", "हम कल फिर आएँगे।"),
                ("Thank you for the wonderful dinner.", "शानदार रात्रि भोजन के लिए धन्यवाद।"),
                ("How much is the service charge?", "सर्विस चार्ज कितना है?"),
                ("I enjoyed the local cuisine.", "मुझे स्थानीय व्यंजन बहुत पसंद आए।"),
                ("Could we sit near the window?", "क्या हम खिड़की के पास बैठ सकते हैं?"),
                ("This place is famous for its seafood.", "यह जगह अपने समुद्री भोजन के लिए मशहूर है।"),
            ]},
            {"title": "Transport & Maps", "desc": "Use transport and maps while travelling", "topic": "Transport", "sentences": [
                ("How do I get to the city centre?", "मैं शहर के केंद्र तक कैसे पहुँचूँ?"),
                ("Is there a bus from the airport?", "क्या हवाई अड्डे से कोई बस है?"),
                ("I need to buy a metro card.", "मुझे एक मेट्रो कार्ड खरीदना है।"),
                ("Which line goes to the museum?", "संग्रहालय के लिए कौन सी लाइन जाती है?"),
                ("Can I get a day pass?", "क्या मुझे एक दिन का पास मिल सकता है?"),
                ("How often does the bus come?", "बस कितनी बार आती है?"),
                ("Please tell me when to get off.", "कृपया मुझे बताइए कि कब उतरना है।"),
                ("I would like to hire a bicycle.", "मैं एक साइकिल किराए पर लेना चाहता हूँ।"),
                ("Is it far from here?", "क्या यह यहाँ से दूर है?"),
                ("The taxi fare is expensive here.", "यहाँ टैक्सी का किराया महँगा है।"),
                ("Let us take the local bus.", "चलो लोकल बस लेते हैं।"),
                ("I am looking at the city map.", "मैं शहर का नक्शा देख रहा हूँ।"),
                ("Can you show me on the map?", "क्या आप मुझे नक्शे पर दिखा सकते हैं?"),
                ("The train station is underground.", "रेलवे स्टेशन भूमिगत है।"),
                ("Please drop me at the nearest metro.", "कृपया मुझे सबसे नज़दीकी मेट्रो पर छोड़ दीजिए।"),
                ("The ferry goes to the island.", "नाव द्वीप तक जाती है।"),
                ("What is the last bus timing?", "आखिरी बस का समय क्या है?"),
                ("I prefer walking in the old city.", "मैं पुराने शहर में पैदल चलना पसंद करता हूँ।"),
                ("The transport system is very efficient.", "परिवहन प्रणाली बहुत कुशल है।"),
                ("Let us check the app for the route.", "चलो रास्ते के लिए ऐप देखते हैं।"),
                ("The bus is very comfortable.", "बस बहुत आरामदायक है।"),
                ("We took a wrong turn.", "हमने गलत मोड़ ले लिया।"),
                ("Please drive to the hotel.", "कृपया होटल तक चलिए।"),
                ("The journey was very scenic.", "यात्रा बहुत सुंदर दृश्यों वाली थी।"),
                ("I will use the metro to explore the city.", "मैं शहर घूमने के लिए मेट्रो का उपयोग करूँगा।"),
            ]},
            {"title": "Shopping Abroad", "desc": "Shop while travelling", "topic": "Shopping", "sentences": [
                ("I am looking for a souvenir shop.", "मैं एक स्मृति चिन्ह की दुकान ढूँढ रहा हूँ।"),
                ("Can I bargain here?", "क्या मैं यहाँ मोलभाव कर सकता हूँ?"),
                ("This is a handmade item.", "यह हस्तनिर्मित वस्तु है।"),
                ("Do you have a bigger size?", "क्या आपके पास बड़ा साइज़ है?"),
                ("I will take two of these.", "मैं इनमें से दो लूँगा।"),
                ("Is there any discount for tourists?", "क्या पर्यटकों के लिए कोई छूट है?"),
                ("Can I pay in my currency?", "क्या मैं अपनी मुद्रा में भुगतान कर सकता हूँ?"),
                ("The price is in dollars.", "कीमत डॉलर में है।"),
                ("This scarf is very beautiful.", "यह दुपट्टा बहुत सुंदर है।"),
                ("I bought gifts for my family.", "मैंने अपने परिवार के लिए उपहार खरीदे।"),
                ("The market closes at 9 PM.", "बाज़ार रात 9 बजे बंद होता है।"),
                ("Can you pack it nicely?", "क्या आप इसे अच्छे से पैक कर सकते हैं?"),
                ("I like the local handicrafts.", "मुझे स्थानीय हस्तशिल्प पसंद हैं।"),
                ("Where is the duty-free shop?", "ड्यूटी-फ्री दुकान कहाँ है?"),
                ("I need a refund for this item.", "मुझे इस वस्तु का रिफंड चाहिए।"),
                ("The shopkeeper was very friendly.", "दुकानदार बहुत मिलनसार था।"),
                ("This price includes tax.", "इस कीमत में कर शामिल है।"),
                ("I am just browsing, thank you.", "मैं बस देख रहा हूँ, धन्यवाद।"),
                ("The shopping street is very lively.", "शॉपिंग स्ट्रीट बहुत जीवंत है।"),
                ("I spent too much money on shopping.", "मैंने खरीदारी पर बहुत पैसे खर्च कर दिए।"),
                ("Can I get this in a different colour?", "क्या मुझे यह अलग रंग में मिल सकता है?"),
                ("I am looking for a traditional dress.", "मैं एक पारंपरिक पोशाक ढूँढ रहा हूँ।"),
                ("The mall has many brands.", "मॉल में कई ब्रांड हैं।"),
                ("Shopping is fun when travelling.", "यात्रा के दौरान खरीदारी मज़ेदार होती है।"),
                ("I bought everything I needed.", "मैंने वह सब खरीद लिया जो मुझे चाहिए था।"),
            ]},
            {"title": "Hotel Requests", "desc": "Make requests at the hotel", "topic": "Hotel Requests", "sentences": [
                ("Could I get a different room?", "क्या मुझे एक अलग कमरा मिल सकता है?"),
                ("The room is too noisy.", "कमरा बहुत शोरगुल वाला है।"),
                ("Please change the bedsheets.", "कृपया बिस्तर की चादरें बदल दीजिए।"),
                ("I need an extra pillow.", "मुझे एक अतिरिक्त तकिया चाहिए।"),
                ("Can you arrange a wake-up call?", "क्या आप वेक-अप कॉल की व्यवस्था कर सकते हैं?"),
                ("I would like room service.", "मैं रूम सर्विस चाहता हूँ।"),
                ("Please send someone to fix the TV.", "कृपया टीवी ठीक करने के लिए किसी को भेजिए।"),
                ("The bathroom is leaking.", "बाथरूम से पानी टपक रहा है।"),
                ("I need a late check-out.", "मुझे देर से चेक-आउट चाहिए।"),
                ("Can I store my luggage here?", "क्या मैं अपना सामान यहाँ रख सकता हूँ?"),
                ("Please book a table for dinner.", "कृपया रात के खाने के लिए टेबल बुक कीजिए।"),
                ("The room service menu is on the table.", "रूम सर्विस का मेनू मेज़ पर है।"),
                ("I would like a massage appointment.", "मैं मसाज के लिए अपॉइंटमेंट चाहता हूँ।"),
                ("Please bring some hot water.", "कृपया कुछ गर्म पानी लाइए।"),
                ("The minibar needs to be refilled.", "मिनीबार को फिर से भरना है।"),
                ("I have a complaint about the room.", "मुझे कमरे के बारे में एक शिकायत है।"),
                ("Can you call me a taxi?", "क्या आप मेरे लिए टैक्सी बुला सकते हैं?"),
                ("Please print my boarding pass.", "कृपया मेरा बोर्डिंग पास प्रिंट कर दीजिए।"),
                ("Is there a laundry service?", "क्या कोई कपड़े धोने की सेवा है?"),
                ("The view from my room is beautiful.", "मेरे कमरे से दृश्य बहुत सुंदर है।"),
                ("I would like to order breakfast in bed.", "मैं बिस्तर पर नाश्ता ऑर्डर करना चाहता हूँ।"),
                ("Please keep the 'Do Not Disturb' sign.", "कृपया 'डू नॉट डिस्टर्ब' का चिन्ह लगा दीजिए।"),
                ("The manager will look into the issue.", "मैनेजर इस मामले को देखेंगे।"),
                ("Thank you for your quick response.", "आपके त्वरित जवाब के लिए धन्यवाद।"),
                ("I am very satisfied with the hotel.", "मैं होटल से बहुत संतुष्ट हूँ।"),
            ]},
            {"title": "Small Talk While Travelling", "desc": "Make conversation while travelling", "topic": "Small Talk", "sentences": [
                ("Is this your first visit here?", "क्या यह आपकी पहली यात्रा है?"),
                ("Where are you from?", "आप कहाँ से हैं?"),
                ("I am from India.", "मैं भारत से हूँ।"),
                ("How long have you been travelling?", "आप कितने समय से यात्रा कर रहे हैं?"),
                ("What places have you visited so far?", "अब तक आपने कौन सी जगहें देखी हैं?"),
                ("The weather is lovely here.", "यहाँ का मौसम बहुत सुंदर है।"),
                ("I am enjoying my trip very much.", "मैं अपनी यात्रा का बहुत आनंद ले रहा हूँ।"),
                ("Have you tried the local food?", "क्या आपने स्थानीय खाना आज़माया?"),
                ("You should visit the old town.", "आपको पुराना शहर ज़रूर देखना चाहिए।"),
                ("The people here are very friendly.", "यहाँ के लोग बहुत मिलनसार हैं।"),
                ("Do you travel often?", "क्या आप अक्सर यात्रा करते हैं?"),
                ("I travel for work sometimes.", "मैं कभी-कभी काम के लिए यात्रा करता हूँ।"),
                ("This is a beautiful country.", "यह एक सुंदर देश है।"),
                ("I love meeting new people while travelling.", "मुझे यात्रा के दौरान नए लोगों से मिलना पसंद है।"),
                ("How was your flight?", "आपकी उड़ान कैसी थी?"),
                ("My flight was smooth and on time.", "मेरी उड़ान सुचारू और समय पर थी।"),
                ("Where are you staying?", "आप कहाँ रुके हैं?"),
                ("I am staying near the beach.", "मैं समुद्र तट के पास रुका हूँ।"),
                ("Let us exchange travel stories.", "चलो यात्रा के किस्से साझा करते हैं।"),
                ("I learned a few local words.", "मैंने कुछ स्थानीय शब्द सीखे।"),
                ("The locals helped me a lot.", "स्थानीय लोगों ने मेरी बहुत मदद की।"),
                ("It was nice talking to you.", "आपसे बात करके अच्छा लगा।"),
                ("Enjoy the rest of your trip!", "अपनी बाकी यात्रा का आनंद लीजिए!"),
                ("Maybe we will meet again.", "शायद हम फिर मिलें।"),
                ("Safe travels to you too!", "आपको भी सुरक्षित यात्रा!"),
            ]},
            {"title": "Travel Essentials", "desc": "Essential travel conversations", "topic": "Essentials", "sentences": [
                ("I forgot my chargers at home.", "मैं अपने चार्जर घर पर भूल गया।"),
                ("Where can I buy a SIM card?", "मैं सिम कार्ड कहाँ से खरीद सकता हूँ?"),
                ("I need to exchange some money.", "मुझे कुछ पैसे बदलने हैं।"),
                ("Is there a pharmacy nearby?", "क्या पास में कोई फार्मेसी है?"),
                ("I have a small headache.", "मुझे हल्का सिरदर्द है।"),
                ("Please give me a painkiller.", "कृपया मुझे एक दर्द निवारक दीजिए।"),
                ("I need sunscreen for the beach.", "मुझे समुद्र तट के लिए सनस्क्रीन चाहिए।"),
                ("Where is the luggage storage?", "सामान रखने की जगह कहाँ है?"),
                ("Can I leave my bag here for two hours?", "क्या मैं अपना बैग दो घंटे यहाँ छोड़ सकता हूँ?"),
                ("I need a quick meal before my flight.", "मुझे अपनी फ्लाइट से पहले जल्दी खाना चाहिए।"),
                ("Where is the nearest restroom?", "सबसे नज़दीकी शौचालय कहाँ है?"),
                ("Is the tap water drinkable?", "क्या नल का पानी पीने योग्य है?"),
                ("I need to buy a travel adapter.", "मुझे एक ट्रैवल एडेप्टर खरीदना है।"),
                ("The hotel provides free toiletries.", "होटल मुफ्त प्रसाधन उपलब्ध कराता है।"),
                ("I lost my room key card.", "मेरा रूम की कार्ड खो गया।"),
                ("Please give me a spare key.", "कृपया मुझे एक अतिरिक्त चाबी दीजिए।"),
                ("I am checking out today.", "मैं आज चेक-आउट कर रहा हूँ।"),
                ("My flight is at 8 PM tonight.", "मेरी फ्लाइट आज रात 8 बजे है।"),
                ("I have a long layover.", "मेरा लंबा लेओवर है।"),
                ("Is there a lounge I can use?", "क्या कोई लाउंज है जो मैं इस्तेमाल कर सकता हूँ?"),
                ("I need to print my documents.", "मुझे अपने दस्तावेज़ प्रिंट करने हैं।"),
                ("The hotel business centre has a printer.", "होटल के बिजनेस सेंटर में प्रिंटर है।"),
                ("I should carry my passport safely.", "मुझे अपना पासपोर्ट सुरक्षित रखना चाहिए।"),
                ("Travel light and travel smart.", "हल्का पैक करो और समझदारी से यात्रा करो।"),
                ("Every trip teaches something new.", "हर यात्रा कुछ नया सिखाती है।"),
            ]},
        ],
    }
