# Intermediate English - 16 lessons x 25 = 400 sentences

def get_intermediate_banks():
    return {
        "course_id": "intermediate",
        "title": "Intermediate English",
        "desc": "Take your English to the next level - opinions, experiences, and natural conversations.",
        "short": "Speak with more confidence",
        "icon": "📈",
        "color": "accent",
        "difficulty": "Intermediate",
        "audience": ["Intermediate Learners", "Working Professionals", "College Students"],
        "price": "₹299",
        "lessons": [
            {"title": "Describing Situations", "desc": "Describe situations clearly", "topic": "Describing", "sentences": [
                ("Let me explain the situation to you.", "मुझे आपको स्थिति समझाने दें।"),
                ("This is what happened yesterday.", "कल ऐसा हुआ था।"),
                ("I was waiting for the bus when I saw him.", "मैं बस का इंतज़ार कर रहा था तभी मैंने उसे देखा।"),
                ("The problem started around 3 PM.", "समस्या लगभग 3 बजे शुरू हुई।"),
                ("I have been facing this issue for a week.", "मैं एक हफ्ते से इस समस्या का सामना कर रहा हूँ।"),
                ("The main issue is the delay in delivery.", "मुख्य समस्या डिलीवरी में देरी है।"),
                ("Let me show you what I mean.", "आइए मैं आपको दिखाता हूँ कि मेरा क्या मतलब है।"),
                ("It happened just like this.", "बिल्कुल ऐसे ही हुआ।"),
                ("I was about to leave when the phone rang.", "मैं जाने ही वाला था कि फोन बजा।"),
                ("This is not what I expected.", "मुझे ऐसी उम्मीद नहीं थी।"),
                ("The situation is more complicated than it seems.", "स्थिति जितनी लगती है उससे कहीं अधिक जटिल है।"),
                ("Let me explain what happened step by step.", "मुझे कदम दर कदम समझाने दें कि क्या हुआ।"),
                ("The first thing that went wrong was the payment.", "सबसे पहले भुगतान में गड़बड़ हुई।"),
                ("In other words, we need to start again.", "दूसरे शब्दों में, हमें फिर से शुरू करना होगा।"),
                ("This is a common problem in our area.", "हमारे क्षेत्र में यह एक आम समस्या है।"),
                ("Have you faced this situation before?", "क्या आपने पहले इस स्थिति का सामना किया है?"),
                ("I can describe the scene in detail.", "मैं दृश्य का विस्तार से वर्णन कर सकता हूँ।"),
                ("It was a very unusual experience.", "यह एक बहुत ही असामान्य अनुभव था।"),
                ("The reason for the problem is quite simple.", "समस्या का कारण काफी सरल है।"),
                ("We need to find a solution quickly.", "हमें जल्दी से एक समाधान खोजना होगा।"),
                ("Let me break it down for you.", "मैं आपके लिए इसे सरल करता हूँ।"),
                ("I will explain everything in detail.", "मैं सब कुछ विस्तार से समझाऊँगा।"),
                ("That clears up a lot of confusion.", "इससे बहुत सारा भ्रम दूर हो गया।"),
                ("I appreciate you explaining it clearly.", "मैं सराहना करता हूँ कि आपने स्पष्ट रूप से समझाया।"),
                ("Now I understand the full picture.", "अब मुझे पूरी तस्वीर समझ आ गई।"),
            ]},
            {"title": "Opinions & Agreement", "desc": "Give opinions and agree", "topic": "Opinions", "sentences": [
                ("In my opinion, this is the best option.", "मेरी राय में, यह सबसे अच्छा विकल्प है।"),
                ("I personally believe we should wait.", "मैं व्यक्तिगत रूप से मानता हूँ कि हमें इंतज़ार करना चाहिए।"),
                ("From my point of view, it is a good idea.", "मेरे दृष्टिकोण से, यह एक अच्छा विचार है।"),
                ("I completely agree with your suggestion.", "मैं आपके सुझाव से पूरी तरह सहमत हूँ।"),
                ("That makes sense. I think you are right.", "यह समझ में आता है। मुझे लगता है आप सही हैं।"),
                ("I see your point, but I have a different view.", "मैं आपकी बात समझता हूँ, लेकिन मेरा एक अलग दृष्टिकोण है।"),
                ("I am not sure I agree with that.", "मुझे यकीन नहीं है कि मैं इससे सहमत हूँ।"),
                ("You have a valid point there.", "आपकी बात वाजिब है।"),
                ("I could not agree more.", "मैं इससे अधिक सहमत नहीं हो सकता।"),
                ("That is exactly what I was thinking.", "यह बिल्कुल वही है जो मैं सोच रहा था।"),
                ("I respectfully disagree with you.", "मैं विनम्रतापूर्वक आपसे असहमत हूँ।"),
                ("Let us agree to disagree.", "चलो असहमत होने पर सहमत होते हैं।"),
                ("I respect your opinion even though I disagree.", "भले ही मैं असहमत हूँ, मैं आपकी राय का सम्मान करता हूँ।"),
                ("Can I share my thoughts on this?", "क्या मैं इस पर अपने विचार साझा कर सकता हूँ?"),
                ("I think we should go ahead with the plan.", "मुझे लगता है हमें योजना के साथ आगे बढ़ना चाहिए।"),
                ("That sounds like a practical solution.", "यह एक व्यावहारिक समाधान लगता है।"),
                ("Let me think about it and get back to you.", "मुझे इसके बारे में सोचने दें और फिर बताऊँ।"),
                ("I appreciate your honest opinion.", "मैं आपकी ईमानदार राय की सराहना करता हूँ।"),
                ("Everyone is entitled to their opinion.", "हर किसी को अपनी राय रखने का अधिकार है।"),
                ("We considered all the views.", "हमने सभी विचारों पर विचार किया।"),
                ("The majority agrees with the proposal.", "बहुमत प्रस्ताव से सहमत है।"),
                ("Opinions make conversations interesting.", "राय बातचीत को दिलचस्प बनाती हैं।"),
                ("I value different perspectives.", "मैं अलग-अलग दृष्टिकोणों को महत्व देता हूँ।"),
                ("We reached a common understanding.", "हम एक सामान्य समझ पर पहुँचे।"),
                ("Respectful disagreement is healthy.", "सम्मानजनक असहमति स्वस्थ है।"),
            ]},
            {"title": "Suggestions & Advice", "desc": "Give suggestions and advice", "topic": "Suggestions", "sentences": [
                ("Have you considered another approach?", "क्या आपने कोई और तरीका सोचा है?"),
                ("I would suggest trying a different method.", "मैं एक अलग तरीका आज़माने का सुझाव दूँगा।"),
                ("Why do we not discuss this further?", "क्यों न हम इस पर और चर्चा करें?"),
                ("Let me offer a different perspective.", "मुझे एक अलग दृष्टिकोण देने दें।"),
                ("I strongly recommend taking this course.", "मैं जोरदार सिफारिश करता हूँ कि यह कोर्स करें।"),
                ("My advice would be to practice every day.", "मेरी सलाह होगी कि रोज़ अभ्यास करें।"),
                ("If I were you, I would start early.", "अगर मैं आपकी जगह होता, तो जल्दी शुरू करता।"),
                ("You should consider all the options.", "आपको सभी विकल्पों पर विचार करना चाहिए।"),
                ("Let us look at the pros and cons first.", "चलो पहले फायदे और नुकसान देखते हैं।"),
                ("I would recommend speaking with an expert.", "मैं एक विशेषज्ञ से बात करने की सिफारिश करूँगा।"),
                ("That is a valid point, but have you thought about the cost?", "यह एक उचित बात है, लेकिन क्या आपने लागत के बारे में सोचा है?"),
                ("You might want to check the details again.", "आप शायद विवरण फिर से जाँचना चाहें।"),
                ("It would be wise to save some money.", "कुछ पैसे बचाना समझदारी होगी।"),
                ("I suggest we take a short break.", "मैं सुझाव देता हूँ कि हम थोड़ा ब्रेक लें।"),
                ("Why not give it a try?", "क्यों न इसे आज़माएँ?"),
                ("Consider the long-term benefits.", "दीर्घकालिक लाभों पर विचार कीजिए।"),
                ("You could ask your manager for advice.", "आप अपने प्रबंधक से सलाह ले सकते हैं।"),
                ("Let me share what worked for me.", "मुझे साझा करने दें कि मेरे लिए क्या काम आया।"),
                ("A little practice goes a long way.", "थोड़ा सा अभ्यास बहुत काम आता है।"),
                ("Good advice is always valuable.", "अच्छी सलाह हमेशा मूल्यवान होती है।"),
                ("We took everyone's advice seriously.", "हमने सभी की सलाह को गंभीरता से लिया।"),
                ("The suggestion was very helpful.", "सुझाव बहुत सहायक था।"),
                ("I will follow your advice.", "मैं आपकी सलाह का पालन करूँगा।"),
                ("Together we can find the best solution.", "हम मिलकर सबसे अच्छा समाधान ढूँढ सकते हैं।"),
                ("Good suggestions come from experience.", "अच्छे सुझाव अनुभव से आते हैं।"),
            ]},
            {"title": "Experiences", "desc": "Share your experiences", "topic": "Experiences", "sentences": [
                ("I have been to Bangalore many times.", "मैं कई बार बंगलौर गया हूँ।"),
                ("I have never tried Japanese food before.", "मैंने पहले कभी जापानी खाना नहीं खाया।"),
                ("It was the best trip of my life.", "यह मेरे जीवन की सबसे अच्छी यात्रा थी।"),
                ("I have learned a lot from my previous job.", "मैंने अपनी पिछली नौकरी से बहुत कुछ सीखा।"),
                ("I have been studying English for two years.", "मैं दो साल से अंग्रेज़ी पढ़ रहा हूँ।"),
                ("I have already completed three levels.", "मैंने पहले ही तीन स्तर पूरे कर लिए हैं।"),
                ("I remember my first day at school clearly.", "मुझे अपना पहला स्कूल का दिन स्पष्ट रूप से याद है।"),
                ("I used to live in a small town.", "मैं पहले एक छोटे शहर में रहता था।"),
                ("I have never seen such a beautiful sunset.", "मैंने इतना सुंदर सूर्यास्त कभी नहीं देखा।"),
                ("I have had some amazing experiences in life.", "मेरे जीवन में कुछ अद्भुत अनुभव रहे हैं।"),
                ("I learned swimming when I was ten.", "मैंने दस साल की उम्र में तैरना सीखा।"),
                ("That was a memorable moment for me.", "वह मेरे लिए एक यादगार पल था।"),
                ("I have travelled to many places in India.", "मैंने भारत की कई जगहों की यात्रा की है।"),
                ("My experience taught me patience.", "मेरे अनुभव ने मुझे धैर्य सिखाया।"),
                ("I once met a famous actor.", "मैं एक बार एक प्रसिद्ध अभिनेता से मिला था।"),
                ("The concert was unforgettable.", "संगीत कार्यक्रम अविस्मरणीय था।"),
                ("I have worked on many interesting projects.", "मैंने कई दिलचस्प परियोजनाओं पर काम किया है।"),
                ("That experience changed my life.", "उस अनुभव ने मेरा जीवन बदल दिया।"),
                ("I have learned to stay positive.", "मैंने सकारात्मक रहना सीखा।"),
                ("Every experience teaches us something.", "हर अनुभव हमें कुछ सिखाता है।"),
                ("I enjoy sharing my travel experiences.", "मुझे अपने यात्रा अनुभव साझा करना पसंद है।"),
                ("We had a great time at the party.", "हमने पार्टी में बहुत अच्छा समय बिताया।"),
                ("I will never forget that day.", "मैं उस दिन को कभी नहीं भूलूँगा।"),
                ("Good experiences stay with us forever.", "अच्छे अनुभव हमेशा हमारे साथ रहते हैं।"),
                ("I am grateful for all my experiences.", "मैं अपने सभी अनुभवों के लिए आभारी हूँ।"),
            ]},
            {"title": "Future Plans", "desc": "Talk about future plans", "topic": "Future Plans", "sentences": [
                ("I plan to start my own business next year.", "मैं अगले साल अपना खुद का व्यवसाय शुरू करने की योजना बना रहा हूँ।"),
                ("I am going to apply for a new job soon.", "मैं जल्द ही एक नई नौकरी के लिए आवेदन करने वाला हूँ।"),
                ("I hope to travel abroad next summer.", "मुझे उम्मीद है अगली गर्मी में विदेश यात्रा करूँगा।"),
                ("My goal is to become fluent in English.", "मेरा लक्ष्य अंग्रेज़ी में धाराप्रवाह होना है।"),
                ("I am thinking about learning a new skill.", "मैं एक नया कौशल सीखने के बारे में सोच रहा हूँ।"),
                ("In the future, I want to work in marketing.", "भविष्य में, मैं मार्केटिंग में काम करना चाहता हूँ।"),
                ("I am excited about what the future holds.", "मैं भविष्य के बारे में उत्साहित हूँ।"),
                ("My plan is to save money and invest.", "मेरी योजना पैसे बचाने और निवेश करने की है।"),
                ("I am working towards my dream career.", "मैं अपने सपनों के करियर की दिशा में काम कर रहा हूँ।"),
                ("I am confident that I will improve.", "मुझे विश्वास है कि मैं सुधार करूँगा।"),
                ("I am looking forward to the weekend.", "मैं वीकेंड का इंतज़ार कर रहा हूँ।"),
                ("My dream is to visit Paris one day.", "मेरा सपना किसी दिन पेरिस जाने का है।"),
                ("The best is yet to come!", "अभी तो सबसे अच्छा आना बाकी है!"),
                ("I am planning to buy a new car.", "मैं एक नई कार खरीदने की योजना बना रहा हूँ।"),
                ("We are going to move to a new city.", "हम एक नए शहर में जाने वाले हैं।"),
                ("I will finish my degree next year.", "मैं अगले साल अपनी डिग्री पूरी करूँगा।"),
                ("I am saving for a house.", "मैं घर के लिए पैसे बचा रहा हूँ।"),
                ("My future plans are clear to me.", "मेरी भविष्य की योजनाएँ मेरे लिए स्पष्ट हैं।"),
                ("I will work hard to achieve my goals.", "मैं अपने लक्ष्यों को पाने के लिए मेहनत करूँगा।"),
                ("We are planning a family vacation.", "हम एक पारिवारिक छुट्टी की योजना बना रहे हैं।"),
                ("I want to learn two more languages.", "मैं दो और भाषाएँ सीखना चाहता हूँ।"),
                ("I will start exercising regularly.", "मैं नियमित रूप से व्यायाम करना शुरू करूँगा।"),
                ("The future looks bright.", "भविष्य उज्ज्वल दिखता है।"),
                ("Plans give direction to life.", "योजनाएँ जीवन को दिशा देती हैं।"),
                ("I am ready for the next chapter.", "मैं अगले अध्याय के लिए तैयार हूँ।"),
            ]},
            {"title": "Social Conversations", "desc": "Engage in social conversations", "topic": "Social", "sentences": [
                ("How have you been? I have not seen you in ages!", "आप कैसे हैं? मैंने आपको बहुत दिनों में नहीं देखा!"),
                ("I am doing well, thanks for asking.", "मैं ठीक हूँ, पूछने के लिए धन्यवाद।"),
                ("Would you like to join us for dinner?", "क्या आप हमारे साथ खाने पर चलेंगे?"),
                ("I would love to come. Thank you for inviting me.", "मुझे बहुत खुशी होगी। आमंत्रित करने के लिए धन्यवाद।"),
                ("Let us catch up over coffee this weekend.", "चलो इस वीकेंड कॉफी पर मिलते हैं।"),
                ("I really enjoyed the party last night.", "मुझे कल रात की पार्टी बहुत अच्छी लगी।"),
                ("The food at the restaurant was amazing.", "रेस्तराँ का खाना अद्भुत था।"),
                ("I am planning a surprise party for my friend.", "मैं अपने दोस्त के लिए एक सरप्राइज़ पार्टी की योजना बना रहा हूँ।"),
                ("How was your vacation? Did you enjoy it?", "आपकी छुट्टियाँ कैसी रहीं? आपको मज़ा आया?"),
                ("I visited Goa with my family. It was fantastic.", "मैं अपने परिवार के साथ गोवा गया था। यह शानदार था।"),
                ("It was nice catching up with you.", "आपसे बातें करके अच्छा लगा।"),
                ("Let us do this again sometime!", "चलो फिर कभी ऐसा करते हैं!"),
                ("What have you been up to lately?", "आप इन दिनों क्या कर रहे हैं?"),
                ("Same old, same old. Working and studying.", "वही पुराना। काम और पढ़ाई।"),
                ("You know what I mean?", "आप जानते हैं मेरा क्या मतलब है?"),
                ("I see what you are saying.", "मैं समझ गया आप क्या कह रहे हैं।"),
                ("Tell me more about it.", "मुझे इसके बारे में और बताइए।"),
                ("By the way, did you hear about Ravi?", "वैसे, क्या आपने रवि के बारे में सुना?"),
                ("I have no idea what you are talking about.", "मुझे कोई अंदाज़ा नहीं है कि आप क्या बात कर रहे हैं।"),
                ("That is exactly what I was thinking!", "यह बिल्कुल वही है जो मैं सोच रहा था!"),
                ("You hit the nail on the head.", "आपने एकदम सही कहा।"),
                ("Let us not jump to conclusions.", "चलो जल्दबाज़ी में निष्कर्ष न निकालें।"),
                ("It is not a big deal, really.", "यह कोई बड़ी बात नहीं है, वास्तव में।"),
                ("Take it easy. Everything will work out.", "आराम से। सब कुछ ठीक हो जाएगा।"),
                ("I am just kidding! Do not take it seriously.", "मैं तो मज़ाक कर रहा था! इसे गंभीरता से मत लीजिए।"),
            ]},
            {"title": "Workplace Talk", "desc": "Talk at the workplace", "topic": "Workplace", "sentences": [
                ("Could you please review the report?", "क्या आप कृपया रिपोर्ट की समीक्षा कर सकते हैं?"),
                ("I will send you the updated file by evening.", "मैं आपको शाम तक अपडेटेड फ़ाइल भेज दूँगा।"),
                ("We need to discuss the project timeline.", "हमें परियोजना की समय-सीमा पर चर्चा करनी है।"),
                ("Let me know if you have any questions.", "अगर आपके कोई प्रश्न हैं तो मुझे बताइए।"),
                ("I am handling the new account.", "मैं नया अकाउंट संभाल रहा हूँ।"),
                ("The team did a great job on this project.", "टीम ने इस परियोजना पर बहुत अच्छा काम किया।"),
                ("Could you please finish this by tomorrow?", "क्या आप कृपया इसे कल तक खत्म कर सकते हैं?"),
                ("I need your input on the presentation.", "मुझे प्रेजेंटेशन पर आपके इनपुट की ज़रूरत है।"),
                ("Let me check with my manager first.", "मुझे पहले अपने प्रबंधक से पूछने दें।"),
                ("We are having a team meeting at 2 PM.", "हमारी दोपहर 2 बजे टीम मीटिंग है।"),
                ("I appreciate your hard work on this.", "मैं इस पर आपकी मेहनत की सराहना करता हूँ।"),
                ("Let me help you with that task.", "मुझे उस काम में आपकी मदद करने दें।"),
                ("I can handle this on my own, thank you.", "मैं इसे अकेले संभाल सकता हूँ, धन्यवाद।"),
                ("I will take the lead on this project.", "मैं इस परियोजना का नेतृत्व लूँगा।"),
                ("We need more resources for this task.", "हमें इस कार्य के लिए और संसाधन चाहिए।"),
                ("The meeting has been moved to 4 PM.", "मीटिंग शाम 4 बजे कर दी गई है।"),
                ("I will share the minutes by email.", "मैं मिनट्स ईमेल से साझा कर दूँगा।"),
                ("Let us schedule a follow-up meeting.", "चलो एक अनुवर्ती मीटिंग निर्धारित करते हैं।"),
                ("Your suggestion was very practical.", "आपका सुझाव बहुत व्यावहारिक था।"),
                ("We are working on the client's feedback.", "हम ग्राहक की प्रतिक्रिया पर काम कर रहे हैं।"),
                ("I will update the tracker now.", "मैं अभी ट्रैकर अपडेट कर दूँगा।"),
                ("Good communication solves half the problems.", "अच्छा संवाद आधी समस्याएँ हल कर देता है।"),
                ("We respect each other's time.", "हम एक-दूसरे के समय का सम्मान करते हैं।"),
                ("The office atmosphere is positive.", "ऑफिस का माहौल सकारात्मक है।"),
                ("I am proud of what we achieved together.", "मुझे गर्व है जो हमने मिलकर हासिल किया।"),
            ]},
            {"title": "Apologizing & Clarifying", "desc": "Apologize and clarify", "topic": "Apologizing", "sentences": [
                ("I sincerely apologize for the inconvenience.", "मैं असुविधा के लिए ईमानदारी से माफ़ी चाहता हूँ।"),
                ("Please accept my apologies for the delay.", "देरी के लिए कृपया मेरी माफ़ी स्वीकार करें।"),
                ("It was my mistake. I take full responsibility.", "यह मेरी गलती थी। मैं पूरी जिम्मेदारी लेता हूँ।"),
                ("I promise this will not happen again.", "मैं वादा करता हूँ ऐसा दोबारा नहीं होगा।"),
                ("I understand your frustration and I am sorry.", "मैं आपकी निराशा समझता हूँ और मुझे खेद है।"),
                ("Let me make it up to you.", "मुझे इसे सुधारने दें।"),
                ("I am really sorry for the confusion.", "भ्रम के लिए मैं वास्तव में खेद हूँ।"),
                ("I did not mean to offend you.", "मेरा आपको बुरा लगाने का इरादा नहीं था।"),
                ("Let me clarify what I meant.", "मुझे स्पष्ट करने दें कि मेरा क्या मतलब था।"),
                ("I think there has been a misunderstanding.", "मुझे लगता है कि कुछ गलतफहमी हुई है।"),
                ("Let me explain what actually happened.", "मुझे बताने दें कि वास्तव में क्या हुआ।"),
                ("I hope we can move past this.", "मुझे उम्मीद है हम इसे पीछे छोड़ सकते हैं।"),
                ("Your understanding is greatly appreciated.", "आपकी समझ की बहुत सराहना की जाती है।"),
                ("All is good. Let us move forward.", "सब ठीक है। चलो आगे बढ़ते हैं।"),
                ("I apologize for my late response.", "मैं अपने देर से जवाब के लिए क्षमा चाहता हूँ।"),
                ("Sorry, I was busy and could not reply.", "क्षमा करें, मैं व्यस्त था और जवाब नहीं दे सका।"),
                ("I am sorry for the misunderstanding.", "गलतफहमी के लिए मैं खेद हूँ।"),
                ("That is not what I meant to say.", "मेरा कहने का यह मतलब नहीं था।"),
                ("What I actually meant was this.", "मेरा वास्तव में यह मतलब था।"),
                ("Let me rephrase that.", "मुझे इसे दोबारा कहने दें।"),
                ("I owe you an apology.", "मैं आपसे माफ़ी माँगता हूँ।"),
                ("I will be more careful next time.", "मैं अगली बार और सावधान रहूँगा।"),
                ("Saying sorry sincerely repairs relationships.", "सच्ची माफ़ी रिश्तों को सुधारती है।"),
                ("Clarification prevents bigger problems.", "स्पष्टीकरण बड़ी समस्याओं को रोकता है।"),
                ("Thank you for giving me a chance to explain.", "मुझे समझाने का मौका देने के लिए धन्यवाद।"),
            ]},
            {"title": "Making Arrangements", "desc": "Make arrangements", "topic": "Arrangements", "sentences": [
                ("I would like to schedule a meeting for next Tuesday.", "मैं अगले मंगलवार के लिए एक मीटिंग शेड्यूल करना चाहूँगा।"),
                ("Does Thursday work for you?", "क्या गुरुवार आपके लिए ठीक है?"),
                ("Let me check the availability of the room.", "मुझे कमरे की उपलब्धता देखने दें।"),
                ("I am afraid I have to cancel our appointment.", "मुझे डर है कि मुझे हमारा अपॉइंटमेंट कैंसल करना होगा।"),
                ("Something urgent has come up.", "कुछ ज़रूरी काम आ गया है।"),
                ("I am sorry, but I will not be able to make it.", "माफ़ कीजिए, लेकिन मैं नहीं आ पाऊँगा।"),
                ("Can we reschedule for another day?", "क्या हम किसी और दिन के लिए रीशेड्यूल कर सकते हैं?"),
                ("The venue is confirmed for the event.", "इवेंट के लिए स्थान की पुष्टि हो गई है।"),
                ("I will arrange the transportation for the team.", "मैं टीम के लिए परिवहन की व्यवस्था करूँगा।"),
                ("Everything is set for the launch.", "लॉन्च के लिए सब कुछ तैयार है।"),
                ("I will confirm all the bookings by tomorrow.", "मैं कल तक सभी बुकिंग की पुष्टि कर दूँगा।"),
                ("Let us fix a time that suits everyone.", "चलो एक ऐसा समय तय करते हैं जो सबको सूट करे।"),
                ("I will book the tickets today.", "मैं आज टिकट बुक कर दूँगा।"),
                ("The arrangements are all done.", "सारी व्यवस्थाएँ पूरी हो गई हैं।"),
                ("Please confirm your availability.", "कृपया अपनी उपलब्धता की पुष्टि करें।"),
                ("We need to arrange a projector for the meeting.", "हमें मीटिंग के लिए एक प्रोजेक्टर की व्यवस्था करनी है।"),
                ("The hotel booking is confirmed.", "होटल बुकिंग कन्फर्म हो गई है।"),
                ("I will pick you up from the station.", "मैं आपको स्टेशन से लेने आऊँगा।"),
                ("The meeting will be held online.", "मीटिंग ऑनलाइन होगी।"),
                ("We arranged everything perfectly.", "हमने सब कुछ बिल्कुल सही व्यवस्थित किया।"),
                ("Planning ahead makes arrangements easy.", "पहले से योजना बनाने से व्यवस्थाएँ आसान होती हैं।"),
                ("I will send you the invitation details.", "मैं आपको आमंत्रण का विवरण भेज दूँगा।"),
                ("Let us coordinate the logistics.", "चलो रसद का समन्वय करते हैं।"),
                ("Everything went according to plan.", "सब कुछ योजना के अनुसार हुआ।"),
                ("Good planning leads to smooth events.", "अच्छी योजना सुचारू आयोजन की ओर ले जाती है।"),
            ]},
            {"title": "Giving Reasons", "desc": "Give reasons and explanations", "topic": "Reasons", "sentences": [
                ("The reason I am saying this is because of safety.", "मैं ऐसा इसलिए कह रहा हूँ क्योंकि सुरक्षा महत्वपूर्ण है।"),
                ("Let me give you an example to illustrate.", "मुझे आपको एक उदाहरण देकर समझाने दें।"),
                ("What I mean is that we need more time.", "मेरा मतलब यह है कि हमें और समय चाहिए।"),
                ("The main reason for this decision is cost.", "इस निर्णय का मुख्य कारण लागत है।"),
                ("I chose this option because it is more efficient.", "मैंने यह विकल्प चुना क्योंकि यह अधिक कुशल है।"),
                ("There are three reasons for this.", "इसके तीन कारण हैं।"),
                ("First of all, it saves time.", "सबसे पहले, यह समय बचाता है।"),
                ("Secondly, it is more affordable.", "दूसरा, यह अधिक किफायती है।"),
                ("Finally, it is better for the environment.", "अंत में, यह पर्यावरण के लिए बेहतर है।"),
                ("In simple terms, the system is not working.", "सीधे शब्दों में, सिस्टम काम नहीं कर रहा है।"),
                ("Let me put it this way.", "मुझे इसे इस तरह से समझाने दें।"),
                ("The basic idea is very simple.", "मूल विचार बहुत सरल है।"),
                ("I would like to add something to that point.", "मैं उस बिंदु पर कुछ जोड़ना चाहूँगा।"),
                ("Let me expand on what I said earlier.", "मुझे अपनी पिछली बात का विस्तार करने दें।"),
                ("The reason we failed is lack of planning.", "हमारी असफलता का कारण योजना की कमी है।"),
                ("That explains why the project got delayed.", "इससे पता चलता है कि परियोजना क्यों विलंबित हुई।"),
                ("I think I have made my point clear.", "मुझे लगता है मैंने अपनी बात स्पष्ट कर दी है।"),
                ("Does that make sense to you?", "क्या यह आपको समझ में आया?"),
                ("I am glad you asked that question.", "मुझे खुशी है कि आपने यह सवाल पूछा।"),
                ("The reason behind this change is customer feedback.", "इस बदलाव के पीछे का कारण ग्राहक प्रतिक्रिया है।"),
                ("Let me show you how this works.", "मुझे आपको दिखाने दें कि यह कैसे काम करता है।"),
                ("This is a classic example of good teamwork.", "यह अच्छी टीमवर्क का एक उत्कृष्ट उदाहरण है।"),
                ("Giving clear reasons builds understanding.", "स्पष्ट कारण बताने से समझ बनती है।"),
                ("Logic supports every good decision.", "तर्क हर अच्छे निर्णय का समर्थन करता है।"),
                ("Explaining well is a valuable skill.", "अच्छी तरह समझाना एक मूल्यवान कौशल है।"),
            ]},
            {"title": "Comparing & Choosing", "desc": "Compare things and choose", "topic": "Comparing", "sentences": [
                ("This restaurant is better than the one we went to last time.", "यह रेस्तराँ पिछली बार वाले से बेहतर है।"),
                ("I prefer tea over coffee in the morning.", "मैं सुबह कॉफी की तुलना में चाय पसंद करता हूँ।"),
                ("Between the two, I would choose the blue one.", "इन दोनों में से, मैं नीला वाला चुनूँगा।"),
                ("This option is more cost-effective than the other.", "यह विकल्प दूसरे की तुलना में अधिक लागत-प्रभावी है।"),
                ("The quality is much better than I expected.", "गुणवत्ता मेरी उम्मीद से कहीं बेहतर है।"),
                ("I like this one because it is more practical.", "मुझे यह पसंद है क्योंकि यह अधिक व्यावहारिक है।"),
                ("My first preference is to work from home.", "मेरी पहली पसंद घर से काम करना है।"),
                ("Compared to last year, sales have increased.", "पिछले साल की तुलना में, बिक्री में वृद्धि हुई है।"),
                ("This is the most affordable option available.", "यह उपलब्ध सबसे किफायती विकल्प है।"),
                ("I would rather stay home than go out today.", "मैं आज बाहर जाने की बजाय घर पर रहना पसंद करूँगा।"),
                ("Neither option is ideal, but this one is better.", "कोई भी विकल्प आदर्श नहीं है, लेकिन यह बेहतर है।"),
                ("The difference between these two is significant.", "इन दोनों के बीच अंतर महत्वपूर्ण है।"),
                ("I have a strong preference for morning shifts.", "मुझे सुबह की शिफ्ट की प्रबल प्राथमिकता है।"),
                ("Which one do you think is better?", "आपको कौन सा बेहतर लगता है?"),
                ("This is similar to what we discussed earlier.", "यह वैसा ही है जैसा हमने पहले चर्चा की थी।"),
                ("Both are good, but my favourite is the red one.", "दोनों अच्छे हैं, लेकिन मेरा पसंदीदा लाल वाला है।"),
                ("I would not recommend that option.", "मैं उस विकल्प की सिफारिश नहीं करूँगा।"),
                ("The new version is far more user-friendly.", "नया वर्शन कहीं अधिक उपयोगकर्ता-अनुकूल है।"),
                ("If you ask me, this is the best choice.", "अगर आप मुझसे पूछें, यह सबसे अच्छा विकल्प है।"),
                ("The only difference is the colour.", "एकमात्र अंतर रंग का है।"),
                ("This model outperforms the previous one.", "यह मॉडल पिछले वाले से बेहतर प्रदर्शन करता है।"),
                ("I think I will go with your suggestion.", "मुझे लगता है मैं आपके सुझाव के साथ चलूँगा।"),
                ("At the end of the day, it comes down to preference.", "आखिरकार, यह पसंद पर निर्भर करता है।"),
                ("Comparing options helps us decide wisely.", "विकल्पों की तुलना करने से हमें समझदारी से निर्णय लेने में मदद मिलती है।"),
                ("Choose what suits you best.", "वह चुनिए जो आपके लिए सबसे उपयुक्त हो।"),
            ]},
            {"title": "Difficult Situations", "desc": "Handle difficult situations", "topic": "Difficult", "sentences": [
                ("This is not an easy situation to handle.", "यह संभालना आसान स्थिति नहीं है।"),
                ("I am trying to stay calm under pressure.", "मैं दबाव में शांत रहने की कोशिश कर रहा हूँ।"),
                ("Let us take a step back and think.", "चलो एक कदम पीछे हटकर सोचते हैं।"),
                ("I know this is a stressful situation.", "मुझे पता है यह एक तनावपूर्ण स्थिति है।"),
                ("We need to find a way out of this mess.", "हमें इस उलझन से बाहर निकलने का रास्ता खोजना होगा।"),
                ("I need to make a difficult choice.", "मुझे एक कठिन चुनाव करना है।"),
                ("Whatever I decide, I will stick with it.", "जो भी निर्णय लूँगा, उस पर अडिग रहूँगा।"),
                ("Let us not panic. We can solve this.", "चलो घबराएँ नहीं। हम इसे हल कर सकते हैं।"),
                ("I have considered all the alternatives.", "मैंने सभी विकल्पों पर विचार कर लिया है।"),
                ("The best course of action is to wait.", "सबसे अच्छा कदम इंतज़ार करना है।"),
                ("I never back down from a challenge.", "मैं कभी चुनौती से पीछे नहीं हटता।"),
                ("This is a test of our patience.", "यह हमारे धैर्य की परीक्षा है।"),
                ("I believe we can turn this around.", "मुझे विश्वास है हम इसे बदल सकते हैं।"),
                ("Sometimes you have to take a leap of faith.", "कभी-कभी आपको विश्वास की छलांग लगानी पड़ती है।"),
                ("I will support whatever you decide.", "जो भी आप तय करेंगे, मैं उसका समर्थन करूँगा।"),
                ("We can get through this together.", "हम एक साथ इससे उबर सकते हैं।"),
                ("Every problem has a solution.", "हर समस्या का एक समाधान है।"),
                ("I am proud of how we handled this.", "मुझे गर्व है कि हमने इसे कैसे संभाला।"),
                ("Stay positive even in tough times.", "कठिन समय में भी सकारात्मक रहिए।"),
                ("Difficulties make us stronger.", "कठिनाइयाँ हमें मजबूत बनाती हैं।"),
                ("We faced the situation bravely.", "हमने स्थिति का साहस से सामना किया।"),
                ("There is always a way forward.", "आगे बढ़ने का रास्ता हमेशा होता है।"),
                ("I learned to stay calm in crises.", "मैंने संकट में शांत रहना सीखा।"),
                ("One step at a time solves everything.", "एक-एक कदम सब कुछ हल कर देता है।"),
                ("We came out stronger from this situation.", "हम इस स्थिति से और मजबूत होकर निकले।"),
            ]},
            {"title": "Natural Conversations", "desc": "Speak naturally", "topic": "Natural", "sentences": [
                ("So, what have you been up to lately?", "तो, आप इन दिनों क्या कर रहे हैं?"),
                ("I have been working on a new project.", "मैं एक नई परियोजना पर काम कर रहा हूँ।"),
                ("That is awesome! Tell me more.", "यह बहुत बढ़िया है! और बताइए।"),
                ("Honestly, I was quite surprised.", "सच कहूँ तो, मैं काफी हैरान था।"),
                ("You would not believe what happened.", "आप विश्वास नहीं करेंगे कि क्या हुआ।"),
                ("Guess what! I got the job!", "अंदाज़ा लगाइए! मुझे नौकरी मिल गई!"),
                ("No way! Congratulations!", "नहीं! बधाई हो!"),
                ("To be honest, I was not expecting that.", "सच कहूँ तो, मुझे ऐसी उम्मीद नहीं थी।"),
                ("It was a pleasant surprise.", "यह एक सुखद आश्चर्य था।"),
                ("I am really happy for you.", "मैं आपके लिए वाकई खुश हूँ।"),
                ("Let us celebrate this good news!", "चलो इस अच्छी खबर का जश्न मनाते हैं!"),
                ("What do you think about this idea?", "आप इस विचार के बारे में क्या सोचते हैं?"),
                ("I think it could work.", "मुझे लगता है यह काम कर सकता है।"),
                ("Let us try it and see.", "चलो इसे आज़माकर देखते हैं।"),
                ("That is a smart move.", "यह एक समझदारी भरा कदम है।"),
                ("I will keep you updated.", "मैं आपको अपडेट करता रहूँगा।"),
                ("Sounds good to me.", "मुझे ठीक लगता है।"),
                ("Let me think about it first.", "मुझे पहले इसके बारे में सोचने दें।"),
                ("I am in! Let us do it.", "मैं तैयार हूँ! चलो करते हैं।"),
                ("That is the best news today!", "यह आज की सबसे अच्छी खबर है!"),
                ("We should do this more often.", "हमें ऐसा और अक्सर करना चाहिए।"),
                ("It was great talking to you.", "आपसे बात करके बहुत अच्छा लगा।"),
                ("Catch you later!", "बाद में मिलते हैं!"),
                ("Stay in touch, okay?", "संपर्क में रहिए, ठीक है?"),
                ("Natural English comes with practice.", "प्राकृतिक अंग्रेज़ी अभ्यास से आती है।"),
            ]},
            {"title": "Fluency Practice", "desc": "Improve your fluency", "topic": "Fluency", "sentences": [
                ("I need to work on my communication skills.", "मुझे अपने संचार कौशल पर काम करने की ज़रूरत है।"),
                ("Practice makes perfect. Keep going!", "अभ्यास से निपुणता आती है। चलते रहिए!"),
                ("I try to speak English whenever I can.", "मैं जब भी हो सके अंग्रेज़ी बोलने की कोशिश करता हूँ।"),
                ("Speaking fluently takes time and effort.", "धाराप्रवाह रूप से बोलने में समय और प्रयास लगता है।"),
                ("I am getting better every single day.", "मैं हर एक दिन बेहतर हो रहा हूँ।"),
                ("Let us practice together! We can help each other.", "चलो एक साथ अभ्यास करें! हम एक-दूसरे की मदद कर सकते हैं।"),
                ("The more you speak, the more confident you become.", "जितना अधिक आप बोलते हैं, उतने ही आत्मविश्वासी बनते हैं।"),
                ("I can express my thoughts better now.", "मैं अब अपने विचार बेहतर ढंग से व्यक्त कर सकता हूँ।"),
                ("Keep pushing your limits and you will improve!", "अपनी सीमाओं को बढ़ाते रहिए और आप सुधार करेंगे!"),
                ("I speak English without thinking too much now.", "मैं अब बिना ज्यादा सोचे अंग्रेज़ी बोल लेता हूँ।"),
                ("My friends notice my improvement.", "मेरे दोस्तों ने मेरा सुधार देखा है।"),
                ("Fluency means speaking smoothly.", "धाराप्रवाहता का मतलब है सहज रूप से बोलना।"),
                ("I practice with audio lessons daily.", "मैं रोज़ ऑडियो पाठों के साथ अभ्यास करता हूँ।"),
                ("Repeating sentences builds muscle memory.", "वाक्यों को दोहराने से मांसपेशियों की स्मृति बनती है।"),
                ("I am not afraid to make mistakes anymore.", "मुझे अब गलतियाँ करने का डर नहीं है।"),
                ("Speaking in English feels natural now.", "अब अंग्रेज़ी बोलना स्वाभाविक लगता है।"),
                ("I think in English sometimes.", "मैं कभी-कभी अंग्रेज़ी में सोचता हूँ।"),
                ("Consistent practice brings fluency.", "निरंतर अभ्यास धाराप्रवाहता लाता है।"),
                ("I set small speaking goals daily.", "मैं रोज़ छोटे बोलने के लक्ष्य निर्धारित करता हूँ।"),
                ("Every conversation is a practice session.", "हर बातचीत एक अभ्यास सत्र है।"),
                ("I am becoming a fluent speaker.", "मैं एक धाराप्रवाह वक्ता बन रहा हूँ।"),
                ("Do not compare yourself with others.", "अपनी तुलना दूसरों से मत कीजिए।"),
                ("Focus on your own progress.", "अपनी खुद की प्रगति पर ध्यान दीजिए।"),
                ("Fluency opens many doors in life.", "धाराप्रवाहता जीवन में कई दरवाज़े खोलती है।"),
                ("I am proud of my speaking journey.", "मुझे अपनी बोलने की यात्रा पर गर्व है।"),
            ]},
        ],
    }
