def get_kids_banks():
    return {
        "course_id": "kids",
        "title": "Kids English",
        "desc": "Fun and simple English for children - colours, animals, games, and everyday things.",
        "short": "Learn English the fun way",
        "icon": "👶",
        "color": "accent",
        "difficulty": "Beginner",
        "audience": ["Kids", "Young Learners", "Parents"],
        "price": "₹149",
        "lessons": [
            {"title": "Greetings for Kids", "desc": "Say hello like a pro", "topic": "Greetings", "sentences": [
                ("Hello! My name is Riya.", "नमस्ते! मेरा नाम रिया है।"),
                ("Good morning, Mummy!", "सुप्रभात, मम्मी!"),
                ("Good night, Daddy!", "शुभ रात्रि, पापा!"),
                ("Hi! How are you?", "नमस्ते! आप कैसे हैं?"),
                ("I am fine, thank you!", "मैं ठीक हूँ, धन्यवाद!"),
                ("Nice to meet you!", "आपसे मिलकर खुशी हुई!"),
                ("Welcome to my home!", "मेरे घर में आपका स्वागत है!"),
                ("See you tomorrow!", "कल मिलते हैं!"),
                ("Goodbye! Have a nice day!", "अलविदा! आपका दिन अच्छा रहे!"),
                ("Please come in!", "कृपया अंदर आइए!"),
                ("Thank you very much!", "बहुत-बहुत धन्यवाद!"),
                ("You are welcome!", "आपका स्वागत है!"),
                ("May I come in?", "क्या मैं अंदर आ सकता हूँ?"),
                ("Hello, friend! How are you today?", "नमस्ते, दोस्त! आज तुम कैसे हो?"),
                ("I am happy to see you!", "मुझे तुम्हें देखकर खुशी हुई!"),
                ("Take care of yourself!", "अपना ख्याल रखना!"),
                ("Sweet dreams!", "मीठे सपने!"),
                ("Good morning to everyone!", "सबको सुप्रभात!"),
                ("I like your smile!", "मुझे तुम्हारी मुस्कान पसंद है!"),
                ("Have a fun day!", "तुम्हारा दिन मज़ेदार रहे!"),
                ("Please sit down.", "कृपया बैठ जाओ।"),
                ("What is your name?", "तुम्हारा नाम क्या है?"),
                ("My name is Aarav.", "मेरा नाम आरव है।"),
                ("How old are you?", "तुम कितने साल के हो?"),
                ("I am six years old.", "मैं छह साल का हूँ।"),
            ]},
            {"title": "My Family", "desc": "Talk about family", "topic": "Family", "sentences": [
                ("This is my mother.", "यह मेरी माँ हैं।"),
                ("My father is very strong.", "मेरे पिता बहुत ताकतवर हैं।"),
                ("I love my family.", "मैं अपने परिवार से प्यार करता हूँ।"),
                ("My grandmother tells me stories.", "मेरी दादी मुझे कहानियाँ सुनाती हैं।"),
                ("My grandfather is my hero.", "मेरे दादाजी मेरे हीरो हैं।"),
                ("I have one brother.", "मेरा एक भाई है।"),
                ("My sister is very cute.", "मेरी बहन बहुत प्यारी है।"),
                ("My uncle gave me a toy.", "मेरे चाचा ने मुझे एक खिलौना दिया।"),
                ("My aunt is a teacher.", "मेरी चाची एक शिक्षिका हैं।"),
                ("We all live together.", "हम सब साथ रहते हैं।"),
                ("My mother cooks for us.", "मेरी माँ हमारे लिए खाना बनाती हैं।"),
                ("My father plays with me.", "मेरे पिता मेरे साथ खेलते हैं।"),
                ("I hug my mother every morning.", "मैं हर सुबह अपनी माँ को गले लगाता हूँ।"),
                ("My family loves me.", "मेरा परिवार मुझसे प्यार करता है।"),
                ("We eat together.", "हम साथ मिलकर खाते हैं।"),
                ("My cousin is my best friend.", "मेरा चचेरा भाई मेरा सबसे अच्छा दोस्त है।"),
                ("I help my mother at home.", "मैं घर पर अपनी माँ की मदद करता हूँ।"),
                ("My father reads me stories.", "मेरे पिता मुझे कहानियाँ पढ़कर सुनाते हैं।"),
                ("We go for a walk together.", "हम साथ टहलने जाते हैं।"),
                ("I love my little sister.", "मैं अपनी छोटी बहन से प्यार करता हूँ।"),
                ("My family is the best!", "मेरा परिवार सबसे अच्छा है!"),
                ("Grandma makes yummy food.", "दादी बहुत स्वादिष्ट खाना बनाती हैं।"),
                ("I like playing with my family.", "मुझे अपने परिवार के साथ खेलना पसंद है।"),
                ("My mother kisses me goodnight.", "मेरी माँ मुझे गुडनाइट किस करती हैं।"),
                ("Family is love.", "परिवार ही प्यार है।"),
            ]},
            {"title": "Colours & Shapes", "desc": "Learn colours and shapes", "topic": "Colours", "sentences": [
                ("The sky is blue.", "आसमान नीला है।"),
                ("I have a red ball.", "मेरे पास एक लाल गेंद है।"),
                ("The grass is green.", "घास हरी है।"),
                ("My favourite colour is yellow.", "मेरा पसंदीदा रंग पीला है।"),
                ("The sun is orange.", "सूरज नारंगी है।"),
                ("I like the pink dress.", "मुझे गुलाबी ड्रेस पसंद है।"),
                ("The clouds are white.", "बादल सफेद हैं।"),
                ("The night sky is black.", "रात का आसमान काला होता है।"),
                ("The apple is red.", "सेब लाल है।"),
                ("The banana is yellow.", "केला पीला है।"),
                ("The tree is green and brown.", "पेड़ हरा और भूरा है।"),
                ("This is a circle.", "यह एक गोला है।"),
                ("The box is square.", "डिब्बा चौकोर है।"),
                ("The table is rectangular.", "मेज़ आयताकार है।"),
                ("The star has five points.", "तारे के पाँच कोने होते हैं।"),
                ("I drew a triangle.", "मैंने एक त्रिकोण बनाया।"),
                ("The ball is round.", "गेंद गोल है।"),
                ("My dress is purple.", "मेरी ड्रेस बैंगनी है।"),
                ("The parrot is green.", "तोता हरा होता है।"),
                ("What colour is this?", "यह किस रंग का है?"),
                ("This is my favourite colour!", "यह मेरा पसंदीदा रंग है!"),
                ("Let us colour the picture.", "चलो चित्र को रंग भरते हैं।"),
                ("I have a rainbow of colours.", "मेरे पास रंगों का इंद्रधनुष है।"),
                ("Colours make the world beautiful.", "रंग दुनिया को सुंदर बनाते हैं।"),
                ("I love bright colours!", "मुझे चटक रंग बहुत पसंद हैं!"),
            ]},
            {"title": "Animals", "desc": "Learn about animals", "topic": "Animals", "sentences": [
                ("The cat says meow.", "बिल्ली म्याऊँ करती है।"),
                ("The dog says bow wow.", "कुत्ता भौं-भौं करता है।"),
                ("The cow gives us milk.", "गाय हमें दूध देती है।"),
                ("The elephant is very big.", "हाथी बहुत बड़ा होता है।"),
                ("The lion is the king of the jungle.", "शेर जंगल का राजा है।"),
                ("I have a pet rabbit.", "मेरे पास एक पालतू खरगोश है।"),
                ("The monkey likes bananas.", "बंदर को केले पसंद हैं।"),
                ("The horse runs fast.", "घोड़ा तेज़ दौड़ता है।"),
                ("The hen gives us eggs.", "मुर्गी हमें अंडे देती है।"),
                ("The fish swims in water.", "मछली पानी में तैरती है।"),
                ("The bird flies in the sky.", "पक्षी आसमान में उड़ता है।"),
                ("The tiger has stripes.", "बाघ पर धारियाँ होती हैं।"),
                ("The giraffe has a long neck.", "जिराफ़ की गर्दन लंबी होती है।"),
                ("The frog jumps high.", "मेंढक ऊँचा कूदता है।"),
                ("The snake crawls on the ground.", "साँप ज़मीन पर रेंगता है।"),
                ("The goat eats grass.", "बकरी घास खाती है।"),
                ("The bee makes honey.", "मधुमक्खी शहद बनाती है।"),
                ("The duck swims in the pond.", "बत्तख तालाब में तैरती है।"),
                ("The mouse is small.", "चूहा छोटा होता है।"),
                ("What is your favourite animal?", "तुम्हारा पसंदीदा जानवर कौन सा है?"),
                ("My favourite animal is the dog.", "मेरा पसंदीदा जानवर कुत्ता है।"),
                ("The animals are our friends.", "जानवर हमारे दोस्त हैं।"),
                ("I like going to the zoo.", "मुझे चिड़ियाघर जाना पसंद है।"),
                ("We should be kind to animals.", "हमें जानवरों के साथ दयालु होना चाहिए।"),
                ("The baby animals are so cute!", "जानवरों के बच्चे बहुत प्यारे होते हैं!"),
            ]},
            {"title": "Food & Sweets", "desc": "Talk about food kids love", "topic": "Food", "sentences": [
                ("I like ice cream.", "मुझे आइसक्रीम पसंद है।"),
                ("Chocolate is so yummy!", "चॉकलेट बहुत स्वादिष्ट होती है!"),
                ("I eat an apple every day.", "मैं हर दिन एक सेब खाता हूँ।"),
                ("Milk makes me strong.", "दूध मुझे मज़बूत बनाता है।"),
                ("I like pizza and pasta.", "मुझे पिज़्ज़ा और पास्ता पसंद है।"),
                ("The cake is delicious.", "केक बहुत स्वादिष्ट है।"),
                ("I drink water when I am thirsty.", "प्यास लगने पर मैं पानी पीता हूँ।"),
                ("I like mangoes in summer.", "मुझे गर्मी में आम पसंद हैं।"),
                ("My mother makes tasty parathas.", "मेरी माँ स्वादिष्ट पराठे बनाती हैं।"),
                ("I like eating vegetables too.", "मुझे सब्ज़ियाँ खाना भी पसंद है।"),
                ("The juice is sweet.", "जूस मीठा है।"),
                ("I have biscuits with my milk.", "मैं दूध के साथ बिस्कुट खाता हूँ।"),
                ("Breakfast is ready!", "नाश्ता तैयार है!"),
                ("I wash my hands before eating.", "मैं खाने से पहले हाथ धोता हूँ।"),
                ("The fruits are healthy.", "फल स्वास्थ्य के लिए अच्छे होते हैं।"),
                ("I like eating sweets on festivals.", "मुझे त्योहारों पर मिठाई खाना पसंद है।"),
                ("Do not eat too many chocolates.", "बहुत सारी चॉकलेट मत खाओ।"),
                ("Eat your lunch properly.", "अपना खाना ठीक से खाओ।"),
                ("I am hungry now.", "मुझे अब भूख लगी है।"),
                ("The soup is hot. Be careful.", "सूप गर्म है। सावधान रहो।"),
                ("I like fruit salad.", "मुझे फ्रूट सलाद पसंद है।"),
                ("Food is yummy!", "खाना बहुत स्वादिष्ट है!"),
                ("I eat with my family.", "मैं अपने परिवार के साथ खाता हूँ।"),
                ("I drink milk before sleeping.", "मैं सोने से पहले दूध पीता हूँ।"),
                ("Healthy food gives us energy.", "स्वस्थ भोजन हमें ऊर्जा देता है।"),
            ]},
            {"title": "My Toys", "desc": "Talk about toys", "topic": "Toys", "sentences": [
                ("I have a toy car.", "मेरे पास एक खिलौना कार है।"),
                ("My teddy bear is soft.", "मेरा टेडी बियर मुलायम है।"),
                ("I play with my blocks.", "मैं अपने ब्लॉक से खेलता हूँ।"),
                ("The ball is my favourite toy.", "गेंद मेरा पसंदीदा खिलौना है।"),
                ("I have a toy train.", "मेरे पास एक खिलौना ट्रेन है।"),
                ("My doll has beautiful hair.", "मेरी गुड़िया के सुंदर बाल हैं।"),
                ("I build a castle with blocks.", "मैं ब्लॉक से महल बनाता हूँ।"),
                ("Can I play with your toy?", "क्या मैं तुम्हारे खिलौने से खेल सकता हूँ?"),
                ("I share my toys with my friends.", "मैं अपने दोस्तों के साथ खिलौने साझा करता हूँ।"),
                ("My toys are clean.", "मेरे खिलौने साफ हैं।"),
                ("The puzzle has many pieces.", "पहेली में कई टुकड़े हैं।"),
                ("I like my toy robot.", "मुझे अपना खिलौना रोबोट पसंद है।"),
                ("I keep my toys in the box.", "मैं अपने खिलौने डिब्बे में रखता हूँ।"),
                ("The kite flies high.", "पतंग ऊँची उड़ती है।"),
                ("I got a new toy today!", "मुझे आज एक नया खिलौना मिला!"),
                ("The toy drum makes noise.", "खिलौना ढोल आवाज़ करता है।"),
                ("I love my toys very much.", "मैं अपने खिलौनों से बहुत प्यार करता हूँ।"),
                ("Let us play together.", "चलो साथ मिलकर खेलते हैं।"),
                ("My toys teach me new things.", "मेरे खिलौने मुझे नई चीज़ें सिखाते हैं।"),
                ("The balloon is red and round.", "गुब्बारा लाल और गोल है।"),
                ("I ride my toy bicycle.", "मैं अपनी खिलौना साइकिल चलाता हूँ।"),
                ("Please share your toys.", "कृपया अपने खिलौने साझा करो।"),
                ("Playing with toys is fun.", "खिलौनों से खेलना मज़ेदार है।"),
                ("I put my toys away after playing.", "खेलने के बाद मैं अपने खिलौने रख देता हूँ।"),
                ("Toys make childhood special.", "खिलौने बचपन को खास बनाते हैं।"),
            ]},
            {"title": "Body Parts", "desc": "Learn body parts", "topic": "Body", "sentences": [
                ("I have two eyes.", "मेरी दो आँखें हैं।"),
                ("I see with my eyes.", "मैं अपनी आँखों से देखता हूँ।"),
                ("I hear with my ears.", "मैं अपने कानों से सुनता हूँ।"),
                ("I smell with my nose.", "मैं अपनी नाक से सूँघता हूँ।"),
                ("I taste with my tongue.", "मैं अपनी जीभ से स्वाद लेता हूँ।"),
                ("I touch with my hands.", "मैं अपने हाथों से छूता हूँ।"),
                ("I have ten fingers.", "मेरे दस उँगलियाँ हैं।"),
                ("I walk with my legs.", "मैं अपने पैरों से चलता हूँ।"),
                ("My hair is black.", "मेरे बाल काले हैं।"),
                ("I brush my teeth twice a day.", "मैं दिन में दो बार दाँत साफ करता हूँ।"),
                ("My heart beats fast when I run.", "दौड़ने पर मेरा दिल तेज़ धड़कता है।"),
                ("I have a big smile.", "मेरी मुस्कान बड़ी है।"),
                ("I use my brain to think.", "मैं सोचने के लिए अपने दिमाग का उपयोग करता हूँ।"),
                ("My shoulders are strong.", "मेरे कंधे मज़बूत हैं।"),
                ("I have ten toes.", "मेरे दस पैर की उँगलियाँ हैं।"),
                ("I point with my finger.", "मैं अपनी उँगली से इशारा करता हूँ।"),
                ("I nod my head.", "मैं अपना सिर हिलाता हूँ।"),
                ("I clap my hands.", "मैं ताली बजाता हूँ।"),
                ("I stamp my feet.", "मैं अपने पैर पटकता हूँ।"),
                ("My knees help me bend.", "मेरे घुटने मुझे झुकने में मदद करते हैं।"),
                ("I wash my face in the morning.", "मैं सुबह अपना चेहरा धोता हूँ।"),
                ("My skin keeps me safe.", "मेरी त्वचा मुझे सुरक्षित रखती है।"),
                ("I am growing taller every year.", "मैं हर साल लंबा हो रहा हूँ।"),
                ("I take care of my body.", "मैं अपने शरीर का ख्याल रखता हूँ।"),
                ("My body is amazing!", "मेरा शरीर अद्भुत है!"),
            ]},
            {"title": "Games & Fun", "desc": "Play games and have fun", "topic": "Games", "sentences": [
                ("Let us play hide and seek!", "चलो लुका-छिपी खेलते हैं!"),
                ("I am it! You can run!", "मैं पकड़ने वाला हूँ! तुम भाग सकते हो!"),
                ("I found you!", "मैंने तुम्हें ढूँढ लिया!"),
                ("You are a fast runner!", "तुम बहुत तेज़ दौड़ते हो!"),
                ("Let us play with the ball.", "चलो गेंद से खेलते हैं।"),
                ("Catch the ball!", "गेंद पकड़ो!"),
                ("I can jump very high.", "मैं बहुत ऊँचा कूद सकता हूँ।"),
                ("Let us play a board game.", "चलो बोर्ड गेम खेलते हैं।"),
                ("It is your turn now.", "अब तुम्हारी बारी है।"),
                ("I won the game!", "मैंने खेल जीत लिया!"),
                ("Good game, well played!", "अच्छा खेल, शाबाश!"),
                ("Let us play again.", "चलो फिर खेलते हैं।"),
                ("I like playing tag.", "मुझे पकड़-पकड़ाई खेलना पसंद है।"),
                ("The swing is fun!", "झूला बहुत मज़ेदार है!"),
                ("I can slide down the slide.", "मैं फिसलपट्टी से फिसल सकता हूँ।"),
                ("Let us make a sandcastle.", "चलो रेत का महल बनाते हैं।"),
                ("I love playing outside.", "मुझे बाहर खेलना बहुत पसंद है।"),
                ("You play very well.", "तुम बहुत अच्छा खेलते हो।"),
                ("Let us be on the same team.", "चलो एक ही टीम में रहते हैं।"),
                ("Ready, set, go!", "तैयार, जाओ!"),
                ("I am the winner!", "मैं विजेता हूँ!"),
                ("We should play fair.", "हमें निष्पक्ष खेलना चाहिए।"),
                ("Playing makes me happy.", "खेलने से मुझे खुशी मिलती है।"),
                ("Let us play until sunset.", "चलो सूर्यास्त तक खेलते हैं।"),
                ("Playing with friends is the best!", "दोस्तों के साथ खेलना सबसे अच्छा है!"),
            ]},
            {"title": "My Feelings", "desc": "Express feelings", "topic": "Feelings", "sentences": [
                ("I am happy!", "मैं खुश हूँ!"),
                ("I am sad.", "मैं उदास हूँ।"),
                ("I am excited!", "मैं उत्साहित हूँ!"),
                ("I am scared of the dark.", "मुझे अंधेरे से डर लगता है।"),
                ("I feel sleepy.", "मुझे नींद आ रही है।"),
                ("I am surprised!", "मैं हैरान हूँ!"),
                ("I am angry.", "मैं गुस्से में हूँ।"),
                ("I feel shy.", "मुझे शर्म आ रही है।"),
                ("I am proud of myself.", "मुझे खुद पर गर्व है।"),
                ("I feel loved.", "मुझे प्यार महसूस होता है।"),
                ("I am nervous about the test.", "मैं टेस्ट को लेकर घबराया हुआ हूँ।"),
                ("Do not cry. It is okay.", "मत रोओ। सब ठीक है।"),
                ("I feel brave today.", "मैं आज बहादुर महसूस कर रहा हूँ।"),
                ("I am curious about this.", "मैं इसके बारे में उत्सुक हूँ।"),
                ("I feel relaxed now.", "मैं अब आराम महसूस कर रहा हूँ।"),
                ("I am grateful for my toys.", "मैं अपने खिलौनों के लिए आभारी हूँ।"),
                ("I feel good after playing.", "खेलने के बाद मैं अच्छा महसूस करता हूँ।"),
                ("I am upset about losing.", "मैं हारने से परेशान हूँ।"),
                ("I feel calm and peaceful.", "मैं शांत और सुकून महसूस करता हूँ।"),
                ("I am bored. Let us play.", "मैं बोर हो रहा हूँ। चलो खेलते हैं।"),
                ("I feel confident!", "मैं आत्मविश्वासी महसूस करता हूँ!"),
                ("Talking about feelings is good.", "भावनाओं के बारे में बात करना अच्छा है।"),
                ("I love my parents.", "मैं अपने माता-पिता से प्यार करता हूँ।"),
                ("A hug makes me feel better.", "गले लगाने से मुझे अच्छा महसूस होता है।"),
                ("Feelings are a part of us.", "भावनाएँ हमारा हिस्सा हैं।"),
            ]},
            {"title": "Simple Requests", "desc": "Ask politely", "topic": "Requests", "sentences": [
                ("Can I have some water, please?", "क्या मुझे कुछ पानी मिल सकता है, कृपया?"),
                ("Please help me, Mummy.", "कृपया मेरी मदद करो, मम्मी।"),
                ("Can you pass me the ball?", "क्या तुम मुझे गेंद दे सकते हो?"),
                ("Please open the door.", "कृपया दरवाज़ा खोलो।"),
                ("May I go out to play?", "क्या मैं बाहर खेलने जा सकता हूँ?"),
                ("Can I have a chocolate?", "क्या मुझे एक चॉकलेट मिल सकती है?"),
                ("Please tell me a story.", "कृपया मुझे एक कहानी सुनाओ।"),
                ("Can you tie my shoelaces?", "क्या तुम मेरे जूते के फीते बाँध सकते हो?"),
                ("Please sing a song for me.", "कृपया मेरे लिए एक गाना गाओ।"),
                ("May I use your crayons?", "क्या मैं तुम्हारे क्रेयॉन इस्तेमाल कर सकता हूँ?"),
                ("Can I sit next to you?", "क्या मैं तुम्हारे बगल में बैठ सकता हूँ?"),
                ("Please give me a hug.", "कृपया मुझे एक गले लगाओ।"),
                ("Can you help me with my homework?", "क्या तुम मेरे होमवर्क में मदद कर सकते हो?"),
                ("Please turn on the light.", "कृपया लाइट चालू करो।"),
                ("May I watch cartoons?", "क्या मैं कार्टून देख सकता हूँ?"),
                ("Please buy me a balloon.", "कृपया मुझे एक गुब्बारा खरीद दो।"),
                ("Can I get a glass of milk?", "क्या मुझे एक गिलास दूध मिल सकता है?"),
                ("Please read me a bedtime story.", "कृपया मुझे सोते समय की कहानी सुनाओ।"),
                ("May I play with my friend?", "क्या मैं अपने दोस्त के साथ खेल सकता हूँ?"),
                ("Please take me to the park.", "कृपया मुझे पार्क ले चलो।"),
                ("Can you show me how to do this?", "क्या तुम मुझे दिखा सकते हो कि यह कैसे करना है?"),
                ("Please be quiet, I am studying.", "कृपया शांत रहो, मैं पढ़ रहा हूँ।"),
                ("Thank you for helping me!", "मेरी मदद करने के लिए धन्यवाद!"),
                ("Saying please is polite.", "प्लीज़ कहना विनम्रता है।"),
                ("Kind words make others happy.", "मीठे शब्द दूसरों को खुश करते हैं।"),
            ]},
            {"title": "My School", "desc": "Talk about school", "topic": "School", "sentences": [
                ("I go to school every day.", "मैं हर दिन स्कूल जाता हूँ।"),
                ("I like my school.", "मुझे अपना स्कूल पसंद है।"),
                ("My teacher is very kind.", "मेरी टीचर बहुत दयालु हैं।"),
                ("I have many friends at school.", "स्कूल में मेरे कई दोस्त हैं।"),
                ("We sing songs in the morning.", "हम सुबह गाने गाते हैं।"),
                ("I carry a colourful bag.", "मैं एक रंगीन बैग ले जाता हूँ।"),
                ("I learn new things at school.", "मैं स्कूल में नई चीज़ें सीखता हूँ।"),
                ("The school bell rings at 8.", "स्कूल की घंटी 8 बजे बजती है।"),
                ("I sit in the first row.", "मैं पहली पंक्ति में बैठता हूँ।"),
                ("We draw and colour in class.", "हम क्लास में चित्र बनाते और रंग भरते हैं।"),
                ("My school has a big playground.", "मेरे स्कूल में एक बड़ा मैदान है।"),
                ("I eat my lunch with my friends.", "मैं अपने दोस्तों के साथ खाना खाता हूँ।"),
                ("The library has many books.", "पुस्तकालय में कई किताबें हैं।"),
                ("I like the story time.", "मुझे कहानी का समय पसंद है।"),
                ("We play games in the sports period.", "हम खेल की अवधि में खेल खेलते हैं।"),
                ("My teacher praised me today.", "मेरी टीचर ने आज मेरी तारीफ की।"),
                ("I help my friends in class.", "मैं क्लास में अपने दोस्तों की मदद करता हूँ।"),
                ("School is a happy place.", "स्कूल एक खुशहाल जगह है।"),
                ("I wear a neat uniform.", "मैं साफ वर्दी पहनता हूँ।"),
                ("We do craft activities too.", "हम क्राफ्ट गतिविधियाँ भी करते हैं।"),
                ("I count numbers in maths class.", "मैं गणित की क्लास में संख्याएँ गिनता हूँ।"),
                ("My friend shares his tiffin with me.", "मेरा दोस्त अपना टिफिन मेरे साथ साझा करता है।"),
                ("I wait for the school bus.", "मैं स्कूल बस का इंतज़ार करता हूँ।"),
                ("I love learning!", "मुझे सीखना बहुत पसंद है!"),
                ("School makes me smart.", "स्कूल मुझे समझदार बनाता है।"),
            ]},
            {"title": "Everyday Things", "desc": "Learn everyday objects", "topic": "Everyday Things", "sentences": [
                ("This is my book.", "यह मेरी किताब है।"),
                ("The pencil is sharp.", "पेंसिल तेज़ है।"),
                ("I drink from a glass.", "मैं गिलास से पीता हूँ।"),
                ("The chair is comfortable.", "कुर्सी आरामदायक है।"),
                ("I sleep on my bed.", "मैं अपने बिस्तर पर सोता हूँ।"),
                ("The window is open.", "खिड़की खुली है।"),
                ("I write with a pen.", "मैं पेन से लिखता हूँ।"),
                ("The clock shows the time.", "घड़ी समय दिखाती है।"),
                ("I brush my hair with a comb.", "मैं कंघी से बाल संवारता हूँ।"),
                ("The bag is heavy.", "बैग भारी है।"),
                ("I use a spoon to eat.", "मैं खाने के लिए चम्मच का उपयोग करता हूँ।"),
                ("The mirror is on the wall.", "आईना दीवार पर है।"),
                ("My shoes are new.", "मेरे जूते नए हैं।"),
                ("The cup has tea in it.", "कप में चाय है।"),
                ("I put books on the shelf.", "मैं किताबें शेल्फ पर रखता हूँ।"),
                ("The door is closed.", "दरवाज़ा बंद है।"),
                ("I draw with crayons.", "मैं क्रेयॉन से चित्र बनाता हूँ।"),
                ("The plate is round.", "थाली गोल है।"),
                ("I keep my toys in a basket.", "मैं अपने खिलौने टोकरी में रखता हूँ।"),
                ("The umbrella keeps me dry.", "छाता मुझे सूखा रखता है।"),
                ("I wear a cap in summer.", "मैं गर्मी में टोपी पहनता हूँ।"),
                ("The light is bright.", "रोशनी तेज़ है।"),
                ("I use a towel after bathing.", "नहाने के बाद मैं तौलिया इस्तेमाल करता हूँ।"),
                ("Every object has a name.", "हर वस्तु का एक नाम होता है।"),
                ("I learn new words every day!", "मैं हर दिन नए शब्द सीखता हूँ!"),
            ]},
            {"title": "Good Habits", "desc": "Learn good habits", "topic": "Habits", "sentences": [
                ("I brush my teeth every morning.", "मैं हर सुबह दाँत साफ करता हूँ।"),
                ("I wash my hands before eating.", "मैं खाने से पहले हाथ धोता हूँ।"),
                ("I take a bath every day.", "मैं हर दिन नहाता हूँ।"),
                ("I sleep early at night.", "मैं रात को जल्दी सोता हूँ।"),
                ("I wake up early in the morning.", "मैं सुबह जल्दी उठता हूँ।"),
                ("I say thank you and please.", "मैं धन्यवाद और कृपया कहता हूँ।"),
                ("I share my things with others.", "मैं अपनी चीज़ें दूसरों के साथ साझा करता हूँ।"),
                ("I keep my room clean.", "मैं अपना कमरा साफ रखता हूँ।"),
                ("I eat healthy food.", "मैं स्वस्थ भोजन खाता हूँ।"),
                ("I drink enough water.", "मैं पर्याप्त पानी पीता हूँ।"),
                ("I respect my elders.", "मैं अपने बड़ों का सम्मान करता हूँ।"),
                ("I listen to my parents.", "मैं अपने माता-पिता की बात सुनता हूँ।"),
                ("I do my homework on time.", "मैं समय पर होमवर्क करता हूँ।"),
                ("I read books every day.", "मैं हर दिन किताबें पढ़ता हूँ।"),
                ("I exercise to stay fit.", "मैं फिट रहने के लिए व्यायाम करता हूँ।"),
                ("I say sorry when I make mistakes.", "गलती होने पर मैं माफ़ी माँगता हूँ।"),
                ("I help others when they need me.", "जरूरत पड़ने पर मैं दूसरों की मदद करता हूँ।"),
                ("I do not waste food.", "मैं खाना बर्बाद नहीं करता।"),
                ("I switch off lights when not needed.", "जरूरत न हो तो मैं लाइट बंद कर देता हूँ।"),
                ("I am honest.", "मैं ईमानदार हूँ।"),
                ("I listen carefully when others speak.", "जब दूसरे बोलते हैं तो मैं ध्यान से सुनता हूँ।"),
                ("Good habits make us better people.", "अच्छी आदतें हमें बेहतर इंसान बनाती हैं।"),
                ("I am a good kid.", "मैं एक अच्छा बच्चा हूँ।"),
                ("Small habits, big results.", "छोटी आदतें, बड़े परिणाम।"),
                ("I am proud of my good habits!", "मुझे अपनी अच्छी आदतों पर गर्व है!"),
                ("The sun shines brightly.", "सूरज चमकता है।"),
                ("The moon comes out at night.", "चाँद रात को निकलता है।"),
                ("The stars twinkle in the sky.", "आसमान में तारे टिमटिमाते हैं।"),
                ("The flowers smell nice.", "फूलों की खुशबू अच्छी होती है।"),
                ("The trees give us shade.", "पेड़ हमें छाया देते हैं।"),
                ("The river flows fast.", "नदी तेज़ बहती है।"),
                ("The mountains are very tall.", "पहाड़ बहुत ऊँचे होते हैं।"),
                ("I like the rainbow.", "मुझे इंद्रधनुष पसंद है।"),
                ("The butterfly is colourful.", "तितली रंगीन होती है।"),
                ("I play in the park.", "मैं पार्क में खेलता हूँ।"),
                ("The garden has many flowers.", "बगीचे में कई फूल हैं।"),
                ("The wind blows softly.", "हवा धीरे चलती है।"),
                ("I like the rain.", "मुझे बारिश पसंद है।"),
                ("The snow is white and cold.", "बर्फ सफेद और ठंडी होती है।"),
                ("The ocean is very big.", "समुद्र बहुत बड़ा होता है।"),
                ("I collect leaves in autumn.", "मैं पतझड़ में पत्तियाँ इकट्ठा करता हूँ।"),
                ("The birds sing in the morning.", "पक्षी सुबह गाते हैं।"),
                ("The grass is soft.", "घास मुलायम होती है।"),
                ("We should plant more trees.", "हमें और पेड़ लगाने चाहिए।"),
                ("The environment is precious.", "पर्यावरण अनमोल है।"),
                ("I love nature.", "मुझे प्रकृति बहुत पसंद है।"),
                ("The hills look beautiful.", "पहाड़ियाँ सुंदर दिखती हैं।"),
                ("The stream makes a sound.", "झरना आवाज़ करता है।"),
                ("Nature gives us everything.", "प्रकृति हमें सब कुछ देती है।"),
                ("Let us keep nature clean.", "चलो प्रकृति को साफ रखते हैं।"),
            ]},
            {"title": "Bedtime", "desc": "Bedtime conversations", "topic": "Bedtime", "sentences": [
                ("It is time to sleep.", "सोने का समय हो गया है।"),
                ("Good night, Mummy!", "शुभ रात्रि, मम्मी!"),
                ("I am sleepy now.", "मुझे अब नींद आ रही है।"),
                ("Please tell me a story.", "कृपया मुझे एक कहानी सुनाओ।"),
                ("Once upon a time...", "एक समय की बात है..."),
                ("I will sleep now.", "मैं अब सो जाऊँगा।"),
                ("Close your eyes and sleep.", "आँखें बंद करो और सो जाओ।"),
                ("I sleep with my teddy bear.", "मैं अपने टेडी बियर के साथ सोता हूँ।"),
                ("Sweet dreams, my child!", "मीठे सपने, मेरे बच्चे!"),
                ("I will dream about my toys.", "मैं अपने खिलौनों के बारे में सपना देखूँगा।"),
                ("Do not stay up too late.", "बहुत देर तक मत जागो।"),
                ("I like my pillow.", "मुझे मेरा तकिया पसंद है।"),
                ("The blanket is warm.", "कंबल गर्म है।"),
                ("I sing a lullaby.", "मैं लोरी गाता हूँ।"),
                ("Tomorrow is a new day.", "कल एक नया दिन है।"),
                ("I will wake up early tomorrow.", "मैं कल जल्दी उठूँगा।"),
                ("Sleep well and grow well.", "अच्छे से सोओ और अच्छे से बढ़ो।"),
                ("I hug my pillow at night.", "मैं रात को अपने तकिये को गले लगाता हूँ।"),
                ("The room is dark and cozy.", "कमरा अंधेरा और आरामदायक है।"),
                ("I count sheep to sleep.", "मैं सोने के लिए भेड़ें गिनता हूँ।"),
                ("Mummy kisses me goodnight.", "मम्मी मुझे गुडनाइट किस करती हैं।"),
                ("I feel safe in my bed.", "मैं अपने बिस्तर पर सुरक्षित महसूस करता हूँ।"),
                ("Sleeping early is a good habit.", "जल्दी सोना एक अच्छी आदत है।"),
                ("Good night, stars!", "शुभ रात्रि, तारों!"),
                ("Good night, sleep tight!", "शुभ रात्रि, अच्छे से सोओ!"),
            ]},
            {"title": "Kid Conversations", "desc": "Simple conversations for kids", "topic": "Conversations", "sentences": [
                ("What is your favourite game?", "तुम्हारा पसंदीदा खेल कौन सा है?"),
                ("My favourite game is cricket.", "मेरा पसंदीदा खेल क्रिकेट है।"),
                ("Do you want to play with me?", "क्या तुम मेरे साथ खेलना चाहते हो?"),
                ("What do you like to eat?", "तुम्हें क्या खाना पसंद है?"),
                ("I like to eat pizza.", "मुझे पिज़्ज़ा खाना पसंद है।"),
                ("What is your favourite colour?", "तुम्हारा पसंदीदा रंग क्या है?"),
                ("My favourite colour is blue.", "मेरा पसंदीदा रंग नीला है।"),
                ("Who is your best friend?", "तुम्हारा सबसे अच्छा दोस्त कौन है?"),
                ("My best friend is Sam.", "मेरा सबसे अच्छा दोस्त सैम है।"),
                ("Where do you live?", "तुम कहाँ रहते हो?"),
                ("I live near the park.", "मैं पार्क के पास रहता हूँ।"),
                ("Do you have any pets?", "क्या तुम्हारे पास कोई पालतू जानवर है?"),
                ("Yes, I have a dog.", "हाँ, मेरे पास एक कुत्ता है।"),
                ("What do you do in your free time?", "तुम खाली समय में क्या करते हो?"),
                ("I draw and paint.", "मैं चित्र बनाता और रंग भरता हूँ।"),
                ("Can I see your drawing?", "क्या मैं तुम्हारा चित्र देख सकता हूँ?"),
                ("Your drawing is beautiful!", "तुम्हारा चित्र सुंदर है!"),
                ("Let us be friends!", "चलो दोस्त बनते हैं!"),
                ("I will share my toys with you.", "मैं अपने खिलौने तुम्हारे साथ साझा करूँगा।"),
                ("What is your favourite cartoon?", "तुम्हारा पसंदीदा कार्टून कौन सा है?"),
                ("I like watching cartoons.", "मुझे कार्टून देखना पसंद है।"),
                ("Let us sing a song together.", "चलो साथ मिलकर एक गाना गाते हैं।"),
                ("You are a good friend.", "तुम एक अच्छे दोस्त हो।"),
                ("Talking with friends is fun.", "दोस्तों के साथ बात करना मज़ेदार है।"),
                ("Let us meet again tomorrow!", "चलो कल फिर मिलते हैं!"),
            ]},
        ],
    }
