# Corporate English - 16 lessons x 25 = 400 sentences

def get_corporate_banks():
    return {
        "course_id": "corporate",
        "title": "Corporate English",
        "desc": "Professional English for the office - meetings, emails, deadlines, and team communication.",
        "short": "Excel at workplace communication",
        "icon": "🏢",
        "color": "brand",
        "difficulty": "Intermediate",
        "audience": ["Working Professionals", "Office Employees", "Managers"],
        "price": "₹299",
        "lessons": [
            {"title": "Office Greetings", "desc": "Greet colleagues professionally", "topic": "Office Greetings", "sentences": [
                ("Good morning, everyone. How is everyone today?", "सुप्रभात, सभी को। आज सब कैसे हैं?"),
                ("Good morning, sir. It is nice to see you.", "सुप्रभात, महोदय। आपको देखकर अच्छा लगा।"),
                ("Welcome to the office!", "ऑफिस में आपका स्वागत है!"),
                ("I hope you had a good weekend.", "मुझे उम्मीद है आपका वीकेंड अच्छा रहा।"),
                ("Nice to see you all at the meeting.", "मीटिंग में आप सभी को देखकर अच्छा लगा।"),
                ("Let us start the day with a quick update.", "चलो दिन की शुरुआत एक त्वरित अपडेट से करते हैं।"),
                ("How are things going with your project?", "आपकी परियोजना के साथ चीज़ें कैसी चल रही हैं?"),
                ("Everything is on track, thank you.", "सब कुछ सही रास्ते पर है, धन्यवाद।"),
                ("Please introduce yourself to the new colleague.", "कृपया नए सहकर्मी से अपना परिचय दीजिए।"),
                ("I would like to welcome our new team member.", "मैं अपने नए टीम सदस्य का स्वागत करना चाहता हूँ।"),
                ("Good afternoon. Let us have lunch together.", "नमस्कार। चलो साथ मिलकर खाना खाते हैं।"),
                ("See you at the meeting at 3 PM.", "शाम 3 बजे की मीटिंग में मिलते हैं।"),
                ("Have a productive day!", "आपका दिन उत्पादक रहे!"),
                ("Take care and see you tomorrow.", "ख्याल रखिए और कल मिलते हैं।"),
                ("It was a pleasure working with you today.", "आज आपके साथ काम करके खुशी हुई।"),
                ("Good evening. Are you leaving now?", "शुभ संध्या। क्या आप अभी जा रहे हैं?"),
                ("I will see you in the next meeting.", "मैं आपसे अगली मीटिंग में मिलूँगा।"),
                ("Please keep me posted on the progress.", "कृपया मुझे प्रगति के बारे में बताते रहिए।"),
                ("Thank you for your cooperation today.", "आज के सहयोग के लिए धन्यवाद।"),
                ("Let us catch up over coffee.", "चलो कॉफी पर मिलकर बात करते हैं।"),
                ("I appreciate your hard work.", "मैं आपकी कड़ी मेहनत की सराहना करता हूँ।"),
                ("The team is doing a great job.", "टीम बहुत अच्छा काम कर रही है।"),
                ("Please share the report when ready.", "तैयार होने पर कृपया रिपोर्ट साझा करें।"),
                ("A positive start makes a good day.", "सकारात्मक शुरुआत दिन को अच्छा बनाती है।"),
                ("Working together brings success.", "साथ काम करने से सफलता मिलती है।"),
            ]},
            {"title": "Meetings", "desc": "Participate in meetings", "topic": "Meetings", "sentences": [
                ("Let us begin the meeting now.", "चलो अब मीटिंग शुरू करते हैं।"),
                ("Thank you all for joining the meeting.", "मीटिंग में शामिल होने के लिए सभी का धन्यवाद।"),
                ("The agenda for today's meeting is...", "आज की मीटिंग का एजेंडा है..."),
                ("Let us go through the points one by one.", "चलो बिंदुओं को एक-एक करके देखते हैं।"),
                ("Could you please share your screen?", "क्या आप कृपया अपनी स्क्रीन साझा कर सकते हैं?"),
                ("I would like to add something here.", "मैं यहाँ कुछ जोड़ना चाहूँगा।"),
                ("Let me summarize what we discussed.", "मुझे जो हमने चर्चा की उसका सारांश देने दें।"),
                ("Does anyone have any questions?", "क्या किसी के पास कोई प्रश्न हैं?"),
                ("I agree with the proposal.", "मैं प्रस्ताव से सहमत हूँ।"),
                ("I have a different opinion on this.", "इस पर मेरी एक अलग राय है।"),
                ("Let us take a vote on this matter.", "चलो इस मामले पर मतदान करते हैं।"),
                ("The deadline for this task is Friday.", "इस कार्य की समय सीमा शुक्रवार है।"),
                ("We need to finalize the budget.", "हमें बजट को अंतिम रूप देना है।"),
                ("Let us schedule a follow-up meeting.", "चलो एक अनुवर्ती मीटिंग निर्धारित करते हैं।"),
                ("I will circulate the minutes of the meeting.", "मैं मीटिंग के मिनट्स साझा करूँगा।"),
                ("The meeting was very productive.", "मीटिंग बहुत उत्पादक रही।"),
                ("Can we focus on the main issue?", "क्या हम मुख्य मुद्दे पर ध्यान केंद्रित कर सकते हैं?"),
                ("Let me note that down.", "मुझे इसे नोट करने दें।"),
                ("We will discuss this in the next meeting.", "हम अगली मीटिंग में इस पर चर्चा करेंगे।"),
                ("Thank you for your valuable inputs.", "आपके मूल्यवान विचारों के लिए धन्यवाद।"),
                ("The meeting will end in five minutes.", "मीटिंग पाँच मिनट में समाप्त होगी।"),
                ("Let us wrap up for today.", "चलो आज के लिए समाप्त करते हैं।"),
                ("Action items will be shared by email.", "कार्रवाई के बिंदु ईमेल से साझा किए जाएँगे।"),
                ("See you all in the next meeting.", "अगली मीटिंग में आप सभी से मिलेंगे।"),
                ("Good meetings lead to good decisions.", "अच्छी मीटिंगें अच्छे निर्णयों की ओर ले जाती हैं।"),
            ]},
            {"title": "Manager Conversations", "desc": "Talk with your manager", "topic": "Manager", "sentences": [
                ("May I speak with you for a moment?", "क्या मैं एक पल आपसे बात कर सकता हूँ?"),
                ("I would like to discuss my workload.", "मैं अपने कार्यभार पर चर्चा करना चाहूँगा।"),
                ("Can I get your feedback on my work?", "क्या मैं अपने काम पर आपकी प्रतिक्रिया ले सकता हूँ?"),
                ("I need some guidance on this task.", "मुझे इस कार्य पर कुछ मार्गदर्शन चाहिए।"),
                ("I have completed the assigned work.", "मैंने सौंपा गया काम पूरा कर लिया है।"),
                ("I would like to request a leave on Friday.", "मैं शुक्रवार को छुट्टी का अनुरोध करना चाहूँगा।"),
                ("I appreciate your support, sir.", "मैं आपके समर्थन की सराहना करता हूँ, महोदय।"),
                ("Could we discuss my career growth?", "क्या हम मेरे करियर विकास पर चर्चा कर सकते हैं?"),
                ("I am ready to take on new responsibilities.", "मैं नई जिम्मेदारियाँ लेने के लिए तैयार हूँ।"),
                ("I faced a challenge with the project.", "मुझे परियोजना में एक चुनौती का सामना करना पड़ा।"),
                ("Let me explain the situation clearly.", "मुझे स्थिति स्पष्ट रूप से समझाने दें।"),
                ("I will improve my performance.", "मैं अपना प्रदर्शन सुधारूँगा।"),
                ("Thank you for the constructive feedback.", "रचनात्मक प्रतिक्रिया के लिए धन्यवाद।"),
                ("I will complete it by the deadline.", "मैं इसे समय सीमा तक पूरा कर लूँगा।"),
                ("May I take a half day today?", "क्या मैं आज आधा दिन ले सकता हूँ?"),
                ("The client is happy with our work.", "ग्राहक हमारे काम से खुश है।"),
                ("I need a small extension on the deadline.", "मुझे समय सीमा पर थोड़ी सी वृद्धि चाहिए।"),
                ("I will present the results in the review.", "मैं समीक्षा में परिणाम प्रस्तुत करूँगा।"),
                ("Please let me know if I can help anywhere.", "कृपया बताइए कि क्या मैं कहीं मदद कर सकता हूँ।"),
                ("I am grateful for this opportunity.", "मैं इस अवसर के लिए आभारी हूँ।"),
                ("I will follow your advice.", "मैं आपकी सलाह का पालन करूँगा।"),
                ("Open communication with the manager is key.", "प्रबंधक के साथ खुला संवाद महत्वपूर्ण है।"),
                ("I take ownership of my tasks.", "मैं अपने कार्यों की जिम्मेदारी लेता हूँ।"),
                ("Respect makes the workplace better.", "सम्मान कार्यस्थल को बेहतर बनाता है।"),
                ("I am committed to the team's success.", "मैं टीम की सफलता के लिए प्रतिबद्ध हूँ।"),
            ]},
            {"title": "Colleague Conversations", "desc": "Talk with colleagues", "topic": "Colleagues", "sentences": [
                ("Can you help me with this file?", "क्या आप इस फ़ाइल में मेरी मदद कर सकते हैं?"),
                ("Let us work on this together.", "चलो इस पर साथ मिलकर काम करते हैं।"),
                ("I will share the data with you.", "मैं आपके साथ डेटा साझा करूँगा।"),
                ("How is your project going?", "आपकी परियोजना कैसी चल रही है?"),
                ("Let us have lunch together today.", "चलो आज साथ मिलकर खाना खाते हैं।"),
                ("Can you review my presentation?", "क्या आप मेरी प्रेजेंटेशन की समीक्षा कर सकते हैं?"),
                ("I liked your idea in the meeting.", "मुझे मीटिंग में आपका विचार पसंद आया।"),
                ("Let us coordinate on this task.", "चलो इस कार्य पर समन्वय करते हैं।"),
                ("I will follow up with the client.", "मैं ग्राहक के साथ अनुवर्ती करूँगा।"),
                ("Do you have the updated file?", "क्या आपके पास अपडेटेड फ़ाइल है?"),
                ("We make a great team.", "हम एक बहुत अच्छी टीम बनाते हैं।"),
                ("Let us celebrate our success!", "चलो अपनी सफलता का जश्न मनाते हैं!"),
                ("I learned a lot from you.", "मैंने आपसे बहुत कुछ सीखा।"),
                ("Can we discuss this over a call?", "क्या हम कॉल पर इस पर चर्चा कर सकते हैं?"),
                ("Please share the meeting notes.", "कृपया मीटिंग के नोट्स साझा करें।"),
                ("I will take care of that task.", "मैं उस कार्य का ध्यान रखूँगा।"),
                ("Good teamwork makes work easier.", "अच्छी टीमवर्क काम को आसान बनाती है।"),
                ("Thank you for your support.", "आपके समर्थन के लिए धन्यवाद।"),
                ("We should brainstorm ideas together.", "हमें साथ मिलकर विचार-मंथन करना चाहिए।"),
                ("I appreciate your help on this project.", "इस परियोजना में आपकी मदद की सराहना करता हूँ।"),
                ("Let me know if you face any issue.", "अगर आपको कोई समस्या हो तो मुझे बताइए।"),
                ("Colleagues become friends at work.", "काम पर सहकर्मी दोस्त बन जाते हैं।"),
                ("We support each other at work.", "हम काम पर एक-दूसरे का समर्थन करते हैं।"),
                ("A positive team is a happy team.", "सकारात्मक टीम ही खुश टीम होती है।"),
                ("Together we achieve more.", "साथ मिलकर हम और अधिक हासिल करते हैं।"),
            ]},
            {"title": "Giving Updates", "desc": "Give work updates", "topic": "Updates", "sentences": [
                ("I wanted to update you on the project status.", "मैं आपको परियोजना की स्थिति का अपडेट देना चाहता था।"),
                ("The project is progressing well.", "परियोजना अच्छी तरह आगे बढ़ रही है।"),
                ("We have completed the first phase.", "हमने पहला चरण पूरा कर लिया है।"),
                ("The task is almost finished.", "कार्य लगभग पूरा हो गया है।"),
                ("We are on schedule.", "हम समय पर हैं।"),
                ("There has been a slight delay.", "थोड़ी देरी हुई है।"),
                ("I will finish it by tomorrow evening.", "मैं इसे कल शाम तक पूरा कर लूँगा।"),
                ("The client has approved the design.", "ग्राहक ने डिज़ाइन को मंज़ूरी दे दी है।"),
                ("We faced some technical issues.", "हमें कुछ तकनीकी समस्याओं का सामना करना पड़ा।"),
                ("I will share the detailed report soon.", "मैं जल्द ही विस्तृत रिपोर्ट साझा करूँगा।"),
                ("The numbers are looking good this month.", "इस महीने के आँकड़े अच्छे दिख रहे हैं।"),
                ("Please find the latest update attached.", "कृपया नवीनतम अपडेट संलग्न देखें।"),
                ("We need more time for testing.", "हमें परीक्षण के लिए और समय चाहिए।"),
                ("The team is working overtime to meet the deadline.", "टीम समय सीमा पूरी करने के लिए ओवरटाइम काम कर रही है।"),
                ("Everything is under control.", "सब कुछ नियंत्रण में है।"),
                ("I will update you on any changes.", "किसी भी बदलाव पर मैं आपको अपडेट करूँगा।"),
                ("The meeting has been rescheduled to 4 PM.", "मीटिंग शाम 4 बजे के लिए पुनर्निर्धारित की गई है।"),
                ("The report has been sent to the management.", "रिपोर्ट प्रबंधन को भेज दी गई है।"),
                ("We are waiting for the vendor's response.", "हम विक्रेता के उत्तर की प्रतीक्षा कर रहे हैं।"),
                ("The trial run was successful.", "परीक्षण रन सफल रहा।"),
                ("I will keep you informed.", "मैं आपको सूचित रखूँगा।"),
                ("Regular updates keep everyone aligned.", "नियमित अपडेट सभी को संरेखित रखते हैं।"),
                ("Transparency builds trust.", "पारदर्शिता विश्वास बनाती है।"),
                ("Good communication prevents misunderstandings.", "अच्छा संवाद गलतफहमियों को रोकता है।"),
                ("I value your feedback on this update.", "मैं इस अपडेट पर आपकी प्रतिक्रिया को महत्व देता हूँ।"),
            ]},
            {"title": "Deadlines & Tasks", "desc": "Manage deadlines and tasks", "topic": "Deadlines", "sentences": [
                ("The deadline for this project is next Monday.", "इस परियोजना की समय सीमा अगला सोमवार है।"),
                ("I will prioritize this task.", "मैं इस कार्य को प्राथमिकता दूँगा।"),
                ("Please submit your work by 5 PM.", "कृपया अपना काम शाम 5 बजे तक जमा करें।"),
                ("I am working on it right now.", "मैं अभी इस पर काम कर रहा हूँ।"),
                ("Can we extend the deadline?", "क्या हम समय सीमा बढ़ा सकते हैं?"),
                ("I need two more days to complete this.", "मुझे इसे पूरा करने के लिए दो और दिन चाहिए।"),
                ("The task is very urgent.", "कार्य बहुत जरूरी है।"),
                ("Let me check the task list.", "मुझे कार्य सूची देखने दें।"),
                ("I have completed all my tasks.", "मैंने अपने सभी कार्य पूरे कर लिए हैं।"),
                ("We need to deliver this by Friday.", "हमें इसे शुक्रवार तक पहुँचाना है।"),
                ("Let us divide the work equally.", "चलो काम को समान रूप से बाँटते हैं।"),
                ("I will handle the first part.", "मैं पहला भाग संभालूँगा।"),
                ("Please track your progress daily.", "कृपया अपनी प्रगति को रोज़ ट्रैक करें।"),
                ("The task is divided into three steps.", "कार्य तीन चरणों में विभाजित है।"),
                ("I am almost done with the report.", "मैं रिपोर्ट के साथ लगभग पूरा कर चुका हूँ।"),
                ("Quality is more important than speed.", "गुणवत्ता गति से अधिक महत्वपूर्ण है।"),
                ("We must not miss this deadline.", "हमें यह समय सीमा नहीं चूकनी चाहिए।"),
                ("I will set reminders for all tasks.", "मैं सभी कार्यों के लिए रिमाइंडर सेट करूँगा।"),
                ("The task has been completed successfully.", "कार्य सफलतापूर्वक पूरा हो गया है।"),
                ("Let us review the completed work.", "चलो पूरे हुए काम की समीक्षा करते हैं।"),
                ("Meeting deadlines shows professionalism.", "समय सीमा पूरी करना व्यावसायिकता दर्शाता है।"),
                ("Plan your work and work your plan.", "अपने काम की योजना बनाइए और योजना पर काम कीजिए।"),
                ("I manage my time effectively.", "मैं अपने समय का प्रभावी ढंग से प्रबंधन करता हूँ।"),
                ("Small tasks add up to big results.", "छोटे कार्य बड़े परिणाम देते हैं।"),
                ("Discipline leads to success.", "अनुशासन सफलता की ओर ले जाता है।"),
            ]},
            {"title": "Emails & Messages", "desc": "Write professional emails", "topic": "Emails", "sentences": [
                ("I am writing this email to request a leave.", "मैं यह ईमेल छुट्टी का अनुरोध करने के लिए लिख रहा हूँ।"),
                ("Please find the attached document.", "कृपया संलग्न दस्तावेज़ देखें।"),
                ("I would like to request a meeting.", "मैं एक मीटिंग का अनुरोध करना चाहूँगा।"),
                ("Thank you for your prompt response.", "आपके त्वरित उत्तर के लिए धन्यवाद।"),
                ("Could you please clarify this point?", "क्या आप कृपया इस बिंदु को स्पष्ट कर सकते हैं?"),
                ("I am following up on my previous email.", "मैं अपने पिछले ईमेल के संबंध में अनुवर्ती कर रहा हूँ।"),
                ("Please reply at your earliest convenience.", "कृपया जल्द से जल्द उत्तर दें।"),
                ("The meeting has been confirmed for Tuesday.", "मीटिंग मंगलवार के लिए कन्फर्म हो गई है।"),
                ("I appreciate your cooperation in this matter.", "इस मामले में आपके सहयोग की सराहना करता हूँ।"),
                ("Please find the minutes of the meeting.", "कृपया मीटिंग के मिनट्स देखें।"),
                ("I would be grateful for your assistance.", "मैं आपकी सहायता के लिए आभारी रहूँगा।"),
                ("Please confirm your availability for the call.", "कृपया कॉल के लिए अपनी उपलब्धता की पुष्टि करें।"),
                ("The report is ready for your review.", "रिपोर्ट आपकी समीक्षा के लिए तैयार है।"),
                ("I have cc'd the concerned team.", "मैंने संबंधित टीम को सीसी किया है।"),
                ("Please use a clear subject line.", "कृपया एक स्पष्ट विषय पंक्ति का उपयोग करें।"),
                ("Let me know if you have any questions.", "अगर आपके कोई प्रश्न हैं तो मुझे बताइए।"),
                ("The attachment could not be opened.", "संलग्न फ़ाइल नहीं खोली जा सकी।"),
                ("I will send the details by end of day.", "मैं दिन के अंत तक विवरण भेज दूँगा।"),
                ("Looking forward to your reply.", "आपके उत्तर की प्रतीक्षा है।"),
                ("Best regards, Rahul", "भवदीय, राहुल"),
                ("A professional email creates a good impression.", "पेशेवर ईमेल एक अच्छी छाप बनाता है।"),
                ("Keep emails short and clear.", "ईमेल छोटे और स्पष्ट रखिए।"),
                ("Check your email before sending.", "भेजने से पहले अपना ईमेल जाँचिए।"),
                ("Emails are important for office communication.", "ऑफिस संचार के लिए ईमेल महत्वपूर्ण हैं।"),
                ("Good writing reflects good thinking.", "अच्छा लेखन अच्छी सोच को दर्शाता है।"),
            ]},
            {"title": "Remote Meetings", "desc": "Handle online meetings", "topic": "Remote Meetings", "sentences": [
                ("Let me share my screen for the presentation.", "मुझे प्रेजेंटेशन के लिए अपनी स्क्रीन साझा करने दें।"),
                ("Can you hear me clearly?", "क्या आप मुझे स्पष्ट सुन सकते हैं?"),
                ("Please mute your microphone.", "कृपया अपना माइक्रोफोन म्यूट करें।"),
                ("I am having some network issues.", "मुझे कुछ नेटवर्क समस्याएँ हो रही हैं।"),
                ("Can you see my screen?", "क्या आप मेरी स्क्रीन देख सकते हैं?"),
                ("Please unmute yourself and speak.", "कृपया अनम्यूट करके बोलिए।"),
                ("The video quality is a bit low.", "वीडियो की गुणवत्ता थोड़ी कम है।"),
                ("I will send the link for the meeting.", "मैं मीटिंग का लिंक भेज दूँगा।"),
                ("Please join the meeting on time.", "कृपया मीटिंग में समय पर शामिल हों।"),
                ("The meeting is being recorded.", "मीटिंग रिकॉर्ड की जा रही है।"),
                ("Can we have a quick huddle?", "क्या हम एक त्वरित बैठक कर सकते हैं?"),
                ("I will put the presentation on the screen.", "मैं प्रेजेंटेशन स्क्रीन पर लगा दूँगा।"),
                ("Please type your questions in the chat.", "कृपया अपने प्रश्न चैट में लिखें।"),
                ("The remote meeting is convenient.", "रिमोट मीटिंग सुविधाजनक है।"),
                ("Let us use the whiteboard for ideas.", "चलो विचारों के लिए व्हाइटबोर्ड का उपयोग करते हैं।"),
                ("My camera is not working today.", "मेरा कैमरा आज काम नहीं कर रहा है।"),
                ("Please check the audio settings.", "कृपया ऑडियो सेटिंग्स जाँचें।"),
                ("I will share the recording after the meeting.", "मैं मीटिंग के बाद रिकॉर्डिंग साझा करूँगा।"),
                ("The online meeting started at 10 AM.", "ऑनलाइन मीटिंग सुबह 10 बजे शुरू हुई।"),
                ("Let us wait for the other members.", "चलो बाकी सदस्यों का इंतज़ार करते हैं।"),
                ("Remote work requires good communication.", "रिमोट काम के लिए अच्छे संवाद की आवश्यकता होती है।"),
                ("I keep my camera on during meetings.", "मैं मीटिंग के दौरान अपना कैमरा चालू रखता हूँ।"),
                ("Online tools make teamwork easy.", "ऑनलाइन उपकरण टीमवर्क को आसान बनाते हैं।"),
                ("Clear audio is important in online meetings.", "ऑनलाइन मीटिंग में स्पष्ट ऑडियो महत्वपूर्ण है।"),
                ("Let us make the remote meeting productive.", "चलो रिमोट मीटिंग को उत्पादक बनाते हैं।"),
            ]},
            {"title": "Presentations", "desc": "Give presentations at work", "topic": "Presentations", "sentences": [
                ("Good morning. I will present the quarterly results.", "सुप्रभात। मैं त्रैमासिक परिणाम प्रस्तुत करूँगा।"),
                ("Let me begin with an introduction.", "मुझे एक परिचय से शुरू करने दें।"),
                ("Today, I will cover three main points.", "आज, मैं तीन मुख्य बिंदुओं को शामिल करूँगा।"),
                ("Let us look at the first slide.", "चलो पहली स्लाइड देखते हैं।"),
                ("As you can see from this chart...", "जैसा कि आप इस चार्ट से देख सकते हैं..."),
                ("The sales have increased by 15 percent.", "बिक्री में 15 प्रतिशत की वृद्धि हुई है।"),
                ("This graph shows the trend clearly.", "यह ग्राफ़ रुझान को स्पष्ट रूप से दर्शाता है।"),
                ("Let me explain this in simple terms.", "मुझे इसे सरल शब्दों में समझाने दें।"),
                ("In conclusion, our results are positive.", "निष्कर्ष में, हमारे परिणाम सकारात्मक हैं।"),
                ("I would like to thank everyone for listening.", "सुनने के लिए मैं सभी का धन्यवाद करना चाहूँगा।"),
                ("Are there any questions?", "क्या कोई प्रश्न हैं?"),
                ("Let me elaborate on that point.", "मुझे उस बिंदु पर विस्तार से बताने दें।"),
                ("The presentation will take twenty minutes.", "प्रेजेंटेशन बीस मिनट का होगा।"),
                ("I have prepared a summary at the end.", "मैंने अंत में एक सारांश तैयार किया है।"),
                ("Please share your feedback after the presentation.", "कृपया प्रेजेंटेशन के बाद अपनी प्रतिक्रिया साझा करें।"),
                ("Practice your presentation beforehand.", "पहले से अपनी प्रेजेंटेशन का अभ्यास कीजिए।"),
                ("Speak clearly and confidently.", "स्पष्ट और आत्मविश्वास से बोलिए।"),
                ("Use visual aids to explain better.", "बेहतर समझाने के लिए दृश्य सामग्री का उपयोग कीजिए।"),
                ("Keep the slides simple.", "स्लाइड्स को सरल रखिए।"),
                ("Engage the audience with questions.", "प्रश्नों से दर्शकों को शामिल कीजिए।"),
                ("The presentation was well received.", "प्रेजेंटेशन को अच्छी प्रतिक्रिया मिली।"),
                ("I felt confident while presenting.", "प्रेजेंटेशन देते समय मैं आत्मविश्वासी महसूस करता था।"),
                ("A good presentation tells a story.", "एक अच्छी प्रेजेंटेशन एक कहानी बताती है।"),
                ("Preparation is the key to presentations.", "प्रेजेंटेशन की कुंजी तैयारी है।"),
                ("Every presentation improves my skills.", "हर प्रेजेंटेशन मेरे कौशल में सुधार करता है।"),
            ]},
            {"title": "Problems & Solutions", "desc": "Handle workplace problems", "topic": "Problems", "sentences": [
                ("We have a problem with the system.", "सिस्टम में एक समस्या है।"),
                ("The server is down.", "सर्वर डाउन है।"),
                ("We need to find a solution quickly.", "हमें जल्दी से एक समाधान खोजना है।"),
                ("Let us analyze the root cause.", "चलो मूल कारण का विश्लेषण करते हैं।"),
                ("I have identified the issue.", "मैंने समस्या की पहचान कर ली है।"),
                ("The error occurred during the update.", "अपडेट के दौरान त्रुटि हुई।"),
                ("We will fix it within an hour.", "हम इसे एक घंटे के भीतर ठीक कर देंगे।"),
                ("Please escalate this to the IT team.", "कृपया इसे आईटी टीम तक बढ़ाएँ।"),
                ("The issue has been resolved.", "समस्या हल हो गई है।"),
                ("Let me check the system logs.", "मुझे सिस्टम लॉग देखने दें।"),
                ("We need a backup plan.", "हमें एक बैकअप योजना चाहिए।"),
                ("The data has been recovered.", "डेटा पुनर्प्राप्त कर लिया गया है।"),
                ("We should prevent this from happening again.", "हमें इसे फिर से होने से रोकना चाहिए।"),
                ("The problem is in the payment gateway.", "समस्या भुगतान गेटवे में है।"),
                ("Let us test the solution first.", "चलो पहले समाधान का परीक्षण करते हैं।"),
                ("The update caused the issue.", "अपडेट ने समस्या पैदा की।"),
                ("I will monitor the situation.", "मैं स्थिति पर नज़र रखूँगा।"),
                ("We handled the crisis well.", "हमने संकट को अच्छे से संभाला।"),
                ("Every problem has a fix.", "हर समस्या का एक समाधान है।"),
                ("Stay calm and solve it step by step.", "शांत रहिए और कदम दर कदम हल कीजिए।"),
                ("The client reported a bug.", "ग्राहक ने एक बग की सूचना दी।"),
                ("We will release a patch today.", "हम आज एक पैच जारी करेंगे।"),
                ("Teamwork solved the problem fast.", "टीमवर्क ने समस्या को जल्दी हल कर दिया।"),
                ("Learn from every problem.", "हर समस्या से सीखिए।"),
                ("A solution-focused team is valuable.", "समाधान-केंद्रित टीम मूल्यवान होती है।"),
            ]},
            {"title": "Follow-ups", "desc": "Follow up on work", "topic": "Follow-ups", "sentences": [
                ("I am following up on the pending request.", "मैं लंबित अनुरोध के संबंध में अनुवर्ती कर रहा हूँ।"),
                ("Have you reviewed my proposal?", "क्या आपने मेरे प्रस्ताव की समीक्षा की है?"),
                ("Just checking on the status.", "बस स्थिति की जाँच कर रहा हूँ।"),
                ("Please share an update when possible.", "जब संभव हो तो कृपया एक अपडेट साझा करें।"),
                ("I would like to follow up on the invoice.", "मैं इनवॉइस के संबंध में अनुवर्ती करना चाहूँगा।"),
                ("The client is waiting for the response.", "ग्राहक उत्तर की प्रतीक्षा कर रहा है।"),
                ("We need to follow up with the vendor.", "हमें विक्रेता के साथ अनुवर्ती करना है।"),
                ("I called them twice today.", "मैंने आज उन्हें दो बार कॉल किया।"),
                ("Please remind me about this tomorrow.", "कृपया मुझे कल इसके बारे में याद दिलाइए।"),
                ("The follow-up email has been sent.", "अनुवर्ती ईमेल भेज दिया गया है।"),
                ("I will follow up again next week.", "मैं अगले हफ्ते फिर अनुवर्ती करूँगा।"),
                ("Regular follow-ups get things done.", "नियमित अनुवर्ती काम पूरा करवाते हैं।"),
                ("The payment is still pending.", "भुगतान अभी भी लंबित है।"),
                ("I am waiting for their confirmation.", "मैं उनकी पुष्टि की प्रतीक्षा कर रहा हूँ।"),
                ("Let us set a reminder for the follow-up.", "चलो अनुवर्ती के लिए एक रिमाइंडर सेट करते हैं।"),
                ("The manager asked for a follow-up report.", "प्रबंधक ने अनुवर्ती रिपोर्ट माँगी।"),
                ("Polite follow-ups bring quick replies.", "विनम्र अनुवर्ती त्वरित उत्तर लाते हैं।"),
                ("I will check the progress tomorrow.", "मैं कल प्रगति की जाँच करूँगा।"),
                ("The task is still in progress.", "कार्य अभी भी प्रगति पर है।"),
                ("Please keep the communication open.", "कृपया संवाद खुला रखिए।"),
                ("Following up shows responsibility.", "अनुवर्ती करना जिम्मेदारी दर्शाता है।"),
                ("I note down all follow-ups.", "मैं सभी अनुवर्ती नोट कर लेता हूँ।"),
                ("Consistent follow-up brings results.", "लगातार अनुवर्ती परिणाम लाता है।"),
                ("Do not hesitate to follow up.", "अनुवर्ती करने में संकोच न करें।"),
                ("Good follow-ups complete the work cycle.", "अच्छे अनुवर्ती कार्य चक्र को पूरा करते हैं।"),
            ]},
            {"title": "Workplace Etiquette", "desc": "Professional workplace behaviour", "topic": "Etiquette", "sentences": [
                ("Please be on time for meetings.", "कृपया मीटिंग के लिए समय पर आइए।"),
                ("Respect everyone's opinion.", "हर किसी की राय का सम्मान कीजिए।"),
                ("Do not interrupt while others speak.", "दूसरों के बोलते समय बीच में मत बोलिए।"),
                ("Keep your workspace clean.", "अपना कार्यक्षेत्र साफ रखिए।"),
                ("Use polite words at work.", "काम पर विनम्र शब्दों का उपयोग कीजिए।"),
                ("Help your colleagues when needed.", "ज़रूरत पड़ने पर अपने सहकर्मियों की मदद कीजिए।"),
                ("Keep your phone on silent in meetings.", "मीटिंग में अपना फोन साइलेंट रखिए।"),
                ("Arrive early and leave on time.", "जल्दी आइए और समय पर जाइए।"),
                ("Dress professionally for the office.", "ऑफिस के लिए पेशेवर कपड़े पहनिए।"),
                ("Do not gossip about colleagues.", "सहकर्मियों के बारे में गपशप न करें।"),
                ("Share credit for team success.", "टीम की सफलता का श्रेय साझा कीजिए।"),
                ("Take responsibility for your mistakes.", "अपनी गलतियों की जिम्मेदारी लीजिए।"),
                ("Be honest in your work.", "अपने काम में ईमानदार रहिए।"),
                ("Say thank you to your colleagues.", "अपने सहकर्मियों को धन्यवाद कहिए।"),
                ("Keep confidential information private.", "गोपनीय जानकारी को निजी रखिए।"),
                ("Be open to feedback.", "प्रतिक्रिया के लिए खुले रहिए।"),
                ("Treat everyone with respect.", "सभी के साथ सम्मान से पेश आइए।"),
                ("Avoid personal calls at work.", "काम पर निजी कॉल से बचिए।"),
                ("Follow the office rules.", "ऑफिस के नियमों का पालन कीजिए।"),
                ("Behave professionally in all situations.", "हर स्थिति में पेशेवर व्यवहार कीजिए।"),
                ("Good manners make a good impression.", "अच्छे आचरण अच्छी छाप बनाते हैं।"),
                ("Respect the office environment.", "ऑफिस के वातावरण का सम्मान कीजिए।"),
                ("Teamwork needs mutual respect.", "टीमवर्क के लिए आपसी सम्मान चाहिए।"),
                ("Professionalism is a choice every day.", "व्यावसायिकता हर दिन एक विकल्प है।"),
                ("Etiquette builds a positive culture.", "शिष्टाचार एक सकारात्मक संस्कृति बनाता है।"),
            ]},
            {"title": "Career Growth", "desc": "Talk about career growth", "topic": "Career Growth", "sentences": [
                ("I want to grow in my career.", "मैं अपने करियर में आगे बढ़ना चाहता हूँ।"),
                ("I am working on my skills.", "मैं अपने कौशल पर काम कर रहा हूँ।"),
                ("Learning new skills helps career growth.", "नए कौशल सीखने से करियर विकास में मदद मिलती है।"),
                ("I attend training sessions regularly.", "मैं नियमित रूप से प्रशिक्षण सत्रों में भाग लेता हूँ।"),
                ("I want to take on more responsibility.", "मैं और अधिक जिम्मेदारी लेना चाहता हूँ।"),
                ("My manager guides me well.", "मेरा प्रबंधक मुझे अच्छा मार्गदर्शन देता है।"),
                ("I am ready for a promotion.", "मैं पदोन्नति के लिए तैयार हूँ।"),
                ("I set yearly goals for myself.", "मैं अपने लिए वार्षिक लक्ष्य निर्धारित करता हूँ।"),
                ("Networking helps career growth.", "नेटवर्किंग करियर विकास में मदद करती है।"),
                ("I learn from senior colleagues.", "मैं वरिष्ठ सहकर्मियों से सीखता हूँ।"),
                ("Certifications add value to my profile.", "प्रमाणन मेरी प्रोफ़ाइल में मूल्य जोड़ते हैं।"),
                ("I am building my professional brand.", "मैं अपना पेशेवर ब्रांड बना रहा हूँ।"),
                ("Constructive feedback helps me improve.", "रचनात्मक प्रतिक्रिया मुझे सुधारने में मदद करती है।"),
                ("I am exploring new opportunities.", "मैं नए अवसरों की खोज कर रहा हूँ।"),
                ("My career path is clear.", "मेरा करियर मार्ग स्पष्ट है।"),
                ("I want to become a manager someday.", "मैं किसी दिन प्रबंधक बनना चाहता हूँ।"),
                ("Hard work leads to career growth.", "कड़ी मेहनत करियर विकास की ओर ले जाती है।"),
                ("I update my resume regularly.", "मैं अपना रिज्यूमे नियमित रूप से अपडेट करता हूँ।"),
                ("I am passionate about my profession.", "मैं अपने पेशे के प्रति भावुक हूँ।"),
                ("Consistency is important for growth.", "विकास के लिए निरंतरता महत्वपूर्ण है।"),
                ("I am investing in my development.", "मैं अपने विकास में निवेश कर रहा हूँ।"),
                ("Mentors guide us in our careers.", "गुरु हमें हमारे करियर में मार्गदर्शन देते हैं।"),
                ("I am excited about my future.", "मैं अपने भविष्य को लेकर उत्साहित हूँ।"),
                ("Growth is a journey, not a destination.", "विकास एक यात्रा है, मंज़िल नहीं।"),
                ("I believe in lifelong learning.", "मैं आजीवन सीखने में विश्वास करता हूँ।"),
            ]},
            {"title": "Client Communication", "desc": "Talk with clients", "topic": "Clients", "sentences": [
                ("We value our clients very much.", "हम अपने ग्राहकों को बहुत महत्व देते हैं।"),
                ("I will connect you with our team.", "मैं आपको हमारी टीम से जोड़ता हूँ।"),
                ("Your requirements have been noted.", "आपकी आवश्यकताएँ नोट कर ली गई हैं।"),
                ("We will deliver the project on time.", "हम परियोजना समय पर पहुँचाएँगे।"),
                ("Please let us know your preferences.", "कृपया हमें अपनी प्राथमिकताएँ बताइए।"),
                ("We appreciate your business.", "हम आपके व्यवसाय की सराहना करते हैं।"),
                ("I will share the proposal by tomorrow.", "मैं कल तक प्रस्ताव साझा करूँगा।"),
                ("The client meeting is at 11 AM.", "ग्राहक मीटिंग सुबह 11 बजे है।"),
                ("Please prepare the presentation for the client.", "कृपया ग्राहक के लिए प्रेजेंटेशन तैयार कीजिए।"),
                ("We should understand the client's needs.", "हमें ग्राहक की आवश्यकताओं को समझना चाहिए।"),
                ("The client is very satisfied with our work.", "ग्राहक हमारे काम से बहुत संतुष्ट है।"),
                ("Let us schedule a call with the client.", "चलो ग्राहक के साथ एक कॉल शेड्यूल करते हैं।"),
                ("I will send the meeting summary to the client.", "मैं ग्राहक को मीटिंग का सारांश भेज दूँगा।"),
                ("The client wants some changes.", "ग्राहक कुछ बदलाव चाहता है।"),
                ("We will incorporate the feedback.", "हम प्रतिक्रिया को शामिल करेंगे।"),
                ("Client satisfaction is our priority.", "ग्राहक संतुष्टि हमारी प्राथमिकता है।"),
                ("I handle client communication professionally.", "मैं ग्राहक संचार को पेशेवर तरीके से संभालता हूँ।"),
                ("The new client seems very promising.", "नया ग्राहक बहुत आशाजनक लग रहा है।"),
                ("We must keep our promises to clients.", "हमें ग्राहकों से किए वादे निभाने चाहिए।"),
                ("A happy client brings more business.", "खुश ग्राहक और व्यवसाय लाता है।"),
                ("The client appreciated our quick response.", "ग्राहक ने हमारे त्वरित उत्तर की सराहना की।"),
                ("We maintain good relations with clients.", "हम ग्राहकों के साथ अच्छे संबंध बनाए रखते हैं।"),
                ("Trust is the foundation of client relations.", "विश्वास ग्राहक संबंधों की नींव है।"),
                ("Clear communication avoids client issues.", "स्पष्ट संवाद ग्राहक समस्याओं से बचाता है।"),
                ("The client is our partner in growth.", "ग्राहक हमारे विकास का साथी है।"),
            ]},
            {"title": "Office Conversations", "desc": "Everyday office talk", "topic": "Office Talk", "sentences": [
                ("Let us grab a coffee break.", "चलो कॉफी ब्रेक लेते हैं।"),
                ("The office is very busy today.", "ऑफिस आज बहुत व्यस्त है।"),
                ("I have back-to-back meetings today.", "आज मेरी लगातार मीटिंगें हैं।"),
                ("The printer is out of paper.", "प्रिंटर में कागज़ खत्म है।"),
                ("Can we book the conference room?", "क्या हम कॉन्फ्रेंस रूम बुक कर सकते हैं?"),
                ("The cafeteria food is good.", "कैफेटेरिया का खाना अच्छा है।"),
                ("I forgot my ID card at home.", "मैं अपना आईडी कार्ड घर पर भूल गया।"),
                ("Please sign the attendance sheet.", "कृपया उपस्थिति पत्रक पर हस्ताक्षर करें।"),
                ("The office closes at 6 PM.", "ऑफिस शाम 6 बजे बंद होता है।"),
                ("I am working from home tomorrow.", "मैं कल घर से काम कर रहा हूँ।"),
                ("The WiFi is not working properly.", "वाई-फाई ठीक से काम नहीं कर रहा है।"),
                ("Let us have a quick stand-up meeting.", "चलो एक त्वरित स्टैंड-अप मीटिंग करते हैं।"),
                ("I will send you the file on chat.", "मैं आपको फ़ाइल चैट पर भेज दूँगा।"),
                ("The parking lot is full.", "पार्किंग स्थल भरा हुआ है।"),
                ("We have a new employee joining today.", "आज एक नया कर्मचारी जुड़ रहा है।"),
                ("Please share the office guidelines.", "कृपया ऑफिस के दिशा-निर्देश साझा करें।"),
                ("The Monday morning meeting is at 10.", "सोमवार सुबह की मीटिंग 10 बजे है।"),
                ("I like the friendly office environment.", "मुझे ऑफिस का मिलनसार वातावरण पसंद है।"),
                ("The team went out for lunch.", "टीम खाने के लिए बाहर गई।"),
                ("Please check the shared drive.", "कृपया साझा ड्राइव देखिए।"),
                ("We celebrated a colleague's birthday.", "हमने एक सहकर्मी का जन्मदिन मनाया।"),
                ("The office has a nice view.", "ऑफिस से अच्छा दृश्य दिखता है।"),
                ("A good office culture motivates everyone.", "अच्छी ऑफिस संस्कृति सभी को प्रेरित करती है।"),
                ("We are like a second family at work.", "काम पर हम दूसरे परिवार की तरह हैं।"),
                ("Every day at the office teaches something.", "ऑफिस में हर दिन कुछ सिखाता है।"),
            ]},
        ],
    }
