def get_dailylife_banks():
    return {
        "course_id": "daily-life",
        "title": "Daily Life English",
        "desc": "Sentences you use every day - at home, market, bank, hospital, and with friends.",
        "short": "Speak English in daily situations",
        "icon": "🏠",
        "color": "brand",
        "difficulty": "Beginner",
        "audience": ["Daily Life Learners", "Absolute Beginners", "All Users"],
        "price": "₹199",
        "lessons": [
            {"title": "Morning Routine", "desc": "Start your day in English", "topic": "Morning", "sentences": [
                ("Good morning! Did you sleep well?", "सुप्रभात! अच्छी नींद आई?"),
                ("I woke up late today.", "मैं आज देर से उठा।"),
                ("Did you brush your teeth?", "क्या आपने दाँत साफ किए?"),
                ("I need to get ready for work.", "मुझे काम के लिए तैयार होना है।"),
                ("What should I wear today?", "आज मुझे क्या पहनना चाहिए?"),
                ("Please make the bed.", "कृपया बिस्तर ठीक कर दीजिए।"),
                ("I am taking a shower now.", "मैं अभी नहा रहा हूँ।"),
                ("Have you seen my keys?", "क्या आपने मेरी चाबियाँ देखी हैं?"),
                ("I am getting late for office.", "मुझे ऑफिस के लिए देर हो रही है।"),
                ("Let me have a quick cup of tea.", "मुझे जल्दी से एक कप चाय पी लेने दो।"),
                ("The water is running.", "पानी बह रहा है।"),
                ("Please switch off the fan.", "कृपया पंखा बंद कर दीजिए।"),
                ("I will be home by 7 in the evening.", "मैं शाम 7 बजे तक घर आ जाऊँगा।"),
                ("Do not forget your lunch box.", "अपना टिफिन मत भूलिए।"),
                ("I need to iron my shirt.", "मुझे अपनी शर्ट प्रेस करनी है।"),
                ("The milk has arrived.", "दूध आ गया है।"),
                ("I am ready. Let us go.", "मैं तैयार हूँ। चलो चलते हैं।"),
                ("Have a nice day at work!", "काम पर आपका दिन अच्छा रहे!"),
                ("Call me when you reach.", "पहुँचते ही मुझे कॉल करना।"),
                ("I will drop the kids to school.", "मैं बच्चों को स्कूल छोड़ दूँगा।"),
                ("The breakfast is on the table.", "नाश्ता मेज़ पर है।"),
                ("I feel fresh after a shower.", "नहाने के बाद मैं तरोताज़ा महसूस करता हूँ।"),
                ("Let me check the time.", "मुझे समय देखने दें।"),
                ("We have a busy day ahead.", "हमारे सामने व्यस्त दिन है।"),
                ("Everything is ready for the day.", "दिन के लिए सब कुछ तैयार है।"),
            ]},
            {"title": "Breakfast & Kitchen", "desc": "Kitchen and breakfast conversations", "topic": "Breakfast", "sentences": [
                ("I am making breakfast. What would you like?", "मैं नाश्ता बना रहा हूँ। आपको क्या चाहिए?"),
                ("Please pass me the salt.", "कृपया मुझे नमक दे दीजिए।"),
                ("The tea is ready.", "चाय तैयार है।"),
                ("Do you want milk in your coffee?", "क्या आप अपनी कॉफी में दूध चाहेंगे?"),
                ("The vegetables need to be cut.", "सब्ज़ियाँ काटनी हैं।"),
                ("I will cook rice today.", "मैं आज चावल बनाऊँगा।"),
                ("Please wash the dishes.", "कृपया बर्तन धो दीजिए।"),
                ("The stove is not working.", "गैस चूल्हा काम नहीं कर रहा है।"),
                ("Where is the frying pan?", "कड़ाही कहाँ है?"),
                ("This curry is very tasty.", "यह करी बहुत स्वादिष्ट है।"),
                ("I need to buy some spices.", "मुझे कुछ मसाले खरीदने हैं।"),
                ("The milk is boiling.", "दूध उबल रहा है।"),
                ("Please cut the onions.", "कृपया प्याज़ काट दीजिए।"),
                ("Is there any sugar left?", "क्या थोड़ी चीनी बची है?"),
                ("I will make rotis for lunch.", "मैं दोपहर के खाने के लिए रोटियाँ बनाऊँगा।"),
                ("The gas cylinder needs to be refilled.", "गैस सिलेंडर भरवाना है।"),
                ("Please turn on the exhaust fan.", "कृपया एग्जॉस्ट फैन चालू कर दीजिए।"),
                ("The fruits are in the fridge.", "फल फ्रिज में हैं।"),
                ("I like my tea without sugar.", "मुझे अपनी चाय बिना चीनी की पसंद है।"),
                ("The kitchen smells wonderful.", "रसोई से बहुत अच्छी खुशबू आ रही है।"),
                ("Can you help me set the table?", "क्या आप मेज़ लगाने में मेरी मदद करेंगे?"),
                ("I will clean the kitchen after cooking.", "मैं खाना बनाने के बाद रसोई साफ करूँगा।"),
                ("The water is not hot enough.", "पानी पर्याप्त गर्म नहीं है।"),
                ("We are out of cooking oil.", "हमारा खाने का तेल खत्म हो गया है।"),
                ("Breakfast is the best time to talk.", "नाश्ते का समय बात करने का सबसे अच्छा समय है।"),
            ]},
            {"title": "Cleaning & Home", "desc": "Household cleaning conversations", "topic": "Cleaning", "sentences": [
                ("I need to clean the house today.", "मुझे आज घर की सफाई करनी है।"),
                ("Please sweep the floor.", "कृपया फर्श झाड़ दीजिए।"),
                ("The dustbin is full.", "कूड़ेदान भर गया है।"),
                ("Please mop the floor.", "कृपया फर्श पोछा कर दीजिए।"),
                ("I am doing the laundry.", "मैं कपड़े धो रहा हूँ।"),
                ("The clothes are dry. Please fold them.", "कपड़े सूख गए हैं। कृपया उन्हें मोड़ दीजिए।"),
                ("I need to dust the shelves.", "मुझे अलमारियाँ साफ करनी हैं।"),
                ("The windows need cleaning.", "खिड़कियों की सफाई करनी है।"),
                ("Where is the broom?", "झाड़ू कहाँ है?"),
                ("I will vacuum the carpet.", "मैं कालीन वैक्यूम करूँगा।"),
                ("Please throw the trash outside.", "कृपया कूड़ा बाहर फेंक दीजिए।"),
                ("The bathroom needs cleaning.", "बाथरूम की सफाई करनी है।"),
                ("I wash the utensils after dinner.", "मैं खाने के बाद बर्तन धोता हूँ।"),
                ("The house looks clean now.", "घर अब साफ दिख रहा है।"),
                ("We clean the fans once a month.", "हम महीने में एक बार पंखे साफ करते हैं।"),
                ("The washing machine is making noise.", "वॉशिंग मशीन आवाज़ कर रही है।"),
                ("Please change the bedsheets.", "कृपया बिस्तर की चादरें बदल दीजिए।"),
                ("I bought new cleaning supplies.", "मैंने नई सफाई की चीज़ें खरीदीं।"),
                ("The floors are shiny after mopping.", "पोछा करने के बाद फर्श चमक रहा है।"),
                ("Let us clean the kitchen together.", "चलो रसोई साथ मिलकर साफ करते हैं।"),
                ("I hate doing the dishes.", "मुझे बर्तन धोना बिल्कुल पसंद नहीं है।"),
                ("The curtains need a wash.", "पर्दों की धुलाई करनी है।"),
                ("A clean home makes me happy.", "साफ घर मुझे खुश करता है।"),
                ("Please put the things back in their place.", "कृपया चीज़ों को उनकी जगह पर रख दीजिए।"),
                ("Cleaning takes most of the Sunday.", "सफाई में ज्यादातर रविवार बीत जाता है।"),
            ]},
            {"title": "Market & Vegetables", "desc": "Buy vegetables at the market", "topic": "Market", "sentences": [
                ("I need to buy vegetables today.", "मुझे आज सब्ज़ियाँ खरीदनी हैं।"),
                ("How much for one kilogram of tomatoes?", "एक किलो टमाटर के कितने हैं?"),
                ("The vegetables look fresh today.", "सब्ज़ियाँ आज ताज़ी लग रही हैं।"),
                ("Can you give me a discount?", "क्या आप थोड़ी छूट दे सकते हैं?"),
                ("Please weigh these potatoes.", "कृपया ये आलू तौल दीजिए।"),
                ("Give me half a kilogram of onions.", "मुझे आधा किलो प्याज़ दीजिए।"),
                ("Are these mangoes sweet?", "क्या ये आम मीठे हैं?"),
                ("I want fresh green vegetables.", "मुझे ताज़ी हरी सब्ज़ियाँ चाहिए।"),
                ("Please pack everything in one bag.", "कृपया सब कुछ एक बैग में पैक कर दीजिए।"),
                ("The price is a bit high today.", "आज कीमत थोड़ी ज्यादा है।"),
                ("I will take two bunches of coriander.", "मैं धनिया के दो गुच्छे लूँगा।"),
                ("Is this cauliflower fresh?", "क्या यह फूलगोभी ताज़ी है?"),
                ("Please give me one kilogram of apples.", "कृपया मुझे एक किलो सेब दीजिए।"),
                ("The spinach is very fresh.", "पालक बहुत ताज़ा है।"),
                ("How much are these bananas?", "ये केले कितने के हैं?"),
                ("I will buy some ginger and garlic.", "मैं कुछ अदरक और लहसुन खरीदूँगा।"),
                ("Please do not give the rotten ones.", "कृपया खराब वाले मत दीजिए।"),
                ("The vendor is very honest.", "विक्रेता बहुत ईमानदार है।"),
                ("I come to this market every week.", "मैं हर हफ्ते इस बाज़ार आता हूँ।"),
                ("The market is very crowded on Sundays.", "रविवार को बाज़ार बहुत भीड़भाड़ वाला होता है।"),
                ("Please give me some green chillies.", "कृपया मुझे कुछ हरी मिर्च दीजिए।"),
                ("That is too expensive. Reduce the price.", "यह बहुत महँगा है। कीमत कम कीजिए।"),
                ("I need lemons for the juice.", "मुझे जूस के लिए नींबू चाहिए।"),
                ("The total bill is 250 rupees.", "कुल बिल 250 रुपये है।"),
                ("Thank you. I will come again.", "धन्यवाद। मैं फिर आऊँगा।"),
            ]},
            {"title": "Grocery Store", "desc": "Shop for groceries", "topic": "Grocery", "sentences": [
                ("I need to buy groceries for the week.", "मुझे हफ्ते के लिए किराने का सामान खरीदना है।"),
                ("We are out of rice.", "हमारा चावल खत्म हो गया है।"),
                ("Please add sugar to the list.", "कृपया सूची में चीनी जोड़ दीजिए।"),
                ("I need a packet of biscuits.", "मुझे बिस्कुट का एक पैकेट चाहिए।"),
                ("Where is the bread section?", "ब्रेड वाला भाग कहाँ है?"),
                ("I want whole wheat flour.", "मुझे गेहूँ का आटा चाहिए।"),
                ("Is there a discount on oil?", "क्या तेल पर छूट है?"),
                ("I will take two bottles of cold drink.", "मैं दो बोतल कोल्ड ड्रिंक लूँगा।"),
                ("The milk packets are in the fridge.", "दूध के पैकेट फ्रिज में हैं।"),
                ("Do you have instant noodles?", "क्या आपके पास इंस्टेंट नूडल्स हैं?"),
                ("Please give me the bill.", "कृपया मुझे बिल दीजिए।"),
                ("I forgot to buy eggs.", "मैं अंडे खरीदना भूल गया।"),
                ("The store is closing soon.", "दुकान जल्द बंद होने वाली है।"),
                ("I need some snacks for the guests.", "मुझे मेहमानों के लिए कुछ नाश्ता चाहिए।"),
                ("Do you have any offers this week?", "क्या इस हफ्ते कोई ऑफर है?"),
                ("I will pay by card.", "मैं कार्ड से भुगतान करूँगा।"),
                ("Please pack the eggs carefully.", "कृपया अंडे सावधानी से पैक कीजिए।"),
                ("I bought everything on my list.", "मैंने अपनी सूची की हर चीज़ खरीद ली।"),
                ("The grocery bill was higher than expected.", "किराने का बिल उम्मीद से ज्यादा आया।"),
                ("Let me make a shopping list.", "मुझे एक खरीदारी सूची बनाने दें।"),
                ("We need cleaning supplies too.", "हमें सफाई का सामान भी चाहिए।"),
                ("This brand is of good quality.", "यह ब्रांड अच्छी गुणवत्ता का है।"),
                ("I prefer buying in bulk.", "मैं थोक में खरीदना पसंद करता हूँ।"),
                ("The new store has better prices.", "नई दुकान की कीमतें बेहतर हैं।"),
                ("Shopping for groceries takes time.", "किराने की खरीदारी में समय लगता है।"),
            ]},
            {"title": "Clothes & Laundry", "desc": "Talk about clothes and laundry", "topic": "Clothes", "sentences": [
                ("I need to wash my clothes.", "मुझे अपने कपड़े धोने हैं।"),
                ("This shirt does not fit me well.", "यह शर्ट मुझे ठीक से नहीं आती।"),
                ("I like wearing cotton clothes in summer.", "मुझे गर्मी में सूती कपड़े पहनना पसंद है।"),
                ("Please iron my formal shirt.", "कृपया मेरी फॉर्मल शर्ट प्रेस कर दीजिए।"),
                ("The dress is very beautiful.", "ड्रेस बहुत सुंदर है।"),
                ("My clothes are dirty. I need to wash them.", "मेरे कपड़े गंदे हैं। मुझे उन्हें धोना है।"),
                ("This colour suits you well.", "यह रंग आप पर अच्छा लगता है।"),
                ("I am wearing new shoes today.", "मैंने आज नए जूते पहने हैं।"),
                ("Please dry the clothes in the sun.", "कृपया कपड़ों को धूप में सुखा दीजिए।"),
                ("I need a new pair of trousers.", "मुझे पतलून की एक नई जोड़ी चाहिए।"),
                ("The button is missing from my shirt.", "मेरी शर्ट का बटन गायब है।"),
                ("I will wear a formal suit for the interview.", "मैं इंटरव्यू के लिए फॉर्मल सूट पहनूँगा।"),
                ("The clothes are still wet.", "कपड़े अभी भी गीले हैं।"),
                ("Please put the clothes in the wardrobe.", "कृपया कपड़े अलमारी में रख दीजिए।"),
                ("This jacket is too small for me.", "यह जैकेट मेरे लिए बहुत छोटी है।"),
                ("I want to buy a traditional dress.", "मैं एक पारंपरिक पोशाक खरीदना चाहता हूँ।"),
                ("The socks are missing.", "मोज़े गायब हैं।"),
                ("I iron my clothes on Sundays.", "मैं रविवार को अपने कपड़े प्रेस करता हूँ।"),
                ("The washing powder is finished.", "वॉशिंग पाउडर खत्म हो गया है।"),
                ("This fabric is very soft.", "यह कपड़ा बहुत मुलायम है।"),
                ("I will change my clothes after work.", "मैं काम के बाद कपड़े बदलूँगा।"),
                ("She is always well dressed.", "वह हमेशा अच्छे कपड़े पहनती है।"),
                ("I need comfortable shoes for walking.", "मुझे चलने के लिए आरामदायक जूते चाहिए।"),
                ("The tailor will stitch my new kurta.", "दर्जी मेरी नई कुर्ता सिलेगा।"),
                ("Dress well and feel confident.", "अच्छे कपड़े पहनो और आत्मविश्वास महसूस करो।"),
            ]},
            {"title": "Restaurant", "desc": "Order food at a restaurant", "topic": "Restaurant", "sentences": [
                ("A table for two, please.", "दो लोगों के लिए टेबल, कृपया।"),
                ("Can I see the menu, please?", "क्या मैं मेनू देख सकता हूँ, कृपया?"),
                ("I would like to order the special thali.", "मैं स्पेशल थाली ऑर्डर करना चाहूँगा।"),
                ("What would you recommend from the menu?", "आप मेनू में से क्या सुझाव देंगे?"),
                ("I am vegetarian. Do you have veg options?", "मैं शाकाहारी हूँ। क्या आपके पास शाकाहारी विकल्प हैं?"),
                ("Please bring me a glass of water.", "कृपया मुझे एक गिलास पानी लाइए।"),
                ("The food was delicious.", "खाना बहुत स्वादिष्ट था।"),
                ("Could I get some extra napkins?", "क्या मुझे कुछ अतिरिक्त नैपकिन मिल सकते हैं?"),
                ("I would like to order dessert.", "मैं मिठाई ऑर्डर करना चाहूँगा।"),
                ("Is the service charge included?", "क्या सर्विस चार्ज शामिल है?"),
                ("The waiter was very polite.", "वेटर बहुत विनम्र था।"),
                ("I have a reservation under the name Sharma.", "मेरी बुकिंग शर्मा नाम से है।"),
                ("How long is the waiting time?", "इंतज़ार का समय कितना है?"),
                ("Please bring the bill.", "कृपया बिल लाइए।"),
                ("I will pay by card.", "मैं कार्ड से भुगतान करूँगा।"),
                ("The portions are very generous.", "मात्राएँ बहुत उदार हैं।"),
                ("Can we sit near the window?", "क्या हम खिड़की के पास बैठ सकते हैं?"),
                ("This restaurant is always crowded.", "यह रेस्तराँ हमेशा भरा रहता है।"),
                ("The biryani here is famous.", "यहाँ की बिरयानी मशहूर है।"),
                ("Please pack the leftover food.", "कृपया बचा हुआ खाना पैक कर दीजिए।"),
                ("The restaurant has a nice ambience.", "रेस्तराँ का वातावरण अच्छा है।"),
                ("I will have the same as him.", "मैं वही लूँगा जो उन्होंने लिया है।"),
                ("Is the food spicy?", "क्या खाना तीखा है?"),
                ("Thank you for the great service.", "शानदार सेवा के लिए धन्यवाद।"),
                ("Let us try a new restaurant this weekend.", "चलो इस वीकेंड कोई नया रेस्तराँ आज़माते हैं।"),
            ]},
            {"title": "Doctor & Clinic", "desc": "Visit the doctor", "topic": "Doctor", "sentences": [
                ("I need to see a doctor.", "मुझे डॉक्टर से मिलना है।"),
                ("I have a fever since yesterday.", "मुझे कल से बुखार है।"),
                ("Where does it hurt?", "कहाँ दर्द हो रहा है?"),
                ("My throat is sore.", "मेरे गले में दर्द है।"),
                ("I have been coughing since morning.", "मुझे सुबह से खांसी आ रही है।"),
                ("Please open your mouth.", "कृपया अपना मुँह खोलिए।"),
                ("I will prescribe some medicines.", "मैं कुछ दवाइयाँ लिख दूँगा।"),
                ("Take this medicine after food.", "यह दवा खाने के बाद लीजिए।"),
                ("Do I need any tests?", "क्या मुझे कोई जाँच करवानी होगी?"),
                ("The reports will come tomorrow.", "रिपोर्ट कल आएँगी।"),
                ("I feel pain in my chest.", "मुझे सीने में दर्द महसूस होता है।"),
                ("You need to rest for a week.", "आपको एक हफ्ते आराम करना होगा।"),
                ("The injection will not hurt much.", "इंजेक्शन से ज्यादा दर्द नहीं होगा।"),
                ("I am feeling dizzy.", "मुझे चक्कर आ रहा है।"),
                ("Please give me the prescription.", "कृपया मुझे पर्ची दे दीजिए।"),
                ("I am allergic to penicillin.", "मुझे पेनिसिलिन से एलर्जी है।"),
                ("The nurse will check your blood pressure.", "नर्स आपका रक्तचाप जाँचेगी।"),
                ("Do I need to come again?", "क्या मुझे फिर आना होगा?"),
                ("I am feeling better than before.", "मैं पहले से बेहतर महसूस कर रहा हूँ।"),
                ("The doctor advised me to drink warm water.", "डॉक्टर ने मुझे गर्म पानी पीने की सलाह दी।"),
                ("Please call me if the fever increases.", "अगर बुखार बढ़े तो कृपया मुझे कॉल कीजिए।"),
                ("I got a flu shot last week.", "मैंने पिछले हफ्ते फ्लू का टीका लगवाया।"),
                ("The clinic opens at 9 AM.", "क्लिनिक सुबह 9 बजे खुलता है।"),
                ("I will take the medicines on time.", "मैं दवाइयाँ समय पर लूँगा।"),
                ("Your reports are normal.", "आपकी रिपोर्ट सामान्य हैं।"),
            ]},
            {"title": "Bank & ATM", "desc": "Banking conversations", "topic": "Bank", "sentences": [
                ("I want to open a bank account.", "मैं एक बैंक खाता खोलना चाहता हूँ।"),
                ("What documents do I need?", "मुझे कौन से दस्तावेज़ चाहिए?"),
                ("I need to deposit some cash.", "मुझे कुछ नकद जमा करना है।"),
                ("Can I withdraw money from this branch?", "क्या मैं इस शाखा से पैसे निकाल सकता हूँ?"),
                ("I forgot my ATM PIN.", "मैं अपना एटीएम पिन भूल गया।"),
                ("Please check my account balance.", "कृपया मेरा खाता शेष देखिए।"),
                ("I want to get a new passbook.", "मैं एक नया पासबुक लेना चाहता हूँ।"),
                ("The cheque has bounced.", "चेक बाउंस हो गया है।"),
                ("I need to update my mobile number.", "मुझे अपना मोबाइल नंबर अपडेट करना है।"),
                ("How do I transfer money online?", "मैं ऑनलाइन पैसे कैसे ट्रांसफर करूँ?"),
                ("The bank is closed on Sundays.", "बैंक रविवार को बंद रहता है।"),
                ("I want to apply for a loan.", "मैं ऋण के लिए आवेदन करना चाहता हूँ।"),
                ("What is the interest rate?", "ब्याज दर क्या है?"),
                ("My account has been blocked.", "मेरा खाता ब्लॉक हो गया है।"),
                ("I need to close my account.", "मुझे अपना खाता बंद करना है।"),
                ("Please issue me a new debit card.", "कृपया मुझे एक नया डेबिट कार्ड जारी करें।"),
                ("The ATM is not dispensing cash.", "एटीएम पैसे नहीं दे रहा है।"),
                ("I lost my cheque book.", "मेरी चेकबुक खो गई है।"),
                ("The bank sent me a notification.", "बैंक ने मुझे एक सूचना भेजी है।"),
                ("I have a fixed deposit account.", "मेरे पास एक फिक्स्ड डिपॉजिट खाता है।"),
                ("Please help me fill this withdrawal form.", "कृपया यह निकासी फॉर्म भरने में मेरी मदद करें।"),
                ("My net banking is not working.", "मेरा नेट बैंकिंग काम नहीं कर रहा है।"),
                ("The cashier will help you.", "कैशियर आपकी मदद करेगा।"),
                ("I want to check my transaction history.", "मैं अपना लेन-देन इतिहास देखना चाहता हूँ।"),
                ("Banking is easy with online apps now.", "ऑनलाइन ऐप से बैंकिंग अब आसान है।"),
            ]},
            {"title": "Salon & Barber", "desc": "At the salon", "topic": "Salon", "sentences": [
                ("I want a haircut, please.", "मुझे बाल कटवाने हैं, कृपया।"),
                ("How much does a haircut cost?", "बाल कटवाने का खर्च कितना है?"),
                ("Please trim my hair a little.", "कृपया मेरे बाल थोड़े से काटिए।"),
                ("I would like a shave too.", "मुझे शेव भी करवानी है।"),
                ("Do you have an appointment?", "क्या आपके पास अपॉइंटमेंट है?"),
                ("The barber is busy right now.", "बार्बर अभी व्यस्त है।"),
                ("Please keep my beard stylish.", "कृपया मेरी दाढ़ी स्टाइलिश रखिए।"),
                ("I want a new hairstyle.", "मैं एक नया हेयरस्टाइल चाहता हूँ।"),
                ("Should I wash your hair first?", "क्या मैं पहले आपके बाल धो दूँ?"),
                ("The haircut looks great!", "हेयरकट बहुत अच्छा लग रहा है!"),
                ("I need a face massage.", "मुझे फेस मसाज चाहिए।"),
                ("Please be gentle.", "कृपया धीरे से कीजिए।"),
                ("How long will it take?", "इसमें कितना समय लगेगा?"),
                ("I will come at 5 PM.", "मैं शाम 5 बजे आऊँगा।"),
                ("The salon is open till 9 PM.", "सैलून रात 9 बजे तक खुला है।"),
                ("Do you do bridal makeup?", "क्या आप शादी का मेकअप करते हैं?"),
                ("I want to colour my hair.", "मैं अपने बालों का रंग करवाना चाहता हूँ।"),
                ("The haircut cost 150 rupees.", "हेयरकट का खर्च 150 रुपये था।"),
                ("My hair was too long.", "मेरे बाल बहुत लंबे थे।"),
                ("Please use a clean towel.", "कृपया साफ तौलिया इस्तेमाल कीजिए।"),
                ("I like this salon very much.", "मुझे यह सैलून बहुत पसंद है।"),
                ("The hairstylist gave good suggestions.", "हेयरस्टाइलिस्ट ने अच्छे सुझाव दिए।"),
                ("I will get a haircut before the wedding.", "मैं शादी से पहले बाल कटवाऊँगा।"),
                ("Please book an appointment for Saturday.", "कृपया शनिवार के लिए अपॉइंटमेंट बुक कीजिए।"),
                ("Looking good makes you feel good.", "अच्छा दिखने से अच्छा महसूस होता है।"),
            ]},
            {"title": "WhatsApp & Social", "desc": "Chat on WhatsApp and social media", "topic": "WhatsApp", "sentences": [
                ("I will send you the photos on WhatsApp.", "मैं आपको फोटो व्हाट्सएप पर भेजूँगा।"),
                ("Did you see my message?", "क्या आपने मेरा मैसेज देखा?"),
                ("Please send me the location.", "कृपया मुझे लोकेशन भेज दीजिए।"),
                ("I am in a group with my colleagues.", "मैं अपने सहकर्मियों के साथ एक ग्रुप में हूँ।"),
                ("Please share the document here.", "कृपया दस्तावेज़ यहाँ साझा करें।"),
                ("I will call you on video.", "मैं आपको वीडियो कॉल करूँगा।"),
                ("Can you send me the voice note?", "क्या आप मुझे वॉयस नोट भेज सकते हैं?"),
                ("I have read your message.", "मैंने आपका मैसेज पढ़ लिया है।"),
                ("Please add me to the group.", "कृपया मुझे ग्रुप में जोड़ दीजिए।"),
                ("I posted a new status today.", "मैंने आज एक नया स्टेटस लगाया।"),
                ("This video is going viral.", "यह वीडियो वायरल हो रहा है।"),
                ("Please mute the group chat.", "कृपया ग्रुप चैट म्यूट कर दीजिए।"),
                ("I saw your post on Instagram.", "मैंने आपकी पोस्ट इंस्टाग्राम पर देखी।"),
                ("Let us video call tonight.", "चलो आज रात वीडियो कॉल करते हैं।"),
                ("The network is weak here.", "यहाँ नेटवर्क कमज़ोर है।"),
                ("Please forward this message to others.", "कृपया यह मैसेज दूसरों को फॉरवर्ड कीजिए।"),
                ("I shared the pictures with the family group.", "मैंने तस्वीरें फैमिली ग्रुप में साझा कीं।"),
                ("Do not share your password online.", "अपना पासवर्ड ऑनलाइन साझा न करें।"),
                ("I am online now.", "मैं अभी ऑनलाइन हूँ।"),
                ("Let us chat later. I am busy now.", "चलो बाद में चैट करते हैं। मैं अभी व्यस्त हूँ।"),
                ("I have not seen your message yet.", "मैंने आपका मैसेज अभी तक नहीं देखा।"),
                ("This app is very popular.", "यह ऐप बहुत लोकप्रिय है।"),
                ("Please react to my message.", "कृपया मेरे मैसेज पर रिएक्ट कीजिए।"),
                ("I will update my profile picture.", "मैं अपनी प्रोफाइल फोटो बदलूँगा।"),
                ("Social media keeps us connected.", "सोशल मीडिया हमें जुड़े रखता है।"),
            ]},
            {"title": "Public Transport", "desc": "Use buses and trains", "topic": "Transport", "sentences": [
                ("Where is the bus stop?", "बस स्टॉप कहाँ है?"),
                ("Which bus goes to the market?", "बाज़ार के लिए कौन सी बस जाती है?"),
                ("How much is the bus fare?", "बस का किराया कितना है?"),
                ("Please let me get down here.", "कृपया मुझे यहाँ उतार दीजिए।"),
                ("Is this seat taken?", "क्या यह सीट खाली है?"),
                ("The bus is late today.", "बस आज देर से आई है।"),
                ("I missed the last bus.", "मैं आखिरी बस मिस कर गया।"),
                ("Where is the ticket counter?", "टिकट काउंटर कहाँ है?"),
                ("One ticket to the city centre, please.", "सिटी सेंटर के लिए एक टिकट, कृपया।"),
                ("Does this train stop at the central station?", "क्या यह ट्रेन सेंट्रल स्टेशन पर रुकती है?"),
                ("The metro is the fastest way to travel.", "यात्रा करने का मेट्रो सबसे तेज़ तरीका है।"),
                ("Please stand behind the yellow line.", "कृपया पीली रेखा के पीछे खड़े रहिए।"),
                ("The bus is very crowded.", "बस बहुत भीड़भाड़ वाली है।"),
                ("I take the metro to work every day.", "मैं हर दिन काम पर मेट्रो लेता हूँ।"),
                ("What is the last train timing?", "आखिरी ट्रेन का समय क्या है?"),
                ("Please move to the back.", "कृपया पीछे जाइए।"),
                ("The driver will stop at the next signal.", "ड्राइवर अगले सिग्नल पर रुकेगा।"),
                ("I need a monthly pass.", "मुझे एक मासिक पास चाहिए।"),
                ("The platform number is 3.", "प्लेटफॉर्म नंबर 3 है।"),
                ("The train is arriving now.", "ट्रेन अभी आ रही है।"),
                ("Mind the gap while boarding.", "चढ़ते समय खाली जगह का ध्यान रखिए।"),
                ("The auto fare is negotiable.", "ऑटो का किराया मोलभाव किया जा सकता है।"),
                ("I will walk to the station.", "मैं स्टेशन तक पैदल चलूँगा।"),
                ("Public transport saves money.", "सार्वजनिक परिवहन पैसे बचाता है।"),
                ("The bus will come in five minutes.", "बस पाँच मिनट में आ जाएगी।"),
            ]},
            {"title": "Auto & Taxi", "desc": "Take autos and taxis", "topic": "Auto", "sentences": [
                ("Auto! Will you go to the station?", "ऑटो! क्या आप स्टेशन चलेंगे?"),
                ("How much will you charge?", "कितना किराया लेंगे?"),
                ("That is too much. Please reduce it.", "यह बहुत ज्यादा है। कृपया कम कीजिए।"),
                ("Please go by the meter.", "कृपया मीटर से चलिए।"),
                ("Please switch on the meter.", "कृपया मीटर चालू कीजिए।"),
                ("Please drop me at this address.", "कृपया मुझे इस पते पर छोड़ दीजिए।"),
                ("Turn left at the next corner.", "अगले कोने पर बाएँ मुड़िए।"),
                ("Please drive slowly.", "कृपया धीरे चलाइए।"),
                ("How long will it take to reach?", "पहुँचने में कितना समय लगेगा?"),
                ("I am in a hurry. Please drive fast.", "मुझे जल्दी है। कृपया तेज़ चलाइए।"),
                ("Please stop here.", "कृपया यहाँ रुकिए।"),
                ("Can I book a cab for tomorrow morning?", "क्या मैं कल सुबह के लिए कैब बुक कर सकता हूँ?"),
                ("The cab is on its way.", "कैब आ रही है।"),
                ("Please share the ride details.", "कृपया राइड का विवरण साझा करें।"),
                ("The driver was very nice.", "ड्राइवर बहुत अच्छा था।"),
                ("I paid through the app.", "मैंने ऐप से भुगतान किया।"),
                ("Please wait for me here.", "कृपया मेरा यहाँ इंतज़ार कीजिए।"),
                ("I will be back in ten minutes.", "मैं दस मिनट में वापस आ जाऊँगा।"),
                ("The traffic is bad today.", "आज ट्रैफिक खराब है।"),
                ("Please use the highway route.", "कृपया हाईवे वाला रास्ता लीजिए।"),
                ("The fare came to 120 rupees.", "किराया 120 रुपये हुआ।"),
                ("I gave a tip to the driver.", "मैंने ड्राइवर को टिप दी।"),
                ("It is safer to book a cab at night.", "रात में कैब बुक करना सुरक्षित है।"),
                ("The auto driver helped me with my luggage.", "ऑटो ड्राइवर ने मेरे सामान में मदद की।"),
                ("Please reach on time for the appointment.", "कृपया अपॉइंटमेंट के लिए समय पर पहुँचिए।"),
            ]},
            {"title": "Delivery & Parcel", "desc": "Receive and send parcels", "topic": "Delivery", "sentences": [
                ("I have a parcel for you.", "आपके लिए एक पार्सल है।"),
                ("Please sign here for delivery.", "कृपया डिलीवरी के लिए यहाँ हस्ताक्षर करें।"),
                ("The courier has arrived.", "कूरियर आ गया है।"),
                ("I want to send this parcel to Delhi.", "मैं यह पार्सल दिल्ली भेजना चाहता हूँ।"),
                ("What is the shipping cost?", "शिपिंग लागत क्या है?"),
                ("How many days will it take?", "इसमें कितने दिन लगेंगे?"),
                ("Please pack it carefully.", "कृपया इसे सावधानी से पैक कीजिए।"),
                ("I am waiting for my delivery.", "मैं अपनी डिलीवरी का इंतज़ार कर रहा हूँ।"),
                ("The delivery is delayed.", "डिलीवरी में देरी हुई है।"),
                ("Please call me when you arrive.", "पहुँचते ही कृपया मुझे कॉल कीजिए।"),
                ("My package has arrived at the office.", "मेरा पैकेज ऑफिस पहुँच गया है।"),
                ("Please leave the parcel at the gate.", "कृपया पार्सल गेट पर छोड़ दीजिए।"),
                ("I need to track my shipment.", "मुझे अपनी शिपमेंट ट्रैक करनी है।"),
                ("The delivery boy is at the door.", "डिलीवरी बॉय दरवाज़े पर है।"),
                ("Please deliver it to my office address.", "कृपया इसे मेरे ऑफिस के पते पर पहुँचाइए।"),
                ("I will send the documents by courier.", "मैं दस्तावेज़ कूरियर से भेजूँगा।"),
                ("The parcel was damaged during transit.", "पार्सल यात्रा के दौरान खराब हो गया।"),
                ("Please use bubble wrap for glass items.", "कृपया काँच की चीज़ों के लिए बबल रैप इस्तेमाल करें।"),
                ("My order is out for delivery.", "मेरा ऑर्डर डिलीवरी के लिए निकल गया है।"),
                ("Please confirm the delivery address.", "कृपया डिलीवरी का पता कन्फर्म करें।"),
                ("The courier office is near the market.", "कूरियर ऑफिस बाज़ार के पास है।"),
                ("I received a damaged box.", "मुझे एक क्षतिग्रस्त डिब्बा मिला।"),
                ("The delivery was made on time.", "डिलीवरी समय पर की गई।"),
                ("Please keep the parcel safely.", "कृपया पार्सल को सुरक्षित रखिए।"),
                ("Online shopping depends on good delivery.", "ऑनलाइन शॉपिंग अच्छी डिलीवरी पर निर्भर है।"),
            ]},
            {"title": "Evening & Leisure", "desc": "Relax and enjoy your evening", "topic": "Evening", "sentences": [
                ("I am free this evening.", "मैं आज शाम को खाली हूँ।"),
                ("Let us watch a movie tonight.", "चलो आज रात कोई फिल्म देखते हैं।"),
                ("I like to read books in the evening.", "मुझे शाम को किताबें पढ़ना पसंद है।"),
                ("Let us go for a walk in the park.", "चलो पार्क में टहलने चलते हैं।"),
                ("The weather is nice for a walk.", "टहलने के लिए मौसम अच्छा है।"),
                ("I am watching my favourite show.", "मैं अपना पसंदीदा शो देख रहा हूँ।"),
                ("Let us listen to some music.", "चलो कुछ संगीत सुनते हैं।"),
                ("I play games on my phone.", "मैं अपने फोन पर गेम खेलता हूँ।"),
                ("The sunset is beautiful today.", "आज सूर्यास्त बहुत सुंदर है।"),
                ("We had tea on the balcony.", "हमने बालकनी में चाय पी।"),
                ("I am tired after a long day.", "लंबे दिन के बाद मैं थक गया हूँ।"),
                ("Let us order food tonight.", "चलो आज रात खाना ऑर्डर करते हैं।"),
                ("I will cook something easy today.", "मैं आज कुछ आसान बनाऊँगा।"),
                ("The kids are playing outside.", "बच्चे बाहर खेल रहे हैं।"),
                ("Let us sit in the garden for a while.", "चलो थोड़ी देर बगीचे में बैठते हैं।"),
                ("I am reading an interesting novel.", "मैं एक दिलचस्प उपन्यास पढ़ रहा हूँ।"),
                ("We talked about our childhood memories.", "हमने अपने बचपन की यादों पर बात की।"),
                ("The evening walk refreshes me.", "शाम की सैर मुझे तरोताज़ा करती है।"),
                ("I will rest for some time.", "मैं कुछ देर आराम करूँगा।"),
                ("Let us make some popcorn.", "चलो कुछ पॉपकॉर्न बनाते हैं।"),
                ("I feel relaxed after yoga.", "योग के बाद मैं आराम महसूस करता हूँ।"),
                ("We planned a family dinner.", "हमने फैमिली डिनर की योजना बनाई।"),
                ("The evening is quiet and peaceful.", "शाम शांत और सुखद है।"),
                ("I call my parents every evening.", "मैं हर शाम अपने माता-पिता को कॉल करता हूँ।"),
                ("Good evening! How was your day?", "शुभ संध्या! आपका दिन कैसा रहा?"),
                ("Where is everyone?", "सब कहाँ हैं?"),
                ("Mom is cooking in the kitchen.", "माँ रसोई में खाना बना रही हैं।"),
                ("Dad has gone to the market.", "पिताजी बाज़ार गए हैं।"),
                ("The children are doing their homework.", "बच्चे अपना होमवर्क कर रहे हैं।"),
                ("We should eat dinner together.", "हमें साथ मिलकर खाना खाना चाहिए।"),
                ("Please call everyone for dinner.", "कृपया सबको खाने के लिए बुला दीजिए।"),
                ("I miss my family when I am away.", "दूर होने पर मुझे अपना परिवार याद आता है।"),
                ("Let us watch TV together.", "चलो साथ मिलकर टीवी देखते हैं।"),
                ("The whole family went for a picnic.", "पूरा परिवार पिकनिक पर गया।"),
                ("We play cards on Sunday evenings.", "हम रविवार की शाम को ताश खेलते हैं।"),
                ("My brother is coming home this weekend.", "मेरा भाई इस वीकेंड घर आ रहा है।"),
                ("Grandma tells the best stories.", "दादी सबसे अच्छी कहानियाँ सुनाती हैं।"),
                ("Let us go to the temple together.", "चलो साथ मिलकर मंदिर चलते हैं।"),
                ("We are planning a family vacation.", "हम एक पारिवारिक छुट्टी की योजना बना रहे हैं।"),
                ("Everyone should help with the housework.", "हर किसी को घर के काम में मदद करनी चाहिए।"),
                ("The family photo is on the wall.", "फैमिली फोटो दीवार पर है।"),
                ("We have family lunch on Sundays.", "हम रविवार को फैमिली लंच करते हैं।"),
                ("My sister helps me with my studies.", "मेरी बहन मेरी पढ़ाई में मदद करती है।"),
                ("I love my family more than anything.", "मैं अपने परिवार को किसी भी चीज़ से ज्यादा प्यार करता हूँ।"),
                ("The elders should be respected.", "बड़ों का सम्मान करना चाहिए।"),
                ("We celebrate every festival together.", "हम हर त्योहार साथ मिलकर मनाते हैं।"),
                ("My uncle is visiting us this week.", "मेरे चाचा इस हफ्ते हमसे मिलने आ रहे हैं।"),
                ("Let us clean the house together.", "चलो घर की सफाई साथ मिलकर करते हैं।"),
                ("Family meals are the best time to talk.", "परिवार के साथ खाना बात करने का सबसे अच्छा समय है।"),
                ("Home is where your family is.", "घर वही है जहाँ आपका परिवार है।"),
            ]},
            {"title": "Neighbours & Society", "desc": "Talk with neighbours", "topic": "Neighbours", "sentences": [
                ("Good morning, neighbour! How are you?", "सुप्रभात, पड़ोसी! आप कैसे हैं?"),
                ("We have a society meeting tomorrow.", "कल हमारी सोसाइटी की मीटिंग है।"),
                ("The maintenance is due this month.", "इस महीने का मेंटेनेंस बाकी है।"),
                ("Please come for tea sometime.", "कृपया कभी चाय पर आइए।"),
                ("The water supply is irregular.", "पानी की आपूर्ति अनियमित है।"),
                ("Who is the secretary of our society?", "हमारी सोसाइटी का सचिव कौन है?"),
                ("The lift is under repair.", "लिफ्ट की मरम्मत चल रही है।"),
                ("Please do not park in front of my gate.", "कृपया मेरे गेट के सामने पार्क न करें।"),
                ("The children play in the common area.", "बच्चे साझा क्षेत्र में खेलते हैं।"),
                ("We organized a cleanliness drive.", "हमने एक सफाई अभियान आयोजित किया।"),
                ("The society has a gym and a park.", "सोसाइटी में एक जिम और पार्क है।"),
                ("Please attend the meeting at 7 PM.", "कृपया शाम 7 बजे की मीटिंग में शामिल हों।"),
                ("The security guard is very helpful.", "सुरक्षा गार्ड बहुत मददगार है।"),
                ("My neighbour's son got a new job.", "मेरे पड़ोसी के बेटे को नई नौकरी मिली।"),
                ("We share the terrace for drying clothes.", "हम कपड़े सुखाने के लिए छत साझा करते हैं।"),
                ("The society celebrates festivals together.", "सोसाइटी त्योहार साथ मिलकर मनाती है।"),
                ("Please keep the corridor clean.", "कृपया गलियारे को साफ रखिए।"),
                ("The visitor parking is full.", "विज़िटर पार्किंग भरी हुई है।"),
                ("Our neighbours are like family now.", "हमारे पड़ोसी अब परिवार जैसे हैं।"),
                ("There is a community kitchen on the ground floor.", "ग्राउंड फ्लोर पर एक सामुदायिक रसोई है।"),
                ("Please switch off the lights in common areas.", "कृपया साझा क्षेत्रों में लाइटें बंद कर दीजिए।"),
                ("The society fee is 500 rupees per month.", "सोसाइटी शुल्क 500 रुपये प्रति माह है।"),
                ("We helped the new family settle in.", "हमने नए परिवार को बसने में मदद की।"),
                ("Good neighbours make a good community.", "अच्छे पड़ोसी अच्छा समुदाय बनाते हैं।"),
                ("Let us all keep our surroundings clean.", "चलो सब अपने आस-पास को साफ रखते हैं।"),
            ]},
            {"title": "Phone & Emergency", "desc": "Handle calls and emergencies", "topic": "Emergency", "sentences": [
                ("There is an emergency. Please call 112.", "एक आपात स्थिति है। कृपया 112 पर कॉल करें।"),
                ("I need an ambulance immediately.", "मुझे तुरंत एम्बुलेंस चाहिए।"),
                ("There has been an accident.", "एक दुर्घटना हुई है।"),
                ("Please call the police.", "कृपया पुलिस को कॉल करें।"),
                ("I am stuck in the lift.", "मैं लिफ्ट में फंस गया हूँ।"),
                ("My house keys are locked inside.", "मेरी घर की चाबियाँ अंदर बंद हो गई हैं।"),
                ("I lost my child in the market.", "मेरा बच्चा बाज़ार में खो गया है।"),
                ("The fire department has been called.", "फायर विभाग को बुला लिया गया है।"),
                ("Please stay calm and follow instructions.", "कृपया शांत रहिए और निर्देशों का पालन कीजिए।"),
                ("I need a doctor urgently.", "मुझे तुरंत डॉक्टर चाहिए।"),
                ("My phone battery is very low.", "मेरे फोन की बैटरी बहुत कम है।"),
                ("Please help me, I am injured.", "कृपया मेरी मदद कीजिए, मैं घायल हूँ।"),
                ("The electricity is off in our area.", "हमारे क्षेत्र में बिजली बंद है।"),
                ("There is a gas leak in the kitchen.", "रसोई में गैस लीक हो रही है।"),
                ("Please inform my family.", "कृपया मेरे परिवार को सूचित कीजिए।"),
                ("I lost my wallet with all my cards.", "मेरा बटुआ सारे कार्ड के साथ खो गया।"),
                ("Is there a hospital nearby?", "क्या पास में कोई अस्पताल है?"),
                ("The water pipe has burst.", "पानी का पाइप फट गया है।"),
                ("Please keep the emergency numbers handy.", "कृपया आपातकालीन नंबर पास में रखिए।"),
                ("My grandmother has fallen down.", "मेरी दादी गिर गई हैं।"),
                ("I need to reach the airport urgently.", "मुझे तुरंत हवाई अड्डा पहुँचना है।"),
                ("The car has broken down on the highway.", "हाईवे पर कार खराब हो गई है।"),
                ("Do not panic. Help is on the way.", "घबराइए मत। मदद आ रही है।"),
                ("Please send your location immediately.", "कृपया तुरंत अपनी लोकेशन भेजिए।"),
                ("Stay safe and be careful.", "सुरक्षित रहिए और सावधान रहिए।"),
            ]},
            {"title": "Weekend Activities", "desc": "Plan and enjoy weekends", "topic": "Weekend", "sentences": [
                ("What are your plans for the weekend?", "आपके वीकेंड के क्या प्लान हैं?"),
                ("I am going shopping this weekend.", "मैं इस वीकेंड खरीदारी करने जा रहा हूँ।"),
                ("Let us visit the museum on Saturday.", "चलो शनिवार को संग्रहालय चलते हैं।"),
                ("I will meet my friends on Sunday.", "मैं रविवार को अपने दोस्तों से मिलूँगा।"),
                ("We are planning a picnic.", "हम एक पिकनिक की योजना बना रहे हैं।"),
                ("The weekend is too short!", "वीकेंड बहुत छोटा होता है!"),
                ("I sleep late on Saturday nights.", "मैं शनिवार की रात देर से सोता हूँ।"),
                ("Let us go to the beach this weekend.", "चलो इस वीकेंड समुद्र तट चलते हैं।"),
                ("I will clean my house on Sunday.", "मैं रविवार को अपना घर साफ करूँगा।"),
                ("We had a wonderful weekend.", "हमारा वीकेंड बहुत शानदार रहा।"),
                ("Let us try the new restaurant this Saturday.", "चलो इस शनिवार नया रेस्तराँ आज़माते हैं।"),
                ("I am going to a wedding this weekend.", "मैं इस वीकेंड एक शादी में जा रहा हूँ।"),
                ("The kids have football practice on Saturdays.", "बच्चों की शनिवार को फुटबॉल प्रैक्टिस है।"),
                ("I will visit my grandparents this weekend.", "मैं इस वीकेंड अपने दादा-दादी से मिलने जाऊँगा।"),
                ("We went for a long drive yesterday.", "हम कल लंबी ड्राइव पर गए।"),
                ("I am learning to cook on weekends.", "मैं वीकेंड पर खाना बनाना सीख रहा हूँ।"),
                ("Let us watch a cricket match together.", "चलो साथ मिलकर क्रिकेट मैच देखते हैं।"),
                ("I read a book on Sunday morning.", "मैं रविवार सुबह एक किताब पढ़ता हूँ।"),
                ("We visited our relatives last weekend.", "हम पिछले वीकेंड अपने रिश्तेदारों से मिलने गए।"),
                ("The weekend went by very fast.", "वीकेंड बहुत जल्दी बीत गया।"),
                ("Let us make plans for next Saturday.", "चलो अगले शनिवार के लिए योजना बनाते हैं।"),
                ("I love lazy Sunday mornings.", "मुझे आरामदायक रविवार की सुबह बहुत पसंद है।"),
                ("We played board games all evening.", "हमने पूरी शाम बोर्ड गेम खेले।"),
                ("I am going for a hike this Sunday.", "मैं इस रविवार ट्रेकिंग पर जा रहा हूँ।"),
                ("Weekends are for family and fun.", "वीकेंड परिवार और मौज-मस्ती के लिए होते हैं।"),
            ]},
        ],
    }
