# Advanced English - 12 lessons x 25 = 300 sentences

def get_advanced_banks():
    return {
        "course_id": "advanced",
        "title": "Advanced English",
        "desc": "Master professional communication, complex discussions, and advanced speaking skills.",
        "short": "Speak with sophistication",
        "icon": "🎯",
        "color": "brand",
        "difficulty": "Advanced",
        "audience": ["Advanced Learners", "Professionals", "Business Owners"],
        "price": "₹399",
        "lessons": [
            {"title": "Professional Communication", "desc": "Master professional communication", "topic": "Professional", "sentences": [
                ("I would like to schedule a meeting to discuss the quarterly results.", "मैं त्रैमासिक परिणामों पर चर्चा के लिए मीटिंग शेड्यूल करना चाहूँगा।"),
                ("Could we arrange a conference call with the stakeholders?", "क्या हम हितधारकों के साथ कॉन्फ्रेंस कॉल कर सकते हैं?"),
                ("Please find the attached report for your reference.", "कृपया आपके संदर्भ के लिए संलग्न रिपोर्ट देखें।"),
                ("I look forward to your feedback on the proposal.", "मैं प्रस्ताव पर आपकी प्रतिक्रिया की प्रतीक्षा कर रहा हूँ।"),
                ("I am writing to express my interest in this opportunity.", "मैं इस अवसर में अपनी रुचि दर्शाने के लिए लिख रहा हूँ।"),
                ("It has been a pleasure collaborating with your team.", "आपकी टीम के साथ सहयोग करके खुशी हुई।"),
                ("I would like to bring an important matter to your attention.", "मैं आपका ध्यान एक महत्वपूर्ण मामले की ओर दिलाना चाहूँगा।"),
                ("Could you provide an update on the project status?", "क्या आप परियोजना की स्थिति पर अपडेट दे सकते हैं?"),
                ("I appreciate your prompt response to my query.", "मेरे प्रश्न पर आपकी त्वरित प्रतिक्रिया की सराहना करता हूँ।"),
                ("Let us align our goals to ensure mutual success.", "आइए आपसी सफलता के लिए अपने लक्ष्यों को संरेखित करें।"),
                ("The deliverables are on track for the deadline.", "समय सीमा के लिए डिलिवरेबल सही रास्ते पर हैं।"),
                ("I need your input to finalize the strategy.", "रणनीति को अंतिम रूप देने के लिए मुझे आपके इनपुट की ज़रूरत है।"),
                ("Let us establish clear expectations from the outset.", "शुरू से ही स्पष्ट अपेक्षाएँ स्थापित करें।"),
                ("I will ensure the deliverables meet the required standards.", "मैं सुनिश्चित करूँगा कि डिलिवरेबल आवश्यक मानकों को पूरा करें।"),
                ("Please acknowledge receipt of this message.", "कृपया इस संदेश की प्राप्ति की पुष्टि करें।"),
                ("I propose that we revisit our timeline.", "मैं प्रस्ताव करता हूँ कि हम अपनी समय-सीमा पर पुनर्विचार करें।"),
                ("We need to prioritize our tasks based on urgency.", "हमें तात्कालिकता के आधार पर अपने कार्यों को प्राथमिकता देनी है।"),
                ("I would be happy to assist you with this matter.", "मुझे इस मामले में आपकी सहायता करने में खुशी होगी।"),
                ("Please do not hesitate to reach out if you have concerns.", "यदि आपको कोई चिंता हो तो कृपया संपर्क करने में संकोच न करें।"),
                ("I am confident we can reach a mutually beneficial agreement.", "मुझे विश्वास है हम आपसी लाभ के समझौते पर पहुँच सकते हैं।"),
                ("Let me reiterate the key points from our discussion.", "मुझे हमारी चर्चा के मुख्य बिंदुओं को दोहराने दें।"),
                ("I value your perspective on this issue.", "मैं इस मुद्दे पर आपके दृष्टिकोण को महत्व देता हूँ।"),
                ("We should leverage our strengths to gain an advantage.", "हमें लाभ पाने के लिए अपनी ताकत का उपयोग करना चाहिए।"),
                ("I recommend that we proceed with the outlined plan.", "मैं सिफारिश करता हूँ कि हम उल्लिखित योजना के साथ आगे बढ़ें।"),
                ("Thank you for your continued support and collaboration.", "आपके निरंतर समर्थन और सहयोग के लिए धन्यवाद।"),
            ]},
            {"title": "Complex Opinions", "desc": "Express complex opinions", "topic": "Complex Opinions", "sentences": [
                ("From a strategic perspective, this approach has several advantages.", "रणनीतिक दृष्टिकोण से, इस तरीके के कई फायदे हैं।"),
                ("I would argue that the underlying issue is more systemic.", "मैं तर्क करूँगा कि अंतर्निहित समस्या अधिक प्रणालीगत है।"),
                ("While I understand your reasoning, I see it differently.", "जबकि मैं आपके तर्क को समझता हूँ, मैं इसे अलग तरह से देखता हूँ।"),
                ("The evidence suggests that we need a different approach.", "साक्ष्य बताते हैं कि हमें एक अलग दृष्टिकोण की आवश्यकता है।"),
                ("There are multiple factors to consider in this case.", "इस मामले में विचार करने के लिए कई कारक हैं।"),
                ("I would like to challenge that assumption.", "मैं उस धारणा को चुनौती देना चाहूँगा।"),
                ("Let me offer a counter-perspective.", "मुझे एक विपरीत दृष्टिकोण देने दें।"),
                ("The data paints a different picture.", "आँकड़े एक अलग तस्वीर दिखाते हैं।"),
                ("It depends on how you look at it.", "यह इस पर निर्भर करता है कि आप इसे कैसे देखते हैं।"),
                ("I am inclined to agree with the majority view.", "मैं बहुमत के दृष्टिकोण से सहमत होने को इच्छुक हूँ।"),
                ("This raises an important question about sustainability.", "यह स्थिरता के बारे में एक महत्वपूर्ण प्रश्न उठाता है।"),
                ("We must weigh the short-term gains against long-term costs.", "हमें अल्पकालिक लाभों को दीर्घकालिक लागतों के विरुद्ध तौलना चाहिए।"),
                ("The situation calls for a balanced approach.", "स्थिति एक संतुलित दृष्टिकोण की माँग करती है।"),
                ("I have reservations about this proposal.", "मुझे इस प्रस्ताव के बारे में कुछ आपत्तियाँ हैं।"),
                ("Let us examine the implications carefully.", "चलो निहितार्थों की सावधानीपूर्वक जाँच करते हैं।"),
                ("My concern is about the execution, not the idea.", "मेरी चिंता विचार के बारे में नहीं, बल्कि क्रियान्वयन के बारे में है।"),
                ("The context matters a great deal here.", "यहाँ संदर्भ बहुत मायने रखता है।"),
                ("We should consider the long-term vision.", "हमें दीर्घकालिक दृष्टि पर विचार करना चाहिए।"),
                ("This decision has far-reaching consequences.", "इस निर्णय के दूरगामी परिणाम हैं।"),
                ("I would caution against hasty conclusions.", "मैं जल्दबाज़ी के निष्कर्षों के खिलाफ सावधान करूँगा।"),
                ("The framework provides a useful lens for analysis.", "ढांचा विश्लेषण के लिए एक उपयोगी दृष्टिकोण प्रदान करता है।"),
                ("We are seeing a paradigm shift in this industry.", "हम इस उद्योग में एक प्रतिमान बदलाव देख रहे हैं।"),
                ("Complex issues require thoughtful discussion.", "जटिल मुद्दों पर विचारपूर्ण चर्चा की आवश्यकता होती है।"),
                ("Every perspective adds value to the discussion.", "हर दृष्टिकोण चर्चा में मूल्य जोड़ता है।"),
                ("Critical thinking is essential for complex problems.", "जटिल समस्याओं के लिए आलोचनात्मक सोच आवश्यक है।"),
            ]},
            {"title": "Presentations & Talks", "desc": "Deliver professional presentations", "topic": "Presentations", "sentences": [
                ("Let me begin by providing some context.", "मुझे कुछ संदर्भ देकर शुरू करने दें।"),
                ("I will structure my presentation into three parts.", "मैं अपनी प्रस्तुति को तीन भागों में विभाजित करूँगा।"),
                ("The objective of this presentation is to outline our strategy.", "इस प्रस्तुति का उद्देश्य हमारी रणनीति को रेखांकित करना है।"),
                ("As the chart illustrates, our growth has been consistent.", "जैसा कि चार्ट दर्शाता है, हमारी वृद्धि लगातार रही है।"),
                ("Let me draw your attention to the key metrics.", "मुझे आपका ध्यान मुख्य मेट्रिक्स की ओर आकर्षित करने दें।"),
                ("This data reflects a positive trend overall.", "यह डेटा समग्र रूप से एक सकारात्मक रुझान दर्शाता है।"),
                ("I would like to highlight a few important findings.", "मैं कुछ महत्वपूर्ण निष्कर्षों पर प्रकाश डालना चाहूँगा।"),
                ("Let us delve deeper into this aspect.", "चलो इस पहलू में और गहराई से जाते हैं।"),
                ("In summary, our approach has proven effective.", "संक्षेप में, हमारा दृष्टिकोण प्रभावी साबित हुआ है।"),
                ("I welcome any questions you may have.", "मैं आपके किसी भी प्रश्न का स्वागत करता हूँ।"),
                ("Let me elaborate on the previous point.", "मुझे पिछले बिंदु पर विस्तार से बताने दें।"),
                ("For instance, consider the case of our recent launch.", "उदाहरण के लिए, हमारे हालिया लॉन्च के मामले पर विचार करें।"),
                ("The figures speak for themselves.", "आँकड़े खुद बोलते हैं।"),
                ("We have seen remarkable progress in this area.", "हमने इस क्षेत्र में उल्लेखनीय प्रगति देखी है।"),
                ("I will conclude with a few recommendations.", "मैं कुछ सिफारिशों के साथ समाप्त करूँगा।"),
                ("Thank you for your attention throughout.", "पूरे समय ध्यान देने के लिए धन्यवाद।"),
                ("Let us open the floor for discussion.", "चलो चर्चा के लिए मंच खोलते हैं।"),
                ("I would be happy to answer your questions.", "मुझे आपके प्रश्नों का उत्तर देने में खुशी होगी।"),
                ("That is an excellent question.", "यह एक उत्कृष्ट प्रश्न है।"),
                ("Allow me to address that concern.", "मुझे उस चिंता का समाधान करने दें।"),
                ("The evidence strongly supports our position.", "साक्ष्य हमारी स्थिति का दृढ़ता से समर्थन करते हैं।"),
                ("We must keep the audience engaged.", "हमें दर्शकों को व्यस्त रखना चाहिए।"),
                ("Storytelling makes presentations memorable.", "कहानी कहने से प्रस्तुतियाँ यादगार बनती हैं।"),
                ("Confidence and clarity define great speakers.", "आत्मविश्वास और स्पष्टता महान वक्ताओं को परिभाषित करते हैं।"),
                ("Every presentation is a chance to inspire.", "हर प्रस्तुति प्रेरित करने का एक अवसर है।"),
            ]},
            {"title": "Negotiation & Persuasion", "desc": "Negotiate and persuade", "topic": "Negotiation", "sentences": [
                ("Let us find common ground on this issue.", "चलो इस मुद्दे पर साझा आधार खोजते हैं।"),
                ("I believe we can structure a deal that benefits everyone.", "मुझे विश्वास है हम ऐसा सौदा बना सकते हैं जो सभी को लाभ दे।"),
                ("Our proposal offers significant long-term value.", "हमारा प्रस्ताव महत्वपूर्ण दीर्घकालिक मूल्य प्रदान करता है।"),
                ("We are willing to be flexible on certain terms.", "हम कुछ शर्तों पर लचीले होने को तैयार हैं।"),
                ("What would make this agreement workable for you?", "आपके लिए इस समझौते को कारगर बनाने के लिए क्या चाहिए?"),
                ("Let me present the case from our perspective.", "मुझे अपने दृष्टिकोण से मामला प्रस्तुत करने दें।"),
                ("I am confident this partnership will prove valuable.", "मुझे विश्वास है यह साझेदारी मूल्यवान साबित होगी।"),
                ("Consider the competitive advantages this offers.", "इससे मिलने वाले प्रतिस्पर्धात्मक लाभों पर विचार करें।"),
                ("We can negotiate the finer details later.", "हम बाद में बारीक विवरणों पर बातचीत कर सकते हैं।"),
                ("The terms are reasonable given the current market.", "वर्तमान बाजार को देखते हुए शर्तें उचित हैं।"),
                ("I would like to emphasize the mutual benefits.", "मैं आपसी लाभों पर जोर देना चाहूँगा।"),
                ("Let us not let minor differences block the deal.", "चलो छोटे मतभेदों को सौदे में बाधा न बनने दें।"),
                ("We have made significant concessions already.", "हम पहले ही महत्वपूर्ण रियायतें दे चुके हैं।"),
                ("This is a fair and balanced proposal.", "यह एक उचित और संतुलित प्रस्ताव है।"),
                ("I can assure you of our full commitment.", "मैं आपको अपनी पूर्ण प्रतिबद्धता का आश्वासन दे सकता हूँ।"),
                ("Successful negotiation requires active listening.", "सफल बातचीत के लिए सक्रिय सुनना आवश्यक है।"),
                ("We reached a mutually satisfactory agreement.", "हम एक पारस्परिक रूप से संतोषजनक समझौते पर पहुँचे।"),
                ("Persuasion is about building trust.", "अनुनय विश्वास बनाने के बारे में है।"),
                ("Facts and figures strengthen your argument.", "तथ्य और आँकड़े आपके तर्क को मजबूत करते हैं।"),
                ("Understand the other party's needs first.", "पहले दूसरे पक्ष की ज़रूरतों को समझिए।"),
                ("A win-win mindset leads to lasting deals.", "जीत-जीत की मानसिकता स्थायी सौदों की ओर ले जाती है।"),
                ("We closed the negotiation successfully.", "हमने बातचीत सफलतापूर्वक पूरी की।"),
                ("Good negotiators build relationships, not just deals.", "अच्छे वार्ताकार सिर्फ सौदे नहीं, संबंध बनाते हैं।"),
                ("Patience and preparation win negotiations.", "धैर्य और तैयारी बातचीत जीतते हैं।"),
                ("The agreement was signed after careful discussion.", "सावधानीपूर्वक चर्चा के बाद समझौते पर हस्ताक्षर हुए।"),
            ]},
            {"title": "Leadership Talk", "desc": "Communicate as a leader", "topic": "Leadership", "sentences": [
                ("As a leader, I believe in empowering my team.", "एक नेता के रूप में, मैं अपनी टीम को सशक्त बनाने में विश्वास करता हूँ।"),
                ("I take responsibility for the team's outcomes.", "मैं टीम के परिणामों की जिम्मेदारी लेता हूँ।"),
                ("Let us define a clear vision for the quarter.", "चलो तिमाही के लिए एक स्पष्ट दृष्टि परिभाषित करते हैं।"),
                ("I am committed to the growth of every team member.", "मैं हर टीम सदस्य के विकास के लिए प्रतिबद्ध हूँ।"),
                ("Great leaders listen more than they speak.", "महान नेता बोलने से ज्यादा सुनते हैं।"),
                ("We need to lead by example.", "हमें उदाहरण द्वारा नेतृत्व करने की आवश्यकता है।"),
                ("I appreciate diverse ideas within the team.", "मैं टीम के भीतर विविध विचारों की सराहना करता हूँ।"),
                ("Let us create an environment of trust.", "चलो विश्वास का वातावरण बनाते हैं।"),
                ("Empowering others brings out their best.", "दूसरों को सशक्त बनाना उनका सर्वश्रेष्ठ सामने लाता है।"),
                ("A leader guides without controlling.", "एक नेता नियंत्रण किए बिना मार्गदर्शन करता है।"),
                ("We celebrate both success and learning.", "हम सफलता और सीख दोनों का जश्न मनाते हैं।"),
                ("I encourage open and honest communication.", "मैं खुले और ईमानदार संवाद को प्रोत्साहित करता हूँ।"),
                ("The team's morale is my priority.", "टीम का मनोबल मेरी प्राथमिकता है।"),
                ("Let us acknowledge the contributions of everyone.", "चलो सभी के योगदान को स्वीकार करते हैं।"),
                ("I make decisions with the team's best interest in mind.", "मैं टीम के सर्वोत्तम हित को ध्यान में रखकर निर्णय लेता हूँ।"),
                ("Clear communication prevents confusion.", "स्पष्ट संवाद भ्रम को रोकता है।"),
                ("A strong vision unites the team.", "एक मजबूत दृष्टि टीम को एकजुट करती है।"),
                ("I believe in constructive feedback.", "मैं रचनात्मक प्रतिक्रिया में विश्वास करता हूँ।"),
                ("Leaders create opportunities for others.", "नेता दूसरों के लिए अवसर बनाते हैं।"),
                ("Resilience is a key leadership quality.", "लचीलापन एक प्रमुख नेतृत्व गुण है।"),
                ("We grew together as a team this year.", "हम इस साल एक टीम के रूप में साथ बढ़े।"),
                ("I am proud to lead such a talented team.", "मुझे इतनी प्रतिभाशाली टीम का नेतृत्व करने पर गर्व है।"),
                ("Leadership is about service, not status.", "नेतृत्व सेवा के बारे में है, पद के बारे में नहीं।"),
                ("Trust is the foundation of great teams.", "विश्वास महान टीमों की नींव है।"),
                ("Together we achieve the extraordinary.", "साथ मिलकर हम असाधारण हासिल करते हैं।"),
            ]},
            {"title": "Conflict & Resolution", "desc": "Handle workplace conflict", "topic": "Conflict", "sentences": [
                ("We have a disagreement that needs resolution.", "हमारा एक मतभेद है जिसे हल करने की आवश्यकता है।"),
                ("Let us discuss this calmly and objectively.", "चलो इस पर शांति और निष्पक्षता से चर्चा करते हैं।"),
                ("I understand there are two sides to this issue.", "मैं समझता हूँ इस मुद्दे के दो पक्ष हैं।"),
                ("Let me hear your perspective first.", "मुझे पहले आपका दृष्टिकोण सुनने दें।"),
                ("We should focus on the problem, not blame people.", "हमें लोगों को दोष देने के बजाय समस्या पर ध्यान देना चाहिए।"),
                ("Let us find a solution that works for everyone.", "चलो एक ऐसा समाधान खोजते हैं जो सभी के लिए काम करे।"),
                ("I apologize if my words caused misunderstanding.", "अगर मेरे शब्दों से गलतफहमी हुई तो मैं क्षमा चाहता हूँ।"),
                ("We need to clear the air between us.", "हमें अपने बीच की बात साफ करनी है।"),
                ("Let us agree on the facts first.", "चलो पहले तथ्यों पर सहमत होते हैं।"),
                ("The conflict was resolved through discussion.", "चर्चा के माध्यम से संघर्ष हल हो गया।"),
                ("We learned to respect each other's views.", "हमने एक-दूसरे के विचारों का सम्मान करना सीखा।"),
                ("A mediated conversation helped us understand.", "मध्यस्थता वाली बातचीत ने हमें समझने में मदद की।"),
                ("We found a middle ground eventually.", "हमें अंततः एक मध्यम रास्ता मिल गया।"),
                ("Healthy conflict can lead to better ideas.", "स्वस्थ संघर्ष बेहतर विचारों की ओर ले जा सकता है।"),
                ("The team moved forward after the resolution.", "समाधान के बाद टीम आगे बढ़ गई।"),
                ("Resolving conflicts requires empathy.", "संघर्षों को हल करने के लिए सहानुभूति की आवश्यकता होती है।"),
                ("We addressed the issue at the right time.", "हमने सही समय पर मुद्दे का समाधान किया।"),
                ("Open dialogue prevents minor issues from growing.", "खुला संवाद छोटे मुद्दों को बढ़ने से रोकता है।"),
                ("The relationship is stronger after the discussion.", "चर्चा के बाद रिश्ता और मजबूत है।"),
                ("Everyone's feelings were heard and respected.", "हर किसी की भावनाओं को सुना और सम्मान दिया गया।"),
                ("We agreed to communicate more clearly going forward.", "हम आगे और स्पष्ट रूप से संवाद करने पर सहमत हुए।"),
                ("Conflict resolution is a valuable skill.", "संघर्ष समाधान एक मूल्यवान कौशल है।"),
                ("Patience is key when emotions run high.", "जब भावनाएँ उच्च हों तो धैर्य महत्वपूर्ण है।"),
                ("We turned the conflict into a learning opportunity.", "हमने संघर्ष को एक सीखने के अवसर में बदल दिया।"),
                ("A respectful workplace resolves issues faster.", "सम्मानजनक कार्यस्थल मुद्दों को जल्दी हल करता है।"),
            ]},
            {"title": "Explaining Complex Ideas", "desc": "Explain complex concepts", "topic": "Complex Ideas", "sentences": [
                ("Let me break this complex concept into simpler parts.", "मुझे इस जटिल अवधारणा को सरल भागों में विभाजित करने दें।"),
                ("Think of it as a chain of connected steps.", "इसे जुड़े हुए कदमों की एक श्रृंखला के रूप में सोचिए।"),
                ("The fundamental principle is quite elegant.", "मूल सिद्धांत काफी सुंदर है।"),
                ("Let us use an analogy to understand this better.", "चलो इसे बेहतर समझने के लिए एक उपमा का उपयोग करते हैं।"),
                ("Imagine the system as a network of parts.", "सिस्टम को भागों के एक नेटवर्क के रूप में कल्पना करें।"),
                ("The concept rests on three basic assumptions.", "अवधारणा तीन बुनियादी मान्यताओं पर आधारित है।"),
                ("This might seem complex, but the logic is simple.", "यह जटिल लग सकता है, लेकिन तर्क सरल है।"),
                ("Let me illustrate with a practical example.", "मुझे एक व्यावहारिक उदाहरण के साथ समझाने दें।"),
                ("The core idea revolves around efficiency.", "मूल विचार दक्षता के इर्द-गिर्द घूमता है।"),
                ("We can simplify it by focusing on the essentials.", "हम आवश्यक चीज़ों पर ध्यान केंद्रित करके इसे सरल बना सकते हैं।"),
                ("There is a logical progression to this process.", "इस प्रक्रिया में एक तार्किक क्रम है।"),
                ("Let me walk you through the steps.", "मुझे आपको चरणों के माध्यम से समझाने दें।"),
                ("The framework provides a structured way to think.", "ढांचा सोचने का एक संरचित तरीका प्रदान करता है।"),
                ("We can view it from different angles.", "हम इसे अलग-अलग कोणों से देख सकते हैं।"),
                ("The model has proven effective in practice.", "मॉडल व्यवहार में प्रभावी साबित हुआ है।"),
                ("Complexity often hides simple truths.", "जटिलता अक्सर सरल सत्य छिपाती है।"),
                ("Explaining simply is a sign of mastery.", "सरलता से समझाना निपुणता का संकेत है।"),
                ("Visuals make complex ideas accessible.", "दृश्य जटिल विचारों को सुलभ बनाते हैं।"),
                ("We tested the theory with real data.", "हमने सिद्धांत का वास्तविक डेटा के साथ परीक्षण किया।"),
                ("The results confirmed our hypothesis.", "परिणामों ने हमारी परिकल्पना की पुष्टि की।"),
                ("Let me connect the dots for you.", "मुझे आपके लिए बिंदुओं को जोड़ने दें।"),
                ("The idea is powerful because it is simple.", "विचार शक्तिशाली है क्योंकि यह सरल है।"),
                ("We applied the principle successfully.", "हमने सिद्धांत को सफलतापूर्वक लागू किया।"),
                ("Understanding comes from asking the right questions.", "सही प्रश्न पूछने से समझ आती है।"),
                ("Great explanations open minds.", "महान स्पष्टीकरण दिमाग खोलते हैं।"),
            ]},
            {"title": "Storytelling", "desc": "Tell engaging stories", "topic": "Storytelling", "sentences": [
                ("Let me tell you a story from my childhood.", "मुझे आपको अपने बचपन की एक कहानी सुनाने दें।"),
                ("It all started on a rainy evening.", "यह सब एक बरसाती शाम को शुरू हुआ।"),
                ("I remember it as if it were yesterday.", "मुझे वह ऐसे याद है जैसे कल की बात हो।"),
                ("There was a moment of complete silence.", "पूरी तरह सन्नाटे का एक पल था।"),
                ("And then, something unexpected happened.", "और फिर, कुछ अप्रत्याशित हुआ।"),
                ("The twist in the story surprised everyone.", "कहानी में मोड़ ने सभी को चौंका दिया।"),
                ("In the end, everything worked out perfectly.", "अंत में, सब कुछ बिल्कुल ठीक हो गया।"),
                ("This experience taught me a valuable lesson.", "इस अनुभव ने मुझे एक मूल्यवान सबक सिखाया।"),
                ("Let me set the scene for you.", "मुझे आपके लिए दृश्य तैयार करने दें।"),
                ("The journey was full of challenges.", "यात्रा चुनौतियों से भरी थी।"),
                ("We laughed, we cried, we grew together.", "हम हँसे, हम रोए, हम साथ बढ़े।"),
                ("The moral of the story is simple.", "कहानी का नैतिक सीख सरल है।"),
                ("Good storytellers capture attention instantly.", "अच्छे कहानीकार तुरंत ध्यान खींचते हैं।"),
                ("Details make stories come alive.", "विवरण कहानियों को जीवंत बनाते हैं।"),
                ("A great story connects people.", "एक महान कहानी लोगों को जोड़ती है।"),
                ("I could picture the entire scene clearly.", "मैं पूरे दृश्य को स्पष्ट रूप से चित्रित कर सकता था।"),
                ("The audience was completely engaged.", "दर्शक पूरी तरह से जुड़े हुए थे।"),
                ("Stories have the power to inspire.", "कहानियों में प्रेरित करने की शक्ति होती है।"),
                ("Every person has a story worth telling.", "हर व्यक्ति के पास बताने लायक एक कहानी है।"),
                ("Let me share the lessons I learned.", "मुझे अपने सीखे गए सबक साझा करने दें।"),
                ("The narrative built up to a climax.", "कथा एक चरमोत्कर्ष की ओर बढ़ी।"),
                ("We overcame every obstacle together.", "हमने हर बाधा को साथ मिलकर पार किया।"),
                ("Storytelling makes communication memorable.", "कहानी कहने से संवाद यादगार बनता है।"),
                ("The ending left everyone inspired.", "अंत ने सभी को प्रेरित छोड़ा।"),
                ("Our stories shape who we are.", "हमारी कहानियाँ हमें आकार देती हैं।"),
            ]},
            {"title": "Formal Communication", "desc": "Use formal language", "topic": "Formal", "sentences": [
                ("I am writing to formally request your approval.", "मैं औपचारिक रूप से आपकी मंज़ूरी का अनुरोध करने के लिए लिख रहा हूँ।"),
                ("Kindly acknowledge the receipt of this document.", "कृपया इस दस्तावेज़ की प्राप्ति स्वीकार करें।"),
                ("We would be grateful for your prompt consideration.", "आपके शीघ्र विचार के लिए हम आभारी होंगे।"),
                ("Please be advised that the policy has changed.", "कृपया सूचित रहें कि नीति बदल गई है।"),
                ("I wish to bring the following to your notice.", "मैं आपके ध्यान में निम्नलिखित लाना चाहता हूँ।"),
                ("It is with great pleasure that we announce the launch.", "यह बड़े आनंद के साथ है कि हम लॉन्च की घोषणा करते हैं।"),
                ("We regret to inform you about the delay.", "हमें खेद है कि हम आपको देरी के बारे में सूचित कर रहे हैं।"),
                ("Kindly find the details enclosed herewith.", "कृपया विवरण इसके साथ संलग्न देखें।"),
                ("We look forward to your favourable response.", "हम आपके अनुकूल उत्तर की प्रतीक्षा कर रहे हैं।"),
                ("I would appreciate your guidance in this matter.", "इस मामले में मैं आपके मार्गदर्शन की सराहना करूँगा।"),
                ("Please do not hesitate to contact us for assistance.", "सहायता के लिए कृपया हमसे संपर्क करने में संकोच न करें।"),
                ("The management has decided to implement new measures.", "प्रबंधन ने नए उपाय लागू करने का निर्णय लिया है।"),
                ("We assure you of our best services at all times.", "हम आपको हर समय अपनी सर्वोत्तम सेवाओं का आश्वासन देते हैं।"),
                ("I hereby confirm my participation in the event.", "मैं इसके द्वारा कार्यक्रम में अपनी भागीदारी की पुष्टि करता हूँ।"),
                ("Kindly arrange for the necessary approvals.", "कृपया आवश्यक स्वीकृतियों की व्यवस्था करें।"),
                ("The undersigned is responsible for this department.", "अधोहस्ताक्षरी इस विभाग के लिए जिम्मेदार है।"),
                ("Please treat this matter as urgent.", "कृपया इस मामले को तात्कालिक मानें।"),
                ("We shall keep you informed of further developments.", "हम आपको आगे के विकास से सूचित रखेंगे।"),
                ("Your cooperation in this regard is highly valued.", "इस संबंध में आपका सहयोग अत्यधिक मूल्यवान है।"),
                ("I take this opportunity to express my sincere thanks.", "मैं इस अवसर का उपयोग अपनी हार्दिक धन्यवाद व्यक्त करने के लिए करता हूँ।"),
                ("Kindly revert at the earliest.", "कृपया जल्द से जल्द जवाब दें।"),
                ("We await your esteemed response.", "हम आपके सम्मानित उत्तर की प्रतीक्षा कर रहे हैं।"),
                ("Formal language conveys professionalism.", "औपचारिक भाषा व्यावसायिकता व्यक्त करती है।"),
                ("Tone matters in formal communication.", "औपचारिक संचार में लहजा मायने रखता है।"),
                ("Clear formal writing reflects competence.", "स्पष्ट औपचारिक लेखन क्षमता को दर्शाता है।"),
            ]},
            {"title": "Advanced Phrases", "desc": "Use advanced English phrases", "topic": "Advanced Phrases", "sentences": [
                ("To be honest, I was taken aback by the news.", "सच कहूँ तो, मैं खबर से अचंभित रह गया।"),
                ("It goes without saying that quality matters.", "यह कहने की आवश्यकता नहीं कि गुणवत्ता मायने रखती है।"),
                ("At the end of the day, results speak louder than words.", "आखिरकार, परिणाम शब्दों से ज्यादा बोलते हैं।"),
                ("Let us keep the ball rolling.", "चलो काम को आगे बढ़ाते रहते हैं।"),
                ("We are on the same page regarding this issue.", "हम इस मुद्दे पर एक ही राय रखते हैं।"),
                ("I will get back to you on that.", "मैं उस पर आपको बाद में बताऊँगा।"),
                ("It is a win-win situation for both parties.", "यह दोनों पक्षों के लिए जीत-जीत की स्थिति है।"),
                ("Let us not beat around the bush.", "चलो घुमा-फिराकर बात न करें।"),
                ("The ball is in your court now.", "अब गेंद आपके पाले में है।"),
                ("We need to think outside the box.", "हमें रचनात्मक ढंग से सोचने की आवश्यकता है।"),
                ("This is a game changer for our business.", "यह हमारे व्यवसाय के लिए एक गेम चेंजर है।"),
                ("Let us touch base next week.", "चलो अगले हफ्ते मिलकर बात करते हैं।"),
                ("We are in the same boat.", "हम सब एक ही नाव में हैं।"),
                ("Cutting corners never helps in the long run.", "शॉर्टकट अपनाना लंबे समय में कभी मदद नहीं करता।"),
                ("The proposal is a no-brainer.", "प्रस्ताव एक स्पष्ट निर्णय है।"),
                ("Let me play devil's advocate here.", "मुझे यहाँ विरोधी पक्ष की भूमिका निभाने दें।"),
                ("We should strike while the iron is hot.", "हमें लोहा गर्म होने पर ही चोट करनी चाहिए।"),
                ("That is the tip of the iceberg.", "यह तो सिर्फ हिमशैल का सिरा है।"),
                ("Let us not reinvent the wheel.", "चलो पहिये को फिर से न बनाएँ।"),
                ("We need to step up our game.", "हमें अपना स्तर बढ़ाना होगा।"),
                ("It is a long shot, but worth trying.", "यह एक लंबा शॉट है, लेकिन आज़माने लायक है।"),
                ("We are burning the midnight oil on this project.", "हम इस परियोजना पर रात-रात भर काम कर रहे हैं।"),
                ("Advanced phrases add colour to your English.", "उन्नत वाक्यांश आपकी अंग्रेज़ी में रंग जोड़ते हैं।"),
                ("Use phrases naturally, not forcefully.", "वाक्यांशों का प्राकृतिक रूप से उपयोग करें, जबरदस्ती नहीं।"),
                ("Mastery comes from using phrases in context.", "निपुणता संदर्भ में वाक्यांशों के उपयोग से आती है।"),
            ]},
            {"title": "Critical Thinking", "desc": "Discuss with critical thinking", "topic": "Critical Thinking", "sentences": [
                ("Let us analyze the situation from all angles.", "चलो स्थिति का सभी कोणों से विश्लेषण करते हैं।"),
                ("What evidence supports this conclusion?", "इस निष्कर्ष का समर्थन करने वाला साक्ष्य क्या है?"),
                ("We should question our assumptions.", "हमें अपनी धारणाओं पर सवाल उठाना चाहिए।"),
                ("Correlation does not always mean causation.", "सहसंबंध का हमेशा कारण से मतलब नहीं होता।"),
                ("Let us consider the counterarguments.", "चलो विपरीत तर्कों पर विचार करते हैं।"),
                ("The data needs careful interpretation.", "डेटा की सावधानीपूर्वक व्याख्या की आवश्यकता है।"),
                ("We must separate facts from opinions.", "हमें तथ्यों को राय से अलग करना चाहिए।"),
                ("What are the potential risks of this approach?", "इस दृष्टिकोण के संभावित जोखिम क्या हैं?"),
                ("Let us evaluate the outcomes objectively.", "चलो परिणामों का निष्पक्ष मूल्यांकन करते हैं।"),
                ("There might be factors we have not considered.", "ऐसे कारक हो सकते हैं जिन पर हमने विचार नहीं किया।"),
                ("Critical thinking requires an open mind.", "आलोचनात्मक सोच के लिए खुला दिमाग चाहिए।"),
                ("Let me question the underlying logic.", "मुझे अंतर्निहित तर्क पर सवाल उठाने दें।"),
                ("The solution may lie in the details.", "समाधान विवरणों में हो सकता है।"),
                ("We should verify the information first.", "हमें पहले जानकारी की पुष्टि करनी चाहिए।"),
                ("Different perspectives reveal different truths.", "अलग-अलग दृष्टिकोण अलग-अलग सत्य प्रकट करते हैं।"),
                ("Let us weigh the evidence carefully.", "चलो साक्ष्य को ध्यान से तौलते हैं।"),
                ("A wise decision is based on solid reasoning.", "बुद्धिमान निर्णय ठोस तर्क पर आधारित होता है।"),
                ("We revisited our initial conclusion.", "हमने अपने प्रारंभिक निष्कर्ष पर पुनर्विचार किया।"),
                ("Questioning leads to deeper understanding.", "सवाल करना गहरी समझ की ओर ले जाता है।"),
                ("The analysis revealed unexpected insights.", "विश्लेषण ने अप्रत्याशित अंतर्दृष्टि प्रकट की।"),
                ("We made a well-informed decision.", "हमने एक सुविचारित निर्णय लिया।"),
                ("Curiosity drives critical thinking.", "जिज्ञासा आलोचनात्मक सोच को चलाती है।"),
                ("Never accept information at face value.", "जानकारी को कभी भी सतही रूप से स्वीकार न करें।"),
                ("Thinking deeply leads to better outcomes.", "गहराई से सोचने से बेहतर परिणाम मिलते हैं।"),
                ("Critical minds solve critical problems.", "आलोचनात्मक दिमाग गंभीर समस्याओं को हल करते हैं।"),
            ]},
            {"title": "Advanced Speaking", "desc": "Refine your speaking skills", "topic": "Advanced Speaking", "sentences": [
                ("I articulate my thoughts with clarity now.", "मैं अब अपने विचार स्पष्टता के साथ व्यक्त करता हूँ।"),
                ("My vocabulary has expanded significantly.", "मेरी शब्दावली में काफी विस्तार हुआ है।"),
                ("I speak with confidence in any situation.", "मैं किसी भी स्थिति में आत्मविश्वास के साथ बोलता हूँ।"),
                ("Nuanced expression comes naturally to me now.", "सूक्ष्म अभिव्यक्ति अब मुझे स्वाभाविक रूप से आती है।"),
                ("I can hold my own in professional discussions.", "मैं पेशेवर चर्चाओं में अपनी बात रख सकता हूँ।"),
                ("My pronunciation has improved a lot.", "मेरे उच्चारण में बहुत सुधार हुआ है।"),
                ("I use appropriate language in every context.", "मैं हर संदर्भ में उपयुक्त भाषा का उपयोग करता हूँ।"),
                ("Speaking in public no longer frightens me.", "सार्वजनिक रूप से बोलना अब मुझे डराता नहीं है।"),
                ("I listen actively and respond thoughtfully.", "मैं सक्रिय रूप से सुनता हूँ और विचारपूर्वक जवाब देता हूँ।"),
                ("My ideas flow smoothly during conversations.", "बातचीत के दौरान मेरे विचार सहजता से प्रवाहित होते हैं।"),
                ("I adapt my language to my audience.", "मैं अपनी भाषा को अपने दर्शकों के अनुसार ढालता हूँ।"),
                ("Persuasive speaking is a powerful skill.", "प्रभावशाली वक्तृत्व एक शक्तिशाली कौशल है।"),
                ("I express myself elegantly in English.", "मैं अंग्रेज़ी में अपनी बात सुंदरता से व्यक्त करता हूँ।"),
                ("Advanced learners think in the language.", "उन्नत सीखने वाले भाषा में सोचते हैं।"),
                ("I continuously refine my speaking style.", "मैं लगातार अपनी बोलने की शैली को निखारता हूँ।"),
                ("My tone matches the situation perfectly.", "मेरा लहजा स्थिति से बिल्कुल मेल खाता है।"),
                ("I engage audiences with compelling stories.", "मैं दर्शकों को सम्मोहक कहानियों से जोड़ता हूँ।"),
                ("Every conversation is a chance to shine.", "हर बातचीत चमकने का एक अवसर है।"),
                ("I speak with precision and purpose.", "मैं सटीकता और उद्देश्य के साथ बोलता हूँ।"),
                ("Mastering speaking takes years of practice.", "बोलने में निपुणता वर्षों के अभ्यास से आती है।"),
                ("I am proud of my advanced speaking skills.", "मुझे अपने उन्नत बोलने के कौशल पर गर्व है।"),
                ("Great speakers are great thinkers first.", "महान वक्ता पहले महान विचारक होते हैं।"),
                ("I inspire others through my words.", "मैं अपने शब्दों से दूसरों को प्रेरित करता हूँ।"),
                ("Confidence and humility make a great speaker.", "आत्मविश्वास और विनम्रता एक महान वक्ता बनाते हैं।"),
                ("My English journey continues to grow.", "मेरी अंग्रेज़ी यात्रा बढ़ती रहती है।"),
            ]},
        ],
    }
