def get_business_banks():
    return {
        "course_id": "business",
        "title": "Business English",
        "desc": "English for business owners and entrepreneurs - sales, customers, suppliers, and deals.",
        "short": "Grow your business with English",
        "icon": "💰",
        "color": "accent",
        "difficulty": "Intermediate",
        "audience": ["Business Owners", "Entrepreneurs", "Salespeople"],
        "price": "₹299",
        "lessons": [
            {"title": "Business Introduction", "desc": "Introduce your business", "topic": "Business Intro", "sentences": [
                ("I run a small business in Delhi.", "मैं दिल्ली में एक छोटा व्यवसाय चलाता हूँ।"),
                ("My company deals in textiles.", "मेरी कंपनी वस्त्रों का व्यापार करती है।"),
                ("We have been in business for ten years.", "हम दस साल से व्यवसाय में हैं।"),
                ("Our company has twenty employees.", "हमारी कंपनी में बीस कर्मचारी हैं।"),
                ("I started this business with a small investment.", "मैंने यह व्यवसाय छोटे निवेश से शुरू किया।"),
                ("We provide quality products to our customers.", "हम अपने ग्राहकों को गुणवत्तापूर्ण उत्पाद प्रदान करते हैं।"),
                ("Our main office is in Mumbai.", "हमारा मुख्य कार्यालय मुंबई में है।"),
                ("We have clients across India.", "हमारे पूरे भारत में ग्राहक हैं।"),
                ("I am the owner of this shop.", "मैं इस दुकान का मालिक हूँ।"),
                ("Our business is growing steadily.", "हमारा व्यवसाय लगातार बढ़ रहा है।"),
                ("We specialize in handmade products.", "हम हस्तनिर्मित उत्पादों में विशेषज्ञ हैं।"),
                ("Our customers are very satisfied.", "हमारे ग्राहक बहुत संतुष्ट हैं।"),
                ("I would like to introduce our company.", "मैं अपनी कंपनी का परिचय देना चाहूँगा।"),
                ("Our brand is known for quality.", "हमारा ब्रांड गुणवत्ता के लिए जाना जाता है।"),
                ("We export our products overseas.", "हम अपने उत्पाद विदेश भेजते हैं।"),
                ("The business started in 2015.", "व्यवसाय 2015 में शुरू हुआ।"),
                ("We believe in customer satisfaction.", "हम ग्राहक संतुष्टि में विश्वास करते हैं।"),
                ("My partner handles the finances.", "मेरा साझेदार वित्त संभालता है।"),
                ("We are expanding to new markets.", "हम नए बाजारों में विस्तार कर रहे हैं।"),
                ("Our vision is to be the best in the industry.", "हमारी दृष्टि उद्योग में सर्वश्रेष्ठ बनना है।"),
                ("Thank you for your interest in our business.", "हमारे व्यवसाय में रुचि के लिए धन्यवाद।"),
                ("We welcome new business partnerships.", "हम नई व्यावसायिक साझेदारियों का स्वागत करते हैं।"),
                ("A strong brand builds trust.", "एक मजबूत ब्रांड विश्वास बनाता है।"),
                ("Every business has a story.", "हर व्यवसाय की एक कहानी होती है।"),
                ("I am proud of my business journey.", "मुझे अपने व्यवसाय की यात्रा पर गर्व है।"),
            ]},
            {"title": "Customer Communication", "desc": "Talk with customers", "topic": "Customers", "sentences": [
                ("Welcome to our store. How can I help you?", "हमारी दुकान में आपका स्वागत है। मैं आपकी क्या मदद कर सकता हूँ?"),
                ("What are you looking for today?", "आप आज क्या ढूँढ रहे हैं?"),
                ("I can recommend our best-selling product.", "मैं हमारा सबसे अधिक बिकने वाला उत्पाद सुझा सकता हूँ।"),
                ("This product comes with a warranty.", "यह उत्पाद वारंटी के साथ आता है।"),
                ("Please let me know if you need any help.", "अगर आपको कोई मदद चाहिए तो कृपया बताइए।"),
                ("Our customers are our priority.", "हमारे ग्राहक हमारी प्राथमिकता हैं।"),
                ("I will check the stock for you.", "मैं आपके लिए स्टॉक जाँचता हूँ।"),
                ("This is our latest collection.", "यह हमारा नवीनतम संग्रह है।"),
                ("Would you like a discount on this?", "क्या आप इस पर छूट चाहेंगे?"),
                ("I will give you a good price.", "मैं आपको एक अच्छी कीमत दूँगा।"),
                ("Thank you for your purchase!", "आपकी खरीदारी के लिए धन्यवाद!"),
                ("We hope to see you again.", "हमें उम्मीद है आप फिर आएँगे।"),
                ("Please share your feedback.", "कृपया अपनी प्रतिक्रिया साझा करें।"),
                ("Your feedback helps us improve.", "आपकी प्रतिक्रिया हमें सुधारने में मदद करती है।"),
                ("I will take care of your order.", "मैं आपके ऑर्डर का ध्यान रखूँगा।"),
                ("The delivery will be made tomorrow.", "डिलीवरी कल की जाएगी।"),
                ("Is there anything else you need?", "क्या आपको और कुछ चाहिए?"),
                ("We value your business.", "हम आपके व्यवसाय को महत्व देते हैं।"),
                ("A happy customer is our best advertisement.", "खुश ग्राहक हमारा सबसे अच्छा विज्ञापन है।"),
                ("I understand your concern.", "मैं आपकी चिंता समझता हूँ।"),
                ("We will solve this for you.", "हम इसे आपके लिए हल कर देंगे।"),
                ("Customer trust is built over time.", "ग्राहक विश्वास समय के साथ बनता है।"),
                ("Treat every customer with respect.", "हर ग्राहक के साथ सम्मान से पेश आइए।"),
                ("Good service brings customers back.", "अच्छी सेवा ग्राहकों को वापस लाती है।"),
                ("We are always here for our customers.", "हम हमेशा अपने ग्राहकों के लिए यहाँ हैं।"),
            ]},
            {"title": "Sales", "desc": "Sell your products", "topic": "Sales", "sentences": [
                ("This is our best-selling product.", "यह हमारा सबसे अधिक बिकने वाला उत्पाद है।"),
                ("The product has many features.", "उत्पाद में कई विशेषताएँ हैं।"),
                ("Let me demonstrate how it works.", "मुझे दिखाने दें कि यह कैसे काम करता है।"),
                ("This will save you money in the long run.", "यह लंबे समय में आपके पैसे बचाएगा।"),
                ("We are offering a special discount today.", "हम आज एक विशेष छूट दे रहे हैं।"),
                ("The quality is better than other brands.", "गुणवत्ता अन्य ब्रांडों से बेहतर है।"),
                ("I am sure you will like this product.", "मुझे यकीन है आपको यह उत्पाद पसंद आएगा।"),
                ("This is a limited time offer.", "यह एक सीमित समय का ऑफर है।"),
                ("Let me show you the price list.", "मुझे आपको मूल्य सूची दिखाने दें।"),
                ("You will not regret this purchase.", "आपको इस खरीदारी पर पछतावा नहीं होगा।"),
                ("We can give you a trial period.", "हम आपको एक परीक्षण अवधि दे सकते हैं।"),
                ("The demand for this product is high.", "इस उत्पाद की माँग अधिक है।"),
                ("Let me compare it with other options.", "मुझे इसे अन्य विकल्पों से तुलना करने दें।"),
                ("Our sales have increased this year.", "इस साल हमारी बिक्री बढ़ी है।"),
                ("We offer bulk discounts.", "हम थोक छूट देते हैं।"),
                ("The product comes with free installation.", "उत्पाद मुफ्त स्थापना के साथ आता है।"),
                ("I will prepare a quotation for you.", "मैं आपके लिए एक कोटेशन तैयार करूँगा।"),
                ("Selling is about solving problems.", "बिक्री समस्याओं को हल करने के बारे में है।"),
                ("Listen to the customer first.", "पहले ग्राहक की सुनिए।"),
                ("A good salesman knows his product.", "एक अच्छा विक्रेता अपने उत्पाद को जानता है।"),
                ("Confidence helps in selling.", "बेचने में आत्मविश्वास मदद करता है।"),
                ("Honesty wins customers.", "ईमानदारी ग्राहक जीतती है।"),
                ("Every customer is important.", "हर ग्राहक महत्वपूर्ण है।"),
                ("Sales are the lifeline of business.", "बिक्री व्यवसाय की जीवन रेखा है।"),
                ("We aim to exceed customer expectations.", "हम ग्राहक की अपेक्षाओं से बढ़कर देने का लक्ष्य रखते हैं।"),
            ]},
            {"title": "Pricing & Payment", "desc": "Discuss prices and payments", "topic": "Pricing", "sentences": [
                ("What is the price of this product?", "इस उत्पाद की कीमत क्या है?"),
                ("The price includes all taxes.", "कीमत में सभी कर शामिल हैं।"),
                ("We can offer a better price for bulk orders.", "हम थोक ऑर्डर के लिए बेहतर कीमत दे सकते हैं।"),
                ("The payment terms are 50 percent advance.", "भुगतान की शर्तें 50 प्रतिशत अग्रिम हैं।"),
                ("Please make the payment within 30 days.", "कृपया 30 दिनों के भीतर भुगतान करें।"),
                ("We accept UPI, cards, and net banking.", "हम यूपीआई, कार्ड और नेट बैंकिंग स्वीकार करते हैं।"),
                ("I will send you the invoice today.", "मैं आज आपको इनवॉइस भेज दूँगा।"),
                ("The total amount comes to 25,000 rupees.", "कुल राशि 25,000 रुपये होती है।"),
                ("Can we negotiate the price?", "क्या हम कीमत पर बातचीत कर सकते हैं?"),
                ("We have flexible payment options.", "हमारे पास लचीले भुगतान विकल्प हैं।"),
                ("The advance payment is non-refundable.", "अग्रिम भुगतान गैर-वापसी योग्य है।"),
                ("Please share your bank details.", "कृपया अपना बैंक विवरण साझा करें।"),
                ("The payment has been received.", "भुगतान प्राप्त हो गया है।"),
                ("I will issue the receipt immediately.", "मैं तुरंत रसीद जारी करूँगा।"),
                ("There is an extra charge for delivery.", "डिलीवरी के लिए एक अतिरिक्त शुल्क है।"),
                ("We give credit to regular customers.", "हम नियमित ग्राहकों को उधार देते हैं।"),
                ("The due date for payment is next month.", "भुगतान की अंतिम तिथि अगले महीने है।"),
                ("Please pay the remaining amount.", "कृपया शेष राशि का भुगतान करें।"),
                ("The pricing is competitive in the market.", "मूल्य निर्धारण बाजार में प्रतिस्पर्धी है।"),
                ("We give discounts for early payment.", "हम जल्दी भुगतान पर छूट देते हैं।"),
                ("Clear pricing builds customer trust.", "स्पष्ट मूल्य निर्धारण ग्राहक विश्वास बनाता है।"),
                ("Always issue a proper bill.", "हमेशा एक उचित बिल जारी करें।"),
                ("Money matters handled well keep business smooth.", "पैसे का अच्छा प्रबंधन व्यवसाय को सुचारू रखता है।"),
                ("We believe in transparent pricing.", "हम पारदर्शी मूल्य निर्धारण में विश्वास करते हैं।"),
                ("Fair prices win loyal customers.", "उचित कीमतें वफादार ग्राहक जीतती हैं।"),
            ]},
            {"title": "Negotiation", "desc": "Negotiate business deals", "topic": "Negotiation", "sentences": [
                ("Let us discuss the terms of the deal.", "चलो सौदे की शर्तों पर चर्चा करते हैं।"),
                ("We can offer a ten percent discount.", "हम दस प्रतिशत की छूट दे सकते हैं।"),
                ("Can you reduce the price a little?", "क्या आप कीमत थोड़ी कम कर सकते हैं?"),
                ("I am open to a better offer.", "मैं एक बेहतर प्रस्ताव के लिए तैयार हूँ।"),
                ("Let us find a middle ground.", "चलो एक मध्यम रास्ता निकालते हैं।"),
                ("We cannot go below this price.", "हम इस कीमत से नीचे नहीं जा सकते।"),
                ("I will consult my partner and get back.", "मैं अपने साझेदार से पूछकर बताऊँगा।"),
                ("Is there any flexibility on the terms?", "क्या शर्तों में कोई लचीलापन है?"),
                ("Let me think about your offer.", "मुझे आपके प्रस्ताव के बारे में सोचने दें।"),
                ("We want a win-win situation.", "हम एक जीत-जीत की स्थिति चाहते हैं।"),
                ("The price is already very low.", "कीमत पहले से ही बहुत कम है।"),
                ("If you order more, we can reduce the price.", "अगर आप ज्यादा ऑर्डर करते हैं, तो हम कीमत कम कर सकते हैं।"),
                ("We can include free delivery in the deal.", "हम सौदे में मुफ्त डिलीवरी शामिल कर सकते हैं।"),
                ("Negotiation is about both parties being happy.", "बातचीत दोनों पक्षों के खुश होने के बारे में है।"),
                ("I am confident we can reach an agreement.", "मुझे विश्वास है हम एक समझौते पर पहुँच सकते हैं।"),
                ("Let us put the agreement in writing.", "चलो समझौते को लिखित रूप में रखते हैं।"),
                ("The final price is fixed.", "अंतिम कीमत तय है।"),
                ("We agreed on the terms finally.", "हम अंततः शर्तों पर सहमत हुए।"),
                ("Patience is important in negotiation.", "बातचीत में धैर्य महत्वपूर्ण है।"),
                ("Listen carefully during negotiation.", "बातचीत के दौरान ध्यान से सुनिए।"),
                ("Be firm but polite.", "दृढ़ रहिए लेकिन विनम्र।"),
                ("Never agree to unfair terms.", "अनुचित शर्तों से कभी सहमत न हों।"),
                ("A good deal benefits both sides.", "एक अच्छा सौदा दोनों पक्षों को लाभ देता है।"),
                ("We closed the deal successfully.", "हमने सौदा सफलतापूर्वक पूरा किया।"),
                ("Business is about building relationships.", "व्यवसाय संबंध बनाने के बारे में है।"),
            ]},
            {"title": "Supplier Communication", "desc": "Talk with suppliers", "topic": "Suppliers", "sentences": [
                ("We need the delivery by next week.", "हमें अगले हफ्ते तक डिलीवरी चाहिए।"),
                ("What is your best price for this order?", "इस ऑर्डर के लिए आपकी सबसे अच्छी कीमत क्या है?"),
                ("The quality of your last batch was good.", "आपके पिछले बैच की गुणवत्ता अच्छी थी।"),
                ("Can you supply 500 units this month?", "क्या आप इस महीने 500 यूनिट की आपूर्ति कर सकते हैं?"),
                ("We will place the order tomorrow.", "हम कल ऑर्डर देंगे।"),
                ("Please confirm the delivery date.", "कृपया डिलीवरी की तारीख की पुष्टि करें।"),
                ("The raw material prices have increased.", "कच्चे माल की कीमतें बढ़ गई हैं।"),
                ("We have been working with this supplier for years.", "हम वर्षों से इस आपूर्तिकर्ता के साथ काम कर रहे हैं।"),
                ("Please send the updated price list.", "कृपया अद्यतन मूल्य सूची भेजें।"),
                ("The shipment was delayed again.", "शिपमेंट फिर से विलंबित हुआ।"),
                ("We expect better quality control.", "हम बेहतर गुणवत्ता नियंत्रण की उम्मीद करते हैं।"),
                ("Let us renew our supply contract.", "चलो अपने आपूर्ति अनुबंध का नवीनीकरण करते हैं।"),
                ("The supplier assured timely delivery.", "आपूर्तिकर्ता ने समय पर डिलीवरी का आश्वासन दिया।"),
                ("We need the goods urgently.", "हमें सामान तुरंत चाहिए।"),
                ("Please pack the order carefully.", "कृपया ऑर्डर को सावधानी से पैक करें।"),
                ("The invoice does not match the order.", "इनवॉइस ऑर्डर से मेल नहीं खाता।"),
                ("We will pay after receiving the goods.", "हम सामान मिलने के बाद भुगतान करेंगे।"),
                ("A reliable supplier is a business asset.", "विश्वसनीय आपूर्तिकर्ता व्यवसाय की संपत्ति होता है।"),
                ("Good relations with suppliers matter.", "आपूर्तिकर्ताओं के साथ अच्छे संबंध महत्वपूर्ण हैं।"),
                ("We negotiate prices with suppliers regularly.", "हम आपूर्तिकर्ताओं के साथ नियमित रूप से कीमतों पर बातचीत करते हैं।"),
                ("The supplier quality is consistent.", "आपूर्तिकर्ता की गुणवत्ता सुसंगत है।"),
                ("We are looking for new suppliers.", "हम नए आपूर्तिकर्ताओं की तलाश कर रहे हैं।"),
                ("Please provide the samples first.", "कृपया पहले नमूने प्रदान करें।"),
                ("Trust is key in supplier relationships.", "आपूर्तिकर्ता संबंधों में विश्वास महत्वपूर्ण है।"),
                ("We value our long-term suppliers.", "हम अपने दीर्घकालिक आपूर्तिकर्ताओं को महत्व देते हैं।"),
            ]},
            {"title": "Business Calls", "desc": "Handle business phone calls", "topic": "Business Calls", "sentences": [
                ("Good morning. Thank you for calling our company.", "सुप्रभात। हमारी कंपनी को कॉल करने के लिए धन्यवाद।"),
                ("How may I assist you today?", "मैं आज आपकी कैसे सहायता कर सकता हूँ?"),
                ("I am calling regarding our order.", "मैं हमारे ऑर्डर के संबंध में कॉल कर रहा हूँ।"),
                ("Please connect me to the sales department.", "कृपया मुझे बिक्री विभाग से जोड़ें।"),
                ("Could you please hold for a moment?", "क्या आप कृपया एक पल प्रतीक्षा कर सकते हैं?"),
                ("I will transfer your call to the manager.", "मैं आपका कॉल प्रबंधक को ट्रांसफर करूँगा।"),
                ("Can I take a message for him?", "क्या मैं उनके लिए एक संदेश ले सकता हूँ?"),
                ("Please call back after 2 PM.", "कृपया दोपहर 2 बजे के बाद वापस कॉल करें।"),
                ("The line is busy right now.", "लाइन अभी व्यस्त है।"),
                ("I will return your call shortly.", "मैं जल्द ही आपका कॉल वापस करूँगा।"),
                ("Thank you for your patience.", "आपके धैर्य के लिए धन्यवाद।"),
                ("We received your inquiry.", "हमें आपकी पूछताछ प्राप्त हुई।"),
                ("I will email you the details.", "मैं आपको विवरण ईमेल कर दूँगा।"),
                ("Could you speak a little slowly, please?", "क्या आप कृपया थोड़ा धीरे बोल सकते हैं?"),
                ("Let me confirm your order details.", "मुझे आपके ऑर्डर के विवरण की पुष्टि करने दें।"),
                ("Our office hours are 9 to 6.", "हमारे कार्यालय के घंटे 9 से 6 हैं।"),
                ("Please note down our reference number.", "कृपया हमारा संदर्भ नंबर नोट करें।"),
                ("I am glad I could help you.", "मुझे खुशी है कि मैं आपकी मदद कर सका।"),
                ("Have a great day. Goodbye!", "आपका दिन शुभ हो। नमस्ते!"),
                ("A professional call creates a good impression.", "पेशेवर कॉल एक अच्छी छाप बनाता है।"),
                ("Answer calls with a smile in your voice.", "अपनी आवाज़ में मुस्कान के साथ कॉल का उत्तर दीजिए।"),
                ("Business calls should be short and clear.", "व्यावसायिक कॉल छोटे और स्पष्ट होने चाहिए।"),
                ("Take notes during important calls.", "महत्वपूर्ण कॉल के दौरान नोट्स लीजिए।"),
                ("Confirm everything discussed on the call.", "कॉल पर चर्चा की गई हर बात की पुष्टि कीजिए।"),
                ("Good phone manners bring business.", "अच्छे फोन शिष्टाचार व्यवसाय लाते हैं।"),
            ]},
            {"title": "Complaints Handling", "desc": "Handle customer complaints", "topic": "Complaints", "sentences": [
                ("I am sorry for the trouble caused.", "हुई परेशानी के लिए मुझे खेद है।"),
                ("We will look into this complaint immediately.", "हम इस शिकायत को तुरंत देखेंगे।"),
                ("I understand your frustration.", "मैं आपकी निराशा समझता हूँ।"),
                ("The issue will be resolved within 24 hours.", "समस्या 24 घंटे के भीतर हल हो जाएगी।"),
                ("We apologize for the inconvenience.", "असुविधा के लिए हम क्षमा चाहते हैं।"),
                ("Please share the details of the problem.", "कृपया समस्या का विवरण साझा करें।"),
                ("We will replace the product for free.", "हम उत्पाद को मुफ्त में बदल देंगे।"),
                ("Your complaint has been registered.", "आपकी शिकायत दर्ज कर ली गई है।"),
                ("We will compensate for the loss.", "हम नुकसान की भरपाई करेंगे।"),
                ("Thank you for reporting this issue.", "यह समस्या बताने के लिए धन्यवाद।"),
                ("The refund will be processed soon.", "रिफंड जल्द ही संसाधित किया जाएगा।"),
                ("We value your feedback.", "हम आपकी प्रतिक्रिया को महत्व देते हैं।"),
                ("This will not happen again.", "ऐसा दोबारा नहीं होगा।"),
                ("Our team is working on the solution.", "हमारी टीम समाधान पर काम कर रही है।"),
                ("I will personally handle your case.", "मैं व्यक्तिगत रूप से आपका मामला संभालूँगा।"),
                ("Please give us a chance to fix it.", "कृपया हमें इसे ठीक करने का मौका दीजिए।"),
                ("The complaint has been resolved to your satisfaction?", "क्या शिकायत आपकी संतुष्टि के अनुसार हल हो गई?"),
                ("Customer complaints teach us to improve.", "ग्राहक शिकायतें हमें सुधारना सिखाती हैं।"),
                ("Handle complaints with patience.", "शिकायतों को धैर्य से संभालिए।"),
                ("A solved complaint wins loyalty.", "हल की गई शिकायत वफादारी जीतती है।"),
                ("We take every complaint seriously.", "हम हर शिकायत को गंभीरता से लेते हैं।"),
                ("Your satisfaction is our goal.", "आपकी संतुष्टि हमारा लक्ष्य है।"),
                ("We learned from this mistake.", "हमने इस गलती से सीखा।"),
                ("The customer is always listened to.", "ग्राहक की बात हमेशा सुनी जाती है।"),
                ("Trust is rebuilt with good service.", "अच्छी सेवा से विश्वास फिर से बनता है।"),
            ]},
            {"title": "Closing Deals", "desc": "Close business deals", "topic": "Closing Deals", "sentences": [
                ("Shall we finalize the deal today?", "क्या हम आज सौदा अंतिम रूप दे सकते हैं?"),
                ("I am ready to sign the agreement.", "मैं समझौते पर हस्ताक्षर करने के लिए तैयार हूँ।"),
                ("Let us confirm the final terms.", "चलो अंतिम शर्तों की पुष्टि करते हैं।"),
                ("The deal is almost complete.", "सौदा लगभग पूरा हो गया है।"),
                ("We have agreed on all the points.", "हम सभी बिंदुओं पर सहमत हो गए हैं।"),
                ("Congratulations on the new deal!", "नए सौदे पर बधाई!"),
                ("This partnership will benefit both of us.", "यह साझेदारी हम दोनों को लाभ देगी।"),
                ("We look forward to working together.", "हम साथ काम करने के लिए उत्सुक हैं।"),
                ("The contract has been signed.", "अनुबंध पर हस्ताक्षर हो गया है।"),
                ("Payment terms are finalized.", "भुगतान की शर्तें अंतिम हो गई हैं।"),
                ("Let us celebrate this success.", "चलो इस सफलता का जश्न मनाते हैं।"),
                ("The first order will be placed next week.", "पहला ऑर्डर अगले हफ्ते दिया जाएगा।"),
                ("We are excited about this partnership.", "हम इस साझेदारी को लेकर उत्साहित हैं।"),
                ("Both parties are satisfied with the deal.", "दोनों पक्ष सौदे से संतुष्ट हैं।"),
                ("The agreement is for one year.", "समझौता एक साल के लिए है।"),
                ("We will deliver as per the contract.", "हम अनुबंध के अनुसार डिलीवरी करेंगे।"),
                ("A successful deal builds confidence.", "सफल सौदा आत्मविश्वास बनाता है।"),
                ("Trust is the basis of every deal.", "विश्वास हर सौदे का आधार है।"),
                ("We sealed the deal with a handshake.", "हमने हाथ मिलाकर सौदा पक्का किया।"),
                ("Business grows through successful deals.", "सफल सौदों से व्यवसाय बढ़ता है।"),
                ("Keep your promises after the deal.", "सौदे के बाद अपने वादे निभाइए।"),
                ("The deal includes after-sales support.", "सौदे में बिक्री के बाद का समर्थन शामिल है।"),
                ("We will start the work immediately.", "हम तुरंत काम शुरू कर देंगे।"),
                ("Thank you for trusting our company.", "हमारी कंपनी पर भरोसा करने के लिए धन्यवाद।"),
                ("This is the beginning of a great journey.", "यह एक शानदार यात्रा की शुरुआत है।"),
            ]},
            {"title": "After-Sales Service", "desc": "Provide after-sales service", "topic": "After-Sales", "sentences": [
                ("Our after-sales service is the best.", "हमारी बिक्री के बाद की सेवा सबसे अच्छी है।"),
                ("Please contact us for any product issues.", "किसी भी उत्पाद समस्या के लिए कृपया हमसे संपर्क करें।"),
                ("The warranty covers this repair.", "वारंटी इस मरम्मत को कवर करती है।"),
                ("Our support team is available 24/7.", "हमारी सहायता टीम 24/7 उपलब्ध है।"),
                ("We provide free servicing for one year.", "हम एक साल के लिए मुफ्त सर्विसिंग प्रदान करते हैं।"),
                ("Your product will be repaired within a week.", "आपका उत्पाद एक सप्ताह के भीतर ठीक कर दिया जाएगा।"),
                ("We offer installation support too.", "हम स्थापना सहायता भी प्रदान करते हैं।"),
                ("Please keep your invoice for service.", "सेवा के लिए कृपया अपना इनवॉइस रखें।"),
                ("The technician will visit your place.", "तकनीशियन आपके घर आएगा।"),
                ("Your feedback helps our service improve.", "आपकी प्रतिक्रिया हमारी सेवा को बेहतर बनाती है।"),
                ("We follow up with customers after delivery.", "हम डिलीवरी के बाद ग्राहकों से अनुवर्ती करते हैं।"),
                ("The replacement part has arrived.", "प्रतिस्थापन हिस्सा आ गया है।"),
                ("We take product safety seriously.", "हम उत्पाद सुरक्षा को गंभीरता से लेते हैं।"),
                ("Our service team is very professional.", "हमारी सेवा टीम बहुत पेशेवर है।"),
                ("After-sales service builds long-term trust.", "बिक्री के बाद की सेवा दीर्घकालिक विश्वास बनाती है।"),
                ("A good product needs good support.", "अच्छे उत्पाद को अच्छे समर्थन की आवश्यकता होती है।"),
                ("We stand behind our products.", "हम अपने उत्पादों के साथ खड़े रहते हैं।"),
                ("Customer care is our pride.", "ग्राहक देखभाल हमारा गौरव है।"),
                ("We resolve issues quickly.", "हम समस्याओं को जल्दी हल करते हैं।"),
                ("The service call was very helpful.", "सेवा कॉल बहुत सहायक थी।"),
                ("We offer exchange within 7 days.", "हम 7 दिनों के भीतर एक्सचेंज देते हैं।"),
                ("Your satisfaction matters after the sale too.", "बिक्री के बाद भी आपकी संतुष्टि मायने रखती है।"),
                ("We keep spare parts available.", "हम अतिरिक्त हिस्से उपलब्ध रखते हैं।"),
                ("Reliable service brings repeat customers.", "विश्वसनीय सेवा बार-बार ग्राहक लाती है।"),
                ("We are just a call away for support.", "सहायता के लिए हम सिर्फ एक कॉल दूर हैं।"),
                ("The business meeting is scheduled for 11 AM.", "व्यावसायिक बैठक सुबह 11 बजे के लिए निर्धारित है।"),
                ("We will discuss the annual targets.", "हम वार्षिक लक्ष्यों पर चर्चा करेंगे।"),
                ("Let me present the sales figures.", "मुझे बिक्री के आँकड़े प्रस्तुत करने दें।"),
                ("The profits have increased this quarter.", "इस तिमाही में लाभ बढ़ा है।"),
                ("We need to cut down expenses.", "हमें खर्चों में कटौती करनी है।"),
                ("Let us review the business plan.", "चलो व्यवसाय योजना की समीक्षा करते हैं।"),
                ("The market trends look positive.", "बाजार के रुझान सकारात्मक दिख रहे हैं।"),
                ("We should expand our product line.", "हमें अपनी उत्पाद श्रृंखला का विस्तार करना चाहिए।"),
                ("The meeting agenda has been shared.", "बैठक का एजेंडा साझा कर दिया गया है।"),
                ("All partners attended the meeting.", "सभी साझेदारों ने बैठक में भाग लिया।"),
                ("We agreed on the marketing strategy.", "हम विपणन रणनीति पर सहमत हुए।"),
                ("The new project needs more investment.", "नई परियोजना को अधिक निवेश की आवश्यकता है।"),
                ("Let us set realistic targets.", "चलो यथार्थवादी लक्ष्य निर्धारित करते हैं।"),
                ("The meeting was very productive.", "बैठक बहुत उत्पादक रही।"),
                ("We will meet again next month.", "हम अगले महीने फिर मिलेंगे।"),
                ("Business decisions need careful thought.", "व्यावसायिक निर्णयों में सावधानीपूर्वक विचार चाहिए।"),
                ("Numbers guide our business decisions.", "आँकड़े हमारे व्यावसायिक निर्णयों का मार्गदर्शन करते हैं।"),
                ("A good meeting saves time.", "अच्छी बैठक समय बचाती है।"),
                ("Everyone's opinion matters in the meeting.", "बैठक में हर किसी की राय मायने रखती है।"),
                ("We documented all the decisions.", "हमने सभी निर्णयों का दस्तावेजीकरण किया।"),
                ("Growth requires smart planning.", "विकास के लिए समझदारी भरी योजना चाहिए।"),
                ("We monitor our progress monthly.", "हम अपनी प्रगति पर मासिक नज़र रखते हैं।"),
                ("Teamwork drives business success.", "टीमवर्क व्यवसाय की सफलता को चलाता है।"),
                ("The meeting ended with clear action items.", "बैठक स्पष्ट कार्रवाई बिंदुओं के साथ समाप्त हुई।"),
                ("Consistent reviews keep business on track.", "नियमित समीक्षाएँ व्यवसाय को सही रास्ते पर रखती हैं।"),
            ]},
            {"title": "Marketing & Offers", "desc": "Talk about marketing", "topic": "Marketing", "sentences": [
                ("We are running a new marketing campaign.", "हम एक नया विपणन अभियान चला रहे हैं।"),
                ("Our advertisement reached many people.", "हमारा विज्ञापन कई लोगों तक पहुँचा।"),
                ("The sale starts this Friday.", "सेल इस शुक्रवार से शुरू होती है।"),
                ("We are offering a buy-one-get-one deal.", "हम एक खरीदो एक मुफ्त पाओ का ऑफर दे रहे हैं।"),
                ("Social media helps our business grow.", "सोशल मीडिया हमारे व्यवसाय को बढ़ने में मदद करता है।"),
                ("Our website gets many visitors.", "हमारी वेबसाइट पर कई आगंतुक आते हैं।"),
                ("We launched a new product line.", "हमने एक नई उत्पाद श्रृंखला लॉन्च की।"),
                ("The promotional video went viral.", "प्रचार वीडियो वायरल हो गया।"),
                ("We give special offers to loyal customers.", "हम वफादार ग्राहकों को विशेष ऑफर देते हैं।"),
                ("Marketing builds brand awareness.", "विपणन ब्रांड जागरूकता बनाता है।"),
                ("The customers liked our new packaging.", "ग्राहकों को हमारी नई पैकेजिंग पसंद आई।"),
                ("We will advertise in local newspapers.", "हम स्थानीय समाचार पत्रों में विज्ञापन देंगे।"),
                ("The response to our offer was amazing.", "हमारे ऑफर की प्रतिक्रिया अद्भुत रही।"),
                ("We organized a customer appreciation event.", "हमने ग्राहक सम्मान कार्यक्रम आयोजित किया।"),
                ("Good marketing tells a true story.", "अच्छा विपणन एक सच्ची कहानी बताता है।"),
                ("We study customer preferences.", "हम ग्राहकों की पसंद का अध्ययन करते हैं।"),
                ("The seasonal sale attracts many customers.", "मौसमी बिक्री कई ग्राहकों को आकर्षित करती है।"),
                ("Our brand message is clear.", "हमारा ब्रांड संदेश स्पष्ट है।"),
                ("Online advertising is cost-effective.", "ऑनलाइन विज्ञापन लागत प्रभावी है।"),
                ("We update our catalogue regularly.", "हम अपनी सूची नियमित रूप से अपडेट करते हैं।"),
                ("Customer word-of-mouth is powerful.", "ग्राहक की मौखिक सिफारिश शक्तिशाली है।"),
                ("Marketing requires creativity.", "विपणन के लिए रचनात्मकता की आवश्यकता होती है।"),
                ("We tracked the campaign results.", "हमने अभियान के परिणामों को ट्रैक किया।"),
                ("The offer ends this Sunday.", "ऑफर इस रविवार को समाप्त होता है।"),
                ("A strong brand sells itself.", "मजबूत ब्रांड खुद बिकता है।"),
            ]},
            {"title": "Online Business", "desc": "Run an online business", "topic": "Online Business", "sentences": [
                ("I sell my products online.", "मैं अपने उत्पाद ऑनलाइन बेचता हूँ।"),
                ("Our online store is doing well.", "हमारा ऑनलाइन स्टोर अच्छा चल रहा है।"),
                ("We receive orders from all over India.", "हमें पूरे भारत से ऑर्डर मिलते हैं।"),
                ("The website payment system is secure.", "वेबसाइट की भुगतान प्रणाली सुरक्षित है।"),
                ("I manage our social media pages.", "मैं हमारे सोशल मीडिया पेजों का प्रबंधन करता हूँ।"),
                ("Online business is growing fast.", "ऑनलाइन व्यवसाय तेजी से बढ़ रहा है।"),
                ("We deliver products across the country.", "हम देश भर में उत्पाद पहुँचाते हैं।"),
                ("The app makes ordering easy.", "ऐप ऑर्डर करना आसान बनाता है।"),
                ("Our online reviews are very good.", "हमारी ऑनलाइन समीक्षाएँ बहुत अच्छी हैं।"),
                ("I handle the digital payments.", "मैं डिजिटल भुगतान संभालता हूँ।"),
                ("The delivery partner is reliable.", "डिलीवरी पार्टनर विश्वसनीय है।"),
                ("We ship orders within 48 hours.", "हम 48 घंटों के भीतर ऑर्डर भेजते हैं।"),
                ("Online selling saves shop rent.", "ऑनलाइन बिक्री दुकान का किराया बचाती है।"),
                ("We use WhatsApp for customer support.", "हम ग्राहक सहायता के लिए व्हाट्सएप का उपयोग करते हैं।"),
                ("The e-commerce platform charges a fee.", "ई-कॉमर्स प्लेटफॉर्म शुल्क लेता है।"),
                ("Our product photos attract customers.", "हमारे उत्पाद फोटो ग्राहकों को आकर्षित करते हैं।"),
                ("We keep updating our online catalogue.", "हम अपनी ऑनलाइन सूची अपडेट करते रहते हैं।"),
                ("Digital marketing boosts online sales.", "डिजिटल मार्केटिंग ऑनलाइन बिक्री बढ़ाती है।"),
                ("The online store never closes.", "ऑनलाइन स्टोर कभी बंद नहीं होता।"),
                ("We respond to customer messages quickly.", "हम ग्राहक संदेशों का जल्दी जवाब देते हैं।"),
                ("Online business needs a good website.", "ऑनलाइन व्यवसाय के लिए एक अच्छी वेबसाइट चाहिए।"),
                ("We offer free shipping above 999 rupees.", "हम 999 रुपये से ऊपर मुफ्त शिपिंग देते हैं।"),
                ("Our customers shop from anywhere.", "हमारे ग्राहक कहीं से भी खरीदारी करते हैं।"),
                ("E-commerce is the future of business.", "ई-कॉमर्स व्यवसाय का भविष्य है।"),
                ("We are building a strong online brand.", "हम एक मजबूत ऑनलाइन ब्रांड बना रहे हैं।"),
            ]},
            {"title": "Business English Words", "desc": "Learn business vocabulary", "topic": "Vocabulary", "sentences": [
                ("We need to increase our revenue.", "हमें अपने राजस्व में वृद्धि करनी है।"),
                ("The profit margin is good.", "लाभ मार्जिन अच्छा है।"),
                ("We manage our inventory carefully.", "हम अपने इन्वेंटरी का ध्यानपूर्वक प्रबंधन करते हैं।"),
                ("The turnover increased this year.", "इस साल कारोबार बढ़ा।"),
                ("We have a strong balance sheet.", "हमारी बैलेंस शीट मजबूत है।"),
                ("The investment will give good returns.", "निवेश अच्छा रिटर्न देगा।"),
                ("We maintain quality standards.", "हम गुणवत्ता मानकों को बनाए रखते हैं।"),
                ("The demand is higher than supply.", "माँग आपूर्ति से अधिक है।"),
                ("Our market share is growing.", "हमारा बाजार हिस्सा बढ़ रहा है।"),
                ("We analyze the competition regularly.", "हम नियमित रूप से प्रतिस्पर्धा का विश्लेषण करते हैं।"),
                ("The company's assets are valuable.", "कंपनी की संपत्तियाँ मूल्यवान हैं।"),
                ("We track our expenses monthly.", "हम अपने खर्चों का मासिक ट्रैक रखते हैं।"),
                ("The shipment will arrive on time.", "शिपमेंट समय पर पहुँचेगा।"),
                ("We need a better supply chain.", "हमें एक बेहतर आपूर्ति श्रृंखला चाहिए।"),
                ("The brand value has increased.", "ब्रांड मूल्य बढ़ गया है।"),
                ("Our customer base is expanding.", "हमारा ग्राहक आधार बढ़ रहा है।"),
                ("We offer competitive rates.", "हम प्रतिस्पर्धी दरें देते हैं।"),
                ("The annual report is ready.", "वार्षिक रिपोर्ट तैयार है।"),
                ("We signed a new partnership.", "हमने एक नई साझेदारी पर हस्ताक्षर किए।"),
                ("The business model is sustainable.", "व्यवसाय मॉडल टिकाऊ है।"),
                ("Business vocabulary shows professionalism.", "व्यवसाय शब्दावली पेशेवरता दर्शाती है।"),
                ("Learn the language of business.", "व्यवसाय की भाषा सीखिए।"),
                ("Clear terms avoid confusion.", "स्पष्ट शर्तें भ्रम से बचाती हैं।"),
                ("Financial terms are important in business.", "व्यवसाय में वित्तीय शर्तें महत्वपूर्ण हैं।"),
                ("Good English opens business doors.", "अच्छी अंग्रेज़ी व्यवसाय के दरवाज़े खोलती है।"),
            ]},
            {"title": "Business Small Talk", "desc": "Chat with business partners", "topic": "Small Talk", "sentences": [
                ("How is your business doing these days?", "आपका व्यवसाय इन दिनों कैसा चल रहा है?"),
                ("Business is going well, thank you.", "व्यवसाय अच्छा चल रहा है, धन्यवाद।"),
                ("The market is changing fast.", "बाजार तेजी से बदल रहा है।"),
                ("We had a good year this year.", "हमारा इस साल अच्छा रहा।"),
                ("Have you tried our new product?", "क्या आपने हमारा नया उत्पाद आज़माया?"),
                ("Let us discuss the industry trends.", "चलो उद्योग के रुझानों पर चर्चा करते हैं।"),
                ("Your shop looks very nice.", "आपकी दुकान बहुत अच्छी लगती है।"),
                ("I heard you are expanding.", "मैंने सुना आप विस्तार कर रहे हैं।"),
                ("Congratulations on your new branch!", "आपकी नई शाखा पर बधाई!"),
                ("We should cooperate on a project.", "हमें एक परियोजना पर सहयोग करना चाहिए।"),
                ("The business community is helpful.", "व्यवसाय समुदाय सहायक होता है।"),
                ("Let us exchange business cards.", "चलो बिजनेस कार्ड बदलते हैं।"),
                ("I look forward to working with you.", "मैं आपके साथ काम करने के लिए उत्सुक हूँ।"),
                ("Networking is important for business.", "व्यवसाय के लिए नेटवर्किंग महत्वपूर्ण है।"),
                ("We meet at the trade fair every year.", "हम हर साल व्यापार मेले में मिलते हैं।"),
                ("The exhibition was a great success.", "प्रदर्शनी बहुत सफल रही।"),
                ("Many new opportunities are coming.", "कई नए अवसर आ रहे हैं।"),
                ("Your feedback is valuable to us.", "आपकी प्रतिक्रिया हमारे लिए मूल्यवान है।"),
                ("Let us stay in touch about the deal.", "चलो सौदे के बारे में संपर्क में रहते हैं।"),
                ("I appreciate your business advice.", "मैं आपकी व्यावसायिक सलाह की सराहना करता हूँ।"),
                ("Good relationships grow business.", "अच्छे संबंध व्यवसाय बढ़ाते हैं।"),
                ("The trade show is next month.", "व्यापार शो अगले महीने है।"),
                ("We are members of the local chamber.", "हम स्थानीय चैंबर के सदस्य हैं।"),
                ("Business runs on trust and contacts.", "व्यवसाय विश्वास और संपर्कों पर चलता है।"),
                ("It is always nice talking business with you.", "आपके साथ व्यवसाय पर बात करना हमेशा अच्छा लगता है।"),
            ]},
            {"title": "Business Problems", "desc": "Solve business problems", "topic": "Business Problems", "sentences": [
                ("We are facing a cash flow problem.", "हमें नकदी प्रवाह की समस्या का सामना करना पड़ रहा है।"),
                ("The sales have dropped this month.", "इस महीने बिक्री गिर गई है।"),
                ("We need to solve this issue quickly.", "हमें इस समस्या को जल्दी हल करना है।"),
                ("The supplier increased the prices.", "आपूर्तिकर्ता ने कीमतें बढ़ा दीं।"),
                ("Our storage space is not enough.", "हमारी भंडारण जगह पर्याप्त नहीं है।"),
                ("We lost a big client.", "हमने एक बड़ा ग्राहक खो दिया।"),
                ("The competition is getting tough.", "प्रतिस्पर्धा कठिन होती जा रही है।"),
                ("We need a new business strategy.", "हमें एक नई व्यवसाय रणनीति चाहिए।"),
                ("The rent has increased.", "किराया बढ़ गया है।"),
                ("We must reduce our costs.", "हमें अपनी लागत कम करनी होगी।"),
                ("The delivery was delayed again.", "डिलीवरी फिर से देर से हुई।"),
                ("We need more working capital.", "हमें अधिक कार्यशील पूंजी चाहिए।"),
                ("The employee left the company.", "कर्मचारी ने कंपनी छोड़ दी।"),
                ("We will overcome this challenge.", "हम इस चुनौती को पार कर लेंगे।"),
                ("Every business faces ups and downs.", "हर व्यवसाय में उतार-चढ़ाव आते हैं।"),
                ("We learned from this setback.", "हमने इस असफलता से सीखा।"),
                ("A problem-solving mindset is essential.", "समस्या-समाधान की मानसिकता आवश्यक है।"),
                ("We discussed solutions with the team.", "हमने टीम के साथ समाधानों पर चर्चा की।"),
                ("The situation is improving now.", "स्थिति अब सुधर रही है।"),
                ("We diversified our products.", "हमने अपने उत्पादों में विविधता लाई।"),
                ("Stay positive during tough times.", "कठिन समय में सकारात्मक रहिए।"),
                ("Adapting to change is important.", "बदलाव के अनुकूल होना महत्वपूर्ण है।"),
                ("We are rebuilding our customer trust.", "हम अपना ग्राहक विश्वास फिर से बना रहे हैं।"),
                ("Hard times make businesses stronger.", "कठिन समय व्यवसायों को मजबूत बनाते हैं।"),
                ("We will rise again with better plans.", "हम बेहतर योजनाओं के साथ फिर उठेंगे।"),
            ]},
        ],
    }
