# Beginner English - 28 lessons x 25 sentences = 700 sentences

def get_beginner_banks():
    return {
        "course_id": "beginner",
        "title": "Beginner English",
        "desc": "Start from zero and build a strong foundation in spoken English. Real-life sentences for daily conversations.",
        "short": "Start from zero and build confidence",
        "icon": "🟢",
        "color": "brand",
        "difficulty": "Beginner",
        "audience": ["Absolute Beginners", "School Students", "Kids"],
        "price": "₹199",
        "lessons": [
            {"title": "Greetings", "desc": "Learn to greet people in English", "topic": "Greetings", "sentences": [
                ("Hello! How are you?", "नमस्ते! आप कैसे हैं?"),
                ("Good morning. I hope you are well.", "सुप्रभात। उम्मीद है आप ठीक हैं।"),
                ("Good afternoon. Nice to meet you.", "नमस्कार। आपसे मिलकर अच्छा लगा।"),
                ("Good evening. How was your day?", "शुभ संध्या। आपका दिन कैसा रहा?"),
                ("How is everything going?", "आपके सब कैसे चल रहा है?"),
                ("I am fine, thank you. And you?", "मैं ठीक हूँ, धन्यवाद। और आप?"),
                ("Long time no see! How have you been?", "बहुत दिनों बाद मिले! आप कैसे हैं?"),
                ("I have been busy with work these days.", "इन दिनों मैं काम में व्यस्त हूँ।"),
                ("Nice to see you again.", "आपको फिर से देखकर अच्छा लगा।"),
                ("I am happy to be here today.", "मुझे आज यहाँ आकर खुशी है।"),
                ("Thank you for having me.", "मुझे बुलाने के लिए धन्यवाद।"),
                ("Have a wonderful day ahead!", "आपका दिन शुभ हो!"),
                ("Take care of yourself.", "अपना ख्याल रखिए।"),
                ("See you tomorrow!", "कल मिलते हैं!"),
                ("See you soon. Bye for now!", "जल्द मिलते हैं। अभी के लिए अलविदा!"),
                ("It was nice talking to you.", "आपसे बात करके अच्छा लगा।"),
                ("Please come in and sit down.", "कृपया अंदर आइए और बैठिए।"),
                ("How is your family doing?", "आपका परिवार कैसा है?"),
                ("Everyone is fine at home.", "घर पर सब ठीक हैं।"),
                ("What a pleasant surprise!", "कितनी अच्छी खुशी की बात है!"),
                ("I did not expect to see you here.", "मुझे आपको यहाँ देखने की उम्मीद नहीं थी।"),
                ("Please sit wherever you like.", "कृपया जहाँ चाहें बैठिए।"),
                ("I hope you are having a good time.", "मुझे उम्मीद है आपको अच्छा लग रहा है।"),
                ("Greetings from my whole family.", "मेरे पूरे परिवार की तरफ से नमस्कार।"),
                ("May I come in?", "क्या मैं अंदर आ सकता हूँ?"),
            ]},
            {"title": "Introduction", "desc": "Introduce yourself and ask about others", "topic": "Introduction", "sentences": [
                ("Hi, I am Rahul. What is your name?", "नमस्ते, मैं राहुल हूँ। आपका नाम क्या है?"),
                ("My name is Anjali. Nice to meet you.", "मेरा नाम अंजलि है। आपसे मिलकर खुशी हुई।"),
                ("I am from Mumbai. Where are you from?", "मैं मुंबई से हूँ। आप कहाँ से हैं?"),
                ("I live in Delhi with my family.", "मैं अपने परिवार के साथ दिल्ली में रहता हूँ।"),
                ("I work as a teacher. What do you do?", "मैं एक शिक्षक हूँ। आप क्या करते हैं?"),
                ("I am a student in class 10.", "मैं दसवीं कक्षा में पढ़ता हूँ।"),
                ("Pleased to meet you.", "आपसे मिलकर खुशी हुई।"),
                ("I have heard a lot about you.", "मैंने आपके बारे में बहुत सुना है।"),
                ("Please call me by my first name.", "कृपया मुझे मेरे पहले नाम से बुलाइए।"),
                ("I am sorry, I did not catch your name.", "माफ कीजिए, मुझे आपका नाम समझ नहीं आया।"),
                ("Could you please spell your name?", "क्या आप कृपया अपना नाम बता सकते हैं?"),
                ("Let me introduce you to my friend.", "मैं आपको अपने दोस्त से मिलवाता हूँ।"),
                ("This is my colleague, Mr. Sharma.", "यह मेरे सहकर्मी, श्री शर्मा हैं।"),
                ("We work together at the same company.", "हम एक ही कंपनी में साथ काम करते हैं।"),
                ("What is your profession?", "आपका पेशा क्या है?"),
                ("I am a businessman.", "मैं एक व्यवसायी हूँ।"),
                ("How do you spend your free time?", "आप अपना खाली समय कैसे बिताते हैं?"),
                ("I like reading books and listening to music.", "मुझे किताबें पढ़ना और संगीत सुनना पसंद है।"),
                ("Where do you work?", "आप कहाँ काम करते हैं?"),
                ("I work in a bank.", "मैं एक बैंक में काम करता हूँ।"),
                ("How many years of experience do you have?", "आपके पास कितने साल का अनुभव है?"),
                ("I have five years of experience.", "मेरे पास पाँच साल का अनुभव है।"),
                ("It is my first visit to this city.", "इस शहर की यह मेरी पहली यात्रा है।"),
                ("I hope we can be good friends.", "मुझे उम्मीद है हम अच्छे दोस्त बन सकते हैं।"),
                ("Welcome to our company!", "हमारी कंपनी में आपका स्वागत है!"),
            ]},
            {"title": "Family", "desc": "Talk about your family in English", "topic": "Family", "sentences": [
                ("I have two brothers and one sister.", "मेरे दो भाई और एक बहन है।"),
                ("My father is a businessman.", "मेरे पिता व्यवसायी हैं।"),
                ("My mother is a homemaker.", "मेरी माँ गृहिणी हैं।"),
                ("I live with my parents.", "मैं अपने माता-पिता के साथ रहता हूँ।"),
                ("My elder sister is a doctor.", "मेरी बड़ी बहन डॉक्टर है।"),
                ("My younger brother is still in school.", "मेरा छोटा भाई अभी स्कूल में है।"),
                ("My grandparents live in a village.", "मेरे दादा-दादी गाँव में रहते हैं।"),
                ("We visit our grandparents every summer.", "हम हर गर्मी में दादा-दादी से मिलने जाते हैं।"),
                ("My uncle is a police officer.", "मेरे चाचा पुलिस अधिकारी हैं।"),
                ("My aunt is a nurse at a hospital.", "मेरी चाची एक अस्पताल में नर्स हैं।"),
                ("I have a cousin who lives in America.", "मेरा एक चचेरा भाई अमेरिका में रहता है।"),
                ("There are five members in my family.", "मेरे परिवार में पाँच सदस्य हैं।"),
                ("We eat dinner together every night.", "हम हर रात साथ खाना खाते हैं।"),
                ("My mother cooks delicious food.", "मेरी माँ स्वादिष्ट खाना बनाती हैं।"),
                ("I help my father in the garden.", "मैं बगीचे में अपने पिता की मदद करता हूँ।"),
                ("I love spending time with my family.", "मुझे परिवार के साथ समय बिताना पसंद है।"),
                ("My sister and I are very close.", "मैं और मेरी बहन बहुत करीब हैं।"),
                ("We have a pet dog at home.", "हमारे घर पर एक पालतू कुत्ता है।"),
                ("My brother is older than me.", "मेरा भाई मुझसे बड़ा है।"),
                ("My parents are very supportive.", "मेरे माता-पिता बहुत सहयोगी हैं।"),
                ("We celebrate festivals together.", "हम त्योहार साथ मिलकर मनाते हैं।"),
                ("My grandfather tells interesting stories.", "मेरे दादाजी दिलचस्प कहानियाँ सुनाते हैं।"),
                ("I am the youngest in my family.", "मैं अपने परिवार में सबसे छोटा हूँ।"),
                ("Family is the most important thing in life.", "परिवार जीवन में सबसे महत्वपूर्ण चीज़ है।"),
                ("I am lucky to have such a loving family.", "मैं भाग्यशाली हूँ कि मुझे इतना प्यारा परिवार मिला।"),
            ]},
            {"title": "Home", "desc": "Describe your home and rooms", "topic": "Home", "sentences": [
                ("We live in a small apartment.", "हम एक छोटे से अपार्टमेंट में रहते हैं।"),
                ("Our house has three bedrooms.", "हमारे घर में तीन बेडरूम हैं।"),
                ("There is a beautiful garden in front of our house.", "हमारे घर के सामने एक सुंदर बगीचा है।"),
                ("I share a room with my brother.", "मैं अपने भाई के साथ एक कमरा साझा करता हूँ।"),
                ("Our house is near the market.", "हमारा घर बाज़ार के पास है।"),
                ("The kitchen is very big.", "रसोईघर बहुत बड़ा है।"),
                ("We have a balcony facing the park.", "हमारी बालकनी पार्क की तरफ है।"),
                ("I water the plants every morning.", "मैं हर सुबह पौधों को पानी देता हूँ।"),
                ("Please keep the door closed.", "कृपया दरवाज़ा बंद रखिए।"),
                ("The lights are not working.", "लाइटें काम नहीं कर रही हैं।"),
                ("Where is the bathroom?", "बाथरूम कहाँ है?"),
                ("The TV is in the living room.", "टीवी लिविंग रूम में है।"),
                ("Please make yourself at home.", "कृपया आराम से रहिए।"),
                ("We clean the house on Sundays.", "हम रविवार को घर की सफाई करते हैं।"),
                ("The rent is due at the end of the month.", "किराया महीने के अंत में देना है।"),
                ("My room is on the first floor.", "मेरा कमरा पहली मंजिल पर है।"),
                ("There is a park near our building.", "हमारी बिल्डिंग के पास एक पार्क है।"),
                ("The neighbours are very friendly.", "पड़ोसी बहुत मिलनसार हैं।"),
                ("We moved to this house last year.", "हम पिछले साल इस घर में आए थे।"),
                ("The house needs some repairs.", "घर में कुछ मरम्मत की ज़रूरत है।"),
                ("Is the water heater working?", "क्या वाटर हीटर काम कर रहा है?"),
                ("I like my home because it is peaceful.", "मुझे अपना घर पसंद है क्योंकि यह शांत है।"),
                ("The windows face the sunrise.", "खिड़कियाँ सूर्योदय की तरफ हैं।"),
                ("We have a small store room.", "हमारे पास एक छोटा स्टोर रूम है।"),
                ("Home is where the heart is.", "घर वही है जहाँ दिल रहता है।"),
            ]},
            {"title": "Daily Routine", "desc": "Describe your daily routine", "topic": "Daily Routine", "sentences": [
                ("I wake up at 6 AM every day.", "मैं हर दिन 6 बजे उठता हूँ।"),
                ("I brush my teeth and wash my face.", "मैं दाँत साफ करता हूँ और चेहरा धोता हूँ।"),
                ("I take a shower before breakfast.", "मैं नाश्ते से पहले नहाता हूँ।"),
                ("I have breakfast at 7:30.", "मैं 7:30 बजे नाश्ता करता हूँ।"),
                ("I drink a glass of milk every morning.", "मैं हर सुबह एक गिलास दूध पीता हूँ।"),
                ("I leave for work at 9 AM.", "मैं 9 बजे काम के लिए निकलता हूँ।"),
                ("I take the bus to my office.", "मैं अपने ऑफिस के लिए बस लेता हूँ।"),
                ("I reach the office by 10 o'clock.", "मैं 10 बजे तक ऑफिस पहुँचता हूँ।"),
                ("I have lunch at 1 PM.", "मैं दोपहर 1 बजे खाना खाता हूँ।"),
                ("I check my emails after lunch.", "मैं खाने के बाद अपने ईमेल देखता हूँ।"),
                ("I go back home at 6 PM.", "मैं शाम 6 बजे घर वापस जाता हूँ।"),
                ("I watch TV for an hour in the evening.", "मैं शाम को एक घंटा टीवी देखता हूँ।"),
                ("I have dinner with my family at 8 PM.", "मैं 8 बजे परिवार के साथ खाना खाता हूँ।"),
                ("I go to sleep at 10:30 PM.", "मैं रात 10:30 बजे सोता हूँ।"),
                ("I exercise for half an hour every day.", "मैं हर दिन आधा घंटा व्यायाम करता हूँ।"),
                ("I read the newspaper in the morning.", "मैं सुबह अखबार पढ़ता हूँ।"),
                ("I check my phone when I wake up.", "मैं उठते ही अपना फोन देखता हूँ।"),
                ("On Sundays, I sleep until 9 AM.", "रविवार को मैं 9 बजे तक सोता हूँ।"),
                ("I like to keep a daily routine.", "मुझे दैनिक दिनचर्या रखना पसंद है।"),
                ("I am usually very busy in the morning.", "मैं सुबह आमतौर पर बहुत व्यस्त रहता हूँ।"),
                ("I cook dinner on weekends.", "मैं वीकेंड पर रात का खाना बनाता हूँ।"),
                ("I do my homework after school.", "मैं स्कूल के बाद होमवर्क करता हूँ।"),
                ("I walk for twenty minutes every evening.", "मैं हर शाम बीस मिनट पैदल चलता हूँ।"),
                ("My routine changes on holidays.", "छुट्टियों में मेरी दिनचर्या बदल जाती है।"),
                ("I try to sleep early every night.", "मैं हर रात जल्दी सोने की कोशिश करता हूँ।"),
            ]},
            {"title": "Time & Dates", "desc": "Tell time and talk about dates", "topic": "Time", "sentences": [
                ("What time is it now?", "अभी कितने बजे हैं?"),
                ("It is half past seven.", "साढ़े सात बजे हैं।"),
                ("It is quarter to five.", "पाँच बजने में पंद्रह मिनट हैं।"),
                ("The meeting starts at 11 AM sharp.", "मीटिंग ठीक 11 बजे शुरू होती है।"),
                ("I am fifteen minutes late today.", "मुझे आज पंद्रह मिनट देर हो गई।"),
                ("What day is today?", "आज कौन सा दिन है?"),
                ("Today is Monday.", "आज सोमवार है।"),
                ("My birthday is on the 15th of August.", "मेरा जन्मदिन 15 अगस्त को है।"),
                ("What is the date today?", "आज तारीख क्या है?"),
                ("It is the 18th of August.", "आज 18 अगस्त है।"),
                ("The shop opens at 9 AM and closes at 9 PM.", "दुकान सुबह 9 बजे खुलती है और रात 9 बजे बंद होती है।"),
                ("We have a holiday on Sunday.", "रविवार को हमारी छुट्टी है।"),
                ("I will visit you next week.", "मैं अगले हफ्ते आपसे मिलने आऊँगा।"),
                ("The train leaves at 6:45.", "ट्रेन 6:45 बजे निकलती है।"),
                ("Can you please wake me up at 7 AM?", "क्या आप मुझे सुबह 7 बजे जगा सकते हैं?"),
                ("I have a class at 3 in the afternoon.", "मेरी दोपहर 3 बजे क्लास है।"),
                ("The flight arrives at midnight.", "फ्लाइट आधी रात को आती है।"),
                ("Let us meet at 5 o'clock sharp.", "चलिए ठीक 5 बजे मिलते हैं।"),
                ("Which month is your favourite?", "आपका पसंदीदा महीना कौन सा है?"),
                ("December is my favourite month.", "दिसंबर मेरा पसंदीदा महीना है।"),
                ("The store is open from Monday to Saturday.", "दुकान सोमवार से शनिवार तक खुली रहती है।"),
                ("I need to submit the report by Friday.", "मुझे शुक्रवार तक रिपोर्ट जमा करनी है।"),
                ("Time flies when you are busy.", "व्यस्त होने पर समय बहुत तेज़ी से बीतता है।"),
                ("We have been waiting for half an hour.", "हम आधे घंटे से इंतज़ार कर रहे हैं।"),
                ("Please be on time tomorrow.", "कृपया कल समय पर आइए।"),
            ]},
            {"title": "Food & Eating", "desc": "Talk about food and eating out", "topic": "Food", "sentences": [
                ("I am hungry. Let us eat something.", "मुझे भूख लगी है। चलो कुछ खाते हैं।"),
                ("What would you like to eat?", "आप क्या खाना पसंद करेंगे?"),
                ("I would like a cup of tea, please.", "मुझे एक कप चाय चाहिए, कृपया।"),
                ("This food is very tasty.", "यह खाना बहुत स्वादिष्ट है।"),
                ("Could you please pass me the salt?", "क्या आप मुझे नमक दे सकते हैं?"),
                ("I am a vegetarian. I do not eat meat.", "मैं शाकाहारी हूँ। मैं मांस नहीं खाता।"),
                ("I am thirsty. Can I get some water?", "मुझे प्यास लगी है। क्या मुझे पानी मिल सकता है?"),
                ("The breakfast is included in the room price.", "नाश्ता कमरे की कीमत में शामिल है।"),
                ("I would like to order a pizza.", "मैं एक पिज़्ज़ा ऑर्डर करना चाहूँगा।"),
                ("Do you have a menu in English?", "क्या आपके पास अंग्रेज़ी में मेनू है?"),
                ("What do you recommend?", "आप क्या सुझाव देंगे?"),
                ("The food here is really good.", "यहाँ का खाना वाकई अच्छा है।"),
                ("I am full. I cannot eat anymore.", "मैं पेट भर गया हूँ। मैं और नहीं खा सकता।"),
                ("Could I get the bill, please?", "क्या मुझे बिल मिल सकता है, कृपया?"),
                ("I usually eat rice and dal.", "मैं आमतौर पर चावल और दाल खाता हूँ।"),
                ("Let us cook something special today.", "चलो आज कुछ खास बनाते हैं।"),
                ("The vegetables are very fresh.", "सब्ज़ियाँ बहुत ताज़ी हैं।"),
                ("Do you like spicy food?", "क्या आपको तीखा खाना पसंद है?"),
                ("I love Indian food.", "मुझे भारतीय खाना बहुत पसंद है।"),
                ("Breakfast is the most important meal of the day.", "नाश्ता दिन का सबसे महत्वपूर्ण भोजन है।"),
                ("We ordered too much food.", "हमने बहुत ज़्यादा खाना ऑर्डर कर लिया।"),
                ("The mangoes are sweet this season.", "इस मौसम में आम बहुत मीठे हैं।"),
                ("Please give me one more glass of water.", "कृपया मुझे एक और गिलास पानी दीजिए।"),
                ("Eating healthy food keeps you fit.", "स्वस्थ भोजन खाने से आप फिट रहते हैं।"),
                ("Let us go out for dinner tonight.", "चलो आज रात खाना बाहर खाते हैं।"),
            ]},
            {"title": "Shopping", "desc": "Go shopping and buy things", "topic": "Shopping", "sentences": [
                ("How much does this cost?", "इसकी कीमत कितनी है?"),
                ("That is too expensive for me.", "यह मेरे लिए बहुत महँगा है।"),
                ("Is there a discount on this item?", "क्या इस आइटम पर छूट है?"),
                ("I am just looking, thank you.", "मैं बस देख रहा हूँ, धन्यवाद।"),
                ("Do you accept credit cards?", "क्या आप क्रेडिट कार्ड स्वीकार करते हैं?"),
                ("Can I pay with cash?", "क्या मैं नकद भुगतान कर सकता हूँ?"),
                ("I need a kilogram of sugar.", "मुझे एक किलो चीनी चाहिए।"),
                ("Can I get a bag for this?", "क्या मुझे इसके लिए एक बैग मिल सकता है?"),
                ("Where can I find the dairy products?", "मुझे डेयरी प्रोडक्ट कहाँ मिलेंगे?"),
                ("I want to buy some fruits.", "मैं कुछ फल खरीदना चाहता हूँ।"),
                ("The apples look very fresh today.", "सेब आज बहुत ताज़े लग रहे हैं।"),
                ("Could you help me choose a good dress?", "क्या आप मुझे एक अच्छी ड्रेस चुनने में मदद करेंगे?"),
                ("I need a size larger.", "मुझे एक साइज़ बड़ा चाहिए।"),
                ("Can I try this on?", "क्या मैं इसे ट्राई कर सकता हूँ?"),
                ("The fitting room is over there.", "फ़िटिंग रूम वहाँ पर है।"),
                ("I will take this. Please pack it.", "मैं यह लूँगा। कृपया इसे पैक कर दीजिए।"),
                ("Can you give me the bill, please?", "क्या आप मुझे बिल दे सकते हैं, कृपया?"),
                ("Thank you for shopping with us!", "हमसे खरीदारी करने के लिए धन्यवाद!"),
                ("I will come again next week.", "मैं अगले हफ्ते फिर आऊँगा।"),
                ("This shirt is on sale.", "यह शर्ट सेल पर है।"),
                ("Do you have this in blue?", "क्या यह नीले रंग में है?"),
                ("The quality of this product is very good.", "इस प्रोडक्ट की गुणवत्ता बहुत अच्छी है।"),
                ("Where is the nearest shopping mall?", "यहाँ से सबसे नज़दीकी मॉल कहाँ है?"),
                ("I am looking for a gift for my mother.", "मैं अपनी माँ के लिए एक उपहार ढूँढ रहा हूँ।"),
                ("Can you wrap this as a gift?", "क्या आप इसे उपहार की तरह पैक कर सकते हैं?"),
            ]},
            {"title": "Money & Payments", "desc": "Handle money and payments", "topic": "Money", "sentences": [
                ("How much money do I need to pay?", "मुझे कितने पैसे देने होंगे?"),
                ("I need to withdraw some money from the ATM.", "मुझे एटीएम से कुछ पैसे निकालने हैं।"),
                ("Can I transfer money online?", "क्या मैं ऑनलाइन पैसे भेज सकता हूँ?"),
                ("What is the exchange rate for dollars?", "डॉलर की विनिमय दर क्या है?"),
                ("I have only 500 rupees with me.", "मेरे पास केवल 500 रुपये हैं।"),
                ("Keep the change.", "बाकी पैसे रख लीजिए।"),
                ("Can I get a receipt, please?", "क्या मुझे रसीद मिल सकती है, कृपया?"),
                ("Where can I find an ATM?", "मुझे एटीएम कहाँ मिलेगा?"),
                ("My wallet was stolen.", "मेरा बटुआ चोरी हो गया।"),
                ("I need to check my bank balance.", "मुझे अपना बैंक बैलेंस देखना है।"),
                ("The money has been transferred to your account.", "पैसे आपके खाते में ट्रांसफर कर दिए गए हैं।"),
                ("What is the minimum balance required?", "न्यूनतम बैलेंस कितना चाहिए?"),
                ("I paid by UPI.", "मैंने यूपीआई से भुगतान किया।"),
                ("The payment did not go through.", "भुगतान नहीं हो पाया।"),
                ("Please send me the payment details.", "कृपया मुझे भुगतान का विवरण भेजिए।"),
                ("How much is the total bill?", "कुल बिल कितना है?"),
                ("I would like to split the bill.", "मैं बिल बाँटना चाहूँगा।"),
                ("Can I pay in installments?", "क्या मैं किश्तों में भुगतान कर सकता हूँ?"),
                ("I have saved enough money for the trip.", "मैंने यात्रा के लिए काफी पैसे बचा लिए हैं।"),
                ("Money management is an important skill.", "पैसों का प्रबंधन एक महत्वपूर्ण कौशल है।"),
                ("The price includes all taxes.", "कीमत में सभी कर शामिल हैं।"),
                ("I got a discount of ten percent.", "मुझे दस प्रतिशत की छूट मिली।"),
                ("Please check the change carefully.", "कृपया बदले हुए पैसे ध्यान से गिनिए।"),
                ("I want to open a savings account.", "मैं एक बचत खाता खोलना चाहता हूँ।"),
                ("Never share your PIN with anyone.", "अपना पिन कभी किसी के साथ साझा न करें।"),
            ]},
            {"title": "Phone Calls", "desc": "Make and receive phone calls", "topic": "Phone", "sentences": [
                ("Hello, may I speak to Mr. Verma?", "नमस्ते, क्या मैं श्री वर्मा से बात कर सकता हूँ?"),
                ("Who is calling, please?", "कौन बुला रहा है, कृपया?"),
                ("This is Priya speaking.", "मैं प्रिया बोल रही हूँ।"),
                ("Please hold on for a moment.", "कृपया एक पल रुकिए।"),
                ("I will connect you to the manager.", "मैं आपको मैनेजर से जोड़ता हूँ।"),
                ("Can you please speak a little louder?", "क्या आप कृपया थोड़ा ज़ोर से बोल सकते हैं?"),
                ("I cannot hear you very clearly.", "मैं आपको स्पष्ट सुन नहीं पा रहा हूँ।"),
                ("I will call you back in ten minutes.", "मैं आपको दस मिनट में वापस कॉल करूँगा।"),
                ("Could you please take a message?", "क्या आप कृपया एक संदेश ले सकते हैं?"),
                ("I missed your call. What happened?", "आपका कॉल मिस हो गया। क्या हुआ?"),
                ("The phone battery is about to die.", "फोन की बैटरी खत्म होने वाली है।"),
                ("I will send you a WhatsApp message.", "मैं आपको व्हाट्सएप पर मैसेज भेजूँगा।"),
                ("Let me check my phone for the details.", "मुझे डिटेल्स के लिए अपना फोन देखने दें।"),
                ("The call got disconnected.", "कॉल कट गया।"),
                ("I will call again in the evening.", "मैं शाम को फिर कॉल करूँगा।"),
                ("Thanks for calling. Goodbye!", "कॉल करने के लिए धन्यवाद। नमस्ते!"),
                ("Please save my number.", "कृपया मेरा नंबर सेव कर लीजिए।"),
                ("Shall I call you on your mobile?", "क्या मैं आपको मोबाइल पर कॉल करूँ?"),
                ("Please text me the address.", "कृपया मुझे पता टेक्स्ट कर दीजिए।"),
                ("Are you free to talk right now?", "क्या आप अभी बात करने के लिए खाली हैं?"),
                ("I am in a meeting right now.", "मैं अभी मीटिंग में हूँ।"),
                ("Let us talk later tonight.", "चलो आज रात बात करते हैं।"),
                ("You have reached the wrong number.", "आपने गलत नंबर पर कॉल किया है।"),
                ("Sorry, I dialed the wrong number.", "माफ कीजिए, मैंने गलत नंबर मिलाया।"),
                ("Please call me as soon as you get this.", "जैसे ही यह मिले, कृपया मुझे कॉल करें।"),
            ]},
            {"title": "Asking for Help", "desc": "Ask for help politely", "topic": "Asking for Help", "sentences": [
                ("Excuse me, can you help me please?", "क्षमा करें, क्या आप मेरी मदद कर सकते हैं?"),
                ("Could you please help me with this?", "क्या आप इसमें मेरी मदद कर सकते हैं?"),
                ("I need help with my luggage.", "मुझे अपने सामान के लिए मदद चाहिए।"),
                ("Can I use your phone for a minute?", "क्या मैं एक मिनट आपका फोन इस्तेमाल कर सकता हूँ?"),
                ("Could you call a taxi for me?", "क्या आप मेरे लिए टैक्सी बुला सकते हैं?"),
                ("Can you please help me fill this form?", "क्या आप यह फॉर्म भरने में मेरी मदद करेंगे?"),
                ("I do not know how to use this machine.", "मुझे नहीं पता कि यह मशीन कैसे चलती है।"),
                ("Could you please explain this to me?", "क्या आप मुझे यह समझा सकते हैं?"),
                ("I appreciate your help very much.", "मैं आपकी मदद की बहुत सराहना करता हूँ।"),
                ("Can you show me how to do this?", "क्या आप मुझे दिखा सकते हैं कि यह कैसे करना है?"),
                ("I am new here. Can you guide me?", "मैं यहाँ नया हूँ। क्या आप मेरा मार्गदर्शन कर सकते हैं?"),
                ("Please help me carry this bag.", "कृपया मेरा यह बैग उठाने में मदद कीजिए।"),
                ("Can you please open this for me?", "क्या आप कृपया मेरे लिए यह खोल सकते हैं?"),
                ("I need someone to help me with this problem.", "मुझे इस समस्या में किसी की मदद चाहिए।"),
                ("Is there anyone who can help me?", "क्या कोई है जो मेरी मदद कर सके?"),
                ("Could you please write down the address?", "क्या आप कृपया पता लिख सकते हैं?"),
                ("Thank you for your kind help.", "आपकी दयालु मदद के लिए धन्यवाद।"),
                ("Can you please tell me where the office is?", "क्या आप बता सकते हैं कि ऑफिस कहाँ है?"),
                ("I cannot do this alone. I need help.", "मैं यह अकेले नहीं कर सकता। मुझे मदद चाहिए।"),
                ("Would you mind helping me for a minute?", "क्या आप एक मिनट मेरी मदद करेंगे?"),
                ("Can you please carry this to my car?", "क्या आप इसे मेरी कार तक ले चलेंगे?"),
                ("I will be grateful for your help.", "मैं आपकी मदद के लिए आभारी रहूँगा।"),
                ("Do you know how to fix this?", "क्या आप जानते हैं कि इसे कैसे ठीक किया जाता है?"),
                ("Please help me find my way back.", "कृपया मेरा वापस जाने का रास्ता ढूँढने में मदद कीजिए।"),
                ("Thank you for your time and help.", "आपके समय और मदद के लिए धन्यवाद।"),
            ]},
            {"title": "Requests & Permission", "desc": "Make requests and ask permission", "topic": "Requests", "sentences": [
                ("Can I come in?", "क्या मैं अंदर आ सकता हूँ?"),
                ("May I use your pen, please?", "क्या मैं आपका पेन इस्तेमाल कर सकता हूँ?"),
                ("Could I borrow your book for a day?", "क्या मैं एक दिन के लिए आपकी किताब ले सकता हूँ?"),
                ("Would you mind opening the window?", "क्या आप खिड़की खोलेंगे?"),
                ("Please sit down and make yourself comfortable.", "कृपया बैठिए और आराम से रहिए।"),
                ("Could you please send me the document?", "क्या आप मुझे दस्तावेज़ भेज सकते हैं?"),
                ("I would like a glass of water, please.", "मुझे एक गिलास पानी चाहिए, कृपया।"),
                ("Can you wait for me for five minutes?", "क्या आप मेरा पाँच मिनट इंतज़ार कर सकते हैं?"),
                ("Could you please turn down the music?", "क्या आप कृपया संगीत धीमा कर सकते हैं?"),
                ("Please do not smoke here.", "कृपया यहाँ धूम्रपान न करें।"),
                ("Is it okay if I sit here?", "क्या मैं यहाँ बैठ सकता हूँ?"),
                ("May I leave early today?", "क्या मैं आज जल्दी निकल सकता हूँ?"),
                ("Is it allowed to take photos here?", "क्या यहाँ फोटो लेना मना है?"),
                ("Could you pass me the newspaper?", "क्या आप मुझे अखबार दे सकते हैं?"),
                ("Please check your email for the update.", "कृपया अपडेट के लिए अपना ईमेल देखिए।"),
                ("Would you like some more tea?", "क्या आप और चाय लेंगे?"),
                ("Can I bring a friend to the party?", "क्या मैं पार्टी में एक दोस्त ला सकता हूँ?"),
                ("Please let me know if you need anything.", "अगर आपको कुछ चाहिए तो कृपया बताइए।"),
                ("Could you please repeat what you said?", "क्या आप कृपया अपनी बात दोहरा सकते हैं?"),
                ("I promise I will return it tomorrow.", "मैं वादा करता हूँ कल वापस कर दूँगा।"),
                ("Thank you for understanding.", "समझने के लिए धन्यवाद।"),
                ("Could you do me a small favour?", "क्या आप मेरी एक छोटी सी मदद कर सकते हैं?"),
                ("Please send me the location on Google Maps.", "कृपया मुझे गूगल मैप पर लोकेशन भेजिए।"),
                ("May I borrow your charger for a while?", "क्या मैं थोड़ी देर आपका चार्जर ले सकता हूँ?"),
                ("Is it okay to park the car here?", "क्या यहाँ कार पार्क करना ठीक है?"),
            ]},
            {"title": "Directions", "desc": "Ask for and give directions", "topic": "Directions", "sentences": [
                ("Excuse me, where is the metro station?", "क्षमा करें, मेट्रो स्टेशन कहाँ है?"),
                ("I am lost. Can you show me the way?", "मैं खो गया हूँ। क्या आप रास्ता दिखा सकते हैं?"),
                ("Go straight for 200 meters.", "200 मीटर सीधे चलिए।"),
                ("Take the first left turn.", "पहला बाएँ मोड़ लीजिए।"),
                ("It is on the right side of the road.", "यह सड़क के दाएँ तरफ है।"),
                ("How far is the airport from here?", "यहाँ से हवाई अड्डा कितनी दूर है?"),
                ("You can take bus number 42.", "आप 42 नंबर की बस ले सकते हैं।"),
                ("It takes about 15 minutes by car.", "कार से लगभग 15 मिनट लगते हैं।"),
                ("The hospital is next to the bank.", "अस्पताल बैंक के बगल में है।"),
                ("I am looking for this restaurant.", "मैं इस रेस्तराँ को ढूँढ रहा हूँ।"),
                ("Turn right after the traffic signal.", "ट्रैफिक सिग्नल के बाद दाएँ मुड़िए।"),
                ("The building is across the street.", "इमारत सड़क के पार है।"),
                ("It will take ten minutes on foot.", "पैदल दस मिनट लगेंगे।"),
                ("I need to go to the railway station.", "मुझे रेलवे स्टेशन जाना है।"),
                ("Is there a parking lot nearby?", "क्या पास में कोई पार्किंग है?"),
                ("The shop is on the corner of the street.", "दुकान सड़क के कोने पर है।"),
                ("Which bus goes to the city center?", "सिटी सेंटर के लिए कौन सी बस जाती है?"),
                ("Walk straight and you will see it.", "सीधे चलिए और आपको दिख जाएगा।"),
                ("It is opposite the post office.", "यह पोस्ट ऑफिस के सामने है।"),
                ("Follow this road for one kilometer.", "इस सड़क पर एक किलोमीटर चलिए।"),
                ("You cannot miss it.", "आप इसे मिस नहीं कर सकते।"),
                ("Is this the right way to the temple?", "क्या यह मंदिर का सही रास्ता है?"),
                ("Please drop me at this address.", "कृपया मुझे इस पते पर छोड़ दीजिए।"),
                ("The market is two blocks away.", "बाज़ार दो ब्लॉक दूर है।"),
                ("Thank you for the directions.", "रास्ता बताने के लिए धन्यवाद।"),
            ]},
            {"title": "Travel Basics", "desc": "Essential travel phrases", "topic": "Travel", "sentences": [
                ("I need to book a flight to Mumbai.", "मुझे मुंबई की फ्लाइट बुक करनी है।"),
                ("How much is a ticket to Delhi?", "दिल्ली का टिकट कितना है?"),
                ("Is there a direct bus to Jaipur?", "क्या जयपुर के लिए सीधी बस है?"),
                ("What is the check-in time?", "चेक-इन का समय क्या है?"),
                ("I would like a window seat, please.", "मुझे खिड़की वाली सीट चाहिए, कृपया।"),
                ("Please take me to this address.", "कृपया मुझे इस पते पर ले चलिए।"),
                ("How much is the fare to the station?", "स्टेशन तक का किराया कितना है?"),
                ("I need to get off at the next stop.", "मुझे अगले स्टॉप पर उतरना है।"),
                ("Please turn on the AC.", "कृपया एसी चालू कर दीजिए।"),
                ("I am going on a trip next week.", "मैं अगले हफ्ते यात्रा पर जा रहा हूँ।"),
                ("Have you packed your bags?", "क्या आपने अपने बैग पैक कर लिए?"),
                ("I am excited about the trip!", "मैं यात्रा को लेकर उत्साहित हूँ!"),
                ("The journey takes about 5 hours.", "यात्रा में लगभग 5 घंटे लगते हैं।"),
                ("We will reach by evening.", "हम शाम तक पहुँच जाएँगे।"),
                ("It is a beautiful place to visit.", "यह घूमने के लिए एक सुंदर जगह है।"),
                ("I need to charge my phone.", "मुझे अपना फोन चार्ज करना है।"),
                ("Do you have a charger with you?", "क्या आपके पास चार्जर है?"),
                ("I forgot my umbrella at home.", "मैं अपना छाता घर पर भूल गया।"),
                ("What is the weather like today?", "आज मौसम कैसा है?"),
                ("It is raining heavily outside.", "बाहर बहुत तेज़ बारिश हो रही है।"),
                ("I need to buy a water bottle.", "मुझे पानी की बोतल खरीदनी है।"),
                ("Can you recommend a good hotel?", "क्या आप एक अच्छा होटल सुझा सकते हैं?"),
                ("I prefer to travel by train.", "मैं ट्रेन से यात्रा करना पसंद करता हूँ।"),
                ("Let me check the train schedule.", "मुझे ट्रेन का शेड्यूल देखने दें।"),
                ("Safe travels! Have a great journey!", "यात्रा सुरक्षित हो! आपकी यात्रा शुभ हो!"),
            ]},
            {"title": "Friends", "desc": "Talk about friends", "topic": "Friends", "sentences": [
                ("My best friend lives next door.", "मेरा सबसे अच्छा दोस्त बगल में रहता है।"),
                ("We have been friends since childhood.", "हम बचपन से दोस्त हैं।"),
                ("I trust my friend completely.", "मुझे अपने दोस्त पर पूरा भरोसा है।"),
                ("I am going to meet my friends this weekend.", "मैं इस वीकेंड अपने दोस्तों से मिलने जा रहा हूँ।"),
                ("We usually hang out at the café nearby.", "हम आमतौर पर पास के कैफे में मिलते हैं।"),
                ("I call my friend every night.", "मैं हर रात अपने दोस्त को कॉल करता हूँ।"),
                ("We play cricket together on Sundays.", "हम रविवार को साथ क्रिकेट खेलते हैं।"),
                ("My friend is coming over tonight.", "मेरा दोस्त आज रात मेरे घर आ रहा है।"),
                ("We talked for hours on the phone.", "हमने फोन पर घंटों बात की।"),
                ("A true friend helps in difficult times.", "सच्चा दोस्त मुश्किल समय में मदद करता है।"),
                ("I am lucky to have such good friends.", "मैं भाग्यशाली हूँ कि मुझे इतने अच्छे दोस्त मिले।"),
                ("Please say hello to your family for me.", "कृपया मेरी तरफ से अपने परिवार को नमस्ते कहिए।"),
                ("We help each other with work.", "हम एक-दूसरे की काम में मदद करते हैं।"),
                ("My friend gave me a nice gift.", "मेरे दोस्त ने मुझे एक अच्छा उपहार दिया।"),
                ("I am going to a friend's wedding.", "मैं अपने दोस्त की शादी में जा रहा हूँ।"),
                ("We studied in the same school.", "हमने एक ही स्कूल में पढ़ाई की।"),
                ("Our families are very close.", "हमारे परिवार बहुत करीबी हैं।"),
                ("Let me introduce you to my friends.", "चलो मैं तुम्हें अपने दोस्तों से मिलवाता हूँ।"),
                ("Friends make life more fun!", "दोस्त जीवन को और मजेदार बनाते हैं!"),
                ("We share everything with each other.", "हम एक-दूसरे के साथ सब कुछ साझा करते हैं।"),
                ("My friend is very honest.", "मेरा दोस्त बहुत ईमानदार है।"),
                ("We meet every month for lunch.", "हम हर महीने दोपहर के खाने पर मिलते हैं।"),
                ("A friend in need is a friend indeed.", "आवश्यकता में काम आने वाला ही सच्चा मित्र होता है।"),
                ("My friends support me in everything.", "मेरे दोस्त हर चीज़ में मेरा समर्थन करते हैं।"),
                ("I am happy to have a friend like you.", "मुझे खुशी है कि मुझे आप जैसा दोस्त मिला।"),
            ]},
            {"title": "Neighbours", "desc": "Talk about neighbours and community", "topic": "Neighbours", "sentences": [
                ("My neighbour is very helpful.", "मेरा पड़ोसी बहुत मददगार है।"),
                ("We invited our neighbours for dinner.", "हमने अपने पड़ोसियों को खाने पर बुलाया।"),
                ("Could I borrow some sugar from you?", "क्या मैं आपसे थोड़ी चीनी ले सकता हूँ?"),
                ("The neighbours are very noisy at night.", "पड़ोसी रात में बहुत शोर करते हैं।"),
                ("The new neighbour seems very nice.", "नया पड़ोसी बहुत अच्छा लग रहा है।"),
                ("We greet each other every morning.", "हम हर सुबह एक-दूसरे का अभिवादन करते हैं।"),
                ("Our neighbours helped us during the flood.", "बाढ़ के दौरान हमारे पड़ोसियों ने हमारी मदद की।"),
                ("The neighbour's dog barks a lot.", "पड़ोसी का कुत्ता बहुत भौंकता है।"),
                ("We have friendly neighbours.", "हमारे पड़ोसी मिलनसार हैं।"),
                ("Please keep the noise down at night.", "कृपया रात में शोर कम रखिए।"),
                ("I borrowed a ladder from my neighbour.", "मैंने अपने पड़ोसी से एक सीढ़ी उधार ली।"),
                ("The neighbours are celebrating a festival.", "पड़ोसी त्योहार मना रहे हैं।"),
                ("We share a common wall with our neighbours.", "हम अपने पड़ोसियों के साथ एक दीवार साझा करते हैं।"),
                ("My neighbour waters my plants when I am away.", "जब मैं दूर होता हूँ तो मेरा पड़ोसी मेरे पौधों को पानी देता है।"),
                ("Good neighbours are a blessing.", "अच्छे पड़ोसी एक वरदान होते हैं।"),
                ("We complained about the loud music.", "हमने तेज़ संगीत की शिकायत की।"),
                ("The neighbour invited us to their party.", "पड़ोसी ने हमें अपनी पार्टी में बुलाया।"),
                ("Our children play together in the park.", "हमारे बच्चे पार्क में साथ खेलते हैं।"),
                ("I have known my neighbour for ten years.", "मैं अपने पड़ोसी को दस साल से जानता हूँ।"),
                ("The neighbours are very cooperative.", "पड़ोसी बहुत सहयोगी हैं।"),
                ("We helped our neighbour carry the groceries.", "हमने पड़ोसी का सामान उठाने में मदद की।"),
                ("It is important to have good relations with neighbours.", "पड़ोसियों के साथ अच्छे संबंध रखना महत्वपूर्ण है।"),
                ("The building has four families.", "इमारत में चार परिवार रहते हैं।"),
                ("Our neighbour is a retired teacher.", "हमारे पड़ोसी एक सेवानिवृत्त शिक्षक हैं।"),
                ("Neighbours should help each other.", "पड़ोसियों को एक-दूसरे की मदद करनी चाहिए।"),
            ]},
            {"title": "School Basics", "desc": "Talk about school and studies", "topic": "School", "sentences": [
                ("I go to school by bus.", "मैं स्कूल बस से जाता हूँ।"),
                ("My favourite subject is English.", "मेरा पसंदीदा विषय अंग्रेज़ी है।"),
                ("I have a lot of homework today.", "आज मेरा बहुत सारा होमवर्क है।"),
                ("The teacher explained the lesson well.", "टीचर ने पाठ अच्छी तरह समझाया।"),
                ("The school is close to my house.", "स्कूल मेरे घर के पास है।"),
                ("I got good marks in the exam.", "मुझे परीक्षा में अच्छे अंक मिले।"),
                ("I need to prepare for my presentation.", "मुझे अपनी प्रेजेंटेशन तैयार करनी है।"),
                ("Can I borrow your notes?", "क्या मैं आपके नोट्स ले सकता हूँ?"),
                ("I study for two hours every night.", "मैं हर रात दो घंटे पढ़ता हूँ।"),
                ("Our school has a big library.", "हमारे स्कूल में एक बड़ा पुस्तकालय है।"),
                ("The exam starts next week.", "परीक्षा अगले हफ्ते शुरू होती है।"),
                ("I understand the lesson now.", "मुझे अब पाठ समझ आ गया।"),
                ("Please raise your hand to speak.", "कृपया बोलने के लिए हाथ उठाइए।"),
                ("We have a science class at 10.", "हमारी 10 बजे विज्ञान की क्लास है।"),
                ("I forgot my homework at home.", "मैं अपना होमवर्क घर पर भूल गया।"),
                ("The teacher asked us to write an essay.", "टीचर ने हमें निबंध लिखने को कहा।"),
                ("I sit in the second row.", "मैं दूसरी पंक्ति में बैठता हूँ।"),
                ("We have a holiday on Monday.", "हमारी सोमवार को छुट्टी है।"),
                ("My school bag is very heavy.", "मेरा स्कूल बैग बहुत भारी है।"),
                ("I like my new teacher.", "मुझे अपने नए टीचर पसंद हैं।"),
                ("We learn new words every day.", "हम हर दिन नए शब्द सीखते हैं।"),
                ("The bell rang for lunch.", "दोपहर के खाने के लिए घंटी बजी।"),
                ("I scored full marks in maths.", "मुझे गणित में पूरे अंक मिले।"),
                ("Education is very important for life.", "जीवन के लिए शिक्षा बहुत महत्वपूर्ण है।"),
                ("I am proud of my school.", "मुझे अपने स्कूल पर गर्व है।"),
            ]},
            {"title": "Work Basics", "desc": "Talk about work and jobs", "topic": "Work", "sentences": [
                ("I work from 9 to 5 every day.", "मैं हर दिन 9 से 5 तक काम करता हूँ।"),
                ("My boss is very supportive.", "मेरे बॉस बहुत सहयोगी हैं।"),
                ("I have a meeting in the afternoon.", "मेरी दोपहर में एक मीटिंग है।"),
                ("Please submit your report by Friday.", "कृपया शुक्रवार तक अपनी रिपोर्ट जमा करें।"),
                ("I like my job because it is interesting.", "मुझे अपनी नौकरी पसंद है क्योंकि यह दिलचस्प है।"),
                ("I am learning new things at work.", "मैं काम पर नई चीज़ें सीख रहा हूँ।"),
                ("The deadline is next Monday.", "अंतिम तिथि अगला सोमवार है।"),
                ("I work with a great team.", "मैं एक शानदार टीम के साथ काम करता हूँ।"),
                ("I take a break at 3 PM.", "मैं दोपहर 3 बजे ब्रेक लेता हूँ।"),
                ("My office is in a high-rise building.", "मेरा ऑफिस एक ऊँची इमारत में है।"),
                ("I have to finish this task today.", "मुझे यह काम आज खत्म करना है।"),
                ("Can you help me with this problem?", "क्या आप इस समस्या में मेरी मदद कर सकते हैं?"),
                ("Let me check the schedule.", "मुझे शेड्यूल देखने दें।"),
                ("I am free this evening.", "मैं आज शाम को खाली हूँ।"),
                ("The project is going well.", "प्रोजेक्ट अच्छा चल रहा है।"),
                ("Hard work always pays off.", "मेहनत का फल हमेशा मिलता है।"),
                ("I get paid at the end of the month.", "मुझे महीने के अंत में वेतन मिलता है।"),
                ("My working hours are flexible.", "मेरे काम के घंटे लचीले हैं।"),
                ("I am looking for a new job.", "मैं एक नई नौकरी की तलाश में हूँ।"),
                ("She works in a hospital.", "वह एक अस्पताल में काम करती है।"),
                ("I have a part-time job.", "मेरे पास एक पार्ट-टाइम नौकरी है।"),
                ("Please come to my cabin.", "कृपया मेरे केबिन में आइए।"),
                ("The company gives us good benefits.", "कंपनी हमें अच्छे लाभ देती है।"),
                ("I enjoy working with my colleagues.", "मुझे अपने सहकर्मियों के साथ काम करने में मजा आता है।"),
                ("Every job has its challenges.", "हर नौकरी की अपनी चुनौतियाँ होती हैं।"),
            ]},
            {"title": "Problems & Complaints", "desc": "Talk about problems and complaints", "topic": "Problems", "sentences": [
                ("I have a problem with my phone.", "मेरे फोन में एक समस्या है।"),
                ("Something is not working properly.", "कुछ ठीक से काम नहीं कर रहा है।"),
                ("I need to report an issue.", "मुझे एक समस्या की रिपोर्ट करनी है।"),
                ("Can you please fix this?", "क्या आप कृपया इसे ठीक कर सकते हैं?"),
                ("I am not feeling well today.", "आज मेरी तबीयत ठीक नहीं है।"),
                ("I have a headache.", "मेरे सिर में दर्द है।"),
                ("I lost my keys somewhere.", "मेरी चाबियाँ कहीं खो गईं।"),
                ("My bag has been stolen.", "मेरा बैग चोरी हो गया है।"),
                ("I need a technician to check this.", "मुझे इसे चेक करने के लिए एक तकनीशियन चाहिए।"),
                ("Can I speak to the manager?", "क्या मैं मैनेजर से बात कर सकता हूँ?"),
                ("I hope the problem is not serious.", "मुझे उम्मीद है समस्या गंभीर नहीं है।"),
                ("Everything will be fine.", "सब कुछ ठीक हो जाएगा।"),
                ("Let me know if you need anything.", "अगर आपको कुछ चाहिए तो बताइए।"),
                ("I will sort it out as soon as possible.", "मैं इसे जल्द से जल्द ठीक कर लूँगा।"),
                ("The tap is leaking in the bathroom.", "बाथरूम में नल टपक रहा है।"),
                ("The room is too cold.", "कमरा बहुत ठंडा है।"),
                ("My order was delivered late.", "मेरा ऑर्डर देर से आया।"),
                ("The product is damaged.", "प्रोडक्ट खराब है।"),
                ("I want to file a complaint.", "मैं एक शिकायत दर्ज करना चाहता हूँ।"),
                ("This is not what I ordered.", "यह वह नहीं है जो मैंने ऑर्डर किया था।"),
                ("There is too much noise outside.", "बाहर बहुत शोर है।"),
                ("The lift is not working.", "लिफ्ट काम नहीं कर रही है।"),
                ("We need to solve this problem quickly.", "हमें इस समस्या को जल्दी हल करना है।"),
                ("Do not worry, we will manage.", "चिंता मत कीजिए, हम संभाल लेंगे।"),
                ("Every problem has a solution.", "हर समस्या का एक समाधान है।"),
            ]},
            {"title": "Appointments", "desc": "Make and manage appointments", "topic": "Appointments", "sentences": [
                ("I want to make an appointment.", "मैं एक अपॉइंटमेंट बुक करना चाहता हूँ।"),
                ("Is the doctor available tomorrow?", "क्या डॉक्टर कल उपलब्ध हैं?"),
                ("I would like to reschedule my appointment.", "मैं अपना अपॉइंटमेंट रीशेड्यूल करना चाहता हूँ।"),
                ("What time is my appointment?", "मेरा अपॉइंटमेंट किस समय है?"),
                ("Please confirm my booking.", "कृपया मेरी बुकिंग कन्फर्म करें।"),
                ("I am here for my 3 PM appointment.", "मैं अपने 3 बजे के अपॉइंटमेंट के लिए यहाँ हूँ।"),
                ("Do I need to bring any documents?", "क्या मुझे कोई दस्तावेज़ लाने की ज़रूरत है?"),
                ("The earliest slot is next Tuesday.", "सबसे जल्दी स्लॉट अगले मंगलवार को है।"),
                ("How long do I have to wait?", "मुझे कितनी देर इंतज़ार करना होगा?"),
                ("Please add me to the waiting list.", "कृपया मुझे वेटिंग लिस्ट में डाल दें।"),
                ("Can I get an appointment for today?", "क्या मुझे आज के लिए अपॉइंटमेंट मिल सकता है?"),
                ("The appointment is confirmed for 11 AM.", "अपॉइंटमेंट सुबह 11 बजे कन्फर्म है।"),
                ("I need to cancel my appointment.", "मुझे अपना अपॉइंटमेंट कैंसल करना है।"),
                ("Please arrive fifteen minutes early.", "कृपया पंद्रह मिनट पहले पहुँचिए।"),
                ("The consultation fee is 500 rupees.", "परामर्श शुल्क 500 रुपये है।"),
                ("Do you accept walk-in patients?", "क्या आप बिना अपॉइंटमेंट के भी मरीज़ देखते हैं?"),
                ("I would like a morning appointment.", "मुझे सुबह का अपॉइंटमेंट चाहिए।"),
                ("Is the specialist available this week?", "क्या विशेषज्ञ इस हफ्ते उपलब्ध हैं?"),
                ("Please remind me about my appointment.", "कृपया मुझे मेरे अपॉइंटमेंट की याद दिलाइए।"),
                ("My appointment got cancelled.", "मेरा अपॉइंटमेंट कैंसल हो गया।"),
                ("I want to see the dentist.", "मैं दंत चिकित्सक से मिलना चाहता हूँ।"),
                ("How much does the check-up cost?", "जाँच का खर्च कितना है?"),
                ("Can you please call me when it is my turn?", "क्या आप मुझे कॉल करेंगे जब मेरी बारी आए?"),
                ("I will wait outside.", "मैं बाहर इंतज़ार करूँगा।"),
                ("Thank you for seeing me.", "मुझसे मिलने के लिए धन्यवाद।"),
            ]},
            {"title": "Online Orders", "desc": "Order products online", "topic": "Online Orders", "sentences": [
                ("I want to order something online.", "मैं ऑनलाइन कुछ ऑर्डर करना चाहता हूँ।"),
                ("How do I place an order on this website?", "मैं इस वेबसाइट पर ऑर्डर कैसे करूँ?"),
                ("I need to create an account first.", "मुझे पहले एक अकाउंट बनाना होगा।"),
                ("Do you offer free delivery?", "क्या आप मुफ्त डिलीवरी देते हैं?"),
                ("How long will delivery take?", "डिलीवरी में कितना समय लगेगा?"),
                ("Can I track my order?", "क्या मैं अपना ऑर्डर ट्रैक कर सकता हूँ?"),
                ("I changed my mind about the order.", "मैंने ऑर्डर के बारे में अपना मन बदल लिया।"),
                ("How do I apply a coupon code?", "मैं कूपन कोड कैसे लगाऊँ?"),
                ("The payment did not go through.", "भुगतान नहीं हो पाया।"),
                ("Please check your email for confirmation.", "कृपया कन्फर्मेशन के लिए अपना ईमेल देखिए।"),
                ("Your order has been shipped.", "आपका ऑर्डर भेज दिया गया है।"),
                ("The delivery partner will call you.", "डिलीवरी पार्टनर आपको कॉल करेगा।"),
                ("What is the delivery charge?", "डिलीवरी शुल्क कितना है?"),
                ("Can I change my delivery address?", "क्या मैं अपना डिलीवरी पता बदल सकता हूँ?"),
                ("The estimated delivery is three days.", "अनुमानित डिलीवरी तीन दिन है।"),
                ("I ordered the wrong size.", "मैंने गलत साइज़ ऑर्डर कर लिया।"),
                ("How do I contact the seller?", "मैं विक्रेता से कैसे संपर्क करूँ?"),
                ("The app is very easy to use.", "ऐप इस्तेमाल करना बहुत आसान है।"),
                ("I added the item to my cart.", "मैंने आइटम को कार्ट में जोड़ दिया।"),
                ("Please deliver it before 6 PM.", "कृपया इसे शाम 6 बजे से पहले डिलीवर करें।"),
                ("Is cash on delivery available?", "क्या कैश ऑन डिलीवरी उपलब्ध है?"),
                ("The product is out of stock.", "प्रोडक्ट स्टॉक में नहीं है।"),
                ("I want to check the product reviews.", "मैं प्रोडक्ट की समीक्षाएँ देखना चाहता हूँ।"),
                ("This website has good offers.", "इस वेबसाइट पर अच्छे ऑफर हैं।"),
                ("I received a notification about my order.", "मुझे अपने ऑर्डर के बारे में सूचना मिली।"),
            ]},
            {"title": "Customer Service", "desc": "Talk to customer service", "topic": "Customer Service", "sentences": [
                ("I want to return this product.", "मैं यह प्रोडक्ट वापस करना चाहता हूँ।"),
                ("I received the wrong item.", "मुझे गलत आइटम मिला है।"),
                ("I need a refund, please.", "मुझे रिफंड चाहिए, कृपया।"),
                ("Please cancel my order.", "कृपया मेरा ऑर्डर कैंसल करें।"),
                ("Can I speak to customer support?", "क्या मैं कस्टमर सपोर्ट से बात कर सकता हूँ?"),
                ("My order number is SB-12345.", "मेरा ऑर्डर नंबर SB-12345 है।"),
                ("Do you have an exchange option?", "क्या आपके पास एक्सचेंज का विकल्प है?"),
                ("I am happy with the service.", "मैं सेवा से खुश हूँ।"),
                ("Sorry for the inconvenience.", "असुविधा के लिए खेद है।"),
                ("We will resolve this issue soon.", "हम इस समस्या को जल्द हल कर देंगे।"),
                ("Thank you for your patience.", "आपके धैर्य के लिए धन्यवाद।"),
                ("How do I file a complaint?", "मैं शिकायत कैसे दर्ज करूँ?"),
                ("The customer service number is busy.", "कस्टमर सर्विस नंबर व्यस्त है।"),
                ("I have been waiting for a long time.", "मैं बहुत देर से इंतज़ार कर रहा हूँ।"),
                ("Please escalate my issue to a senior.", "कृपया मेरी समस्या को वरिष्ठ अधिकारी तक पहुँचाएँ।"),
                ("The representative was very helpful.", "प्रतिनिधि बहुत मददगार थे।"),
                ("My issue has been resolved.", "मेरी समस्या हल हो गई है।"),
                ("Can you give me a reference number?", "क्या आप मुझे एक संदर्भ संख्या दे सकते हैं?"),
                ("I want to speak to a human agent.", "मैं एक इंसानी एजेंट से बात करना चाहता हूँ।"),
                ("The warranty covers this repair.", "वारंटी इस मरम्मत को कवर करती है।"),
                ("Please send me a replacement.", "कृपया मुझे एक प्रतिस्थापन भेजें।"),
                ("I will never buy from this company again.", "मैं इस कंपनी से फिर कभी नहीं खरीदूँगा।"),
                ("Your feedback is very important to us.", "आपकी प्रतिक्रिया हमारे लिए बहुत महत्वपूर्ण है।"),
                ("The support team responded quickly.", "सपोर्ट टीम ने जल्दी जवाब दिया।"),
                ("Thank you for choosing our service.", "हमारी सेवा चुनने के लिए धन्यवाद।"),
            ]},
            {"title": "Plans & Invitations", "desc": "Make plans and invite people", "topic": "Plans", "sentences": [
                ("What are you doing this weekend?", "आप इस वीकेंड क्या कर रहे हैं?"),
                ("I am planning to visit my parents.", "मैं अपने माता-पिता से मिलने जाने की योजना बना रहा हूँ।"),
                ("Let us go for a movie tonight.", "चलो आज रात फिल्म देखने चलते हैं।"),
                ("That sounds like a great idea!", "यह बहुत अच्छा विचार लगता है!"),
                ("I will confirm my plans later.", "मैं बाद में अपने प्लान कन्फर्म करूँगा।"),
                ("Sorry, I already have other plans.", "क्षमा करें, मेरे पास पहले से अन्य योजनाएँ हैं।"),
                ("Maybe we can meet next weekend.", "शायद हम अगले वीकेंड मिल सकते हैं।"),
                ("Let me check my schedule.", "मुझे अपना शेड्यूल देखने दें।"),
                ("I am free on Saturday afternoon.", "मैं शनिवार दोपहर को खाली हूँ।"),
                ("What time should we meet?", "हमें कितने बजे मिलना चाहिए?"),
                ("How about meeting at 5 PM?", "शाम 5 बजे मिलने के बारे में क्या ख्याल है?"),
                ("I will pick you up at your place.", "मैं आपको आपके घर से लेने आऊँगा।"),
                ("Do not forget to bring your ID card.", "अपना आईडी कार्ड लाना मत भूलिए।"),
                ("It is going to be a fun day!", "यह एक मजेदार दिन होने वाला है!"),
                ("I cannot wait for the weekend!", "मैं वीकेंड का इंतज़ार नहीं कर सकता!"),
                ("Would you like to join us for dinner?", "क्या आप हमारे साथ खाना खाएँगे?"),
                ("I would love to come. Thank you!", "मुझे बहुत खुशी होगी। धन्यवाद!"),
                ("We are having a party on Sunday.", "हम रविवार को एक पार्टी कर रहे हैं।"),
                ("Please come with your family.", "कृपया अपने परिवार के साथ आइए।"),
                ("The party starts at 7 PM.", "पार्टी शाम 7 बजे शुरू होती है।"),
                ("I will bring a dish for the dinner.", "मैं खाने के लिए एक डिश लाऊँगा।"),
                ("Let us plan a trip together.", "चलो एक साथ यात्रा की योजना बनाते हैं।"),
                ("I will check the dates and let you know.", "मैं तारीखें देखकर आपको बताऊँगा।"),
                ("It is a plan!", "यह तय हुआ!"),
                ("We should do this more often.", "हमें ऐसा और अक्सर करना चाहिए।"),
            ]},
            {"title": "Common Conversations", "desc": "Everyday conversation phrases", "topic": "Common Conversations", "sentences": [
                ("Excuse me, do you have a minute?", "क्षमा करें, क्या आपके पास एक मिनट है?"),
                ("Sure, what can I do for you?", "ज़रूर, मैं आपके लिए क्या कर सकता हूँ?"),
                ("That is a good question.", "यह एक अच्छा सवाल है।"),
                ("I agree with you completely.", "मैं आपसे पूरी तरह सहमत हूँ।"),
                ("I am not sure about that.", "मुझे इसके बारे में निश्चित नहीं है।"),
                ("Let me think about it.", "मुझे इसके बारे में सोचने दें।"),
                ("That is very kind of you.", "आपकी बहुत दयालुता है।"),
                ("No problem at all!", "कोई बात नहीं!"),
                ("Take your time.", "अपना समय लीजिए।"),
                ("I really appreciate it.", "मैं वास्तव में इसकी सराहना करता हूँ।"),
                ("What do you think about this?", "आप इसके बारे में क्या सोचते हैं?"),
                ("I think it is a great opportunity.", "मुझे लगता है यह एक बड़ा अवसर है।"),
                ("Let us discuss this later.", "चलो इस पर बाद में चर्चा करते हैं।"),
                ("I understand what you mean.", "मैं समझता हूँ आपका क्या मतलब है।"),
                ("That is interesting!", "यह दिलचस्प है!"),
                ("How interesting!", "कितना दिलचस्प!"),
                ("I had no idea about that.", "मुझे इसके बारे में कोई जानकारी नहीं थी।"),
                ("You are absolutely right.", "आप बिल्कुल सही हैं।"),
                ("Let us move on to the next topic.", "चलो अगले विषय पर चलते हैं।"),
                ("Can we talk about something else?", "क्या हम किसी और चीज़ के बारे में बात कर सकते हैं?"),
                ("I am glad we had this conversation.", "मुझे खुशी है कि हमने यह बातचीत की।"),
                ("What do you suggest?", "आप क्या सुझाव देते हैं?"),
                ("I will keep that in mind.", "मैं इसे ध्यान में रखूँगा।"),
                ("It was nice meeting you.", "आपसे मिलकर अच्छा लगा।"),
                ("Let us stay in touch.", "चलो संपर्क में रहते हैं।"),
            ]},
            {"title": "Speaking Confidence", "desc": "Build confidence in speaking", "topic": "Confidence", "sentences": [
                ("Do not be afraid to make mistakes.", "गलतियाँ करने से मत डरिए।"),
                ("Practice English every day.", "रोज़ अंग्रेज़ी का अभ्यास कीजिए।"),
                ("Speak slowly and clearly.", "धीरे और स्पष्ट बोलिए।"),
                ("You will improve with time.", "समय के साथ आप सुधार करेंगे।"),
                ("Try to use English in daily life.", "रोज़मर्रा की जिंदगी में अंग्रेज़ी इस्तेमाल करने की कोशिश कीजिए।"),
                ("Listen to English songs and podcasts.", "अंग्रेज़ी के गाने और पॉडकास्ट सुनिए।"),
                ("Watch English movies with subtitles.", "उपशीर्षक के साथ अंग्रेज़ी फिल्में देखिए।"),
                ("Read English newspapers every day.", "रोज़ अंग्रेज़ी का अखबार पढ़िए।"),
                ("Write one paragraph in English daily.", "रोज़ एक पैराग्राफ अंग्रेज़ी में लिखिए।"),
                ("Talk to yourself in English in the mirror.", "आईने में खुद से अंग्रेज़ी में बात कीजिए।"),
                ("Record your voice and listen to it.", "अपनी आवाज़ रिकॉर्ड करें और सुनें।"),
                ("Learning a new language takes time.", "नई भाषा सीखने में समय लगता है।"),
                ("Every small step counts.", "हर छोटा कदम मायने रखता है।"),
                ("I am proud of my progress.", "मुझे अपनी प्रगति पर गर्व है।"),
                ("I can do this! I will improve!", "मैं यह कर सकता हूँ! मैं सुधार करूँगा!"),
                ("Could you please speak a bit slower?", "क्या आप कृपया थोड़ा धीरे बोल सकते हैं?"),
                ("What does this word mean?", "इस शब्द का क्या अर्थ है?"),
                ("How do you pronounce this word?", "आप इस शब्द का उच्चारण कैसे करते हैं?"),
                ("Can you give me an example?", "क्या आप मुझे एक उदाहरण दे सकते हैं?"),
                ("I need to practice speaking more.", "मुझे और अधिक बोलने का अभ्यास करने की ज़रूरत है।"),
                ("I will speak English with my friends.", "मैं अपने दोस्तों के साथ अंग्रेज़ी बोलूँगा।"),
                ("Confidence comes with practice.", "आत्मविश्वास अभ्यास से आता है।"),
                ("I will not give up on my goal.", "मैं अपने लक्ष्य से हार नहीं मानूँगा।"),
                ("I believe in myself.", "मुझे खुद पर विश्वास है।"),
                ("Every day I am getting better at English!", "हर दिन मैं अंग्रेज़ी में बेहतर हो रहा हूँ!"),
            ]},
            {"title": "Feelings & Emotions", "desc": "Express your feelings in English", "topic": "Feelings", "sentences": [
                ("I am very happy today.", "मैं आज बहुत खुश हूँ।"),
                ("I feel sad about the news.", "मुझे इस खबर पर दुख हो रहा है।"),
                ("I am excited about the trip.", "मैं यात्रा को लेकर उत्साहित हूँ।"),
                ("I am a little nervous.", "मैं थोड़ा घबराया हुआ हूँ।"),
                ("I feel tired after work.", "काम के बाद मैं थका हुआ महसूस करता हूँ।"),
                ("I am worried about the exam.", "मैं परीक्षा को लेकर चिंतित हूँ।"),
                ("I am proud of my son.", "मुझे अपने बेटे पर गर्व है।"),
                ("I feel relaxed on weekends.", "मैं वीकेंड पर आराम महसूस करता हूँ।"),
                ("I am surprised to see you here.", "आपको यहाँ देखकर मुझे हैरानी हुई।"),
                ("I am grateful for your help.", "मैं आपकी मदद के लिए आभारी हूँ।"),
                ("I am disappointed with the result.", "मैं परिणाम से निराश हूँ।"),
                ("I feel confident about my English.", "मुझे अपनी अंग्रेज़ी पर भरोसा है।"),
                ("I am feeling much better now.", "मैं अब काफी बेहतर महसूस कर रहा हूँ।"),
                ("Do not be angry. Let us talk.", "गुस्सा मत कीजिए। चलो बात करते हैं।"),
                ("I feel lonely sometimes.", "मैं कभी-कभी अकेला महसूस करता हूँ।"),
                ("I am thankful for my family.", "मैं अपने परिवार के लिए आभारी हूँ।"),
                ("She looks very happy today.", "वह आज बहुत खुश दिख रही है।"),
                ("I am in a good mood.", "मेरा मूड अच्छा है।"),
                ("I am feeling bored.", "मुझे बोरियत महसूस हो रही है।"),
                ("I am amazed by this place.", "मैं इस जगह से चकित हूँ।"),
                ("I feel peaceful here.", "मुझे यहाँ शांति महसूस होती है।"),
                ("I am frustrated with the delay.", "मैं देरी से परेशान हूँ।"),
                ("Please do not feel bad about it.", "कृपया इसके लिए बुरा महसूस मत कीजिए।"),
                ("I am hopeful for the future.", "मैं भविष्य के लिए आशावान हूँ।"),
                ("It is okay to feel this way.", "ऐसा महसूस करना ठीक है।"),
            ]},
            {"title": "Weather & Seasons", "desc": "Talk about the weather", "topic": "Weather", "sentences": [
                ("What is the weather like today?", "आज मौसम कैसा है?"),
                ("It is sunny outside.", "बाहर धूप है।"),
                ("It is very hot in summer.", "गर्मी में बहुत गर्मी होती है।"),
                ("It is raining heavily.", "बहुत तेज़ बारिश हो रही है।"),
                ("The weather is pleasant today.", "आज मौसम सुहावना है।"),
                ("It is cloudy. It might rain.", "बादल छाए हैं। बारिश हो सकती है।"),
                ("I like the monsoon season.", "मुझे मानसून का मौसम पसंद है।"),
                ("Winter is my favourite season.", "सर्दी मेरा पसंदीदा मौसम है।"),
                ("It is getting cold outside.", "बाहर ठंड बढ़ रही है।"),
                ("Take an umbrella. It may rain.", "छाता ले लीजिए। बारिश हो सकती है।"),
                ("The temperature is 35 degrees.", "तापमान 35 डिग्री है।"),
                ("It is very humid today.", "आज बहुत उमस है।"),
                ("The sky is clear tonight.", "आज रात आसमान साफ है।"),
                ("I love the cool breeze in the evening.", "मुझे शाम की ठंडी हवा बहुत पसंद है।"),
                ("It rained all night.", "पूरी रात बारिश हुई।"),
                ("We should carry water in summer.", "गर्मी में हमें पानी साथ रखना चाहिए।"),
                ("The fog is very thick in the morning.", "सुबह कोहरा बहुत घना है।"),
                ("I hope the weather stays nice.", "मुझे उम्मीद है मौसम अच्छा रहेगा।"),
                ("It is too windy to go out.", "बाहर जाने के लिए हवा बहुत तेज़ है।"),
                ("The weather changed suddenly.", "मौसम अचानक बदल गया।"),
                ("Autumn leaves are falling.", "पतझड़ के पत्ते गिर रहे हैं।"),
                ("I feel cold. Please close the window.", "मुझे ठंड लग रही है। कृपया खिड़की बंद करें।"),
                ("The weather forecast says it will rain.", "मौसम पूर्वानुमान के अनुसार बारिश होगी।"),
                ("Let us enjoy this lovely weather.", "चलो इस सुंदर मौसम का आनंद लेते हैं।"),
                ("Every season has its own beauty.", "हर मौसम की अपनी सुंदरता होती है।"),
            ]},
            {"title": "Health & Body", "desc": "Talk about health and your body", "topic": "Health", "sentences": [
                ("I am not feeling well.", "मेरी तबीयत ठीक नहीं है।"),
                ("I have a fever and a cough.", "मुझे बुखार और खांसी है।"),
                ("My stomach is hurting.", "मेरे पेट में दर्द हो रहा है।"),
                ("I need to see a doctor.", "मुझे डॉक्टर से मिलना है।"),
                ("Take this medicine twice a day.", "यह दवा दिन में दो बार लीजिए।"),
                ("Drink plenty of water.", "खूब सारा पानी पीजिए।"),
                ("Get enough sleep to stay healthy.", "स्वस्थ रहने के लिए पर्याप्त नींद लीजिए।"),
                ("I exercise to stay fit.", "मैं फिट रहने के लिए व्यायाम करता हूँ।"),
                ("My eyes are tired.", "मेरी आँखें थकी हुई हैं।"),
                ("I have a toothache.", "मेरे दाँत में दर्द है।"),
                ("Please take rest for two days.", "कृपया दो दिन आराम कीजिए।"),
                ("I eat healthy food.", "मैं स्वस्थ भोजन खाता हूँ।"),
                ("Wash your hands before eating.", "खाने से पहले हाथ धोइए।"),
                ("I feel weak today.", "मैं आज कमज़ोर महसूस कर रहा हूँ।"),
                ("The doctor gave me a check-up.", "डॉक्टर ने मेरी जाँच की।"),
                ("I am allergic to some medicines.", "मुझे कुछ दवाओं से एलर्जी है।"),
                ("My blood pressure is normal.", "मेरा रक्तचाप सामान्य है।"),
                ("I sleep for eight hours daily.", "मैं रोज़ आठ घंटे सोता हूँ।"),
                ("Yoga is good for health.", "योग स्वास्थ्य के लिए अच्छा है।"),
                ("I have a slight headache.", "मुझे हल्का सिरदर्द है।"),
                ("Take care of your health.", "अपने स्वास्थ्य का ख्याल रखिए।"),
                ("I am feeling better after the medicine.", "दवा के बाद मैं बेहतर महसूस कर रहा हूँ।"),
                ("Health is wealth.", "स्वास्थ्य ही सबसे बड़ा धन है।"),
                ("Please book a doctor's appointment for me.", "कृपया मेरे लिए डॉक्टर का अपॉइंटमेंट बुक करें।"),
                ("I will take care of myself.", "मैं अपना ख्याल रखूँगा।"),
            ]},
            {"title": "Celebrations & Festivals", "desc": "Talk about festivals and celebrations", "topic": "Celebrations", "sentences": [
                ("Happy Diwali to you and your family!", "आपको और आपके परिवार को दिवाली की शुभकामनाएँ!"),
                ("We celebrate Diwali with lights and sweets.", "हम दिवाली रोशनी और मिठाइयों के साथ मनाते हैं।"),
                ("Happy New Year! Wishing you all the best!", "नया साल मुबारक! आपको ढेर सारी शुभकामनाएँ!"),
                ("We decorate the house with flowers.", "हम घर को फूलों से सजाते हैं।"),
                ("My favourite festival is Holi.", "मेरा पसंदीदा त्योहार होली है।"),
                ("We wear new clothes on festivals.", "हम त्योहारों पर नए कपड़े पहनते हैं।"),
                ("Happy Birthday! May you have a great year!", "जन्मदिन मुबारक! आपका साल शानदार हो!"),
                ("We cut a cake on birthdays.", "हम जन्मदिन पर केक काटते हैं।"),
                ("The wedding ceremony was beautiful.", "शादी की रस्म बहुत सुंदर थी।"),
                ("We give gifts to our loved ones.", "हम अपने प्रियजनों को उपहार देते हैं।"),
                ("Eid Mubarak to you and your family!", "आपको और आपके परिवार को ईद मुबारक!"),
                ("We prepare special food on festivals.", "हम त्योहारों पर विशेष भोजन बनाते हैं।"),
                ("Let us celebrate this moment together.", "चलो इस पल को साथ मिलकर मनाते हैं।"),
                ("Congratulations on your success!", "आपकी सफलता पर बधाई!"),
                ("We light candles on Diwali night.", "हम दिवाली की रात दीये जलाते हैं।"),
                ("The whole family gathers for the festival.", "त्योहार पर पूरा परिवार इकट्ठा होता है।"),
                ("I received many good wishes today.", "मुझे आज बहुत सारी शुभकामनाएँ मिलीं।"),
                ("We sing and dance during celebrations.", "हम उत्सव के दौरान गाते और नाचते हैं।"),
                ("Please come and join the celebration.", "कृपया उत्सव में शामिल होइए।"),
                ("May your dreams come true!", "आपके सपने पूरे हों!"),
                ("The festival brings happiness to everyone.", "त्योहार सभी के लिए खुशी लाता है।"),
                ("We exchange sweets with neighbours.", "हम पड़ोसियों के साथ मिठाइयाँ बाँटते हैं।"),
                ("I am looking forward to the celebration.", "मैं उत्सव का इंतज़ार कर रहा हूँ।"),
                ("Best wishes for the new beginning!", "नई शुरुआत के लिए शुभकामनाएँ!"),
                ("Festivals bring families closer.", "त्योहार परिवारों को करीब लाते हैं।"),
            ]},
        ],
    }
