def get_school_banks():
    return {
        "course_id": "school",
        "title": "School English",
        "desc": "English for school students - classroom, homework, exams, and friends.",
        "short": "Ace your school English",
        "icon": "🎒",
        "color": "brand",
        "difficulty": "Beginner",
        "audience": ["School Students", "Kids", "Teenagers"],
        "price": "₹149",
        "lessons": [
            {"title": "Classroom", "desc": "In the classroom", "topic": "Classroom", "sentences": [
                ("Good morning, teacher!", "सुप्रभात, शिक्षक जी!"),
                ("May I come in?", "क्या मैं अंदर आ सकता हूँ?"),
                ("Please sit down, everyone.", "कृपया सब बैठ जाइए।"),
                ("Open your books to page ten.", "अपनी किताबें पेज दस पर खोलिए।"),
                ("Can you hear me at the back?", "क्या आप पीछे से मुझे सुन सकते हैं?"),
                ("Please be quiet in the class.", "कृपया कक्षा में शांत रहिए।"),
                ("I did not understand the question.", "मुझे प्रश्न समझ नहीं आया।"),
                ("Could you please repeat that?", "क्या आप कृपया इसे दोहरा सकते हैं?"),
                ("What is the homework for today?", "आज का होमवर्क क्या है?"),
                ("Please submit your notebooks.", "कृपया अपनी कॉपियाँ जमा करें।"),
                ("Can I go to the washroom?", "क्या मैं शौचालय जा सकता हूँ?"),
                ("The class will start now.", "कक्षा अब शुरू होगी।"),
                ("Please listen carefully.", "कृपया ध्यान से सुनिए।"),
                ("Raise your hand before speaking.", "बोलने से पहले हाथ उठाइए।"),
                ("What is the answer to this question?", "इस प्रश्न का उत्तर क्या है?"),
                ("Very good answer!", "बहुत अच्छा उत्तर!"),
                ("Please write down the notes.", "कृपया नोट्स लिख लीजिए।"),
                ("The bell has rung.", "घंटी बज गई है।"),
                ("We will continue tomorrow.", "हम कल जारी रखेंगे।"),
                ("Have you all understood?", "क्या आप सब समझ गए?"),
                ("Yes, teacher, we understood.", "हाँ, शिक्षक जी, हम समझ गए।"),
                ("Please clean the blackboard.", "कृपया ब्लैकबोर्ड साफ कर दीजिए।"),
                ("I am sitting in the front row.", "मैं पहली पंक्ति में बैठा हूँ।"),
                ("The class is very interesting.", "कक्षा बहुत रोचक है।"),
                ("Thank you for the lesson, teacher.", "पाठ के लिए धन्यवाद, शिक्षक जी।"),
            ]},
            {"title": "Homework & Studies", "desc": "Do homework and study", "topic": "Homework", "sentences": [
                ("I have a lot of homework today.", "आज मेरा बहुत सारा होमवर्क है।"),
                ("I finished my homework yesterday.", "मैंने कल अपना होमवर्क पूरा कर लिया।"),
                ("Can you help me with this sum?", "क्या आप इस सवाल में मेरी मदद कर सकते हैं?"),
                ("I study for two hours daily.", "मैं रोज़ दो घंटे पढ़ता हूँ।"),
                ("Please revise the chapter at home.", "कृपया घर पर अध्याय दोहराइए।"),
                ("I have not done my homework.", "मैंने अपना होमवर्क नहीं किया है।"),
                ("Why did you not complete it?", "आपने इसे पूरा क्यों नहीं किया?"),
                ("I was not well yesterday.", "कल मेरी तबीयत ठीक नहीं थी।"),
                ("Please do it by tomorrow.", "कृपया इसे कल तक कर दीजिए।"),
                ("I need to practise maths more.", "मुझे गणित का और अभ्यास करना है।"),
                ("The notes are very helpful.", "नोट्स बहुत मददगार हैं।"),
                ("Let me check the answer key.", "मुझे उत्तर कुंजी देखने दें।"),
                ("I made a mistake in my homework.", "मैंने अपने होमवर्क में एक गलती की।"),
                ("Please correct the errors.", "कृपया गलतियाँ सुधार दीजिए।"),
                ("I like to study in the morning.", "मुझे सुबह पढ़ना पसंद है।"),
                ("My mother helps me with my homework.", "मेरी माँ मेरा होमवर्क करने में मदद करती हैं।"),
                ("I will complete the project tonight.", "मैं आज रात प्रोजेक्ट पूरा करूँगा।"),
                ("Do not copy from others.", "दूसरों से नकल मत कीजिए।"),
                ("Practice makes perfect in studies too.", "पढ़ाई में भी अभ्यास से निपुणता आती है।"),
                ("I scored well because I studied hard.", "मैंने मेहनत से पढ़ा इसलिए अच्छे अंक आए।"),
                ("Let us study together after school.", "चलो स्कूल के बाद साथ पढ़ते हैं।"),
                ("I need to finish this chapter today.", "मुझे यह अध्याय आज खत्म करना है।"),
                ("The homework is due on Friday.", "होमवर्क शुक्रवार तक जमा करना है।"),
                ("I am trying my best.", "मैं अपनी पूरी कोशिश कर रहा हूँ।"),
                ("Studies are important for our future.", "हमारे भविष्य के लिए पढ़ाई महत्वपूर्ण है।"),
            ]},
            {"title": "Exams", "desc": "Talk about exams", "topic": "Exams", "sentences": [
                ("My exams start next week.", "मेरी परीक्षाएँ अगले हफ्ते शुरू होती हैं।"),
                ("I am preparing for my exams.", "मैं अपनी परीक्षाओं की तैयारी कर रहा हूँ।"),
                ("What is the exam schedule?", "परीक्षा का कार्यक्रम क्या है?"),
                ("The exam is for three hours.", "परीक्षा तीन घंटे की है।"),
                ("I am a little nervous about the exam.", "मैं परीक्षा को लेकर थोड़ा घबराया हुआ हूँ।"),
                ("Please bring your admit card.", "कृपया अपना एडमिट कार्ड लाइए।"),
                ("Do not write anything on the question paper.", "प्रश्न पत्र पर कुछ न लिखें।"),
                ("Read the questions carefully first.", "पहले प्रश्नों को ध्यान से पढ़िए।"),
                ("The paper was very easy.", "पेपर बहुत आसान था।"),
                ("I answered all the questions.", "मैंने सभी प्रश्नों के उत्तर दिए।"),
                ("When will the results come out?", "परिणाम कब आएँगे?"),
                ("I got good marks in the exam.", "मुझे परीक्षा में अच्छे अंक मिले।"),
                ("Congratulations on your results!", "आपके परिणामों पर बधाई!"),
                ("I need to improve my weak subjects.", "मुझे अपने कमज़ोर विषयों में सुधार करना है।"),
                ("The exam was postponed.", "परीक्षा स्थगित कर दी गई।"),
                ("I studied all night before the exam.", "मैंने परीक्षा से पहले पूरी रात पढ़ाई की।"),
                ("Do not leave any question unanswered.", "कोई प्रश्न बिना उत्तर के न छोड़ें।"),
                ("Check your answer sheet before submitting.", "जमा करने से पहले अपनी उत्तर पुस्तिका जाँच लीजिए।"),
                ("The exam hall is on the second floor.", "परीक्षा कक्ष दूसरी मंजिल पर है।"),
                ("I hope I pass with good marks.", "मुझे उम्मीद है मैं अच्छे अंकों से पास होऊँगा।"),
                ("Hard work is the key to success.", "कड़ी मेहनत ही सफलता की कुंजी है।"),
                ("I am confident about my preparation.", "मुझे अपनी तैयारी पर भरोसा है।"),
                ("The examiner was very strict.", "परीक्षक बहुत सख्त थे।"),
                ("I will study smartly this time.", "मैं इस बार समझदारी से पढ़ूँगा।"),
                ("Exams test what you have learned.", "परीक्षाएँ जाँचती हैं कि आपने क्या सीखा।"),
            ]},
            {"title": "Projects & Presentations", "desc": "Do projects and presentations", "topic": "Projects", "sentences": [
                ("I am working on my science project.", "मैं अपने विज्ञान प्रोजेक्ट पर काम कर रहा हूँ।"),
                ("The project is due next Monday.", "प्रोजेक्ट अगले सोमवार तक जमा करना है।"),
                ("We made the project in a group.", "हमने प्रोजेक्ट एक समूह में बनाया।"),
                ("I need some materials for the project.", "मुझे प्रोजेक्ट के लिए कुछ सामग्री चाहिए।"),
                ("The presentation will be for ten minutes.", "प्रेजेंटेशन दस मिनट का होगा।"),
                ("I am presenting on environmental pollution.", "मैं पर्यावरण प्रदूषण पर प्रेजेंटेशन दे रहा हूँ।"),
                ("Please speak loudly and clearly.", "कृपया ज़ोर से और स्पष्ट बोलिए।"),
                ("Make eye contact with the audience.", "दर्शकों के साथ आँख मिलाकर बात कीजिए।"),
                ("I used charts in my presentation.", "मैंने अपनी प्रेजेंटेशन में चार्ट इस्तेमाल किए।"),
                ("The teacher appreciated my project.", "शिक्षक ने मेरे प्रोजेक्ट की सराहना की।"),
                ("I am nervous about presenting.", "मैं प्रेजेंटेशन देने से घबरा रहा हूँ।"),
                ("Take a deep breath before you start.", "शुरू करने से पहले गहरी साँस लीजिए।"),
                ("The topic is very interesting.", "विषय बहुत रोचक है।"),
                ("We divided the work among ourselves.", "हमने काम को आपस में बाँट लिया।"),
                ("I collected information from the internet.", "मैंने इंटरनेट से जानकारी एकत्र की।"),
                ("Please prepare a chart for the display.", "कृपया प्रदर्शन के लिए एक चार्ट तैयार कीजिए।"),
                ("The models were displayed in the hall.", "मॉडल हॉल में प्रदर्शित किए गए।"),
                ("I will finish the presentation slides today.", "मैं आज प्रेजेंटेशन की स्लाइड्स पूरी करूँगा।"),
                ("Ask questions at the end.", "अंत में प्रश्न पूछिए।"),
                ("Great presentation! Well done!", "शानदार प्रेजेंटेशन! बहुत बढ़िया!"),
                ("I learned a lot from this project.", "मैंने इस प्रोजेक्ट से बहुत कुछ सीखा।"),
                ("Teamwork makes the project better.", "टीमवर्क से प्रोजेक्ट बेहतर बनता है।"),
                ("I am proud of our group project.", "मुझे अपने समूह प्रोजेक्ट पर गर्व है।"),
                ("The science fair was a big success.", "विज्ञान मेला बहुत सफल रहा।"),
                ("Presentations build confidence.", "प्रेजेंटेशन आत्मविश्वास बढ़ाते हैं।"),
            ]},
            {"title": "School Friends", "desc": "Talk with school friends", "topic": "School Friends", "sentences": [
                ("Will you play with me at lunch?", "क्या तुम मेरे साथ लंच पर खेलोगे?"),
                ("Let us sit together in class.", "चलो क्लास में साथ बैठते हैं।"),
                ("Can I borrow your pencil?", "क्या मैं तुम्हारा पेंसिल ले सकता हूँ?"),
                ("My best friend is in my class.", "मेरा सबसे अच्छा दोस्त मेरी कक्षा में है।"),
                ("We share our tiffin at lunch.", "हम लंच में अपना टिफिन साझा करते हैं।"),
                ("Do you want to play cricket after school?", "क्या तुम स्कूल के बाद क्रिकेट खेलना चाहोगे?"),
                ("I will wait for you at the gate.", "मैं गेट पर तुम्हारा इंतज़ार करूँगा।"),
                ("Our team won the match!", "हमारी टीम मैच जीत गई!"),
                ("Let us study for the test together.", "चलो टेस्ट के लिए साथ पढ़ते हैं।"),
                ("I like your new bag.", "मुझे तुम्हारा नया बैग पसंद है।"),
                ("Please help me with this question.", "कृपया इस प्रश्न में मेरी मदद करो।"),
                ("We go home together every day.", "हम हर दिन साथ घर जाते हैं।"),
                ("My friend is very funny.", "मेरा दोस्त बहुत मज़ाकिया है।"),
                ("We made a secret club at school.", "हमने स्कूल में एक गुप्त क्लब बनाया।"),
                ("Do not tell anyone my secret.", "किसी को मेरा राज़ मत बताना।"),
                ("I promise I will keep it a secret.", "मैं वादा करता हूँ इसे गुप्त रखूँगा।"),
                ("Let us be partners for the project.", "चलो प्रोजेक्ट के लिए पार्टनर बनते हैं।"),
                ("You are a true friend.", "तुम सच्चे दोस्त हो।"),
                ("We have fun together every day.", "हम हर दिन साथ मज़ा करते हैं।"),
                ("I will miss you in the holidays.", "छुट्टियों में मुझे तुम्हारी याद आएगी।"),
                ("Let us meet during the summer break.", "चलो गर्मी की छुट्टियों में मिलते हैं।"),
                ("My friend helped me when I fell.", "जब मैं गिरा तो मेरे दोस्त ने मेरी मदद की।"),
                ("A good friend is a great gift.", "अच्छा दोस्त एक महान उपहार होता है।"),
                ("School is fun because of friends.", "दोस्तों की वजह से स्कूल मज़ेदार है।"),
                ("Friends make memories for life.", "दोस्त जीवन भर की यादें बनाते हैं।"),
            ]},
            {"title": "Permission & Absence", "desc": "Ask permission and report absence", "topic": "Permission", "sentences": [
                ("May I leave early today?", "क्या मैं आज जल्दी निकल सकता हूँ?"),
                ("I was absent yesterday.", "मैं कल अनुपस्थित था।"),
                ("I had a fever, so I stayed home.", "मुझे बुखार था, इसलिए मैं घर पर रहा।"),
                ("Please grant me leave for two days.", "कृपया मुझे दो दिन की छुट्टी दीजिए।"),
                ("I need to go to the doctor.", "मुझे डॉक्टर के पास जाना है।"),
                ("My mother has written an application.", "मेरी माँ ने एक आवेदन लिखा है।"),
                ("Please sign my leave application.", "कृपया मेरे छुट्टी आवेदन पर हस्ताक्षर कीजिए।"),
                ("I missed the school bus today.", "मैं आज स्कूल बस मिस कर गया।"),
                ("My father dropped me to school.", "मेरे पिता मुझे स्कूल छोड़ गए।"),
                ("I will bring the medical certificate tomorrow.", "मैं कल मेडिकल प्रमाण पत्र लाऊँगा।"),
                ("May I sit next to the window?", "क्या मैं खिड़की के पास बैठ सकता हूँ?"),
                ("Please allow me to go to the library.", "कृपया मुझे पुस्तकालय जाने की अनुमति दीजिए।"),
                ("I am feeling unwell. Can I go home?", "मेरी तबीयत ठीक नहीं है। क्या मैं घर जा सकता हूँ?"),
                ("The teacher allowed me to leave early.", "शिक्षक ने मुझे जल्दी जाने की अनुमति दी।"),
                ("Please inform my parents about this.", "कृपया इसके बारे में मेरे माता-पिता को सूचित करें।"),
                ("I came late because of the traffic.", "मैं ट्रैफिक की वजह से देर से आया।"),
                ("I will not be late again.", "मैं फिर देर नहीं करूँगा।"),
                ("My grandmother is not well.", "मेरी दादी की तबीयत ठीक नहीं है।"),
                ("I need to attend a family function.", "मुझे एक पारिवारिक कार्यक्रम में शामिल होना है।"),
                ("Please mark my attendance.", "कृपया मेरी उपस्थिति दर्ज कीजिए।"),
                ("I have a doctor's appointment at noon.", "मेरा दोपहर में डॉक्टर का अपॉइंटमेंट है।"),
                ("I will complete the missed work tomorrow.", "मैं कल छूटा हुआ काम पूरा करूँगा।"),
                ("Thank you for understanding, teacher.", "समझने के लिए धन्यवाद, शिक्षक जी।"),
                ("Regular attendance is important.", "नियमित उपस्थिति महत्वपूर्ण है।"),
                ("I am sorry for being late.", "देर से आने के लिए मुझे खेद है।"),
            ]},
            {"title": "School Activities", "desc": "Participate in school activities", "topic": "Activities", "sentences": [
                ("The annual day is next month.", "वार्षिक दिवस अगले महीने है।"),
                ("I am participating in the dance.", "मैं नृत्य में भाग ले रहा हूँ।"),
                ("We have a sports day this Friday.", "हमारा खेल दिवस इस शुक्रवार है।"),
                ("I won the running race!", "मैंने दौड़ प्रतियोगिता जीती!"),
                ("The debate competition was exciting.", "वाद-विवाद प्रतियोगिता रोमांचक थी।"),
                ("I gave a speech on Independence Day.", "मैंने स्वतंत्रता दिवस पर भाषण दिया।"),
                ("Our school won the quiz contest.", "हमारे स्कूल ने क्विज़ प्रतियोगिता जीती।"),
                ("I am in the school choir.", "मैं स्कूल गाना मंडली में हूँ।"),
                ("The painting exhibition was beautiful.", "चित्रकला प्रदर्शनी बहुत सुंदर थी।"),
                ("We practice for the play every evening.", "हम हर शाम नाटक का अभ्यास करते हैं।"),
                ("I am the class monitor.", "मैं कक्षा मॉनिटर हूँ।"),
                ("Please maintain discipline in the queue.", "कृपया कतार में अनुशासन बनाए रखें।"),
                ("The sports teacher trained us well.", "खेल शिक्षक ने हमें अच्छी तरह प्रशिक्षित किया।"),
                ("I love the school library.", "मुझे स्कूल पुस्तकालय बहुत पसंद है।"),
                ("We planted trees on Environment Day.", "हमने पर्यावरण दिवस पर पेड़ लगाए।"),
                ("The cultural programme was fantastic.", "सांस्कृतिक कार्यक्रम शानदार था।"),
                ("I got a prize for my essay.", "मुझे अपने निबंध के लिए पुरस्कार मिला।"),
                ("The school trip is to the zoo.", "स्कूल यात्रा चिड़ियाघर की है।"),
                ("We are preparing for the science fair.", "हम विज्ञान मेले की तैयारी कर रहे हैं।"),
                ("I am captain of the football team.", "मैं फुटबॉल टीम का कप्तान हूँ।"),
                ("Participation is more important than winning.", "जीतने से ज्यादा महत्वपूर्ण भागीदारी है।"),
                ("The assembly starts at 8 AM.", "प्रार्थना सभा सुबह 8 बजे शुरू होती है।"),
                ("We sang the national anthem.", "हमने राष्ट्रगान गाया।"),
                ("School activities teach us many skills.", "स्कूल गतिविधियाँ हमें कई कौशल सिखाती हैं।"),
                ("I enjoy every school activity.", "मैं हर स्कूल गतिविधि का आनंद लेता हूँ।"),
            ]},
            {"title": "Study Skills", "desc": "Learn how to study better", "topic": "Study Skills", "sentences": [
                ("Make a timetable for your studies.", "अपनी पढ़ाई के लिए समय सारणी बनाइए।"),
                ("Study in a quiet place.", "शांत जगह पर पढ़ाई कीजिए।"),
                ("Take short breaks while studying.", "पढ़ाई के दौरान छोटे ब्रेक लीजिए।"),
                ("Revise what you learned every day.", "रोज़ जो सीखा है उसे दोहराइए।"),
                ("Write notes in your own words.", "अपने शब्दों में नोट्स लिखिए।"),
                ("Ask questions when you do not understand.", "जब समझ न आए तो प्रश्न पूछिए।"),
                ("Practice previous year papers.", "पिछले वर्षों के प्रश्न पत्रों का अभ्यास कीजिए।"),
                ("Study the difficult subject first.", "पहले कठिन विषय की पढ़ाई कीजिए।"),
                ("Use diagrams to understand better.", "बेहतर समझ के लिए चित्रों का उपयोग कीजिए।"),
                ("Group study can be very helpful.", "समूह अध्ययन बहुत सहायक हो सकता है।"),
                ("I make flashcards for vocabulary.", "मैं शब्दावली के लिए फ्लैशकार्ड बनाता हूँ।"),
                ("Sleep well before the exam.", "परीक्षा से पहले अच्छी नींद लीजिए।"),
                ("Eat healthy food while studying.", "पढ़ाई के दौरान स्वस्थ भोजन खाइए।"),
                ("Do not study for very long hours.", "बहुत लंबे समय तक मत पढ़िए।"),
                ("I set daily goals for my studies.", "मैं अपनी पढ़ाई के लिए दैनिक लक्ष्य निर्धारित करता हूँ।"),
                ("Consistency is the key to success.", "निरंतरता ही सफलता की कुंजी है।"),
                ("I use the library to study.", "मैं पढ़ाई के लिए पुस्तकालय का उपयोग करता हूँ।"),
                ("Explain the topic to a friend.", "विषय को एक दोस्त को समझाइए।"),
                ("Mark the important points.", "महत्वपूर्ण बिंदुओं को चिह्नित कीजिए।"),
                ("I record my lessons and listen again.", "मैं अपने पाठ रिकॉर्ड करता हूँ और फिर सुनता हूँ।"),
                ("Stay positive and keep learning.", "सकारात्मक रहिए और सीखते रहिए।"),
                ("Good study habits make learning easy.", "अच्छी अध्ययन आदतें सीखना आसान बनाती हैं।"),
                ("I plan my week every Sunday.", "मैं हर रविवार अपने सप्ताह की योजना बनाता हूँ।"),
                ("Never give up on difficult subjects.", "कठिन विषयों पर कभी हार न मानें।"),
                ("Every student can succeed with effort.", "प्रयास से हर विद्यार्थी सफल हो सकता है।"),
            ]},
            {"title": "School Speaking", "desc": "Speak confidently at school", "topic": "Speaking", "sentences": [
                ("I want to improve my spoken English.", "मैं अपनी बोली जाने वाली अंग्रेज़ी सुधारना चाहता हूँ।"),
                ("I speak English with my friends.", "मैं अपने दोस्तों के साथ अंग्रेज़ी बोलता हूँ।"),
                ("Please correct me if I make mistakes.", "अगर मैं गलती करूँ तो कृपया मुझे सुधारिए।"),
                ("I practice English every day.", "मैं हर दिन अंग्रेज़ी का अभ्यास करता हूँ।"),
                ("Speaking English is fun.", "अंग्रेज़ी बोलना मज़ेदार है।"),
                ("I am not afraid to speak now.", "मुझे अब बोलने में डर नहीं लगता।"),
                ("I can introduce myself in English.", "मैं अंग्रेज़ी में अपना परिचय दे सकता हूँ।"),
                ("My teacher encourages me to speak.", "मेरे शिक्षक मुझे बोलने के लिए प्रोत्साहित करते हैं।"),
                ("I learn new words every day.", "मैं हर दिन नए शब्द सीखता हूँ।"),
                ("I read English story books.", "मैं अंग्रेज़ी की कहानी की किताबें पढ़ता हूँ।"),
                ("English is an international language.", "अंग्रेज़ी एक अंतरराष्ट्रीय भाषा है।"),
                ("I will speak English at the debate.", "मैं वाद-विवाद में अंग्रेज़ी बोलूँगा।"),
                ("Practice speaking in front of the mirror.", "आईने के सामने बोलने का अभ्यास कीजिए।"),
                ("I am improving day by day.", "मैं दिन-ब-दिन सुधार कर रहा हूँ।"),
                ("Do not worry about making mistakes.", "गलतियाँ करने की चिंता मत कीजिए।"),
                ("I asked the teacher a question in English.", "मैंने शिक्षक से अंग्रेज़ी में प्रश्न पूछा।"),
                ("I use English in my daily routine.", "मैं अपनी दैनिक दिनचर्या में अंग्रेज़ी का उपयोग करता हूँ।"),
                ("My vocabulary is growing.", "मेरी शब्दावली बढ़ रही है।"),
                ("I will speak English with confidence.", "मैं आत्मविश्वास के साथ अंग्रेज़ी बोलूँगा।"),
                ("The more I practice, the better I get.", "जितना अधिक अभ्यास करता हूँ, उतना बेहतर होता हूँ।"),
                ("I am not scared of new words.", "मुझे नए शब्दों से डर नहीं लगता।"),
                ("Speaking clearly is important.", "स्पष्ट बोलना महत्वपूर्ण है।"),
                ("I talk to myself in English.", "मैं खुद से अंग्रेज़ी में बात करता हूँ।"),
                ("Every mistake teaches me something.", "हर गलती मुझे कुछ सिखाती है।"),
                ("I am becoming a confident speaker!", "मैं एक आत्मविश्वासी वक्ता बन रहा हूँ!"),
                ("My favourite subject is science.", "मेरा पसंदीदा विषय विज्ञान है।"),
                ("I am good at mathematics.", "मैं गणित में अच्छा हूँ।"),
                ("English class is my favourite.", "अंग्रेज़ी की कक्षा मेरी पसंदीदा है।"),
                ("History is very interesting.", "इतिहास बहुत रोचक है।"),
                ("I do not like geography much.", "मुझे भूगोल ज्यादा पसंद नहीं है।"),
                ("We have six periods every day.", "हमारी हर दिन छह कक्षाएँ होती हैं।"),
                ("The physics teacher explains very well.", "भौतिकी के शिक्षक बहुत अच्छे से समझाते हैं।"),
                ("I have art class on Wednesdays.", "बुधवार को मेरी कला की कक्षा है।"),
                ("We learn about plants in biology.", "हम जीव विज्ञान में पौधों के बारे में सीखते हैं।"),
                ("My handwriting is neat.", "मेरी लिखावट साफ है।"),
                ("I scored well in chemistry.", "मुझे रसायन विज्ञान में अच्छे अंक मिले।"),
                ("The computer class is very useful.", "कंप्यूटर कक्षा बहुत उपयोगी है।"),
                ("We have a maths quiz tomorrow.", "कल हमारी गणित की क्विज़ है।"),
                ("I am learning French as a second language.", "मैं दूसरी भाषा के रूप में फ्रेंच सीख रहा हूँ।"),
                ("The literature class is enjoyable.", "साहित्य की कक्षा आनंददायक है।"),
                ("I need to work on my English grammar.", "मुझे अपने अंग्रेज़ी व्याकरण पर काम करना है।"),
                ("We did an experiment in the lab.", "हमने प्रयोगशाला में एक प्रयोग किया।"),
                ("The music class is on Friday.", "संगीत की कक्षा शुक्रवार को है।"),
                ("I understand the lesson better now.", "मुझे अब पाठ बेहतर समझ आ रहा है।"),
                ("Our teacher gives us interesting homework.", "हमारे शिक्षक हमें दिलचस्प होमवर्क देते हैं।"),
                ("I study all subjects equally.", "मैं सभी विषयों को समान रूप से पढ़ता हूँ।"),
                ("The exam has five subjects.", "परीक्षा में पाँच विषय हैं।"),
                ("I like solving puzzles in maths.", "मुझे गणित में पहेलियाँ हल करना पसंद है।"),
                ("Every subject has its own importance.", "हर विषय का अपना महत्व होता है।"),
                ("I am curious to learn new things.", "मैं नई चीज़ें सीखने के लिए उत्सुक हूँ।"),
            ]},
            {"title": "School Day", "desc": "Describe a school day", "topic": "School Day", "sentences": [
                ("I wake up at 6:30 for school.", "मैं स्कूल के लिए 6:30 बजे उठता हूँ।"),
                ("I wear my uniform and go to school.", "मैं अपनी वर्दी पहनकर स्कूल जाता हूँ।"),
                ("The school bus arrives at 7:45.", "स्कूल बस 7:45 पर आती है।"),
                ("My first class starts at 8 AM.", "मेरी पहली कक्षा सुबह 8 बजे शुरू होती है।"),
                ("We have a short break at 10.", "हमारा 10 बजे छोटा ब्रेक है।"),
                ("I eat my lunch at noon.", "मैं दोपहर में अपना खाना खाता हूँ।"),
                ("The school ends at 2:30 PM.", "स्कूल दोपहर 2:30 बजे खत्म होता है।"),
                ("I reach home by 3 PM.", "मैं 3 बजे तक घर पहुँच जाता हूँ।"),
                ("I do my homework after a short rest.", "थोड़े आराम के बाद मैं होमवर्क करता हूँ।"),
                ("I play with my friends in the evening.", "मैं शाम को अपने दोस्तों के साथ खेलता हूँ।"),
                ("I study for an hour before dinner.", "मैं खाने से पहले एक घंटा पढ़ता हूँ।"),
                ("My day at school is always busy.", "स्कूल में मेरा दिन हमेशा व्यस्त रहता है।"),
                ("I enjoy the games period the most.", "मुझे खेल की अवधि सबसे ज्यादा पसंद है।"),
                ("We have assembly every morning.", "हमारी हर सुबह प्रार्थना सभा होती है。"),
                ("The teacher checks our homework daily.", "शिक्षक हमारा होमवर्क रोज़ जाँचते हैं।"),
                ("I like the school canteen.", "मुझे स्कूल कैंटीन पसंद है।"),
                ("We go to the playground for sports.", "हम खेल के लिए मैदान जाते हैं।"),
                ("I pack my bag the night before.", "मैं रात को अपना बैग पैक करता हूँ।"),
                ("The school day passes very quickly.", "स्कूल का दिन बहुत जल्दी बीत जाता है।"),
                ("I learn something new every day at school.", "मैं स्कूल में हर दिन कुछ नया सीखता हूँ।"),
                ("My mother packs a tasty lunch for me.", "मेरी माँ मेरे लिए स्वादिष्ट लंच पैक करती हैं।"),
                ("I wait for the bus with my friends.", "मैं अपने दोस्तों के साथ बस का इंतज़ार करता हूँ।"),
                ("The teachers are very kind.", "शिक्षक बहुत दयालु हैं।"),
                ("I love going to school.", "मुझे स्कूल जाना बहुत पसंद है।"),
                ("A school day is a learning day.", "स्कूल का दिन सीखने का दिन होता है।"),
            ]},
            {"title": "Asking Teacher", "desc": "Ask questions to the teacher", "topic": "Asking Teacher", "sentences": [
                ("Teacher, I have a question.", "शिक्षक जी, मुझे एक प्रश्न है।"),
                ("Can you explain this again, please?", "क्या आप इसे फिर से समझा सकते हैं, कृपया?"),
                ("What is the meaning of this word?", "इस शब्द का क्या अर्थ है?"),
                ("How do you solve this problem?", "आप इस समस्या को कैसे हल करते हैं?"),
                ("Why is the sky blue?", "आसमान नीला क्यों है?"),
                ("Is this answer correct?", "क्या यह उत्तर सही है?"),
                ("When is the next test?", "अगला टेस्ट कब है?"),
                ("What will come in the exam?", "परीक्षा में क्या आएगा?"),
                ("Can we have an extra period of games?", "क्या हमें खेल की एक अतिरिक्त अवधि मिल सकती है?"),
                ("I did not understand the homework.", "मुझे होमवर्क समझ नहीं आया।"),
                ("Please give us some more examples.", "कृपया हमें कुछ और उदाहरण दीजिए।"),
                ("What is the correct spelling?", "सही वर्तनी क्या है?"),
                ("Can you show me how to do this experiment?", "क्या आप मुझे दिखा सकते हैं कि यह प्रयोग कैसे करना है?"),
                ("How many marks is this question worth?", "इस प्रश्न के कितने अंक हैं?"),
                ("Where can I find more information?", "मुझे और जानकारी कहाँ मिल सकती है?"),
                ("Can we watch an educational video?", "क्या हम एक शैक्षिक वीडियो देख सकते हैं?"),
                ("What is the homework for tomorrow?", "कल का होमवर्क क्या है?"),
                ("Please help me with this paragraph.", "कृपया इस अनुच्छेद में मेरी मदद कीजिए।"),
                ("I have finished my work.", "मैंने अपना काम पूरा कर लिया है।"),
                ("Can I help the teacher distribute papers?", "क्या मैं शिक्षक को कागज़ बाँटने में मदद कर सकता हूँ?"),
                ("Thank you for explaining, teacher.", "समझाने के लिए धन्यवाद, शिक्षक जी।"),
                ("I understand now.", "मुझे अब समझ आ गया।"),
                ("Can you repeat the question?", "क्या आप प्रश्न दोहरा सकते हैं?"),
                ("Asking questions helps us learn.", "प्रश्न पूछने से हमें सीखने में मदद मिलती है।"),
                ("A good student always asks questions.", "एक अच्छा विद्यार्थी हमेशा प्रश्न पूछता है।"),
            ]},
            {"title": "After School", "desc": "After school activities", "topic": "After School", "sentences": [
                ("I go for tuition after school.", "मैं स्कूल के बाद ट्यूशन जाता हूँ।"),
                ("I play football in the evening.", "मैं शाम को फुटबॉल खेलता हूँ।"),
                ("I have drawing class after school.", "स्कूल के बाद मेरी ड्रॉइंग क्लास है।"),
                ("I help my mother at home.", "मैं घर पर अपनी माँ की मदद करता हूँ।"),
                ("I do my homework first, then I play.", "मैं पहले होमवर्क करता हूँ, फिर खेलता हूँ।"),
                ("I go to the park with my friends.", "मैं अपने दोस्तों के साथ पार्क जाता हूँ।"),
                ("I watch cartoons after school.", "मैं स्कूल के बाद कार्टून देखता हूँ।"),
                ("I read story books in the evening.", "मैं शाम को कहानी की किताबें पढ़ता हूँ।"),
                ("I practice the piano every day.", "मैं हर दिन पियानो का अभ्यास करता हूँ।"),
                ("I go for swimming classes.", "मैं तैराकी की कक्षाओं में जाता हूँ।"),
                ("I visit my grandmother after school.", "मैं स्कूल के बाद अपनी दादी से मिलने जाता हूँ।"),
                ("We play hide and seek in the evening.", "हम शाम को लुका-छिपी खेलते हैं।"),
                ("I like to draw and colour.", "मुझे चित्र बनाना और रंग भरना पसंद है।"),
                ("I help in watering the garden.", "मैं बगीचे में पानी देने में मदद करता हूँ।"),
                ("I do not waste my time after school.", "मैं स्कूल के बाद अपना समय बर्बाद नहीं करता।"),
                ("I play chess with my father.", "मैं अपने पिता के साथ शतरंज खेलता हूँ।"),
                ("I learn to cook simple dishes.", "मैं साधारण व्यंजन बनाना सीखता हूँ।"),
                ("My evening routine is fixed.", "मेरी शाम की दिनचर्या निश्चित है।"),
                ("I talk to my friends on the phone.", "मैं अपने दोस्तों से फोन पर बात करता हूँ।"),
                ("I collect stamps as a hobby.", "मैं शौक के रूप में डाक टिकट इकट्ठा करता हूँ।"),
                ("We have dinner together at 8.", "हम 8 बजे साथ मिलकर खाना खाते हैं।"),
                ("I go to bed early on school nights.", "मैं स्कूल वाली रातों में जल्दी सो जाता हूँ।"),
                ("I prepare my bag for the next day.", "मैं अगले दिन के लिए अपना बैग तैयार करता हूँ।"),
                ("Balancing studies and play is important.", "पढ़ाई और खेल में संतुलन रखना महत्वपूर्ण है।"),
                ("My day ends with a good sleep.", "मेरा दिन अच्छी नींद के साथ खत्म होता है।"),
            ]},
        ],
    }
