def get_interview_banks():
    return {
        "course_id": "interview",
        "title": "Interview English",
        "desc": "English for job interviews - self introduction, common questions, and confident answers.",
        "short": "Clear your interview with confidence",
        "icon": "💼",
        "color": "accent",
        "difficulty": "Intermediate",
        "audience": ["Interview Candidates", "Job Seekers", "Students"],
        "price": "₹299",
        "lessons": [
            {"title": "Self Introduction", "desc": "Introduce yourself confidently", "topic": "Self Introduction", "sentences": [
                ("Good morning, sir. Thank you for giving me this opportunity.", "सुप्रभात, महोदय। मुझे यह अवसर देने के लिए धन्यवाद।"),
                ("My name is Vikram Singh.", "मेरा नाम विक्रम सिंह है।"),
                ("I am from Jaipur, Rajasthan.", "मैं जयपुर, राजस्थान से हूँ।"),
                ("I belong to a middle-class family.", "मैं एक मध्यम वर्गीय परिवार से हूँ।"),
                ("I completed my graduation in Commerce.", "मैंने वाणिज्य में स्नातक पूरा किया।"),
                ("I have done my MBA in Marketing.", "मैंने मार्केटिंग में एमबीए किया है।"),
                ("I am a hard-working and honest person.", "मैं एक मेहनती और ईमानदार व्यक्ति हूँ।"),
                ("I am very interested in this role.", "मुझे इस भूमिका में बहुत रुचि है।"),
                ("I have good communication skills.", "मेरे पास अच्छे संचार कौशल हैं।"),
                ("I am a quick learner.", "मैं जल्दी सीखने वाला व्यक्ति हूँ।"),
                ("I enjoy working in a team.", "मुझे एक टीम में काम करना पसंद है।"),
                ("I am punctual and dedicated.", "मैं समय का पाबंद और समर्पित हूँ।"),
                ("My short-term goal is to learn new skills.", "मेरा अल्पकालिक लक्ष्य नए कौशल सीखना है।"),
                ("My long-term goal is to grow with the company.", "मेरा दीर्घकालिक लक्ष्य कंपनी के साथ बढ़ना है।"),
                ("I am excited to be here today.", "मुझे आज यहाँ आकर उत्साहित हूँ।"),
                ("I have a positive attitude towards work.", "काम के प्रति मेरा दृष्टिकोण सकारात्मक है।"),
                ("I like to take up new challenges.", "मुझे नई चुनौतियाँ लेना पसंद है।"),
                ("My family has always supported me.", "मेरे परिवार ने हमेशा मेरा समर्थन किया है।"),
                ("I am confident about my abilities.", "मुझे अपनी क्षमताओं पर भरोसा है।"),
                ("I am ready to work hard for the company.", "मैं कंपनी के लिए कड़ी मेहनत करने को तैयार हूँ।"),
                ("I believe in continuous learning.", "मैं निरंतर सीखने में विश्वास करता हूँ।"),
                ("Thank you for this opportunity to introduce myself.", "मुझे अपना परिचय देने का अवसर देने के लिए धन्यवाद।"),
                ("I hope to be a valuable member of your team.", "मुझे उम्मीद है कि मैं आपकी टीम का मूल्यवान सदस्य बनूँगा।"),
                ("I am eager to start this journey with your company.", "मैं आपकी कंपनी के साथ यह यात्रा शुरू करने को उत्सुक हूँ।"),
                ("That is all about me. Thank you!", "मेरे बारे में बस इतना ही। धन्यवाद!"),
            ]},
            {"title": "Tell Me About Yourself", "desc": "Answer the classic first question", "topic": "About Yourself", "sentences": [
                ("Tell me about yourself.", "अपने बारे में बताइए।"),
                ("I will tell you about my background and skills.", "मैं आपको अपनी पृष्ठभूमि और कौशल के बारे में बताऊँगा।"),
                ("I grew up in a small town in Uttar Pradesh.", "मैं उत्तर प्रदेश के एक छोटे शहर में बड़ा हुआ।"),
                ("I studied computer science in college.", "मैंने कॉलेज में कंप्यूटर विज्ञान पढ़ा।"),
                ("I started my career as a junior analyst.", "मैंने अपना करियर एक जूनियर विश्लेषक के रूप में शुरू किया।"),
                ("I have three years of experience in this field.", "मुझे इस क्षेत्र में तीन साल का अनुभव है।"),
                ("I enjoy solving complex problems.", "मुझे जटिल समस्याओं को हल करना पसंद है।"),
                ("My strengths include teamwork and leadership.", "मेरी ताकत में टीमवर्क और नेतृत्व शामिल हैं।"),
                ("I am passionate about my work.", "मैं अपने काम के प्रति जुनूनी हूँ।"),
                ("I like to finish my tasks on time.", "मुझे अपने कार्य समय पर पूरे करना पसंद है।"),
                ("I am looking for a role where I can grow.", "मैं एक ऐसी भूमिका की तलाश में हूँ जहाँ मैं बढ़ सकूँ।"),
                ("I adapt quickly to new environments.", "मैं नए वातावरण में जल्दी ढल जाता हूँ।"),
                ("I have worked on many successful projects.", "मैंने कई सफल परियोजनाओं पर काम किया है।"),
                ("I value honesty and hard work.", "मैं ईमानदारी और कड़ी मेहनत को महत्व देता हूँ।"),
                ("In my free time, I like reading and travelling.", "खाली समय में मुझे पढ़ना और यात्रा करना पसंद है।"),
                ("I am always open to learning new things.", "मैं हमेशा नई चीज़ें सीखने के लिए तैयार रहता हूँ।"),
                ("I can handle pressure very well.", "मैं दबाव को बहुत अच्छे से संभाल सकता हूँ।"),
                ("I am detail-oriented and organized.", "मैं विवरणों पर ध्यान देने वाला और संगठित हूँ।"),
                ("I have a clear vision for my career.", "मेरे करियर के लिए मेरी एक स्पष्ट दृष्टि है।"),
                ("I believe in giving my hundred percent.", "मैं अपना सौ प्रतिशत देने में विश्वास करता हूँ।"),
                ("I am grateful for my journey so far.", "मैं अपनी अब तक की यात्रा के लिए आभारी हूँ।"),
                ("I am confident I can contribute to your company.", "मुझे विश्वास है कि मैं आपकी कंपनी में योगदान दे सकता हूँ।"),
                ("To sum up, I am a motivated professional.", "संक्षेप में, मैं एक प्रेरित पेशेवर हूँ।"),
                ("I look forward to working with your team.", "मैं आपकी टीम के साथ काम करने के लिए उत्सुक हूँ।"),
                ("That gives you an idea about me.", "इससे आपको मेरे बारे में अंदाज़ा हो गया होगा।"),
            ]},
            {"title": "Education", "desc": "Talk about your education", "topic": "Education", "sentences": [
                ("I completed my schooling from Delhi Public School.", "मैंने अपनी स्कूली शिक्षा दिल्ली पब्लिक स्कूल से पूरी की।"),
                ("I scored 85 percent in my board exams.", "मुझे बोर्ड परीक्षाओं में 85 प्रतिशत अंक मिले।"),
                ("I studied science in class 12.", "मैंने बारहवीं में विज्ञान पढ़ा।"),
                ("I graduated in 2021.", "मैंने 2021 में स्नातक किया।"),
                ("My degree is in Business Administration.", "मेरी डिग्री व्यवसाय प्रशासन में है।"),
                ("I did my masters in English literature.", "मैंने अंग्रेज़ी साहित्य में स्नातकोत्तर किया।"),
                ("I was a good student in college.", "मैं कॉलेज में एक अच्छा छात्र था।"),
                ("I received a scholarship for my studies.", "मुझे अपनी पढ़ाई के लिए छात्रवृत्ति मिली।"),
                ("I attended workshops on communication skills.", "मैंने संचार कौशल पर कार्यशालाओं में भाग लिया।"),
                ("My favourite subject was mathematics.", "मेरा पसंदीदा विषय गणित था।"),
                ("I completed a certification course in digital marketing.", "मैंने डिजिटल मार्केटिंग में एक प्रमाणन पाठ्यक्रम पूरा किया।"),
                ("I am currently pursuing an online MBA.", "मैं वर्तमान में ऑनलाइन एमबीए कर रहा हूँ।"),
                ("Education is the foundation of my career.", "शिक्षा मेरे करियर की नींव है।"),
                ("I learned teamwork during college projects.", "मैंने कॉलेज परियोजनाओं के दौरान टीमवर्क सीखा।"),
                ("I was the class representative in my final year.", "मैं अपने अंतिम वर्ष में कक्षा प्रतिनिधि था।"),
                ("I have a strong academic background.", "मेरी शैक्षणिक पृष्ठभूमि मज़बूत है।"),
                ("I always try to learn new skills.", "मैं हमेशा नए कौशल सीखने की कोशिश करता हूँ।"),
                ("I completed my internship at a reputed firm.", "मैंने एक प्रतिष्ठित फर्म में इंटर्नशिप पूरी की।"),
                ("My education taught me discipline.", "मेरी शिक्षा ने मुझे अनुशासन सिखाया।"),
                ("I topped my university in the final year.", "मैंने अंतिम वर्ष में अपने विश्वविद्यालय में टॉप किया।"),
                ("I have certificates in many computer courses.", "मेरे पास कई कंप्यूटर पाठ्यक्रमों के प्रमाण पत्र हैं।"),
                ("Continuous education keeps me updated.", "निरंतर शिक्षा मुझे अपडेट रखती है।"),
                ("I am ready to learn new things for this job.", "मैं इस नौकरी के लिए नई चीज़ें सीखने को तैयार हूँ।"),
                ("My teachers were my biggest inspiration.", "मेरे शिक्षक मेरी सबसे बड़ी प्रेरणा थे।"),
                ("Education opens many doors.", "शिक्षा कई दरवाज़े खोलती है।"),
            ]},
            {"title": "Work Experience", "desc": "Talk about your experience", "topic": "Experience", "sentences": [
                ("I have four years of work experience.", "मेरे पास चार साल का कार्य अनुभव है।"),
                ("I worked as a customer service executive.", "मैंने एक ग्राहक सेवा कार्यकारी के रूप में काम किया।"),
                ("I was responsible for handling client queries.", "मैं ग्राहकों के सवालों को संभालने के लिए जिम्मेदार था।"),
                ("I managed a team of five people.", "मैंने पाँच लोगों की एक टीम का प्रबंधन किया।"),
                ("I worked on several important projects.", "मैंने कई महत्वपूर्ण परियोजनाओं पर काम किया।"),
                ("I increased sales by twenty percent.", "मैंने बिक्री में बीस प्रतिशत की वृद्धि की।"),
                ("I received the best employee award.", "मुझे सर्वश्रेष्ठ कर्मचारी पुरस्कार मिला।"),
                ("My previous company was in Mumbai.", "मेरी पिछली कंपनी मुंबई में थी।"),
                ("I worked there for three years.", "मैंने वहाँ तीन साल काम किया।"),
                ("I handled the accounts department.", "मैंने लेखा विभाग संभाला।"),
                ("I learned a lot from my previous job.", "मैंने अपनी पिछली नौकरी से बहुत कुछ सीखा।"),
                ("I am leaving my job for better opportunities.", "मैं बेहतर अवसरों के लिए अपनी नौकरी छोड़ रहा हूँ।"),
                ("I was promoted twice in my last job.", "मुझे अपनी पिछली नौकरी में दो बार पदोन्नति मिली।"),
                ("I have experience in sales and marketing.", "मुझे बिक्री और विपणन में अनुभव है।"),
                ("I trained new employees in my team.", "मैंने अपनी टीम में नए कर्मचारियों को प्रशिक्षित किया।"),
                ("My colleagues appreciated my work.", "मेरे सहकर्मियों ने मेरे काम की सराहना की।"),
                ("I am skilled in Microsoft Office and Excel.", "मैं माइक्रोसॉफ्ट ऑफिस और एक्सेल में कुशल हूँ।"),
                ("I worked with international clients.", "मैंने अंतरराष्ट्रीय ग्राहकों के साथ काम किया।"),
                ("I have a good track record of performance.", "मेरा प्रदर्शन का अच्छा रिकॉर्ड है।"),
                ("I enjoy taking ownership of my work.", "मुझे अपने काम की जिम्मेदारी लेना पसंद है।"),
                ("I have handled difficult situations calmly.", "मैंने कठिन परिस्थितियों को शांति से संभाला है।"),
                ("My experience matches this job perfectly.", "मेरा अनुभव इस नौकरी से बिल्कुल मेल खाता है।"),
                ("I am proud of my professional achievements.", "मुझे अपनी पेशेवर उपलब्धियों पर गर्व है।"),
                ("I am looking for new challenges now.", "मैं अब नई चुनौतियों की तलाश में हूँ।"),
                ("Experience teaches us what books cannot.", "अनुभव हमें वह सिखाता है जो किताबें नहीं सिखा सकतीं।"),
            ]},
            {"title": "Strengths & Weaknesses", "desc": "Talk about strengths and weaknesses", "topic": "Strengths", "sentences": [
                ("My greatest strength is my dedication.", "मेरी सबसे बड़ी ताकत मेरा समर्पण है।"),
                ("I am a very organized person.", "मैं एक बहुत संगठित व्यक्ति हूँ।"),
                ("I am good at solving problems.", "मैं समस्याओं को हल करने में अच्छा हूँ।"),
                ("I learn new things very quickly.", "मैं नई चीज़ें बहुत जल्दी सीखता हूँ।"),
                ("I work well under pressure.", "मैं दबाव में अच्छा काम करता हूँ।"),
                ("I am a team player.", "मैं एक टीम प्लेयर हूँ।"),
                ("I am honest and trustworthy.", "मैं ईमानदार और भरोसेमंद हूँ।"),
                ("I have strong leadership qualities.", "मेरे पास मज़बूत नेतृत्व गुण हैं।"),
                ("My communication skills are very good.", "मेरे संचार कौशल बहुत अच्छे हैं।"),
                ("I am flexible and adaptable.", "मैं लचीला और अनुकूलनीय हूँ।"),
                ("My weakness is that I am a perfectionist.", "मेरी कमज़ोरी यह है कि मैं पूर्णतावादी हूँ।"),
                ("Sometimes I take on too much work.", "कभी-कभी मैं बहुत ज़्यादा काम ले लेता हूँ।"),
                ("I am working on my public speaking.", "मैं अपने सार्वजनिक भाषण पर काम कर रहा हूँ।"),
                ("I can be impatient at times.", "मैं कभी-कभी अधीर हो सकता हूँ।"),
                ("I am trying to improve my delegation skills.", "मैं अपने प्रत्यायोजन कौशल में सुधार करने की कोशिश कर रहा हूँ।"),
                ("I ask for help when I need it.", "जब जरूरत होती है तो मैं मदद माँगता हूँ।"),
                ("I am working on being more confident.", "मैं अधिक आत्मविश्वासी बनने पर काम कर रहा हूँ।"),
                ("I turn my weaknesses into learning points.", "मैं अपनी कमज़ोरियों को सीखने के बिंदुओं में बदलता हूँ।"),
                ("I am always improving myself.", "मैं हमेशा खुद में सुधार करता रहता हूँ।"),
                ("Self-awareness is one of my strengths.", "आत्म-जागरूकता मेरी ताकतों में से एक है।"),
                ("I take feedback positively.", "मैं प्रतिक्रिया को सकारात्मक रूप से लेता हूँ।"),
                ("I never give up easily.", "मैं आसानी से हार नहीं मानता।"),
                ("I am disciplined in my daily routine.", "मैं अपनी दैनिक दिनचर्या में अनुशासित हूँ।"),
                ("Knowing your weaknesses helps you grow.", "अपनी कमज़ोरियों को जानना आपको बढ़ने में मदद करता है।"),
                ("I am committed to personal growth.", "मैं व्यक्तिगत विकास के लिए प्रतिबद्ध हूँ।"),
            ]},
            {"title": "Why This Company?", "desc": "Explain why you want this job", "topic": "Why Company", "sentences": [
                ("I want to work for your company because of its reputation.", "मैं आपकी कंपनी के लिए इसकी प्रतिष्ठा के कारण काम करना चाहता हूँ।"),
                ("Your company is a leader in this industry.", "आपकी कंपनी इस उद्योग में अग्रणी है।"),
                ("I admire your company's values.", "मैं आपकी कंपनी के मूल्यों की प्रशंसा करता हूँ।"),
                ("This role matches my skills perfectly.", "यह भूमिका मेरे कौशल से बिल्कुल मेल खाती है।"),
                ("I am excited about your company's growth.", "मैं आपकी कंपनी के विकास को लेकर उत्साहित हूँ।"),
                ("Your company offers great learning opportunities.", "आपकी कंपनी बेहतरीन सीखने के अवसर देती है।"),
                ("I researched your company and was impressed.", "मैंने आपकी कंपनी पर शोध किया और प्रभावित हुआ।"),
                ("I believe my experience will add value here.", "मुझे विश्वास है मेरा अनुभव यहाँ मूल्य जोड़ेगा।"),
                ("I want to grow with a dynamic company.", "मैं एक गतिशील कंपनी के साथ बढ़ना चाहता हूँ।"),
                ("Your work culture appeals to me.", "आपकी कार्य संस्कृति मुझे आकर्षित करती है।"),
                ("I like the way your company innovates.", "मुझे आपकी कंपनी के नवाचार का तरीका पसंद है।"),
                ("This position is a perfect fit for my career goals.", "यह पद मेरे करियर लक्ष्यों के लिए एकदम सही है।"),
                ("I am passionate about the work your company does.", "मैं उस काम के प्रति भावुक हूँ जो आपकी कंपनी करती है।"),
                ("Your clients speak highly of your services.", "आपके ग्राहक आपकी सेवाओं की बहुत प्रशंसा करते हैं।"),
                ("I want to be part of your success story.", "मैं आपकी सफलता की कहानी का हिस्सा बनना चाहता हूँ।"),
                ("I can contribute to your ongoing projects.", "मैं आपकी चल रही परियोजनाओं में योगदान दे सकता हूँ।"),
                ("Your company cares about employee growth.", "आपकी कंपनी कर्मचारी विकास की परवाह करती है।"),
                ("I share the same vision as your company.", "मैं आपकी कंपनी के समान दृष्टिकोण साझा करता हूँ।"),
                ("I am ready to give my best to this role.", "मैं इस भूमिका के लिए अपना सर्वश्रेष्ठ देने को तैयार हूँ।"),
                ("The job responsibilities excite me.", "नौकरी की जिम्मेदारियाँ मुझे उत्साहित करती हैं।"),
                ("I see a long-term future here.", "मैं यहाँ एक दीर्घकालिक भविष्य देखता हूँ।"),
                ("Your company respects its employees.", "आपकी कंपनी अपने कर्मचारियों का सम्मान करती है।"),
                ("I would be proud to work here.", "मुझे यहाँ काम करने पर गर्व होगा।"),
                ("I am looking for stability and growth.", "मैं स्थिरता और विकास की तलाश में हूँ।"),
                ("This is the right place for my skills.", "यह मेरे कौशल के लिए सही जगह है।"),
            ]},
            {"title": "Salary & Expectations", "desc": "Discuss salary expectations", "topic": "Salary", "sentences": [
                ("What is your expected salary?", "आपकी अपेक्षित वेतन क्या है?"),
                ("I am expecting around six lakhs per annum.", "मैं लगभग छह लाख प्रति वर्ष की उम्मीद कर रहा हूँ।"),
                ("I am flexible about the salary.", "मैं वेतन के बारे में लचीला हूँ।"),
                ("What is the salary range for this position?", "इस पद के लिए वेतन सीमा क्या है?"),
                ("I am open to negotiation.", "मैं बातचीत के लिए तैयार हूँ।"),
                ("My current salary is five lakhs per annum.", "मेरा वर्तमान वेतन पाँच लाख प्रति वर्ष है।"),
                ("I would like a salary review after six months.", "मैं छह महीने बाद वेतन समीक्षा चाहूँगा।"),
                ("What benefits does the company provide?", "कंपनी क्या लाभ प्रदान करती है?"),
                ("Is there a performance bonus?", "क्या कोई प्रदर्शन बोनस है?"),
                ("I am more focused on growth than salary.", "मैं वेतन से ज्यादा विकास पर ध्यान केंद्रित कर रहा हूँ।"),
                ("The salary should match my experience.", "वेतन मेरे अनुभव के अनुरूप होना चाहिए।"),
                ("I will accept the market rate.", "मैं बाजार दर स्वीकार करूँगा।"),
                ("Please share the complete compensation details.", "कृपया पूरा मुआवजा विवरण साझा करें।"),
                ("Does the company provide health insurance?", "क्या कंपनी स्वास्थ्य बीमा प्रदान करती है?"),
                ("I have considered my expenses and expectations.", "मैंने अपने खर्चों और अपेक्षाओं पर विचार किया है।"),
                ("I am willing to start with a reasonable package.", "मैं उचित पैकेज के साथ शुरू करने को तैयार हूँ।"),
                ("What is the appraisal cycle?", "मूल्यांकन चक्र क्या है?"),
                ("I expect a fair and competitive salary.", "मैं एक उचित और प्रतिस्पर्धी वेतन की उम्मीद करता हूँ।"),
                ("I am confident we can reach an agreement.", "मुझे विश्वास है हम एक समझौते पर पहुँच सकते हैं।"),
                ("My previous CTC was 6.5 lakhs.", "मेरा पिछला सीटीसी 6.5 लाख था।"),
                ("I am looking for a twenty percent hike.", "मैं बीस प्रतिशत वृद्धि की तलाश में हूँ।"),
                ("Salary is important, but growth matters more.", "वेतन महत्वपूर्ण है, लेकिन विकास अधिक मायने रखता है।"),
                ("I will wait for the official offer.", "मैं आधिकारिक प्रस्ताव का इंतज़ार करूँगा।"),
                ("Let us discuss the details after the selection.", "चयन के बाद विवरण पर चर्चा करते हैं।"),
                ("I am sure we can find a middle ground.", "मुझे यकीन है हम एक समझौता पा सकते हैं।"),
                ("What would you do if you missed a deadline?", "अगर आप समय सीमा चूक जाएँ तो आप क्या करेंगे?"),
                ("How do you handle a difficult customer?", "आप एक मुश्किल ग्राहक को कैसे संभालते हैं?"),
                ("Tell me about a time you faced a challenge.", "मुझे एक ऐसे समय के बारे में बताइए जब आपको चुनौती का सामना करना पड़ा।"),
                ("I stay calm and analyze the situation.", "मैं शांत रहता हूँ और स्थिति का विश्लेषण करता हूँ।"),
                ("I would prioritize the tasks first.", "मैं पहले कार्यों को प्राथमिकता दूँगा।"),
                ("I always communicate openly with my team.", "मैं हमेशा अपनी टीम के साथ खुलकर संवाद करता हूँ।"),
                ("I would inform my manager immediately.", "मैं तुरंत अपने प्रबंधक को सूचित करूँगा।"),
                ("I take responsibility for my mistakes.", "मैं अपनी गलतियों की जिम्मेदारी लेता हूँ।"),
                ("I look for solutions instead of blaming others.", "मैं दूसरों को दोष देने के बजाय समाधान ढूँढता हूँ।"),
                ("I would apologize and fix the issue.", "मैं माफ़ी माँगूँगा और समस्या ठीक करूँगा।"),
                ("I stay positive even in tough situations.", "मैं कठिन परिस्थितियों में भी सकारात्मक रहता हूँ।"),
                ("I would ask for guidance if needed.", "ज़रूरत पड़ने पर मैं मार्गदर्शन माँगूँगा।"),
                ("I handled a similar situation at my last job.", "मैंने अपनी पिछली नौकरी में ऐसी ही स्थिति संभाली थी।"),
                ("I learned a valuable lesson from that experience.", "मैंने उस अनुभव से एक मूल्यवान सबक सीखा।"),
                ("I would first understand the root cause.", "मैं पहले मूल कारण समझूँगा।"),
                ("I do not panic in emergencies.", "मैं आपात स्थितियों में घबराता नहीं हूँ।"),
                ("I would work overtime to complete the task.", "मैं कार्य पूरा करने के लिए अतिरिक्त समय काम करूँगा।"),
                ("I believe in solving problems systematically.", "मैं समस्याओं को व्यवस्थित रूप से हल करने में विश्वास करता हूँ।"),
                ("I would discuss it with the team.", "मैं टीम के साथ इस पर चर्चा करूँगा।"),
                ("I stay professional in every situation.", "मैं हर स्थिति में पेशेवर रहता हूँ।"),
                ("I would prepare a backup plan.", "मैं एक बैकअप योजना तैयार करूँगा।"),
                ("Challenges help me grow.", "चुनौतियाँ मुझे बढ़ने में मदद करती हैं।"),
                ("I learn from every difficult situation.", "मैं हर कठिन परिस्थिति से सीखता हूँ।"),
                ("I would take initiative to solve it.", "मैं इसे हल करने के लिए पहल करूँगा।"),
                ("I am always solution-oriented.", "मैं हमेशा समाधान-उन्मुख हूँ।"),
            ]},
            {"title": "HR Questions", "desc": "Answer common HR questions", "topic": "HR Questions", "sentences": [
                ("Why should we hire you?", "हमें आपको क्यों नियुक्त करना चाहिए?"),
                ("Where do you see yourself in five years?", "आप खुद को पाँच साल में कहाँ देखते हैं?"),
                ("Why did you leave your last job?", "आपने अपनी पिछली नौकरी क्यों छोड़ी?"),
                ("I left for better career growth.", "मैंने बेहतर करियर विकास के लिए छोड़ा।"),
                ("What motivates you to work?", "आपको काम करने के लिए क्या प्रेरित करता है?"),
                ("My family is my biggest motivation.", "मेरा परिवार मेरी सबसे बड़ी प्रेरणा है।"),
                ("How do you manage your time?", "आप अपना समय कैसे प्रबंधित करते हैं?"),
                ("I use a planner and set priorities.", "मैं एक प्लानर का उपयोग करता हूँ और प्राथमिकताएँ निर्धारित करता हूँ।"),
                ("What are your salary expectations?", "आपकी वेतन अपेक्षाएँ क्या हैं?"),
                ("Can you work under pressure?", "क्या आप दबाव में काम कर सकते हैं?"),
                ("Yes, I perform well under pressure.", "हाँ, मैं दबाव में अच्छा प्रदर्शन करता हूँ।"),
                ("Are you willing to relocate?", "क्या आप स्थानांतरण के लिए तैयार हैं?"),
                ("Yes, I am flexible about the location.", "हाँ, मैं स्थान के बारे में लचीला हूँ।"),
                ("What do you know about our company?", "आप हमारी कंपनी के बारे में क्या जानते हैं?"),
                ("Your company was founded in 2010.", "आपकी कंपनी 2010 में स्थापित हुई थी।"),
                ("Do you have any questions for us?", "क्या आपके पास हमारे लिए कोई प्रश्न हैं?"),
                ("What are the working hours?", "काम के घंटे क्या हैं?"),
                ("When can you join?", "आप कब जुड़ सकते हैं?"),
                ("I can join immediately.", "मैं तुरंत जुड़ सकता हूँ।"),
                ("I would need a notice period of one month.", "मुझे एक महीने की नोटिस अवधि चाहिए।"),
                ("How do you handle criticism?", "आप आलोचना को कैसे संभालते हैं?"),
                ("I take criticism as feedback to improve.", "मैं आलोचना को सुधार के लिए प्रतिक्रिया मानता हूँ।"),
                ("Are you comfortable working overtime?", "क्या आप ओवरटाइम काम करने में सहज हैं?"),
                ("I am ready to work extra when required.", "आवश्यकता होने पर मैं अतिरिक्त काम करने को तैयार हूँ।"),
                ("Thank you for this opportunity.", "इस अवसर के लिए धन्यवाद।"),
            ]},
            {"title": "Career Goals", "desc": "Talk about your career goals", "topic": "Career Goals", "sentences": [
                ("My career goal is to become a team leader.", "मेरा करियर लक्ष्य एक टीम लीडर बनना है।"),
                ("I want to specialize in data analytics.", "मैं डेटा विश्लेषण में विशेषज्ञ बनना चाहता हूँ।"),
                ("I plan to grow within this company.", "मैं इस कंपनी के भीतर बढ़ने की योजना बना रहा हूँ।"),
                ("I want to improve my leadership skills.", "मैं अपने नेतृत्व कौशल में सुधार करना चाहता हूँ।"),
                ("My goal is to contribute to the company's success.", "मेरा लक्ष्य कंपनी की सफलता में योगदान देना है।"),
                ("I aim to become a subject matter expert.", "मैं एक विषय विशेषज्ञ बनने का लक्ष्य रखता हूँ।"),
                ("I want to take on more responsibilities.", "मैं और अधिक जिम्मेदारियाँ लेना चाहता हूँ।"),
                ("I am working towards a managerial role.", "मैं एक प्रबंधकीय भूमिका की दिशा में काम कर रहा हूँ।"),
                ("I want to learn from experienced mentors.", "मैं अनुभवी गुरुओं से सीखना चाहता हूँ।"),
                ("My goal is to be an asset to the company.", "मेरा लक्ष्य कंपनी के लिए एक संपत्ति बनना है।"),
                ("I want to build a strong professional network.", "मैं एक मजबूत पेशेवर नेटवर्क बनाना चाहता हूँ।"),
                ("I plan to complete a certification this year.", "मैं इस साल एक प्रमाणन पूरा करने की योजना बना रहा हूँ।"),
                ("I am focused on continuous improvement.", "मैं निरंतर सुधार पर केंद्रित हूँ।"),
                ("I want to mentor juniors in the future.", "मैं भविष्य में कनिष्ठों को मार्गदर्शन देना चाहता हूँ।"),
                ("My goals align with the company's vision.", "मेरे लक्ष्य कंपनी की दृष्टि के साथ संरेखित हैं।"),
                ("I want to be recognized for my work.", "मैं अपने काम के लिए पहचाना जाना चाहता हूँ।"),
                ("I aim to increase my domain knowledge.", "मैं अपने क्षेत्र का ज्ञान बढ़ाने का लक्ष्य रखता हूँ।"),
                ("I want to handle bigger projects.", "मैं बड़ी परियोजनाओं को संभालना चाहता हूँ।"),
                ("I am committed to achieving my goals.", "मैं अपने लक्ष्यों को प्राप्त करने के लिए प्रतिबद्ध हूँ।"),
                ("My short-term goal is to perform excellently here.", "मेरा अल्पकालिक लक्ष्य यहाँ उत्कृष्ट प्रदर्शन करना है।"),
                ("I want to build expertise step by step.", "मैं कदम दर कदम विशेषज्ञता बनाना चाहता हूँ।"),
                ("I am excited about my career path.", "मैं अपने करियर पथ को लेकर उत्साहित हूँ।"),
                ("I believe in setting realistic goals.", "मैं यथार्थवादी लक्ष्य निर्धारित करने में विश्वास करता हूँ।"),
                ("Hard work leads to goal achievement.", "कड़ी मेहनत लक्ष्य प्राप्ति की ओर ले जाती है।"),
                ("I have a clear roadmap for my career.", "मेरे करियर के लिए मेरे पास एक स्पष्ट रोडमैप है।"),
            ]},
            {"title": "Questions to Ask", "desc": "Ask the interviewer questions", "topic": "Asking Questions", "sentences": [
                ("Can you tell me more about the team?", "क्या आप मुझे टीम के बारे में और बता सकते हैं?"),
                ("What does a typical day look like in this role?", "इस भूमिका में एक सामान्य दिन कैसा होता है?"),
                ("What are the growth opportunities here?", "यहाँ विकास के अवसर क्या हैं?"),
                ("How does the company measure success?", "कंपनी सफलता को कैसे मापती है?"),
                ("What is the company culture like?", "कंपनी की संस्कृति कैसी है?"),
                ("Who will I be reporting to?", "मैं किसके अधीन काम करूँगा?"),
                ("What are the key challenges of this role?", "इस भूमिका की प्रमुख चुनौतियाँ क्या हैं?"),
                ("Is there a training program for new employees?", "क्या नए कर्मचारियों के लिए प्रशिक्षण कार्यक्रम है?"),
                ("How does the company support work-life balance?", "कंपनी कार्य-जीवन संतुलन का समर्थन कैसे करती है?"),
                ("What are the next steps in the process?", "प्रक्रिया में अगले कदम क्या हैं?"),
                ("When can I expect to hear from you?", "मुझे आपसे कब सुनने की उम्मीद करनी चाहिए?"),
                ("How often are performance reviews conducted?", "प्रदर्शन समीक्षाएँ कितनी बार की जाती हैं?"),
                ("What tools does the team use?", "टीम कौन से उपकरण इस्तेमाल करती है?"),
                ("Can I see the office?", "क्या मैं ऑफिस देख सकता हूँ?"),
                ("Is remote work an option?", "क्या दूर से काम करने का विकल्प है?"),
                ("What is the probation period?", "परिवीक्षा अवधि क्या है?"),
                ("Are there any upcoming projects I can join?", "क्या कोई आगामी परियोजनाएँ हैं जिनसे मैं जुड़ सकता हूँ?"),
                ("How does the team handle conflicts?", "टीम संघर्षों को कैसे संभालती है?"),
                ("What do employees enjoy most about working here?", "कर्मचारी यहाँ काम करने में सबसे ज्यादा क्या पसंद करते हैं?"),
                ("Is there a dress code?", "क्या कोई ड्रेस कोड है?"),
                ("How is feedback given to employees?", "कर्मचारियों को प्रतिक्रिया कैसे दी जाती है?"),
                ("What is the team size?", "टीम का आकार क्या है?"),
                ("Asking questions shows my interest.", "प्रश्न पूछना मेरी रुचि दर्शाता है।"),
                ("I am curious about this role.", "मैं इस भूमिका के बारे में उत्सुक हूँ।"),
                ("Thank you for answering my questions.", "मेरे प्रश्नों का उत्तर देने के लिए धन्यवाद।"),
            ]},
            {"title": "Interview Day", "desc": "Prepare for the interview day", "topic": "Interview Day", "sentences": [
                ("I reached the interview venue early.", "मैं इंटरव्यू स्थल पर जल्दी पहुँच गया।"),
                ("I dressed professionally for the interview.", "मैंने इंटरव्यू के लिए पेशेवर कपड़े पहने।"),
                ("I carried all my documents.", "मैं अपने सभी दस्तावेज़ ले गया।"),
                ("I took a deep breath before entering.", "अंदर जाने से पहले मैंने गहरी साँस ली।"),
                ("The receptionist asked me to wait.", "रिसेप्शनिस्ट ने मुझे इंतज़ार करने को कहा।"),
                ("I greeted the interviewer with a smile.", "मैंने साक्षात्कारकर्ता का मुस्कान के साथ अभिवादन किया।"),
                ("I shook hands confidently.", "मैंने आत्मविश्वास से हाथ मिलाया।"),
                ("I answered the questions clearly.", "मैंने प्रश्नों के उत्तर स्पष्ट रूप से दिए।"),
                ("I maintained eye contact during the interview.", "मैंने साक्षात्कार के दौरान आँख मिलाकर बात की।"),
                ("I asked intelligent questions.", "मैंने समझदारी भरे प्रश्न पूछे।"),
                ("The interview lasted thirty minutes.", "साक्षात्कार तीस मिनट तक चला।"),
                ("I thanked the interviewer at the end.", "अंत में मैंने साक्षात्कारकर्ता को धन्यवाद दिया।"),
                ("I felt good about my performance.", "मुझे अपने प्रदर्शन के बारे में अच्छा लगा।"),
                ("The panel was very friendly.", "पैनल बहुत मिलनसार था।"),
                ("I will wait for the result.", "मैं परिणाम का इंतज़ार करूँगा।"),
                ("I prepared well for the interview.", "मैंने इंटरव्यू के लिए अच्छी तैयारी की।"),
                ("I practiced my answers at home.", "मैंने घर पर अपने उत्तरों का अभ्यास किया।"),
                ("I stayed calm and focused.", "मैं शांत और केंद्रित रहा।"),
                ("The first impression matters a lot.", "पहली छाप बहुत मायने रखती है।"),
                ("I arrived ten minutes before time.", "मैं समय से दस मिनट पहले पहुँच गया।"),
                ("I had all the required certificates.", "मेरे पास सभी आवश्यक प्रमाण पत्र थे।"),
                ("I was honest in all my answers.", "मैं अपने सभी उत्तरों में ईमानदार था।"),
                ("I hope I get selected.", "मुझे उम्मीद है मेरा चयन होगा।"),
                ("Preparation gives confidence.", "तैयारी आत्मविश्वास देती है।"),
                ("I will keep improving for the next round.", "मैं अगले दौर के लिए सुधार करता रहूँगा।"),
            ]},
            {"title": "Common Interview Words", "desc": "Use professional words in interviews", "topic": "Vocabulary", "sentences": [
                ("I have strong analytical skills.", "मेरे पास मजबूत विश्लेषणात्मक कौशल हैं।"),
                ("I am proficient in English.", "मैं अंग्रेज़ी में दक्ष हूँ।"),
                ("I am result-oriented.", "मैं परिणाम-उन्मुख हूँ।"),
                ("I am a self-starter.", "मैं एक आत्म-प्रारंभक हूँ।"),
                ("I have excellent time management.", "मेरे पास उत्कृष्ट समय प्रबंधन है।"),
                ("I am customer-focused.", "मैं ग्राहक-केंद्रित हूँ।"),
                ("I have attention to detail.", "मेरे पास विवरण पर ध्यान देने की क्षमता है।"),
                ("I am innovative and creative.", "मैं नवोन्मेषी और रचनात्मक हूँ।"),
                ("I am proactive in my work.", "मैं अपने काम में सक्रिय हूँ।"),
                ("I deliver quality work.", "मैं गुणवत्तापूर्ण काम देता हूँ।"),
                ("I meet deadlines consistently.", "मैं समय सीमाओं का लगातार पालन करता हूँ।"),
                ("I have strong interpersonal skills.", "मेरे पास मजबूत पारस्परिक कौशल हैं।"),
                ("I am adaptable to change.", "मैं बदलाव के लिए अनुकूलनीय हूँ।"),
                ("I am goal-driven.", "मैं लक्ष्य-संचालित हूँ।"),
                ("I am a critical thinker.", "मैं आलोचनात्मक विचारक हूँ।"),
                ("I collaborate well with others.", "मैं दूसरों के साथ अच्छा सहयोग करता हूँ।"),
                ("I take initiative at work.", "मैं काम पर पहल करता हूँ।"),
                ("I am efficient and productive.", "मैं कुशल और उत्पादक हूँ।"),
                ("I have a growth mindset.", "मेरे पास विकास की मानसिकता है।"),
                ("I am detail-driven.", "मैं विवरण-संचालित हूँ।"),
                ("I am committed to excellence.", "मैं उत्कृष्टता के लिए प्रतिबद्ध हूँ।"),
                ("I handle multitasking well.", "मैं एक साथ कई काम अच्छे से करता हूँ।"),
                ("Professional words impress interviewers.", "पेशेवर शब्द साक्षात्कारकर्ताओं को प्रभावित करते हैं।"),
                ("I keep learning professional vocabulary.", "मैं पेशेवर शब्दावली सीखता रहता हूँ।"),
                ("Words show your professionalism.", "शब्द आपकी पेशेवरता दिखाते हैं।"),
            ]},
            {"title": "Body Language & Confidence", "desc": "Show confidence in interviews", "topic": "Confidence", "sentences": [
                ("Sit straight during the interview.", "साक्षात्कार के दौरान सीधे बैठिए।"),
                ("Maintain good posture.", "अच्छी मुद्रा बनाए रखिए।"),
                ("Smile politely when you speak.", "बोलते समय विनम्रता से मुस्कुराइए।"),
                ("Do not cross your arms.", "अपनी बाहें मत क्रॉस कीजिए।"),
                ("Use confident body language.", "आत्मविश्वासपूर्ण शारीरिक भाषा का उपयोग कीजिए।"),
                ("Speak at a steady pace.", "स्थिर गति से बोलिए।"),
                ("Do not rush your answers.", "अपने उत्तरों में जल्दबाजी मत कीजिए।"),
                ("Pause and think before answering.", "उत्तर देने से पहले रुककर सोचिए।"),
                ("Listen carefully to the question.", "प्रश्न को ध्यान से सुनिए।"),
                ("Ask for clarification if needed.", "ज़रूरत हो तो स्पष्टीकरण माँगिए।"),
                ("Your confidence shows in your voice.", "आपका आत्मविश्वास आपकी आवाज़ में दिखता है।"),
                ("Practice speaking in front of a mirror.", "आईने के सामने बोलने का अभ्यास कीजिए।"),
                ("Take a moment to collect your thoughts.", "अपने विचारों को एकत्र करने के लिए एक पल लीजिए।"),
                ("Avoid using filler words like umm.", "उम्म जैसे शब्दों का उपयोग न करें।"),
                ("Be enthusiastic about the role.", "भूमिका के प्रति उत्साहित रहिए।"),
                ("Dress smartly for confidence.", "आत्मविश्वास के लिए स्मार्ट कपड़े पहनिए।"),
                ("A firm handshake shows confidence.", "मजबूत हाथ मिलाना आत्मविश्वास दर्शाता है।"),
                ("Do not fidget during the interview.", "साक्षात्कार के दौरान इधर-उधर न हिलें।"),
                ("Keep your answers concise.", "अपने उत्तर संक्षिप्त रखिए।"),
                ("Show passion in your tone.", "अपने स्वर में जुनून दिखाइए।"),
                ("Be yourself and be honest.", "स्वयं बनिए और ईमानदार रहिए।"),
                ("Confidence comes from preparation.", "आत्मविश्वास तैयारी से आता है।"),
                ("Positive energy impresses interviewers.", "सकारात्मक ऊर्जा साक्षात्कारकर्ताओं को प्रभावित करती है।"),
                ("I believe in myself.", "मुझे खुद पर विश्वास है।"),
                ("Every interview makes me stronger.", "हर साक्षात्कार मुझे मजबूत बनाता है।"),
            ]},
            {"title": "Follow-up & Thank You", "desc": "Follow up after the interview", "topic": "Follow-up", "sentences": [
                ("I sent a thank you email after the interview.", "साक्षात्कार के बाद मैंने धन्यवाद ईमेल भेजा।"),
                ("Thank you for giving me your time today.", "आज मुझे अपना समय देने के लिए धन्यवाद।"),
                ("I appreciate the opportunity to interview.", "साक्षात्कार का अवसर देने के लिए मैं आभारी हूँ।"),
                ("I enjoyed meeting the team.", "मुझे टीम से मिलकर अच्छा लगा।"),
                ("I am very interested in this position.", "मुझे इस पद में बहुत रुचि है।"),
                ("I am following up on my application.", "मैं अपने आवेदन के संबंध में अनुवर्ती कर रहा हूँ।"),
                ("Have you made a decision about the role?", "क्या आपने भूमिका के बारे में निर्णय लिया है?"),
                ("I would like to know the status of my application.", "मैं अपने आवेदन की स्थिति जानना चाहूँगा।"),
                ("I am available for another round of discussion.", "मैं चर्चा के एक और दौर के लिए उपलब्ध हूँ।"),
                ("Please let me know if you need more information.", "अगर आपको और जानकारी चाहिए तो कृपया बताइए।"),
                ("I am excited about the possibility of joining.", "मैं जुड़ने की संभावना को लेकर उत्साहित हूँ।"),
                ("I will wait for your response.", "मैं आपके उत्तर का इंतज़ार करूँगा।"),
                ("Following up shows your interest.", "अनुवर्ती करना आपकी रुचि दर्शाता है।"),
                ("A polite follow-up is appreciated.", "विनम्र अनुवर्ती की सराहना की जाती है।"),
                ("I thanked the panel for their time.", "मैंने पैनल को उनके समय के लिए धन्यवाद दिया।"),
                ("I shared my portfolio with them.", "मैंने उनके साथ अपना पोर्टफोलियो साझा किया।"),
                ("I asked about the next steps.", "मैंने अगले चरणों के बारे में पूछा।"),
                ("I stayed positive while waiting.", "इंतज़ार करते हुए मैं सकारात्मक रहा।"),
                ("The recruiter said they will revert soon.", "भर्तीकर्ता ने कहा वे जल्द बताएँगे।"),
                ("I prepared for the next round.", "मैंने अगले दौर की तैयारी की।"),
                ("I kept my documents ready.", "मैंने अपने दस्तावेज़ तैयार रखे।"),
                ("Patience is important after an interview.", "साक्षात्कार के बाद धैर्य महत्वपूर्ण है।"),
                ("I learned from this experience.", "मैंने इस अनुभव से सीखा।"),
                ("Good things come to those who wait.", "इंतज़ार करने वालों को अच्छी चीज़ें मिलती हैं।"),
                ("I am ready for new opportunities.", "मैं नए अवसरों के लिए तैयार हूँ।"),
            ]},
            {"title": "Interview Conversations", "desc": "Practice full interview conversations", "topic": "Conversations", "sentences": [
                ("Good morning. Please have a seat.", "सुप्रभात। कृपया बैठिए।"),
                ("Thank you. Good morning to you too.", "धन्यवाद। आपको भी सुप्रभात।"),
                ("So, tell me about yourself.", "तो, अपने बारे में बताइए।"),
                ("I am a graduate with three years of experience.", "मैं तीन साल के अनुभव वाला स्नातक हूँ।"),
                ("Why are you interested in this role?", "आप इस भूमिका में रुचि क्यों रखते हैं?"),
                ("I am passionate about this field of work.", "मैं काम के इस क्षेत्र के प्रति भावुक हूँ।"),
                ("What are your strengths?", "आपकी ताकतें क्या हैं?"),
                ("My strengths are dedication and learning ability.", "मेरी ताकतें समर्पण और सीखने की क्षमता हैं।"),
                ("Where do you see yourself in five years?", "आप खुद को पाँच साल में कहाँ देखते हैं?"),
                ("I see myself growing with this company.", "मैं खुद को इस कंपनी के साथ बढ़ता हुआ देखता हूँ।"),
                ("Do you have any questions for us?", "क्या आपके पास हमारे लिए कोई प्रश्न हैं?"),
                ("Yes, I would like to know about the team.", "हाँ, मैं टीम के बारे में जानना चाहूँगा।"),
                ("When can you join us?", "आप हमसे कब जुड़ सकते हैं?"),
                ("I can join within fifteen days.", "मैं पंद्रह दिनों के भीतर जुड़ सकता हूँ।"),
                ("We will inform you about the result.", "हम आपको परिणाम के बारे में सूचित करेंगे।"),
                ("Thank you for the interview.", "साक्षात्कार के लिए धन्यवाद।"),
                ("It was nice talking to you.", "आपसे बात करके अच्छा लगा।"),
                ("We will be in touch with you.", "हम आपसे संपर्क में रहेंगे।"),
                ("I look forward to hearing from you.", "मैं आपसे सुनने की उम्मीद करता हूँ।"),
                ("Have a great day, sir.", "आपका दिन शुभ हो, महोदय।"),
                ("The conversation went very well.", "बातचीत बहुत अच्छी रही।"),
                ("I answered every question confidently.", "मैंने हर प्रश्न का उत्तर आत्मविश्वास से दिया।"),
                ("I practiced this conversation many times.", "मैंने इस बातचीत का कई बार अभ्यास किया।"),
                ("Practice makes interviews easier.", "अभ्यास साक्षात्कार को आसान बनाता है।"),
                ("I am one step closer to my dream job.", "मैं अपने सपनों की नौकरी के एक कदम और करीब हूँ।"),
            ]},
        ],
    }
