-- SunoBolo English — D1 seed data (generated from src/data/seed)
-- Regenerate: npx tsx scripts/seed-d1.mts

INSERT OR IGNORE INTO course_categories (id, name, slug, sort_order) VALUES
  ('kids', 'Kids English', 'english-for-kids', 1),
  ('students', 'School English', 'school-english', 2),
  ('adults', 'Adult English', 'english-for-beginners', 3),
  ('professionals', 'Professional English', 'interview-english', 4);

INSERT OR IGNORE INTO courses (id, category_id, slug, title, tagline, description, long_description, level, audience, emoji, color, is_free, sort_order, featured, seo_title, seo_description, lesson_count, sentence_count) VALUES
  ('kids', 'kids', 'english-for-kids', 'Kids English', 'Khel-khel mein English seekho', 'Alphabet, numbers, colors, animals aur family — chhoton ke liye easy English sentences.', 'Kids English course mein bachche khel-khel mein English bolna seekhte hain. Har sentence ko 3 baar sunkar aur 3 baar bolkar, bachche jaldi yaad kar lete hain. Yeh course 4–14 saal ke bachon ke liye hai.', 'kids', 'kids', '🧸', 'amber', 1, 1, 1, 'English for Kids — SunoBolo English', 'Bachon ke liye English speaking practice — alphabet, animals, colors, family. Suno bolo repeat karo method.', 4, 20),
  ('school', 'students', 'school-english', 'School English', 'Classroom aur school ke liye', 'Classroom English, teacher conversation aur vocabulary — school students ke liye.', 'School English course students ko classroom, teacher aur dostों ke saath English bolne ki practice deta hai. Class 1 se 12 tak ke students ke liye useful.', 'school', 'students', '🎒', 'indigo', 1, 2, 0, 'School English — SunoBolo English', 'Classroom English, teacher conversation aur vocabulary — school students ke liye speaking practice.', 4, 20),
  ('beginner', 'adults', 'english-for-beginners', 'Beginner English', 'Zero se English shuru karo', 'Introduction, greetings, family, food, shopping aur daily routine — 100 sentences.', 'Beginner English course unke liye hai jo English bilkul shuru se seekhna chahte hain. Roz 10–15 minute practice karke aap apni pehli English sentence bolna shuru kar sakte hain. Har lesson simple aur practical hai.', 'beginner', 'adults', '🌱', 'emerald', 1, 3, 1, 'English for Beginners — SunoBolo English', 'Zero se English bolna seekho — 100+ easy sentences with Hindi meaning. Suno, bolo, repeat karo.', 10, 100),
  ('intermediate', 'adults', 'intermediate-english', 'Intermediate English', 'Bolna aur samajhna behtar karo', 'Daily conversation, office, travel, opinions aur storytelling — 50 sentences.', 'Intermediate course unke liye hai jo basic English samajhte hain par fluent nahi bol paate. Practical topics par practice karke aap zyada confidently English bol payenge.', 'intermediate', 'adults', '🚀', 'sky', 0, 4, 1, 'Intermediate English Course — SunoBolo English', 'Daily conversation, office aur travel ke liye English speaking practice — 50 sentences.', 5, 50),
  ('advanced', 'adults', 'advanced-english', 'Advanced English', 'Professional aur fluent bolo', 'Meetings, negotiation aur professional communication — 30 sentences.', 'Advanced course professional English chahne walon ke liye hai — meetings, presentations, negotiation aur polished communication ke liye.', 'advanced', 'adults', '🎯', 'violet', 0, 5, 0, 'Advanced English Course — SunoBolo English', 'Meetings, negotiation aur professional communication ke liye advanced English speaking practice.', 3, 30),
  ('daily', 'adults', 'daily-use-english', 'Daily Life English', 'Roz ki zindagi ke sentences', 'Ghar, shopping, restaurant, bank, hospital, phone — har jagah ki English.', 'Daily Life English course roz ki zindagi ke har situation ke liye hai — ghar se le kar bank, hospital, shopping aur phone tak. Yeh sabse practical course hai daily use ke liye.', 'daily', 'adults', '☀️', 'orange', 0, 6, 1, 'Daily Use English Sentences — SunoBolo English', 'Roz ki zindagi ke 50+ English sentences — ghar, shopping, bank, hospital, phone aur WhatsApp ke liye.', 5, 50),
  ('interview', 'professionals', 'interview-english', 'Interview English', 'Interview jeet ke aao', 'Tell me about yourself, HR questions aur situational answers — 30 sentences.', 'Interview English course aapko job interview ke har question ka jawab confidence ke saath bolna sikhata hai. Practice karke aap interviewer ke saamne bina ghabraaye bol payenge.', 'interview', 'professionals', '💼', 'indigo', 0, 7, 1, 'Interview English — SunoBolo English', 'Job interview ke liye English practice — tell me about yourself, HR aur situational questions.', 3, 30),
  ('corporate', 'professionals', 'corporate-english', 'Corporate English', 'Office aur meetings ke liye', 'Office English, meetings, team aur client communication — 30 sentences.', 'Corporate English course office ki professional life ke liye hai — meetings, emails, team coordination aur client calls ke liye polished English.', 'corporate', 'professionals', '🏢', 'teal', 0, 8, 0, 'Corporate English — SunoBolo English', 'Office, meetings aur client communication ke liye professional English practice.', 3, 30),
  ('business', 'professionals', 'business-english', 'Business English', 'Business ke liye English', 'Customer dealing, pricing, orders aur negotiation — 30 sentences.', 'Business English course businessmen aur entrepreneurs ke liye hai — suppliers, customers, pricing, orders aur negotiation ke liye.', 'business', 'professionals', '📊', 'rose', 0, 9, 0, 'Business English — SunoBolo English', 'Business calls, negotiation, pricing aur orders ke liye English speaking practice.', 3, 30),
  ('travel', 'professionals', 'travel-english', 'Travel English', 'Safar mein English bolo', 'Airport, hotel, taxi, restaurant aur directions — 30 sentences.', 'Travel English course aapko har travel situation ke liye taiyaar karta hai — airport se lekar hotel, taxi, restaurant aur directions tak.', 'travel', 'professionals', '✈️', 'sky', 0, 10, 0, 'Travel English — SunoBolo English', 'Airport, hotel, taxi, restaurant aur directions ke liye English sentences.', 3, 30);

INSERT OR IGNORE INTO lessons (id, course_id, title, emoji, description, sort_order, is_free, sentence_count) VALUES
  ('kids-l1', 'kids', 'Alphabet & Numbers', '🔤', 'ABCD aur ginti — easy shuruaat.', 1, 1, 5),
  ('kids-l2', 'kids', 'Colors & Shapes', '🌈', 'Rang aur aakar seekho.', 2, 1, 5),
  ('kids-l3', 'kids', 'Animals & Fruits', '🐘', 'Janwar aur phal ke naam.', 3, 1, 5),
  ('kids-l4', 'kids', 'Family & My Body', '👨‍👩‍👧', 'Parivaar aur shareer ke ang.', 4, 1, 5),
  ('school-l1', 'school', 'In the Classroom', '🏫', 'Classroom mein bole jane wale sentences.', 1, 1, 5),
  ('school-l2', 'school', 'Talking to the Teacher', '🧑‍🏫', 'Teacher se baat karne ke sentences.', 2, 1, 5),
  ('school-l3', 'school', 'Talking in Class', '🗨️', 'Class mein students ki baat-cheet.', 3, 1, 5),
  ('school-l4', 'school', 'Useful Vocabulary', '📚', 'School ke useful words aur sentences.', 4, 1, 5),
  ('beginner-l1', 'beginner', 'Introduction', '👋', 'Apna parichay dena seekho.', 1, 1, 10),
  ('beginner-l2', 'beginner', 'Greetings', '🙏', 'Namaste aur wishes ke sentences.', 2, 1, 10),
  ('beginner-l3', 'beginner', 'Family', '👨‍👩‍👧‍👦', 'Parivaar ke baare mein baat karo.', 3, 1, 10),
  ('beginner-l4', 'beginner', 'Home', '🏠', 'Ghar aur kamron ke sentences.', 4, 1, 10),
  ('beginner-l5', 'beginner', 'Food', '🍛', 'Khana aur khaana-pina.', 5, 1, 10),
  ('beginner-l6', 'beginner', 'Shopping', '🛒', 'Bazaar aur shopping ke sentences.', 6, 1, 10),
  ('beginner-l7', 'beginner', 'Daily Routine', '⏰', 'Roz ki dincharya English mein.', 7, 1, 10),
  ('beginner-l8', 'beginner', 'Friends', '🤝', 'Doston ke saath baat-cheet.', 8, 1, 10),
  ('beginner-l9', 'beginner', 'Phone Calls', '📞', 'Phone par baat karne ke sentences.', 9, 1, 10),
  ('beginner-l10', 'beginner', 'Daily Conversation', '💬', 'Roz ki aam baat-cheet.', 10, 1, 10),
  ('intermediate-l1', 'intermediate', 'Daily Conversation', '🗣️', 'Aam baat-cheet ko aage badhao.', 1, 0, 10),
  ('intermediate-l2', 'intermediate', 'Office & Work', '💻', 'Kaam aur office ke sentences.', 2, 0, 10),
  ('intermediate-l3', 'intermediate', 'Travel & Social', '🌍', 'Travel aur social situations.', 3, 0, 10),
  ('intermediate-l4', 'intermediate', 'Opinions & Experiences', '💭', 'Apni rai aur anubhav batana.', 4, 0, 10),
  ('intermediate-l5', 'intermediate', 'Requests & Storytelling', '📖', 'Request karna aur kahani sunana.', 5, 0, 10),
  ('advanced-l1', 'advanced', 'Meetings & Presentations', '📊', 'Meeting aur presentation mein bolo.', 1, 0, 10),
  ('advanced-l2', 'advanced', 'Negotiation & Persuasion', '⚖️', 'Samjhaana aur deal karna.', 2, 0, 10),
  ('advanced-l3', 'advanced', 'Professional Communication', '✉️', 'Professional emails aur calls.', 3, 0, 10),
  ('daily-l1', 'daily', 'At Home', '🏠', 'Ghar ke kaam aur baat-cheet.', 1, 0, 10),
  ('daily-l2', 'daily', 'Shopping & Restaurant', '🛍️', 'Kharidari aur khane ka order.', 2, 0, 10),
  ('daily-l3', 'daily', 'Travel & Directions', '🗺️', 'Rasta poochna aur safar.', 3, 0, 10),
  ('daily-l4', 'daily', 'Bank & Hospital', '🏦', 'Bank aur hospital ke sentences.', 4, 0, 10),
  ('daily-l5', 'daily', 'Phone & WhatsApp', '📱', 'Phone aur WhatsApp par baat.', 5, 0, 10),
  ('interview-l1', 'interview', 'About Yourself', '🙋', 'Apne baare mein batana.', 1, 0, 10),
  ('interview-l2', 'interview', 'HR Questions', '📋', 'HR ke aam questions.', 2, 0, 10),
  ('interview-l3', 'interview', 'Situational Questions', '🧩', 'Situation-based answers.', 3, 0, 10),
  ('corporate-l1', 'corporate', 'Office & Meetings', '🗓️', 'Meeting aur office ke sentences.', 1, 0, 10),
  ('corporate-l2', 'corporate', 'Team & Manager', '🤝', 'Team aur manager se baat.', 2, 0, 10),
  ('corporate-l3', 'corporate', 'Clients & Deadlines', '⏳', 'Client aur deadlines ka dhyan.', 3, 0, 10),
  ('business-l1', 'business', 'Customer & Suppliers', '🛠️', 'Customer aur supplier se baat.', 1, 0, 10),
  ('business-l2', 'business', 'Pricing & Orders', '💰', 'Price, order aur payment.', 2, 0, 10),
  ('business-l3', 'business', 'Negotiation & Partnership', '🤝', 'Deal aur partnership karna.', 3, 0, 10),
  ('travel-l1', 'travel', 'Airport & Immigration', '🛫', 'Airport aur immigration.', 1, 0, 10),
  ('travel-l2', 'travel', 'Hotel & Taxi', '🏨', 'Hotel check-in aur taxi.', 2, 0, 10),
  ('travel-l3', 'travel', 'Restaurant & Directions', '🍽️', 'Khana aur rasta poochna.', 3, 0, 10);

INSERT OR IGNORE INTO sentences (id, lesson_id, course_id, english, hindi, difficulty, sort_order, is_free) VALUES
  ('kids-l1-s1', 'kids-l1', 'kids', 'A for Apple.', 'A for Apple।', 'easy', 1, 1),
  ('kids-l1-s2', 'kids-l1', 'kids', 'B for Ball.', 'B for Ball।', 'easy', 2, 1),
  ('kids-l1-s3', 'kids-l1', 'kids', 'I am five years old.', 'मैं पाँच साल का हूँ।', 'easy', 3, 1),
  ('kids-l1-s4', 'kids-l1', 'kids', 'One, two, three.', 'एक, दो, तीन।', 'easy', 4, 1),
  ('kids-l1-s5', 'kids-l1', 'kids', 'I can count to ten.', 'मैं दस तक गिन सकता हूँ।', 'easy', 5, 1),
  ('kids-l2-s1', 'kids-l2', 'kids', 'This is red.', 'यह लाल है।', 'easy', 1, 1),
  ('kids-l2-s2', 'kids-l2', 'kids', 'I like the blue sky.', 'मुझे नीला आसमान पसंद है।', 'easy', 2, 1),
  ('kids-l2-s3', 'kids-l2', 'kids', 'The sun is yellow.', 'सूरज पीला है।', 'easy', 3, 1),
  ('kids-l2-s4', 'kids-l2', 'kids', 'The ball is round.', 'गेंद गोल है।', 'easy', 4, 1),
  ('kids-l2-s5', 'kids-l2', 'kids', 'A circle has no corners.', 'वृत्त में कोई कोना नहीं होता।', 'medium', 5, 1),
  ('kids-l3-s1', 'kids-l3', 'kids', 'The cat says meow.', 'बिल्ली म्याऊँ बोलती है।', 'easy', 1, 1),
  ('kids-l3-s2', 'kids-l3', 'kids', 'The dog is my friend.', 'कुत्ता मेरा दोस्त है।', 'easy', 2, 1),
  ('kids-l3-s3', 'kids-l3', 'kids', 'I eat an apple every day.', 'मैं रोज़ एक सेब खाता हूँ।', 'medium', 3, 1),
  ('kids-l3-s4', 'kids-l3', 'kids', 'Mangoes are sweet.', 'आम मीठे होते हैं।', 'easy', 4, 1),
  ('kids-l3-s5', 'kids-l3', 'kids', 'The elephant is big.', 'हाथी बड़ा होता है।', 'easy', 5, 1),
  ('kids-l4-s1', 'kids-l4', 'kids', 'This is my mother.', 'यह मेरी माँ हैं।', 'easy', 1, 1),
  ('kids-l4-s2', 'kids-l4', 'kids', 'I love my family.', 'मुझे अपना परिवार बहुत पसंद है।', 'easy', 2, 1),
  ('kids-l4-s3', 'kids-l4', 'kids', 'My eyes are brown.', 'मेरी आँखें भूरी हैं।', 'easy', 3, 1),
  ('kids-l4-s4', 'kids-l4', 'kids', 'I wash my hands.', 'मैं अपने हाथ धोता हूँ।', 'easy', 4, 1),
  ('kids-l4-s5', 'kids-l4', 'kids', 'My name is Rohan.', 'मेरा नाम रोहन है।', 'easy', 5, 1),
  ('school-l1-s1', 'school-l1', 'school', 'May I come in?', 'क्या मैं अंदर आ सकता हूँ?', 'easy', 1, 1),
  ('school-l1-s2', 'school-l1', 'school', 'Please open your books.', 'कृपया अपनी किताबें खोलिए।', 'easy', 2, 1),
  ('school-l1-s3', 'school-l1', 'school', 'I have a question.', 'मेरा एक सवाल है।', 'easy', 3, 1),
  ('school-l1-s4', 'school-l1', 'school', 'Can I go to the washroom?', 'क्या मैं वॉशरूम जा सकता हूँ?', 'easy', 4, 1),
  ('school-l1-s5', 'school-l1', 'school', 'The class starts at nine.', 'कक्षा नौ बजे शुरू होती है।', 'medium', 5, 1),
  ('school-l2-s1', 'school-l2', 'school', 'Listen carefully, please.', 'कृपया ध्यान से सुनिए।', 'easy', 1, 1),
  ('school-l2-s2', 'school-l2', 'school', 'Write the answer on the board.', 'उत्तर ब्लैकबोर्ड पर लिखिए।', 'medium', 2, 1),
  ('school-l2-s3', 'school-l2', 'school', 'Raise your hand to speak.', 'बोलने के लिए हाथ उठाइए।', 'medium', 3, 1),
  ('school-l2-s4', 'school-l2', 'school', 'Read this paragraph aloud.', 'यह अनुच्छेद ज़ोर से पढ़िए।', 'medium', 4, 1),
  ('school-l2-s5', 'school-l2', 'school', 'Did everyone understand?', 'क्या सबको समझ आया?', 'medium', 5, 1),
  ('school-l3-s1', 'school-l3', 'school', 'I did my homework.', 'मैंने अपना होमवर्क किया।', 'easy', 1, 1),
  ('school-l3-s2', 'school-l3', 'school', 'I don''t understand this question.', 'मुझे यह सवाल समझ नहीं आया।', 'medium', 2, 1),
  ('school-l3-s3', 'school-l3', 'school', 'Can you explain it again?', 'क्या आप इसे फिर से समझा सकते हैं?', 'medium', 3, 1),
  ('school-l3-s4', 'school-l3', 'school', 'She is my classmate.', 'वह मेरी सहपाठी है।', 'easy', 4, 1),
  ('school-l3-s5', 'school-l3', 'school', 'I like studying English.', 'मुझे अंग्रेज़ी पढ़ना पसंद है।', 'easy', 5, 1),
  ('school-l4-s1', 'school-l4', 'school', 'This is a pencil.', 'यह एक पेंसिल है।', 'easy', 1, 1),
  ('school-l4-s2', 'school-l4', 'school', 'The teacher writes on the board.', 'टीचर बोर्ड पर लिखती हैं।', 'medium', 2, 1),
  ('school-l4-s3', 'school-l4', 'school', 'I carry a school bag.', 'मैं स्कूल बैग ले जाता हूँ।', 'easy', 3, 1),
  ('school-l4-s4', 'school-l4', 'school', 'The library has many books.', 'पुस्तकालय में कई किताबें हैं।', 'medium', 4, 1),
  ('school-l4-s5', 'school-l4', 'school', 'Practice makes perfect.', 'अभ्यास से सफलता मिलती है।', 'medium', 5, 1),
  ('beginner-l1-s1', 'beginner-l1', 'beginner', 'My name is Rahul.', 'मेरा नाम राहुल है।', 'easy', 1, 1),
  ('beginner-l1-s2', 'beginner-l1', 'beginner', 'I am from India.', 'मैं भारत से हूँ।', 'easy', 2, 1),
  ('beginner-l1-s3', 'beginner-l1', 'beginner', 'I live in Delhi.', 'मैं दिल्ली में रहता हूँ।', 'easy', 3, 1),
  ('beginner-l1-s4', 'beginner-l1', 'beginner', 'I am twenty-five years old.', 'मैं पच्चीस साल का हूँ।', 'easy', 4, 1),
  ('beginner-l1-s5', 'beginner-l1', 'beginner', 'I work in a company.', 'मैं एक कंपनी में काम करता हूँ।', 'easy', 5, 1),
  ('beginner-l1-s6', 'beginner-l1', 'beginner', 'I am a student.', 'मैं एक छात्र हूँ।', 'easy', 6, 1),
  ('beginner-l1-s7', 'beginner-l1', 'beginner', 'Nice to meet you.', 'आपसे मिलकर अच्छा लगा।', 'easy', 7, 1),
  ('beginner-l1-s8', 'beginner-l1', 'beginner', 'My family lives in Jaipur.', 'मेरा परिवार जयपुर में रहता है।', 'medium', 8, 1),
  ('beginner-l1-s9', 'beginner-l1', 'beginner', 'I speak Hindi and English.', 'मैं हिंदी और अंग्रेज़ी बोलता हूँ।', 'medium', 9, 1),
  ('beginner-l1-s10', 'beginner-l1', 'beginner', 'I am learning English.', 'मैं अंग्रेज़ी सीख रहा हूँ।', 'easy', 10, 1),
  ('beginner-l2-s1', 'beginner-l2', 'beginner', 'Good morning.', 'सुप्रभात।', 'easy', 1, 1),
  ('beginner-l2-s2', 'beginner-l2', 'beginner', 'How are you?', 'आप कैसे हैं?', 'easy', 2, 1),
  ('beginner-l2-s3', 'beginner-l2', 'beginner', 'I am fine, thank you.', 'मैं ठीक हूँ, धन्यवाद।', 'easy', 3, 1),
  ('beginner-l2-s4', 'beginner-l2', 'beginner', 'What is your name?', 'आपका नाम क्या है?', 'easy', 4, 1),
  ('beginner-l2-s5', 'beginner-l2', 'beginner', 'Where are you from?', 'आप कहाँ से हैं?', 'easy', 5, 1),
  ('beginner-l2-s6', 'beginner-l2', 'beginner', 'See you tomorrow.', 'कल मिलते हैं।', 'easy', 6, 1),
  ('beginner-l2-s7', 'beginner-l2', 'beginner', 'Have a nice day.', 'आपका दिन शुभ हो।', 'easy', 7, 1),
  ('beginner-l2-s8', 'beginner-l2', 'beginner', 'Welcome to our home.', 'हमारे घर में आपका स्वागत है।', 'medium', 8, 1),
  ('beginner-l2-s9', 'beginner-l2', 'beginner', 'Good evening, sir.', 'शुभ संध्या, सर।', 'easy', 9, 1),
  ('beginner-l2-s10', 'beginner-l2', 'beginner', 'Take care.', 'अपना ख्याल रखिए।', 'easy', 10, 1),
  ('beginner-l3-s1', 'beginner-l3', 'beginner', 'This is my father.', 'यह मेरे पिता हैं।', 'easy', 1, 1),
  ('beginner-l3-s2', 'beginner-l3', 'beginner', 'My mother is a teacher.', 'मेरी माँ शिक्षिका हैं।', 'medium', 2, 1),
  ('beginner-l3-s3', 'beginner-l3', 'beginner', 'I have one brother.', 'मेरा एक भाई है।', 'easy', 3, 1),
  ('beginner-l3-s4', 'beginner-l3', 'beginner', 'My sister lives in Mumbai.', 'मेरी बहन मुंबई में रहती है।', 'medium', 4, 1),
  ('beginner-l3-s5', 'beginner-l3', 'beginner', 'My grandmother tells good stories.', 'मेरी दादी अच्छी कहानियाँ सुनाती हैं।', 'medium', 5, 1),
  ('beginner-l3-s6', 'beginner-l3', 'beginner', 'We are a happy family.', 'हम एक खुशहाल परिवार हैं।', 'easy', 6, 1),
  ('beginner-l3-s7', 'beginner-l3', 'beginner', 'My uncle is a doctor.', 'मेरे चाचा डॉक्टर हैं।', 'medium', 7, 1),
  ('beginner-l3-s8', 'beginner-l3', 'beginner', 'Do you have children?', 'क्या आपके बच्चे हैं?', 'medium', 8, 1),
  ('beginner-l3-s9', 'beginner-l3', 'beginner', 'My cousin is my best friend.', 'मेरा कज़न मेरा सबसे अच्छा दोस्त है।', 'medium', 9, 1),
  ('beginner-l3-s10', 'beginner-l3', 'beginner', 'I love my parents.', 'मैं अपने माता-पिता से प्यार करता हूँ।', 'easy', 10, 1),
  ('beginner-l4-s1', 'beginner-l4', 'beginner', 'My house is in the city.', 'मेरा घर शहर में है।', 'easy', 1, 1),
  ('beginner-l4-s2', 'beginner-l4', 'beginner', 'We live in a flat.', 'हम एक फ्लैट में रहते हैं।', 'easy', 2, 1),
  ('beginner-l4-s3', 'beginner-l4', 'beginner', 'My room is upstairs.', 'मेरा कमरा ऊपर है।', 'medium', 3, 1),
  ('beginner-l4-s4', 'beginner-l4', 'beginner', 'The kitchen is small but nice.', 'रसोई छोटी है लेकिन अच्छी है।', 'medium', 4, 1),
  ('beginner-l4-s5', 'beginner-l4', 'beginner', 'I sleep in the bedroom.', 'मैं शयनकक्ष में सोता हूँ।', 'easy', 5, 1),
  ('beginner-l4-s6', 'beginner-l4', 'beginner', 'There is a garden in front of my house.', 'मेरे घर के सामने एक बगीचा है।', 'medium', 6, 1),
  ('beginner-l4-s7', 'beginner-l4', 'beginner', 'Please come inside.', 'कृपया अंदर आइए।', 'easy', 7, 1),
  ('beginner-l4-s8', 'beginner-l4', 'beginner', 'The house has two floors.', 'घर में दो मंज़िलें हैं।', 'medium', 8, 1),
  ('beginner-l4-s9', 'beginner-l4', 'beginner', 'We have a new sofa in the hall.', 'हमारे पास हॉल में नया सोफ़ा है।', 'medium', 9, 1),
  ('beginner-l4-s10', 'beginner-l4', 'beginner', 'My home is my comfort.', 'मेरा घर मेरा सुकून है।', 'easy', 10, 1),
  ('beginner-l5-s1', 'beginner-l5', 'beginner', 'I am hungry.', 'मुझे भूख लगी है।', 'easy', 1, 1),
  ('beginner-l5-s2', 'beginner-l5', 'beginner', 'What would you like to eat?', 'आप क्या खाना पसंद करेंगे?', 'medium', 2, 1),
  ('beginner-l5-s3', 'beginner-l5', 'beginner', 'I would like some tea.', 'मुझे चाय चाहिए।', 'easy', 3, 1),
  ('beginner-l5-s4', 'beginner-l5', 'beginner', 'This food is delicious.', 'यह खाना बहुत स्वादिष्ट है।', 'medium', 4, 1),
  ('beginner-l5-s5', 'beginner-l5', 'beginner', 'I like rice and dal.', 'मुझे चावल और दाल पसंद है।', 'easy', 5, 1),
  ('beginner-l5-s6', 'beginner-l5', 'beginner', 'Please pass the salt.', 'कृपया नमक दीजिए।', 'medium', 6, 1),
  ('beginner-l5-s7', 'beginner-l5', 'beginner', 'Breakfast is ready.', 'नाश्ता तैयार है।', 'easy', 7, 1),
  ('beginner-l5-s8', 'beginner-l5', 'beginner', 'I don''t eat meat.', 'मैं मांस नहीं खाता।', 'easy', 8, 1),
  ('beginner-l5-s9', 'beginner-l5', 'beginner', 'The water is cold.', 'पानी ठंडा है।', 'easy', 9, 1),
  ('beginner-l5-s10', 'beginner-l5', 'beginner', 'Thank you for the meal.', 'खाने के लिए धन्यवाद।', 'easy', 10, 1),
  ('beginner-l6-s1', 'beginner-l6', 'beginner', 'How much does this cost?', 'इसकी कितनी कीमत है?', 'easy', 1, 1),
  ('beginner-l6-s2', 'beginner-l6', 'beginner', 'This is too expensive.', 'यह बहुत महंगा है।', 'medium', 2, 1),
  ('beginner-l6-s3', 'beginner-l6', 'beginner', 'Do you have a smaller size?', 'क्या आपके पास छोटा साइज़ है?', 'medium', 3, 1),
  ('beginner-l6-s4', 'beginner-l6', 'beginner', 'I want to buy this shirt.', 'मैं यह शर्ट खरीदना चाहता हूँ।', 'medium', 4, 1),
  ('beginner-l6-s5', 'beginner-l6', 'beginner', 'Can I pay by card?', 'क्या मैं कार्ड से भुगतान कर सकता हूँ?', 'medium', 5, 1),
  ('beginner-l6-s6', 'beginner-l6', 'beginner', 'Please give me a discount.', 'कृपया मुझे छूट दीजिए।', 'medium', 6, 1),
  ('beginner-l6-s7', 'beginner-l6', 'beginner', 'I am just looking, thank you.', 'मैं बस देख रहा हूँ, धन्यवाद।', 'medium', 7, 1),
  ('beginner-l6-s8', 'beginner-l6', 'beginner', 'Where is the vegetable market?', 'सब्ज़ी मंडी कहाँ है?', 'medium', 8, 1),
  ('beginner-l6-s9', 'beginner-l6', 'beginner', 'I need one kilo of sugar.', 'मुझे एक किलो चीनी चाहिए।', 'medium', 9, 1),
  ('beginner-l6-s10', 'beginner-l6', 'beginner', 'Please pack it nicely.', 'कृपया इसे अच्छे से पैक करें।', 'medium', 10, 1),
  ('beginner-l7-s1', 'beginner-l7', 'beginner', 'I wake up at six.', 'मैं छह बजे उठता हूँ।', 'easy', 1, 1),
  ('beginner-l7-s2', 'beginner-l7', 'beginner', 'I brush my teeth every morning.', 'मैं हर सुबह दाँत साफ़ करता हूँ।', 'medium', 2, 1),
  ('beginner-l7-s3', 'beginner-l7', 'beginner', 'I take a shower.', 'मैं नहाता हूँ।', 'easy', 3, 1),
  ('beginner-l7-s4', 'beginner-l7', 'beginner', 'I eat breakfast at eight.', 'मैं आठ बजे नाश्ता करता हूँ।', 'medium', 4, 1),
  ('beginner-l7-s5', 'beginner-l7', 'beginner', 'I go to work by bus.', 'मैं बस से काम पर जाता हूँ।', 'medium', 5, 1),
  ('beginner-l7-s6', 'beginner-l7', 'beginner', 'I come home at six in the evening.', 'मैं शाम छह बजे घर आता हूँ।', 'medium', 6, 1),
  ('beginner-l7-s7', 'beginner-l7', 'beginner', 'I watch TV after dinner.', 'मैं खाने के बाद टीवी देखता हूँ।', 'medium', 7, 1),
  ('beginner-l7-s8', 'beginner-l7', 'beginner', 'I go to bed at eleven.', 'मैं ग्यारह बजे सोता हूँ।', 'medium', 8, 1),
  ('beginner-l7-s9', 'beginner-l7', 'beginner', 'I drink two glasses of water.', 'मैं दो गिलास पानी पीता हूँ।', 'medium', 9, 1),
  ('beginner-l7-s10', 'beginner-l7', 'beginner', 'My routine is simple.', 'मेरी दिनचर्या सरल है।', 'easy', 10, 1),
  ('beginner-l8-s1', 'beginner-l8', 'beginner', 'He is my best friend.', 'वह मेरा सबसे अच्छा दोस्त है।', 'easy', 1, 1),
  ('beginner-l8-s2', 'beginner-l8', 'beginner', 'We play cricket together.', 'हम साथ में क्रिकेट खेलते हैं।', 'medium', 2, 1),
  ('beginner-l8-s3', 'beginner-l8', 'beginner', 'She helps me with my work.', 'वह मेरे काम में मेरी मदद करती है।', 'medium', 3, 1),
  ('beginner-l8-s4', 'beginner-l8', 'beginner', 'We have known each other for ten years.', 'हम एक-दूसरे को दस साल से जानते हैं।', 'hard', 4, 1),
  ('beginner-l8-s5', 'beginner-l8', 'beginner', 'My friends are coming tonight.', 'मेरे दोस्त आज रात आ रहे हैं।', 'medium', 5, 1),
  ('beginner-l8-s6', 'beginner-l8', 'beginner', 'Let''s meet on Sunday.', 'चलो रविवार को मिलते हैं।', 'easy', 6, 1),
  ('beginner-l8-s7', 'beginner-l8', 'beginner', 'I trust my friends.', 'मैं अपने दोस्तों पर भरोसा करता हूँ।', 'medium', 7, 1),
  ('beginner-l8-s8', 'beginner-l8', 'beginner', 'A friend in need is a friend indeed.', 'सच्चा दोस्त मुश्किल में काम आता है।', 'hard', 8, 1),
  ('beginner-l8-s9', 'beginner-l8', 'beginner', 'We share everything.', 'हम सब कुछ साझा करते हैं।', 'medium', 9, 1),
  ('beginner-l8-s10', 'beginner-l8', 'beginner', 'I am lucky to have good friends.', 'मैं भाग्यशाली हूँ कि मेरे अच्छे दोस्त हैं।', 'medium', 10, 1),
  ('beginner-l9-s1', 'beginner-l9', 'beginner', 'Hello, who is speaking?', 'नमस्ते, कौन बोल रहा है?', 'easy', 1, 1),
  ('beginner-l9-s2', 'beginner-l9', 'beginner', 'Can I speak to Ramesh?', 'क्या मैं रमेश से बात कर सकता हूँ?', 'medium', 2, 1),
  ('beginner-l9-s3', 'beginner-l9', 'beginner', 'Please hold on.', 'कृपया थोड़ा रुकिए।', 'medium', 3, 1),
  ('beginner-l9-s4', 'beginner-l9', 'beginner', 'He is not at home right now.', 'वह अभी घर पर नहीं हैं।', 'medium', 4, 1),
  ('beginner-l9-s5', 'beginner-l9', 'beginner', 'Can I leave a message?', 'क्या मैं एक संदेश छोड़ सकता हूँ?', 'medium', 5, 1),
  ('beginner-l9-s6', 'beginner-l9', 'beginner', 'I will call you back.', 'मैं आपको वापस कॉल करूँगा।', 'easy', 6, 1),
  ('beginner-l9-s7', 'beginner-l9', 'beginner', 'Sorry, I dialed the wrong number.', 'माफ़ कीजिए, मैंने गलत नंबर मिलाया।', 'medium', 7, 1),
  ('beginner-l9-s8', 'beginner-l9', 'beginner', 'The line is busy.', 'लाइन व्यस्त है।', 'easy', 8, 1),
  ('beginner-l9-s9', 'beginner-l9', 'beginner', 'Please speak slowly.', 'कृपया धीरे बोलिए।', 'medium', 9, 1),
  ('beginner-l9-s10', 'beginner-l9', 'beginner', 'Thanks for calling.', 'कॉल करने के लिए धन्यवाद।', 'easy', 10, 1),
  ('beginner-l10-s1', 'beginner-l10', 'beginner', 'What are you doing?', 'आप क्या कर रहे हैं?', 'easy', 1, 1),
  ('beginner-l10-s2', 'beginner-l10', 'beginner', 'I am reading a book.', 'मैं एक किताब पढ़ रहा हूँ।', 'easy', 2, 1),
  ('beginner-l10-s3', 'beginner-l10', 'beginner', 'Let''s go for a walk.', 'चलो टहलने चलते हैं।', 'easy', 3, 1),
  ('beginner-l10-s4', 'beginner-l10', 'beginner', 'I am tired today.', 'मैं आज थका हुआ हूँ।', 'easy', 4, 1),
  ('beginner-l10-s5', 'beginner-l10', 'beginner', 'The weather is nice today.', 'आज मौसम अच्छा है।', 'medium', 5, 1),
  ('beginner-l10-s6', 'beginner-l10', 'beginner', 'I don''t know.', 'मुझे नहीं पता।', 'easy', 6, 1),
  ('beginner-l10-s7', 'beginner-l10', 'beginner', 'I think it will rain.', 'मुझे लगता है बारिश होगी।', 'medium', 7, 1),
  ('beginner-l10-s8', 'beginner-l10', 'beginner', 'Please wait for me.', 'कृपया मेरा इंतज़ार कीजिए।', 'easy', 8, 1),
  ('beginner-l10-s9', 'beginner-l10', 'beginner', 'Congratulations on your success.', 'आपकी सफलता पर बधाई।', 'medium', 9, 1),
  ('beginner-l10-s10', 'beginner-l10', 'beginner', 'Let''s meet again soon.', 'चलो जल्दी फिर मिलते हैं।', 'easy', 10, 1),
  ('intermediate-l1-s1', 'intermediate-l1', 'intermediate', 'How was your day?', 'आपका दिन कैसा रहा?', 'easy', 1, 0),
  ('intermediate-l1-s2', 'intermediate-l1', 'intermediate', 'I had a busy day at work.', 'काम पर मेरा दिन व्यस्त रहा।', 'medium', 2, 0),
  ('intermediate-l1-s3', 'intermediate-l1', 'intermediate', 'What do you do on weekends?', 'आप वीकेंड पर क्या करते हैं?', 'medium', 3, 0),
  ('intermediate-l1-s4', 'intermediate-l1', 'intermediate', 'I usually relax at home.', 'मैं आमतौर पर घर पर आराम करता हूँ।', 'medium', 4, 0),
  ('intermediate-l1-s5', 'intermediate-l1', 'intermediate', 'Did you watch the match last night?', 'क्या आपने कल रात मैच देखा?', 'medium', 5, 0),
  ('intermediate-l1-s6', 'intermediate-l1', 'intermediate', 'The movie was quite interesting.', 'फ़िल्म काफ़ी दिलचस्प थी।', 'medium', 6, 0),
  ('intermediate-l1-s7', 'intermediate-l1', 'intermediate', 'Let''s plan something this weekend.', 'चलो इस वीकेंड कुछ प्लान करते हैं।', 'medium', 7, 0),
  ('intermediate-l1-s8', 'intermediate-l1', 'intermediate', 'I am not feeling well today.', 'मैं आज ठीक नहीं महसूस कर रहा हूँ।', 'medium', 8, 0),
  ('intermediate-l1-s9', 'intermediate-l1', 'intermediate', 'Take rest and get well soon.', 'आराम करो और जल्दी ठीक हो जाओ।', 'medium', 9, 0),
  ('intermediate-l1-s10', 'intermediate-l1', 'intermediate', 'I will join you later.', 'मैं बाद में आपसे जुड़ूँगा।', 'medium', 10, 0),
  ('intermediate-l2-s1', 'intermediate-l2', 'intermediate', 'I have a meeting at ten.', 'मेरी दस बजे मीटिंग है।', 'easy', 1, 0),
  ('intermediate-l2-s2', 'intermediate-l2', 'intermediate', 'Please send me the report by evening.', 'कृपया मुझे शाम तक रिपोर्ट भेज दीजिए।', 'medium', 2, 0),
  ('intermediate-l2-s3', 'intermediate-l2', 'intermediate', 'The deadline is on Friday.', 'आखिरी तारीख शुक्रवार है।', 'medium', 3, 0),
  ('intermediate-l2-s4', 'intermediate-l2', 'intermediate', 'I will finish this task today.', 'मैं आज यह काम पूरा करूँगा।', 'medium', 4, 0),
  ('intermediate-l2-s5', 'intermediate-l2', 'intermediate', 'Can we reschedule the meeting?', 'क्या हम मीटिंग को आगे बढ़ा सकते हैं?', 'medium', 5, 0),
  ('intermediate-l2-s6', 'intermediate-l2', 'intermediate', 'I need your help with this project.', 'मुझे इस प्रोजेक्ट में आपकी मदद चाहिए।', 'medium', 6, 0),
  ('intermediate-l2-s7', 'intermediate-l2', 'intermediate', 'The client approved our plan.', 'क्लाइंट ने हमारी योजना को मंज़ूरी दे दी।', 'medium', 7, 0),
  ('intermediate-l2-s8', 'intermediate-l2', 'intermediate', 'I am working on the presentation.', 'मैं प्रेजेंटेशन पर काम कर रहा हूँ।', 'medium', 8, 0),
  ('intermediate-l2-s9', 'intermediate-l2', 'intermediate', 'Please update me on the progress.', 'कृपया मुझे प्रगति की जानकारी देते रहिए।', 'medium', 9, 0),
  ('intermediate-l2-s10', 'intermediate-l2', 'intermediate', 'Great work, keep it up.', 'बहुत अच्छा काम, ऐसे ही जारी रखिए।', 'easy', 10, 0),
  ('intermediate-l3-s1', 'intermediate-l3', 'intermediate', 'I am planning a trip to Goa.', 'मैं गोवा की यात्रा की योजना बना रहा हूँ।', 'medium', 1, 0),
  ('intermediate-l3-s2', 'intermediate-l3', 'intermediate', 'The train departs at eight.', 'ट्रेन आठ बजे रवाना होती है।', 'medium', 2, 0),
  ('intermediate-l3-s3', 'intermediate-l3', 'intermediate', 'I booked a hotel near the beach.', 'मैंने समुद्र तट के पास होटल बुक किया।', 'medium', 3, 0),
  ('intermediate-l3-s4', 'intermediate-l3', 'intermediate', 'It was a wonderful experience.', 'यह एक अद्भुत अनुभव था।', 'medium', 4, 0),
  ('intermediate-l3-s5', 'intermediate-l3', 'intermediate', 'We had a great time at the party.', 'हमने पार्टी में बहुत मज़ा किया।', 'medium', 5, 0),
  ('intermediate-l3-s6', 'intermediate-l3', 'intermediate', 'She is very friendly and helpful.', 'वह बहुत मिलनसार और मददगार है।', 'medium', 6, 0),
  ('intermediate-l3-s7', 'intermediate-l3', 'intermediate', 'Could you take a photo of us?', 'क्या आप हमारी एक फोटो खींच सकते हैं?', 'medium', 7, 0),
  ('intermediate-l3-s8', 'intermediate-l3', 'intermediate', 'The food here is amazing.', 'यहाँ का खाना बहुत बढ़िया है।', 'easy', 8, 0),
  ('intermediate-l3-s9', 'intermediate-l3', 'intermediate', 'I will visit you next month.', 'मैं अगले महीने आपसे मिलने आऊँगा।', 'medium', 9, 0),
  ('intermediate-l3-s10', 'intermediate-l3', 'intermediate', 'It was nice talking to you.', 'आपसे बात करके अच्छा लगा।', 'medium', 10, 0),
  ('intermediate-l4-s1', 'intermediate-l4', 'intermediate', 'In my opinion, this is the best option.', 'मेरी राय में, यह सबसे अच्छा विकल्प है।', 'hard', 1, 0),
  ('intermediate-l4-s2', 'intermediate-l4', 'intermediate', 'I completely agree with you.', 'मैं आपसे पूरी तरह सहमत हूँ।', 'medium', 2, 0),
  ('intermediate-l4-s3', 'intermediate-l4', 'intermediate', 'I am not sure about that.', 'मुझे उस बारे में पक्का नहीं पता।', 'medium', 3, 0),
  ('intermediate-l4-s4', 'intermediate-l4', 'intermediate', 'I think we should try again.', 'मुझे लगता है हमें फिर कोशिश करनी चाहिए।', 'medium', 4, 0),
  ('intermediate-l4-s5', 'intermediate-l4', 'intermediate', 'From my experience, practice is the key.', 'मेरे अनुभव से, अभ्यास ही कुंजी है।', 'hard', 5, 0),
  ('intermediate-l4-s6', 'intermediate-l4', 'intermediate', 'That sounds like a good idea.', 'यह एक अच्छा विचार लग रहा है।', 'medium', 6, 0),
  ('intermediate-l4-s7', 'intermediate-l4', 'intermediate', 'I used to be afraid of speaking English.', 'मुझे पहले अंग्रेज़ी बोलने से डर लगता था।', 'hard', 7, 0),
  ('intermediate-l4-s8', 'intermediate-l4', 'intermediate', 'Now I enjoy talking in English.', 'अब मुझे अंग्रेज़ी में बात करने में मज़ा आता है।', 'medium', 8, 0),
  ('intermediate-l4-s9', 'intermediate-l4', 'intermediate', 'It was difficult in the beginning.', 'शुरुआत में यह मुश्किल था।', 'medium', 9, 0),
  ('intermediate-l4-s10', 'intermediate-l4', 'intermediate', 'I believe in small daily practice.', 'मैं छोटे दैनिक अभ्यास में विश्वास करता हूँ।', 'hard', 10, 0),
  ('intermediate-l5-s1', 'intermediate-l5', 'intermediate', 'Could you do me a favour?', 'क्या आप मेरा एक काम कर सकते हैं?', 'medium', 1, 0),
  ('intermediate-l5-s2', 'intermediate-l5', 'intermediate', 'Would you mind helping me?', 'क्या आप मेरी मदद करेंगे?', 'medium', 2, 0),
  ('intermediate-l5-s3', 'intermediate-l5', 'intermediate', 'I was walking home when I saw him.', 'मैं घर जा रहा था तभी मैंने उसे देखा।', 'hard', 3, 0),
  ('intermediate-l5-s4', 'intermediate-l5', 'intermediate', 'Once upon a time, there was a king.', 'एक समय की बात है, एक राजा था।', 'medium', 4, 0),
  ('intermediate-l5-s5', 'intermediate-l5', 'intermediate', 'The story has a happy ending.', 'कहानी का अंत खुशहाल है।', 'medium', 5, 0),
  ('intermediate-l5-s6', 'intermediate-l5', 'intermediate', 'Let me tell you what happened yesterday.', 'मैं आपको बताता हूँ कल क्या हुआ।', 'hard', 6, 0),
  ('intermediate-l5-s7', 'intermediate-l5', 'intermediate', 'First, we prepared the food.', 'पहले, हमने खाना तैयार किया।', 'medium', 7, 0),
  ('intermediate-l5-s8', 'intermediate-l5', 'intermediate', 'After that, we went to the market.', 'उसके बाद, हम बाज़ार गए।', 'medium', 8, 0),
  ('intermediate-l5-s9', 'intermediate-l5', 'intermediate', 'Finally, we reached home safely.', 'आखिरकार, हम सुरक्षित घर पहुँच गए।', 'medium', 9, 0),
  ('intermediate-l5-s10', 'intermediate-l5', 'intermediate', 'It was an unforgettable day.', 'वह एक अविस्मरणीय दिन था।', 'hard', 10, 0),
  ('advanced-l1-s1', 'advanced-l1', 'advanced', 'Let''s begin today''s meeting.', 'चलिए आज की मीटिंग शुरू करते हैं।', 'medium', 1, 0),
  ('advanced-l1-s2', 'advanced-l1', 'advanced', 'I would like to present the quarterly results.', 'मैं तिमाही परिणाम प्रस्तुत करना चाहूँगा।', 'hard', 2, 0),
  ('advanced-l1-s3', 'advanced-l1', 'advanced', 'As you can see, our sales have increased.', 'जैसा कि आप देख सकते हैं, हमारी बिक्री बढ़ी है।', 'hard', 3, 0),
  ('advanced-l1-s4', 'advanced-l1', 'advanced', 'Let me highlight the key points.', 'मुझे मुख्य बिंदुओं पर प्रकाश डालने दीजिए।', 'medium', 4, 0),
  ('advanced-l1-s5', 'advanced-l1', 'advanced', 'We need to focus on the customer experience.', 'हमें ग्राहक अनुभव पर ध्यान देने की ज़रूरत है।', 'hard', 5, 0),
  ('advanced-l1-s6', 'advanced-l1', 'advanced', 'Let''s move on to the next agenda item.', 'चलिए अगले एजेंडे पर चलते हैं।', 'hard', 6, 0),
  ('advanced-l1-s7', 'advanced-l1', 'advanced', 'Are there any questions from the audience?', 'क्या श्रोताओं की ओर से कोई प्रश्न हैं?', 'hard', 7, 0),
  ('advanced-l1-s8', 'advanced-l1', 'advanced', 'Let me summarize what we discussed.', 'मैं संक्षेप में बताऊँ कि हमने क्या चर्चा की।', 'hard', 8, 0),
  ('advanced-l1-s9', 'advanced-l1', 'advanced', 'I appreciate everyone''s contribution.', 'मैं सभी के योगदान की सराहना करता हूँ।', 'medium', 9, 0),
  ('advanced-l1-s10', 'advanced-l1', 'advanced', 'Thank you for your attention.', 'आपके ध्यान के लिए धन्यवाद।', 'medium', 10, 0),
  ('advanced-l2-s1', 'advanced-l2', 'advanced', 'We are offering a competitive price.', 'हम एक प्रतिस्पर्धी मूल्य दे रहे हैं।', 'medium', 1, 0),
  ('advanced-l2-s2', 'advanced-l2', 'advanced', 'Can you improve this offer?', 'क्या आप यह ऑफ़र बेहतर कर सकते हैं?', 'medium', 2, 0),
  ('advanced-l2-s3', 'advanced-l2', 'advanced', 'Let''s find a middle ground.', 'चलिए एक समझौता निकालते हैं।', 'medium', 3, 0),
  ('advanced-l2-s4', 'advanced-l2', 'advanced', 'This deal is beneficial for both sides.', 'यह सौदा दोनों पक्षों के लिए फायदेमंद है।', 'hard', 4, 0),
  ('advanced-l2-s5', 'advanced-l2', 'advanced', 'I understand your concern, however...', 'मैं आपकी चिंता समझता हूँ, हालाँकि...', 'hard', 5, 0),
  ('advanced-l2-s6', 'advanced-l2', 'advanced', 'We can add more value for the same price.', 'हम उसी कीमत पर और मूल्य जोड़ सकते हैं।', 'hard', 6, 0),
  ('advanced-l2-s7', 'advanced-l2', 'advanced', 'Think about the long-term benefits.', 'दीर्घकालिक लाभों के बारे में सोचिए।', 'hard', 7, 0),
  ('advanced-l2-s8', 'advanced-l2', 'advanced', 'If you order today, we can offer a discount.', 'यदि आप आज ऑर्डर करते हैं, तो हम छूट दे सकते हैं।', 'hard', 8, 0),
  ('advanced-l2-s9', 'advanced-l2', 'advanced', 'Let me discuss this with my team.', 'मुझे अपनी टीम से इस पर चर्चा करने दीजिए।', 'medium', 9, 0),
  ('advanced-l2-s10', 'advanced-l2', 'advanced', 'I am confident we can reach an agreement.', 'मुझे विश्वास है हम एक समझौते पर पहुँच सकते हैं।', 'hard', 10, 0),
  ('advanced-l3-s1', 'advanced-l3', 'advanced', 'I am writing regarding the contract renewal.', 'मैं अनुबंध नवीनीकरण के संबंध में लिख रहा हूँ।', 'hard', 1, 0),
  ('advanced-l3-s2', 'advanced-l3', 'advanced', 'Please find the attached document.', 'संलग्न दस्तावेज़ देखिए।', 'medium', 2, 0),
  ('advanced-l3-s3', 'advanced-l3', 'advanced', 'Could you clarify this point?', 'क्या आप इस बिंदु को स्पष्ट कर सकते हैं?', 'medium', 3, 0),
  ('advanced-l3-s4', 'advanced-l3', 'advanced', 'I would appreciate your feedback.', 'मैं आपकी प्रतिक्रिया की सराहना करूँगा।', 'medium', 4, 0),
  ('advanced-l3-s5', 'advanced-l3', 'advanced', 'We need to align on the timeline.', 'हमें समय-सीमा पर सहमत होना होगा।', 'hard', 5, 0),
  ('advanced-l3-s6', 'advanced-l3', 'advanced', 'Let''s set up a call to discuss this.', 'इस पर चर्चा करने के लिए चलिए एक कॉल तय करते हैं।', 'hard', 6, 0),
  ('advanced-l3-s7', 'advanced-l3', 'advanced', 'The report is due by the end of the week.', 'रिपोर्ट सप्ताह के अंत तक जमा करनी है।', 'hard', 7, 0),
  ('advanced-l3-s8', 'advanced-l3', 'advanced', 'I look forward to your response.', 'मैं आपके उत्तर की प्रतीक्षा करूँगा।', 'medium', 8, 0),
  ('advanced-l3-s9', 'advanced-l3', 'advanced', 'Thank you for the opportunity.', 'अवसर के लिए धन्यवाद।', 'medium', 9, 0),
  ('advanced-l3-s10', 'advanced-l3', 'advanced', 'Let''s keep this conversation professional.', 'इस बातचीत को पेशेवर बनाए रखें।', 'hard', 10, 0),
  ('daily-l1-s1', 'daily-l1', 'daily', 'I am going to the market.', 'मैं बाज़ार जा रहा हूँ।', 'easy', 1, 0),
  ('daily-l1-s2', 'daily-l1', 'daily', 'The food is on the table.', 'खाना मेज़ पर है।', 'easy', 2, 0),
  ('daily-l1-s3', 'daily-l1', 'daily', 'Please switch off the lights.', 'कृपया लाइटें बंद कर दीजिए।', 'medium', 3, 0),
  ('daily-l1-s4', 'daily-l1', 'daily', 'I will be home by seven.', 'मैं सात बजे तक घर आ जाऊँगा।', 'medium', 4, 0),
  ('daily-l1-s5', 'daily-l1', 'daily', 'Where are my keys?', 'मेरी चाबियाँ कहाँ हैं?', 'easy', 5, 0),
  ('daily-l1-s6', 'daily-l1', 'daily', 'The milk is finished.', 'दूध खत्म हो गया है।', 'easy', 6, 0),
  ('daily-l1-s7', 'daily-l1', 'daily', 'Can you help me clean the house?', 'क्या आप घर की सफ़ाई में मेरी मदद करेंगे?', 'medium', 7, 0),
  ('daily-l1-s8', 'daily-l1', 'daily', 'The tap is leaking.', 'नल से पानी टपक रहा है।', 'medium', 8, 0),
  ('daily-l1-s9', 'daily-l1', 'daily', 'I need to buy groceries.', 'मुझे किराने का सामान खरीदना है।', 'medium', 9, 0),
  ('daily-l1-s10', 'daily-l1', 'daily', 'Dinner is ready, come and eat.', 'खाना तैयार है, आकर खाइए।', 'medium', 10, 0),
  ('daily-l2-s1', 'daily-l2', 'daily', 'I want to exchange this item.', 'मैं यह वस्तु बदलना चाहता हूँ।', 'medium', 1, 0),
  ('daily-l2-s2', 'daily-l2', 'daily', 'Do you have this in another colour?', 'क्या यह आपके पास दूसरे रंग में है?', 'medium', 2, 0),
  ('daily-l2-s3', 'daily-l2', 'daily', 'Please give me the bill.', 'कृपया मुझे बिल दीजिए।', 'easy', 3, 0),
  ('daily-l2-s4', 'daily-l2', 'daily', 'A table for two, please.', 'दो लोगों के लिए एक टेबल, कृपया।', 'medium', 4, 0),
  ('daily-l2-s5', 'daily-l2', 'daily', 'Can I see the menu?', 'क्या मैं मेन्यू देख सकता हूँ?', 'easy', 5, 0),
  ('daily-l2-s6', 'daily-l2', 'daily', 'I ordered a veg thali.', 'मैंने वेज थाली ऑर्डर की थी।', 'medium', 6, 0),
  ('daily-l2-s7', 'daily-l2', 'daily', 'This dish is not what I ordered.', 'यह व्यंजन वह नहीं है जो मैंने ऑर्डर किया था।', 'medium', 7, 0),
  ('daily-l2-s8', 'daily-l2', 'daily', 'Please bring some water.', 'कृपया थोड़ा पानी लाइए।', 'easy', 8, 0),
  ('daily-l2-s9', 'daily-l2', 'daily', 'The food was very tasty.', 'खाना बहुत स्वादिष्ट था।', 'easy', 9, 0),
  ('daily-l2-s10', 'daily-l2', 'daily', 'Can I get the parcel?', 'क्या मैं पार्सल ले सकता हूँ?', 'medium', 10, 0),
  ('daily-l3-s1', 'daily-l3', 'daily', 'Where is the nearest bus stop?', 'सबसे नज़दीकी बस स्टॉप कहाँ है?', 'medium', 1, 0),
  ('daily-l3-s2', 'daily-l3', 'daily', 'How do I reach the railway station?', 'मैं रेलवे स्टेशन कैसे पहुँचूँ?', 'medium', 2, 0),
  ('daily-l3-s3', 'daily-l3', 'daily', 'Is it far from here?', 'क्या यह यहाँ से दूर है?', 'easy', 3, 0),
  ('daily-l3-s4', 'daily-l3', 'daily', 'Turn left at the next crossing.', 'अगले चौराहे पर बाएँ मुड़िए।', 'medium', 4, 0),
  ('daily-l3-s5', 'daily-l3', 'daily', 'Go straight for two kilometres.', 'दो किलोमीटर सीधे जाइए।', 'medium', 5, 0),
  ('daily-l3-s6', 'daily-l3', 'daily', 'Please drop me at this address.', 'कृपया मुझे इस पते पर छोड़ दीजिए।', 'medium', 6, 0),
  ('daily-l3-s7', 'daily-l3', 'daily', 'Which platform does the train leave from?', 'ट्रेन किस प्लेटफॉर्म से चलती है?', 'hard', 7, 0),
  ('daily-l3-s8', 'daily-l3', 'daily', 'I missed my bus.', 'मेरी बस छूट गई।', 'easy', 8, 0),
  ('daily-l3-s9', 'daily-l3', 'daily', 'Can I book a ticket online?', 'क्या मैं ऑनलाइन टिकट बुक कर सकता हूँ?', 'medium', 9, 0),
  ('daily-l3-s10', 'daily-l3', 'daily', 'The journey took three hours.', 'यात्रा में तीन घंटे लगे।', 'medium', 10, 0),
  ('daily-l4-s1', 'daily-l4', 'daily', 'I want to open a savings account.', 'मैं बचत खाता खोलना चाहता हूँ।', 'hard', 1, 0),
  ('daily-l4-s2', 'daily-l4', 'daily', 'I need to deposit this cheque.', 'मुझे यह चेक जमा करना है।', 'medium', 2, 0),
  ('daily-l4-s3', 'daily-l4', 'daily', 'What is the current exchange rate?', 'वर्तमान विनिमय दर क्या है?', 'hard', 3, 0),
  ('daily-l4-s4', 'daily-l4', 'daily', 'I have an appointment with the doctor.', 'मेरी डॉक्टर से अपॉइंटमेंट है।', 'medium', 4, 0),
  ('daily-l4-s5', 'daily-l4', 'daily', 'I am not feeling well.', 'मैं ठीक महसूस नहीं कर रहा हूँ।', 'easy', 5, 0),
  ('daily-l4-s6', 'daily-l4', 'daily', 'I have a headache and fever.', 'मुझे सिरदर्द और बुखार है।', 'medium', 6, 0),
  ('daily-l4-s7', 'daily-l4', 'daily', 'How often should I take this medicine?', 'मुझे यह दवा कितनी बार लेनी चाहिए?', 'hard', 7, 0),
  ('daily-l4-s8', 'daily-l4', 'daily', 'Do I need a test?', 'क्या मुझे कोई जाँच करानी होगी?', 'medium', 8, 0),
  ('daily-l4-s9', 'daily-l4', 'daily', 'Where is the pharmacy?', 'फार्मेसी कहाँ है?', 'medium', 9, 0),
  ('daily-l4-s10', 'daily-l4', 'daily', 'I am feeling better now.', 'मैं अब बेहतर महसूस कर रहा हूँ।', 'easy', 10, 0),
  ('daily-l5-s1', 'daily-l5', 'daily', 'I will send you the details on WhatsApp.', 'मैं आपको व्हाट्सएप पर विवरण भेजूँगा।', 'medium', 1, 0),
  ('daily-l5-s2', 'daily-l5', 'daily', 'Did you receive my message?', 'क्या आपको मेरा संदेश मिला?', 'medium', 2, 0),
  ('daily-l5-s3', 'daily-l5', 'daily', 'Please share your location.', 'कृपया अपना लोकेशन साझा करें।', 'medium', 3, 0),
  ('daily-l5-s4', 'daily-l5', 'daily', 'I am on a call right now.', 'मैं अभी कॉल पर हूँ।', 'medium', 4, 0),
  ('daily-l5-s5', 'daily-l5', 'daily', 'Text me when you reach home.', 'घर पहुँचकर मुझे मैसेज करना।', 'medium', 5, 0),
  ('daily-l5-s6', 'daily-l5', 'daily', 'The network is very slow here.', 'यहाँ नेटवर्क बहुत धीमा है।', 'medium', 6, 0),
  ('daily-l5-s7', 'daily-l5', 'daily', 'Can we video call later?', 'क्या हम बाद में वीडियो कॉल कर सकते हैं?', 'medium', 7, 0),
  ('daily-l5-s8', 'daily-l5', 'daily', 'I have forwarded the file to you.', 'मैंने फ़ाइल आपको फॉरवर्ड कर दी है।', 'medium', 8, 0),
  ('daily-l5-s9', 'daily-l5', 'daily', 'Please unmute yourself.', 'कृपया अपना माइक ऑन कीजिए।', 'medium', 9, 0),
  ('daily-l5-s10', 'daily-l5', 'daily', 'Can you hear me clearly?', 'क्या आप मुझे साफ़ सुन पा रहे हैं?', 'medium', 10, 0),
  ('interview-l1-s1', 'interview-l1', 'interview', 'Please tell me about yourself.', 'कृपया अपने बारे में बताइए।', 'medium', 1, 0),
  ('interview-l1-s2', 'interview-l1', 'interview', 'I am a graduate in commerce.', 'मैं वाणिज्य में स्नातक हूँ।', 'medium', 2, 0),
  ('interview-l1-s3', 'interview-l1', 'interview', 'I have three years of work experience.', 'मुझे तीन साल का कार्य अनुभव है।', 'medium', 3, 0),
  ('interview-l1-s4', 'interview-l1', 'interview', 'I am a quick learner.', 'मैं जल्दी सीखने वाला व्यक्ति हूँ।', 'medium', 4, 0),
  ('interview-l1-s5', 'interview-l1', 'interview', 'I enjoy working in a team.', 'मुझे टीम में काम करना पसंद है।', 'medium', 5, 0),
  ('interview-l1-s6', 'interview-l1', 'interview', 'My goal is to grow in this field.', 'मेरा लक्ष्य इस क्षेत्र में आगे बढ़ना है।', 'hard', 6, 0),
  ('interview-l1-s7', 'interview-l1', 'interview', 'I am passionate about my work.', 'मैं अपने काम के प्रति जुनूनी हूँ।', 'hard', 7, 0),
  ('interview-l1-s8', 'interview-l1', 'interview', 'I have completed a course in digital marketing.', 'मैंने डिजिटल मार्केटिंग का कोर्स पूरा किया है।', 'hard', 8, 0),
  ('interview-l1-s9', 'interview-l1', 'interview', 'I am looking for a challenging role.', 'मैं एक चुनौतीपूर्ण भूमिका की तलाश में हूँ।', 'hard', 9, 0),
  ('interview-l1-s10', 'interview-l1', 'interview', 'I am confident about my skills.', 'मैं अपने कौशल के प्रति आश्वस्त हूँ।', 'medium', 10, 0),
  ('interview-l2-s1', 'interview-l2', 'interview', 'What are your strengths?', 'आपकी ताकतें क्या हैं?', 'medium', 1, 0),
  ('interview-l2-s2', 'interview-l2', 'interview', 'My strength is my dedication to work.', 'मेरी ताकत काम के प्रति मेरी लगन है।', 'hard', 2, 0),
  ('interview-l2-s3', 'interview-l2', 'interview', 'What is your biggest weakness?', 'आपकी सबसे बड़ी कमज़ोरी क्या है?', 'medium', 3, 0),
  ('interview-l2-s4', 'interview-l2', 'interview', 'I sometimes hesitate to say no.', 'मुझे कभी-कभी ''ना'' कहने में झिझक होती है।', 'hard', 4, 0),
  ('interview-l2-s5', 'interview-l2', 'interview', 'Why do you want this job?', 'आप यह नौकरी क्यों चाहते हैं?', 'medium', 5, 0),
  ('interview-l2-s6', 'interview-l2', 'interview', 'This role matches my skills perfectly.', 'यह भूमिका मेरे कौशल से बिल्कुल मेल खाती है।', 'hard', 6, 0),
  ('interview-l2-s7', 'interview-l2', 'interview', 'Where do you see yourself in five years?', 'आप खुद को पाँच साल में कहाँ देखते हैं?', 'hard', 7, 0),
  ('interview-l2-s8', 'interview-l2', 'interview', 'I see myself growing with this company.', 'मैं खुद को इस कंपनी के साथ बढ़ता हुआ देखता हूँ।', 'hard', 8, 0),
  ('interview-l2-s9', 'interview-l2', 'interview', 'What are your salary expectations?', 'आपकी वेतन अपेक्षाएँ क्या हैं?', 'medium', 9, 0),
  ('interview-l2-s10', 'interview-l2', 'interview', 'I expect a salary in line with the market.', 'मैं बाज़ार के अनुरूप वेतन की उम्मीद करता हूँ।', 'hard', 10, 0),
  ('interview-l3-s1', 'interview-l3', 'interview', 'How do you handle pressure?', 'आप दबाव कैसे संभालते हैं?', 'medium', 1, 0),
  ('interview-l3-s2', 'interview-l3', 'interview', 'I stay calm and prioritise my tasks.', 'मैं शांत रहता हूँ और अपने काम को प्राथमिकता देता हूँ।', 'hard', 2, 0),
  ('interview-l3-s3', 'interview-l3', 'interview', 'Tell me about a challenge you faced.', 'आपने किस चुनौती का सामना किया, बताइए।', 'hard', 3, 0),
  ('interview-l3-s4', 'interview-l3', 'interview', 'I once handled a difficult customer.', 'एक बार मैंने एक मुश्किल ग्राहक को संभाला।', 'hard', 4, 0),
  ('interview-l3-s5', 'interview-l3', 'interview', 'How do you manage deadlines?', 'आप समय-सीमा कैसे प्रबंधित करते हैं?', 'medium', 5, 0),
  ('interview-l3-s6', 'interview-l3', 'interview', 'I plan my work and follow a schedule.', 'मैं अपने काम की योजना बनाता हूँ और समय-सारणी का पालन करता हूँ।', 'hard', 6, 0),
  ('interview-l3-s7', 'interview-l3', 'interview', 'Why should we hire you?', 'हमें आपको क्यों नियुक्त करना चाहिए?', 'medium', 7, 0),
  ('interview-l3-s8', 'interview-l3', 'interview', 'I bring both skill and sincerity to work.', 'मैं काम में कौशल और ईमानदारी दोनों लाता हूँ।', 'hard', 8, 0),
  ('interview-l3-s9', 'interview-l3', 'interview', 'Are you willing to work on weekends?', 'क्या आप वीकेंड पर काम करने को तैयार हैं?', 'medium', 9, 0),
  ('interview-l3-s10', 'interview-l3', 'interview', 'Yes, I am flexible when needed.', 'हाँ, ज़रूरत पड़ने पर मैं लचीला हूँ।', 'medium', 10, 0),
  ('corporate-l1-s1', 'corporate-l1', 'corporate', 'Let''s schedule a meeting for Monday.', 'चलिए सोमवार के लिए एक मीटिंग तय करते हैं।', 'medium', 1, 0),
  ('corporate-l1-s2', 'corporate-l1', 'corporate', 'I will share the meeting agenda beforehand.', 'मैं मीटिंग का एजेंडा पहले साझा करूँगा।', 'hard', 2, 0),
  ('corporate-l1-s3', 'corporate-l1', 'corporate', 'Please mute your microphone.', 'कृपया अपना माइक्रोफ़ोन म्यूट करें।', 'medium', 3, 0),
  ('corporate-l1-s4', 'corporate-l1', 'corporate', 'Let''s stick to the point.', 'चलिए मुद्दे पर बने रहते हैं।', 'medium', 4, 0),
  ('corporate-l1-s5', 'corporate-l1', 'corporate', 'I will take the minutes of the meeting.', 'मैं मीटिंग के मिनट्स लिखूँगा।', 'hard', 5, 0),
  ('corporate-l1-s6', 'corporate-l1', 'corporate', 'We have reached a decision.', 'हम एक निर्णय पर पहुँच गए हैं।', 'medium', 6, 0),
  ('corporate-l1-s7', 'corporate-l1', 'corporate', 'Action items will be shared shortly.', 'कार्य बिंदु जल्द ही साझा किए जाएँगे।', 'hard', 7, 0),
  ('corporate-l1-s8', 'corporate-l1', 'corporate', 'The meeting has been postponed.', 'मीटिंग स्थगित कर दी गई है।', 'medium', 8, 0),
  ('corporate-l1-s9', 'corporate-l1', 'corporate', 'Please join the call on time.', 'कृपया कॉल में समय पर शामिल हों।', 'medium', 9, 0),
  ('corporate-l1-s10', 'corporate-l1', 'corporate', 'Let''s wrap up for today.', 'चलिए आज के लिए समाप्त करते हैं।', 'medium', 10, 0),
  ('corporate-l2-s1', 'corporate-l2', 'corporate', 'I need a quick update on the project.', 'मुझे प्रोजेक्ट पर एक त्वरित अपडेट चाहिए।', 'medium', 1, 0),
  ('corporate-l2-s2', 'corporate-l2', 'corporate', 'Let''s divide the work among the team.', 'चलिए काम को टीम में बाँटते हैं।', 'medium', 2, 0),
  ('corporate-l2-s3', 'corporate-l2', 'corporate', 'I appreciate your hard work.', 'मैं आपकी मेहनत की सराहना करता हूँ।', 'medium', 3, 0),
  ('corporate-l2-s4', 'corporate-l2', 'corporate', 'Please keep me informed of any issues.', 'कृपया मुझे किसी भी समस्या की जानकारी देते रहिए।', 'hard', 4, 0),
  ('corporate-l2-s5', 'corporate-l2', 'corporate', 'I will support you in this task.', 'मैं इस कार्य में आपका समर्थन करूँगा।', 'medium', 5, 0),
  ('corporate-l2-s6', 'corporate-l2', 'corporate', 'Let''s have a one-on-one discussion.', 'चलिए एक-पर-एक चर्चा करते हैं।', 'hard', 6, 0),
  ('corporate-l2-s7', 'corporate-l2', 'corporate', 'The team performed exceptionally well.', 'टीम ने बेहद अच्छा प्रदर्शन किया।', 'hard', 7, 0),
  ('corporate-l2-s8', 'corporate-l2', 'corporate', 'We need to improve our communication.', 'हमें अपने संचार में सुधार करने की ज़रूरत है।', 'medium', 8, 0),
  ('corporate-l2-s9', 'corporate-l2', 'corporate', 'Please complete this before the review.', 'कृपया इसे समीक्षा से पहले पूरा करें।', 'medium', 9, 0),
  ('corporate-l2-s10', 'corporate-l2', 'corporate', 'Thank you for your cooperation.', 'आपके सहयोग के लिए धन्यवाद।', 'medium', 10, 0),
  ('corporate-l3-s1', 'corporate-l3', 'corporate', 'The client wants the proposal today.', 'क्लाइंट आज ही प्रस्ताव चाहता है।', 'medium', 1, 0),
  ('corporate-l3-s2', 'corporate-l3', 'corporate', 'We must meet the delivery deadline.', 'हमें डिलीवरी की समय-सीमा पूरी करनी ही होगी।', 'hard', 2, 0),
  ('corporate-l3-s3', 'corporate-l3', 'corporate', 'Please prioritise this urgent task.', 'कृपया इस ज़रूरी कार्य को प्राथमिकता दें।', 'hard', 3, 0),
  ('corporate-l3-s4', 'corporate-l3', 'corporate', 'I will follow up with the client tomorrow.', 'मैं कल क्लाइंट से फॉलो-अप करूँगा।', 'medium', 4, 0),
  ('corporate-l3-s5', 'corporate-l3', 'corporate', 'The project is on track.', 'प्रोजेक्ट सही रास्ते पर है।', 'medium', 5, 0),
  ('corporate-l3-s6', 'corporate-l3', 'corporate', 'We have a tight schedule this week.', 'इस सप्ताह हमारा कार्यक्रम बहुत व्यस्त है।', 'medium', 6, 0),
  ('corporate-l3-s7', 'corporate-l3', 'corporate', 'Let''s confirm the requirements once more.', 'चलिए आवश्यकताओं की एक बार फिर पुष्टि करते हैं।', 'hard', 7, 0),
  ('corporate-l3-s8', 'corporate-l3', 'corporate', 'The client was satisfied with our work.', 'क्लाइंट हमारे काम से संतुष्ट था।', 'medium', 8, 0),
  ('corporate-l3-s9', 'corporate-l3', 'corporate', 'We need an extension on the deadline.', 'हमें समय-सीमा में विस्तार चाहिए।', 'hard', 9, 0),
  ('corporate-l3-s10', 'corporate-l3', 'corporate', 'Quality is our top priority.', 'गुणवत्ता हमारी सबसे बड़ी प्राथमिकता है।', 'medium', 10, 0),
  ('business-l1-s1', 'business-l1', 'business', 'We guarantee on-time delivery.', 'हम समय पर डिलीवरी की गारंटी देते हैं।', 'medium', 1, 0),
  ('business-l1-s2', 'business-l1', 'business', 'The supplier has confirmed the order.', 'सप्लायर ने ऑर्डर की पुष्टि कर दी है।', 'medium', 2, 0),
  ('business-l1-s3', 'business-l1', 'business', 'We are facing a shortage of stock.', 'हमें स्टॉक की कमी का सामना करना पड़ रहा है।', 'hard', 3, 0),
  ('business-l1-s4', 'business-l1', 'business', 'Please check the quality of the goods.', 'कृपया माल की गुणवत्ता जाँच लीजिए।', 'medium', 4, 0),
  ('business-l1-s5', 'business-l1', 'business', 'The shipment has arrived.', 'शिपमेंट आ गया है।', 'medium', 5, 0),
  ('business-l1-s6', 'business-l1', 'business', 'We value our regular customers.', 'हम अपने नियमित ग्राहकों को महत्व देते हैं।', 'medium', 6, 0),
  ('business-l1-s7', 'business-l1', 'business', 'Can you arrange bulk supply?', 'क्या आप थोक आपूर्ति की व्यवस्था कर सकते हैं?', 'hard', 7, 0),
  ('business-l1-s8', 'business-l1', 'business', 'Our products are 100% genuine.', 'हमारे उत्पाद 100% असली हैं।', 'medium', 8, 0),
  ('business-l1-s9', 'business-l1', 'business', 'Please confirm the delivery address.', 'कृपया डिलीवरी का पता पुष्टि करें।', 'medium', 9, 0),
  ('business-l1-s10', 'business-l1', 'business', 'Customer satisfaction is our priority.', 'ग्राहक संतुष्टि हमारी प्राथमिकता है।', 'medium', 10, 0),
  ('business-l2-s1', 'business-l2', 'business', 'What is the wholesale price?', 'थोक मूल्य क्या है?', 'medium', 1, 0),
  ('business-l2-s2', 'business-l2', 'business', 'The price includes all taxes.', 'कीमत में सभी कर शामिल हैं।', 'medium', 2, 0),
  ('business-l2-s3', 'business-l2', 'business', 'We offer a 10 percent discount on bulk orders.', 'हम थोक ऑर्डर पर 10 प्रतिशत छूट देते हैं।', 'hard', 3, 0),
  ('business-l2-s4', 'business-l2', 'business', 'The order has been placed successfully.', 'ऑर्डर सफलतापूर्वक कर दिया गया है।', 'medium', 4, 0),
  ('business-l2-s5', 'business-l2', 'business', 'Payment is due within 30 days.', 'भुगतान 30 दिनों के भीतर करना होगा।', 'hard', 5, 0),
  ('business-l2-s6', 'business-l2', 'business', 'Please issue the invoice.', 'कृपया इनवॉइस जारी करें।', 'medium', 6, 0),
  ('business-l2-s7', 'business-l2', 'business', 'The payment has been received.', 'भुगतान प्राप्त हो गया है।', 'medium', 7, 0),
  ('business-l2-s8', 'business-l2', 'business', 'Can we split the payment into two parts?', 'क्या हम भुगतान दो हिस्सों में कर सकते हैं?', 'hard', 8, 0),
  ('business-l2-s9', 'business-l2', 'business', 'The advance payment is 30 percent.', 'अग्रिम भुगतान 30 प्रतिशत है।', 'hard', 9, 0),
  ('business-l2-s10', 'business-l2', 'business', 'Please mention the delivery charges.', 'कृपया डिलीवरी शुल्क बताइए।', 'medium', 10, 0),
  ('business-l3-s1', 'business-l3', 'business', 'We are open to discussion.', 'हम चर्चा के लिए तैयार हैं।', 'medium', 1, 0),
  ('business-l3-s2', 'business-l3', 'business', 'Let''s draft a partnership agreement.', 'चलिए एक साझेदारी समझौता तैयार करते हैं।', 'hard', 2, 0),
  ('business-l3-s3', 'business-l3', 'business', 'We can adjust the terms slightly.', 'हम शर्तों में थोड़ा बदलाव कर सकते हैं।', 'hard', 3, 0),
  ('business-l3-s4', 'business-l3', 'business', 'Trust is the base of this partnership.', 'विश्वास इस साझेदारी की नींव है।', 'medium', 4, 0),
  ('business-l3-s5', 'business-l3', 'business', 'We would like a better rate.', 'हम बेहतर दर चाहेंगे।', 'medium', 5, 0),
  ('business-l3-s6', 'business-l3', 'business', 'Let''s sign the agreement this week.', 'चलिए इस सप्ताह समझौते पर हस्ताक्षर करते हैं।', 'medium', 6, 0),
  ('business-l3-s7', 'business-l3', 'business', 'This will be a long-term partnership.', 'यह एक दीर्घकालिक साझेदारी होगी।', 'medium', 7, 0),
  ('business-l3-s8', 'business-l3', 'business', 'We should discuss the profit sharing.', 'हमें लाभ-विभाजन पर चर्चा करनी चाहिए।', 'hard', 8, 0),
  ('business-l3-s9', 'business-l3', 'business', 'I am confident this deal will work.', 'मुझे विश्वास है यह सौदा काम करेगा।', 'medium', 9, 0),
  ('business-l3-s10', 'business-l3', 'business', 'Let''s celebrate our new partnership.', 'चलिए अपनी नई साझेदारी का जश्न मनाते हैं।', 'medium', 10, 0),
  ('travel-l1-s1', 'travel-l1', 'travel', 'Where is the check-in counter?', 'चेक-इन काउंटर कहाँ है?', 'medium', 1, 0),
  ('travel-l1-s2', 'travel-l1', 'travel', 'I have one bag to check in.', 'मुझे एक बैग चेक-इन करना है।', 'medium', 2, 0),
  ('travel-l1-s3', 'travel-l1', 'travel', 'Is this the boarding gate?', 'क्या यह बोर्डिंग गेट है?', 'medium', 3, 0),
  ('travel-l1-s4', 'travel-l1', 'travel', 'The flight is delayed by two hours.', 'फ्लाइट दो घंटे देरी से है।', 'hard', 4, 0),
  ('travel-l1-s5', 'travel-l1', 'travel', 'May I see your boarding pass?', 'क्या मैं आपका बोर्डिंग पास देख सकता हूँ?', 'medium', 5, 0),
  ('travel-l1-s6', 'travel-l1', 'travel', 'What is the purpose of your visit?', 'आपकी यात्रा का उद्देश्य क्या है?', 'hard', 6, 0),
  ('travel-l1-s7', 'travel-l1', 'travel', 'I am here for tourism.', 'मैं यहाँ पर्यटन के लिए हूँ।', 'medium', 7, 0),
  ('travel-l1-s8', 'travel-l1', 'travel', 'How long will you stay?', 'आप कितने दिन रुकेंगे?', 'medium', 8, 0),
  ('travel-l1-s9', 'travel-l1', 'travel', 'I am staying for one week.', 'मैं एक सप्ताह रुकूँगा।', 'medium', 9, 0),
  ('travel-l1-s10', 'travel-l1', 'travel', 'I am travelling with my family.', 'मैं अपने परिवार के साथ यात्रा कर रहा हूँ।', 'medium', 10, 0),
  ('travel-l2-s1', 'travel-l2', 'travel', 'I have a reservation under the name Sharma.', 'मेरा शर्मा नाम से आरक्षण है।', 'hard', 1, 0),
  ('travel-l2-s2', 'travel-l2', 'travel', 'Can I check in early?', 'क्या मैं जल्दी चेक-इन कर सकता हूँ?', 'medium', 2, 0),
  ('travel-l2-s3', 'travel-l2', 'travel', 'Please show your ID card.', 'कृपया अपना पहचान पत्र दिखाइए।', 'medium', 3, 0),
  ('travel-l2-s4', 'travel-l2', 'travel', 'What time is breakfast served?', 'नाश्ता किस समय मिलता है?', 'medium', 4, 0),
  ('travel-l2-s5', 'travel-l2', 'travel', 'I would like a room with a view.', 'मुझे दृश्य वाला कमरा चाहिए।', 'hard', 5, 0),
  ('travel-l2-s6', 'travel-l2', 'travel', 'The air conditioner is not working.', 'एयर कंडीशनर काम नहीं कर रहा है।', 'hard', 6, 0),
  ('travel-l2-s7', 'travel-l2', 'travel', 'I want to check out tomorrow morning.', 'मैं कल सुबह चेक-आउट करना चाहता हूँ।', 'medium', 7, 0),
  ('travel-l2-s8', 'travel-l2', 'travel', 'Please call me a taxi.', 'कृपया मेरे लिए टैक्सी बुलाइए।', 'medium', 8, 0),
  ('travel-l2-s9', 'travel-l2', 'travel', 'How much is the fare to the airport?', 'हवाई अड्डे तक किराया कितना है?', 'medium', 9, 0),
  ('travel-l2-s10', 'travel-l2', 'travel', 'Please use the meter.', 'कृपया मीटर चलाइए।', 'medium', 10, 0),
  ('travel-l3-s1', 'travel-l3', 'travel', 'A table near the window, please.', 'खिड़की के पास एक टेबल, कृपया।', 'medium', 1, 0),
  ('travel-l3-s2', 'travel-l3', 'travel', 'What do you recommend?', 'आप क्या सुझाव देते हैं?', 'medium', 2, 0),
  ('travel-l3-s3', 'travel-l3', 'travel', 'I am a vegetarian.', 'मैं शाकाहारी हूँ।', 'easy', 3, 0),
  ('travel-l3-s4', 'travel-l3', 'travel', 'Please make it less spicy.', 'कृपया इसे कम तीखा बनाइए।', 'medium', 4, 0),
  ('travel-l3-s5', 'travel-l3', 'travel', 'Can I have the bill, please?', 'क्या मुझे बिल मिल सकता है, कृपया?', 'easy', 5, 0),
  ('travel-l3-s6', 'travel-l3', 'travel', 'How can I reach the city centre?', 'मैं शहर के केंद्र तक कैसे पहुँचूँ?', 'medium', 6, 0),
  ('travel-l3-s7', 'travel-l3', 'travel', 'Is it safe to walk at night?', 'क्या रात में चलना सुरक्षित है?', 'medium', 7, 0),
  ('travel-l3-s8', 'travel-l3', 'travel', 'The museum is opposite the park.', 'संग्रहालय पार्क के सामने है।', 'hard', 8, 0),
  ('travel-l3-s9', 'travel-l3', 'travel', 'I am lost, can you help me?', 'मैं रास्ता भटक गया हूँ, क्या आप मेरी मदद करेंगे?', 'medium', 9, 0),
  ('travel-l3-s10', 'travel-l3', 'travel', 'Thank you for your help.', 'आपकी मदद के लिए धन्यवाद।', 'easy', 10, 0);

INSERT OR IGNORE INTO packages (id, name, price, original_price, currency, tagline, features, popular, color) VALUES
  ('free', 'FREE', 0, 0, '₹', 'Shuruaat ke liye perfect', '["Kids English + School English","Beginner English (10 lessons)","Roz ki practice tracking","Browser Text-to-Speech"]', 0, 'emerald'),
  ('complete-english', 'COMPLETE ENGLISH', 499, 999, '₹', 'Beginner se Advanced tak sab kuch', '["Beginner + Intermediate + Advanced","500+ practice sentences","Progress tracking & streak","Daily life English included","Mobile + Desktop"]', 1, 'sky'),
  ('professional', 'PROFESSIONAL', 599, 1199, '₹', 'Job aur career ke liye', '["Interview English","Corporate English","Business English","Travel English","All paid sentence practice"]', 0, 'indigo'),
  ('complete-pack', 'COMPLETE PACK', 799, 1999, '₹', 'Sab kuch — lifetime access', '["All 10 courses — every sentence","Kids + School + Adults + Professionals","All future courses included","Priority support","Lifetime access"]', 1, 'violet');

INSERT OR IGNORE INTO package_courses (package_id, course_id) VALUES
  ('free', 'kids'),
  ('free', 'school'),
  ('free', 'beginner'),
  ('complete-english', 'beginner'),
  ('complete-english', 'intermediate'),
  ('complete-english', 'advanced'),
  ('complete-english', 'daily'),
  ('professional', 'interview'),
  ('professional', 'corporate'),
  ('professional', 'business'),
  ('professional', 'travel'),
  ('complete-pack', 'kids'),
  ('complete-pack', 'school'),
  ('complete-pack', 'beginner'),
  ('complete-pack', 'intermediate'),
  ('complete-pack', 'advanced'),
  ('complete-pack', 'daily'),
  ('complete-pack', 'interview'),
  ('complete-pack', 'corporate'),
  ('complete-pack', 'business'),
  ('complete-pack', 'travel');

INSERT OR IGNORE INTO users (id, name, email, avatar_color, is_admin, created_at) VALUES
  ('u-1', 'Rahul Sharma', 'rahul@example.com', 'sky', 0, '2026-07-02T09:00:00.000Z'),
  ('u-2', 'Priya Patel', 'priya@example.com', 'rose', 0, '2026-07-10T11:30:00.000Z'),
  ('u-3', 'Amit Verma', 'amit@example.com', 'emerald', 0, '2026-07-15T08:15:00.000Z'),
  ('u-4', 'Sneha Gupta', 'sneha@example.com', 'violet', 0, '2026-07-20T13:45:00.000Z'),
  ('u-5', 'Vikram Singh', 'vikram@example.com', 'amber', 0, '2026-08-01T16:20:00.000Z'),
  ('u-admin', 'Admin', 'admin@sunobolo.com', 'indigo', 1, '2026-06-01T00:00:00.000Z');

INSERT OR IGNORE INTO admin_users (user_id, role, created_at) VALUES
  ('u-admin', 'admin', '2026-06-01T00:00:00.000Z');
